/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\ag_filters.dat" ENCODING="CP1252" / LRECL=25 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        hh_b1b14 23           
   ag2a_11 24               ag10_01 25 .          

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   hh_b1b14    'Do you or any member of your household use, own, or hold use righ' +
   'ts for any parc'
   ag2a_11 'What year was the last completed short rainy season?'
   ag10_01    'Did the household process any of the products harvested on the fa' +
   'rm in the last' .

VALUE LABELS
 hh_b1b14
     1 'YES'
     2 'NO' /
 ag2a_11
     1 'OCT-DEC 2019'
     2 'OCT-DEC 2020' /
 ag10_01
     1 'YES'
     2 'NO' / .


SAVE OUTFILE='.\ag_filters.sav'.
