/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\ag_sec_7a.dat" ENCODING="CP1252" / LRECL=94 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        cropid 23-25          
   ag7a_02 26               ag7a_03 27-33            ag7a_04 34-41         
   ag7a_05_1 42             ag7a_05_2 43-44          ag7a_06_1 45          
   ag7a_06_2 46-47          ag7a_07_1a 48-49         ag7a_07_1b 50         
   ag7a_07_2a 51-52         ag7a_07_2b 53            ag7a_08 54            
   ag7a_09 55-56            ag7a_10 57               ag7a_11 58            
   ag7a_12 59               ag7a_13 60               ag7a_14 61            
   ag7a_15 62-63            ag7a_16 64-69            ag7a_17 70-76         
   ag7a_18 77-81            ag7a_19 82-85            ag7a_20 86-90         
   ag7a_21 91-94 .       

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   cropid 'Fruit Tree Crop Code'
   ag7a_02 'Did you sell any of the [FRUIT] collected?'
   ag7a_03 'What was the total quanity sold? (KG)'
   ag7a_04 'What was the total value of [FRUIT] sold? (TSH)'
   ag7a_05_1    'Who in HH was responsible for negotiating sale of [FRUIT]? (ID 1)'
   ag7a_05_2    'Who in HH was responsible for negotiating sale of [FRUIT]? (ID 2)'
   ag7a_06_1    'Who in your household decided what to do with these earnings? (HH' +
   ' ID 1)'
   ag7a_06_2    'Who in your household decided what to do with these earnings? (HH' +
   ' ID 2)'
   ag7a_07_1a 'Where did you sell most of the fruit? (NR ID 1)'
   ag7a_07_1b 'Where is [NETWORK] located? (NR 1 LOCATION)'
   ag7a_07_2a 'Where did you sell most of the fruit? (NR ID 2)'
   ag7a_07_2b 'Where is [NETWORK] located? (NR 2 LOCATION)'
   ag7a_08 'Do you have any of this harvest in storage now?'
   ag7a_09 'How much of this harvest do you still have in storage? (KG)'
   ag7a_10 'What is your main method of storage?'
   ag7a_11 'Did you do anything to protect the stored crop?'
   ag7a_12 'What did you do?'
   ag7a_13    'Portion of production lost post-harvest to rotting, insects, rode' +
   'nts, theft, etc'
   ag7a_14 'What was the reason for this loss?'
   ag7a_15 'Out of 10 units of [FRUIT], how many were lost?'
   ag7a_16 'What was the value of this lost [FRUIT]? (TSH)'
   ag7a_17 'How much of the harvest was consumed? (KG)'
   ag7a_18    'How much of the harvest was stored as seed for the next planting ' +
   'season? (KG)'
   ag7a_19    'How much of the harvest was given as payments for labour or non-l' +
   'abour payments?'
   ag7a_20 'How much of the harvest was given away as gifts? (KG)'
   ag7a_21 'How much of the harvest was used as animal feed? (KG)' .

VALUE LABELS
 cropid
     11 'MAIZE'
     12 'PADDY'
     13 'SORGHUM'
     14 'BULRUSH MILLET'
     15 'FINGER MILLET'
     16 'WHEAT'
     17 'BARLEY'
     18 'BLACK PEPPER'
     19 'SEAWEED'
     21 'CASSAVA'
     22 'SWEET POTATOES'
     23 'IRISH POTATOES'
     24 'YAMS'
     25 'COCOYAMS'
     26 'ONIONS'
     27 'GINGER'
     31 'BEANS'
     32 'COWPEAS'
     33 'GREEN GRAM'
     34 'PIGEON PEA'
     35 'CHICK PEAS'
     36 'BAMBARA NUTS'
     37 'FIELD PEAS'
     38 'MALAY APPLE'
     39 'STAR FRUIT'
     41 'SUNFLOWER'
     42 'SESAME'
     43 'GROUNDNUT'
     44 'PALM OIL'
     45 'COCONUT'
     46 'CASHEW NUT'
     47 'SOYABEANS'
     48 'CASTER SEED'
     50 'COTTON'
     51 'TOBACCO'
     52 'PYRETHRUM'
     53 'SISAL'
     54 'COFFEE'
     55 'TEA'
     56 'COCOA'
     57 'RUBBER'
     58 'WATTLE'
     59 'KAPOK'
     60 'SUGAR CANE'
     61 'CARDAMOM'
     62 'JUTE'
     63 'TAMARIND'
     64 'CINNAMON'
     65 'NUTMEG'
     66 'CLOVE'
     67 'BREAD FRUIT'
     68 'POMELO'
     69 'JACK FRUIT'
     70 'PASSION FRUIT'
     71 'BANANA'
     72 'AVOCADO'
     73 'MANGO'
     74 'PAPAW'
     75 'PINEAPPLE'
     76 'ORANGE'
     77 'GRAPEFRUIT'
     78 'GRAPES'
     79 'MANDARIN'
     80 'GUAVA'
     81 'PLUMS'
     82 'APPLES'
     83 'PEARS'
     84 'PEACHES'
     86 'CABBAGE'
     87 'TOMATOES'
     88 'SPINACH'
     89 'CARROT'
     90 'CHILIES'
     91 'AMARANTHS'
     92 'PUMPKINS'
     93 'CUCUMBER'
     94 'EGG PLANT'
     95 'WATER MELLON'
     96 'CAULIFLOWER'
     97 'DURIAN'
     98 'BILIMBI'
     99 'RAMBUTAN'
     100 'OKRA'
     101 'FIWI'
     200 'CUSTARD APPLE'
     201 'GOD FRUIT'
     202 'MITOBO'
     203 'PLUM'
     204 'PEACHES'
     205 'POMEGRANATE'
     210 'DATE'
     211 'TUNGAMAA'
     212 'VANILLA'
     300 'GREEN TOMATO'
     301 'MONKEYBREAD'
     302 'BAMBOO'
     303 'FIREWOOD/FODDER'
     304 'TIMBER'
     305 'MEDICINAL PLANT'
     306 'FENCE TREE'
     851 'LIME'
     852 'LEMON'
     998 'OTHER (SPECIFY)' /
 ag7a_02
     1 'YES'
     2 'NO' /
 ag7a_07_1a
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag7a_07_1b
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag7a_07_2a
     0 'NOT APPLICABLE'
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag7a_07_2b
     1 'NDANI YA KIJIJI/MJI'
     2 'KARIBU NA KIJIJI'
     3 'KARIBU NA MJI'
     4 'WILAYA NYINGINE'
     5 'MKOA MWINGINE'
     6 'NJE YA NCHI' /
 ag7a_08
     1 'YES'
     2 'NO' /
 ag7a_10
     1 'LOCALLY MADE TRADITIONAL STRUCTURE'
     2 'IMPROVED LOCALLY MADE STRUCTURE'
     3 'MODERN STRUCTURE'
     4 'SACKS/OPEN DRUM'
     5 'AIRTIGHT DRUM'
     6 'UNPROTECTED PILE'
     7 'OTHER (SPECIFY)' /
 ag7a_11
     1 'YES'
     2 'NO' /
 ag7a_12
     1 'SPRAYING'
     2 'SMOKING'
     3 'OTHER (SPECIFY)' /
 ag7a_13
     1 'YES'
     2 'NO' /
 ag7a_14
     1 'ROTTING'
     2 'INSECTS'
     3 'RODENTS, PESTS'
     4 'THEFT'
     5 'OTHER (SPECIFY)' / .


SAVE OUTFILE='.\ag_sec_7a.sav'.
