/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\ag_sec_4a.dat" ENCODING="CP1252" / LRECL=144 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        plot_id 23-24         
   cropid 25-27             ag4a_01 28               ag4a_02 29            
   ag4a_03 30               ag4a_04 31               ag4a_05 32            
   ag4a_06 33-80 (A)        ag4a_08 81               ag4a_10_1 82-86       
   ag4a_10_2 87             ag4a_10a_1 88-91         ag4a_10a_2 92         
   ag4a_10b 93              ag4a_10c_1 94-98         ag4a_10c_2 99         
   ag4a_12 100-106          ag4a_13_1 107-108        ag4a_13_2 109         
   ag4a_17 110              ag4a_18 111              ag4a_19 112           
   ag4a_20 113              ag4a_21 114-117          ag4a_22 118           
   ag4a_23 119              ag4a_24_1 120-121        ag4a_24_2 122-123     
   ag4a_25 124-125          ag4a_26 126              ag4a_27 127-132       
   ag4a_28 133-140          ag4a_29_1 141-142        ag4a_29_2 143-144 .   


FORMATS
  ag4a_10_1 (F6.2) /       ag4a_10a_1 (F5.2) /      ag4a_10c_1 (F6.2) /    
  ag4a_21 (F5.2) /         ag4a_27 (F7.1) / .
    
VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   plot_id 'PLOT ID'
   cropid 'CROP CODE'
   ag4a_01 'Was crop planted in entire area of plot?'
   ag4a_02 'Approximately, how much of the plot was planted with [CROP]?'
   ag4a_03 "Why didn't you plant the entire plot with [CROP]?"
   ag4a_04 'Was cultivation intercropped?'
   ag4a_05 'What is the reason for this intercropping?'
   ag4a_06    'What was the name of the main seed variety for this [CROP] on thi' +
   's plot?'
   ag4a_08 'Were the main seeds...'
   ag4a_10_1 'What was the total amount of seeds used? (QUANTITY)'
   ag4a_10_2 'What was the total amount of seeds used? (UNIT)'
   ag4a_10a_1    'What was the total seeds used on plot came from the previous seas' +
   'on? (QUANTITY)'
   ag4a_10a_2    'What was the total seeds used on plot came from the previous seas' +
   'on? (UNIT)'
   ag4a_10b 'What type of seed were the seeds from the previous season?'
   ag4a_10c_1    'How much of the total seed used on plot came from purchases? (QUA' +
   'NTITY)'
   ag4a_10c_2    'How much of the total seed used on plot came from purchases? (UNI' +
   'T)'
   ag4a_12 'What was the total amount paid for seeds? (TSH)'
   ag4a_13_1 'Where did you buy most of the seeds?'
   ag4a_13_2 'Where is [SELLER] located?'
   ag4a_17 'Were there any losses of crops before the harvest?'
   ag4a_18 'What was the cause of these losses?'
   ag4a_19    'Did you harvest any [CROP] on [PLOT] in the long rainy season 202' +
   '0?'
   ag4a_20 "Why didn't you harvest any [CROP] on this plot?"
   ag4a_21 'What was the area harvested in the long rainy season 2020?'
   ag4a_22 'Was area harvested less than area planted?'
   ag4a_23 'What was the reason it was less than the area planted?'
   ag4a_24_1 'What was the first and last month of the harvest period? (BEGIN)'
   ag4a_24_2 'What was the first and last month of the harvest period? (END)'
   ag4a_25 'How many more days do you expect the harvest to last?'
   ag4a_26    'What fraction of the crop remains to be harvested in this period?'
   ag4a_27 'What was the quantity harvested?'
   ag4a_28 'What is the estimated value of the harvested crop?'
   ag4a_29_1    'Who in HH made the decisions concerning the use of the harvested ' +
   'crop? (ID 1)'
   ag4a_29_2    'Who in HH made the decisions concerning the use of the harvested ' +
   'crop? (ID 2)' .

VALUE LABELS
 cropid
     11 'MAIZE'
     12 'PADDY'
     13 'SORGHUM'
     14 'BULRUSH MILLET'
     15 'FINGER MILLET'
     16 'WHEAT'
     17 'BARLEY'
     18 'BLACK PEPPER'
     19 'SEAWEED'
     21 'CASSAVA'
     22 'SWEET POTATOES'
     23 'IRISH POTATOES'
     24 'YAMS'
     25 'COCOYAMS'
     26 'ONIONS'
     27 'GINGER'
     31 'BEANS'
     32 'COWPEAS'
     33 'GREEN GRAM'
     34 'PIGEON PEA'
     35 'CHICK PEAS'
     36 'BAMBARA NUTS'
     37 'FIELD PEAS'
     38 'MALAY APPLE'
     39 'STAR FRUIT'
     41 'SUNFLOWER'
     42 'SESAME'
     43 'GROUNDNUT'
     44 'PALM OIL'
     45 'COCONUT'
     46 'CASHEW NUT'
     47 'SOYABEANS'
     48 'CASTER SEED'
     50 'COTTON'
     51 'TOBACCO'
     52 'PYRETHRUM'
     53 'SISAL'
     54 'COFFEE'
     55 'TEA'
     56 'COCOA'
     57 'RUBBER'
     58 'WATTLE'
     59 'KAPOK'
     60 'SUGAR CANE'
     61 'CARDAMOM'
     62 'JUTE'
     63 'TAMARIND'
     64 'CINNAMON'
     65 'NUTMEG'
     66 'CLOVE'
     67 'BREAD FRUIT'
     68 'POMELO'
     69 'JACK FRUIT'
     70 'PASSION FRUIT'
     71 'BANANA'
     72 'AVOCADO'
     73 'MANGO'
     74 'PAPAW'
     75 'PINEAPPLE'
     76 'ORANGE'
     77 'GRAPEFRUIT'
     78 'GRAPES'
     79 'MANDARIN'
     80 'GUAVA'
     81 'PLUMS'
     82 'APPLES'
     83 'PEARS'
     84 'PEACHES'
     86 'CABBAGE'
     87 'TOMATOES'
     88 'SPINACH'
     89 'CARROT'
     90 'CHILIES'
     91 'AMARANTHS'
     92 'PUMPKINS'
     93 'CUCUMBER'
     94 'EGG PLANT'
     95 'WATER MELLON'
     96 'CAULIFLOWER'
     97 'DURIAN'
     98 'BILIMBI'
     99 'RAMBUTAN'
     100 'OKRA'
     101 'FIWI'
     200 'CUSTARD APPLE'
     201 'GOD FRUIT'
     202 'MITOBO'
     203 'PLUM'
     204 'PEACHES'
     205 'POMEGRANATE'
     210 'DATE'
     211 'TUNGAMAA'
     212 'VANILLA'
     300 'GREEN TOMATO'
     301 'MONKEYBREAD'
     302 'BAMBOO'
     303 'FIREWOOD/FODDER'
     304 'TIMBER'
     305 'MEDICINAL PLANT'
     306 'FENCE TREE'
     851 'LIME'
     852 'LEMON'
     998 'OTHER (SPECIFY)' /
 ag4a_01
     1 'YES'
     2 'NO' /
 ag4a_02
     1 '1/4'
     2 '1/2'
     3 '3/4' /
 ag4a_03
     1 'WAS DIVIDED'
     2 'DROUGHT'
     3 'LACK OF TOOLS/EQUIPMENTS'
     4 'LACK SEEDS'
     5 'FLOODS'
     6 'LOANS'
     7 'AG EQUIPMENTS'
     8 'OTHER, SPECIFY' /
 ag4a_04
     1 'YES'
     2 'NO' /
 ag4a_05
     1 'SUBSTITUTE IF EITHER CROP FAILS'
     2 'MORE FERTILE FOR THE SOIL'
     3 'OTHER (SPECIFY)' /
 ag4a_08
     1 'IMPROVED'
     2 'TRADITIONAL'
     3 'IMPROVED, RECYCLED'
     4 'OTHER (SPECIFY)' /
 ag4a_10_2
     1 'KG'
     2 '20 LITER BUCKET'
     3 'SMALL CUP'
     4 'LARGE CUP'
     5 'OTHER (SPECIFY)' /
 ag4a_10a_1
     0 'HAKUNA' /
 ag4a_10a_2
     1 'KG'
     2 '20 LITER BUCKET'
     3 'SMALL CUP'
     4 'LARGE CUP'
     5 'OTHER (SPECIFY)' /
 ag4a_10b
     1 'IMPROVED'
     2 'TRADITIONAL'
     3 'IMPROVED RECYCLED'
     4 'OTHER (SPECIFY)' /
 ag4a_10c_1
     0 'NONE' /
 ag4a_10c_2
     1 'KG'
     2 '20 LITER BUCKET'
     3 'SMALL CUP'
     4 'LARGE CUP'
     5 'OTHER (SPECIFY)' /
 ag4a_13_1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag4a_13_2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag4a_17
     1 'YES'
     2 'NO' /
 ag4a_18
     1 'BIRDS'
     2 'ANIMALS'
     3 'INSECTS'
     4 'DISEASES'
     5 'THEFT'
     6 'OTHER (SPECIFY)'
     7 'FLOOD / RAIN'
     8 'DROUGHT' /
 ag4a_19
     1 'YES'
     2 'NO' /
 ag4a_20
     1 'NOT MINE TO HARVEST'
     2 'STILL IN PLOT'
     3 'DESTRUCTION'
     4 'OTHER (SPECIFY)'
     5 'FLOOD / RAIN'
     6 'DROUGHT' /
 ag4a_22
     1 'YES'
     2 'NO' /
 ag4a_23
     1 'DROUGHT'
     2 'RAINS'
     3 'FIRE'
     4 'INSECTS'
     5 'ANIMALS'
     6 'CROP THEFT'
     7 'DISEASES AND COMMUNITY PROBLEMS'
     8 'LACK OF CASUAL LABOR'
     9 'OTHER (SPECIFY)' /
 ag4a_24_1
     1 'JANUARY'
     2 'FEBRUARY'
     3 'MARCH'
     4 'APRIL'
     5 'MAY'
     6 'JUNE'
     7 'JULY'
     8 'AUGUST'
     9 'SEPTEMBER'
     10 'OCTOBER'
     11 'NOVEMBER'
     12 'DECEMBER' /
 ag4a_24_2
     0 'HARVEST NOT YET COMPLETE'
     1 'JANUARY'
     2 'FEBRUARY'
     3 'MARCH'
     4 'APRIL'
     5 'MAY'
     6 'JUNE'
     7 'JULY'
     8 'AUGUST'
     9 'SEPTEMBER'
     10 'OCTOBER'
     11 'NOVEMBER'
     12 'DECEMBER' / .


SAVE OUTFILE='.\ag_sec_4a.sav'.
