/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\ag_sec_3a.dat" ENCODING="CP1252" / LRECL=568 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        plot_id 23-24         
   plotname 25-40 (A)       plot_desc 41-56 (A)      prevplot_id 57-59 (A) 
   ag3a_02_1 60-64          ag3a_02_2 65-68          ag3a_02_3 69-72       
   ag3a_03 73               ag3a_04 74-80            ag3a_07 81-83         
   ag3a_08a_1 84            ag3a_08a_2 85            ag3a_08b_1 86-87      
   ag3a_08b_2 88-89         ag3a_08b_3 90-91         ag3a_08c1 92-93       
   ag3a_08c2 94             ag3a_09a_1 95            ag3a_09a_2 96         
   ag3a_09b_1 97-98         ag3a_09b_2 99-100        ag3a_09b_3 101        
   ag3a_09c1 102-103        ag3a_09c2 104            ag3a_10 105           
   ag3a_11 106              ag3a_12 107              ag3a_13 108           
   ag3a_14 109              ag3a_15 110              ag3a_16_1 111         
   ag3a_16_2 112            ag3a_17 113              ag3a_18 114           
   ag3a_19 115              ag3a_20 116              ag3a_21 117           
   ag3a_22 118-121          ag3a_23 122-123          ag3a_24 124-132       
   ag3a_25 133-134          ag3a_26_1 135-136        ag3a_26_2 137         
   ag3a_27 138              ag3a_28a 139             ag3a_28b 140          
   ag3a_28c 141             ag3a_28d 142             ag3a_29_1 143-144     
   ag3a_29_2 145-146        ag3a_30 147              ag3a_31_1 148-149     
   ag3a_31_2 150-151        ag3a_31a 152             ag3a_32_1 153         
   ag3a_32_2 154            ag3a_33 155-161          ag3a_34_1 162-167     
   ag3a_34_2 168            ag3a_35 169              ag3a_36_1 170-171     
   ag3a_36_2 172            ag3a_37_1 173-174        ag3a_37_2 175-176     
   ag3a_38 177-180          ag3a_38a 181             ag3a_39 182           
   ag3a_40 183              ag3a_41 184              ag3a_42 185-191       
   ag3a_43 192              ag3a_44 193-196          ag3a_45 197-202       
   ag3a_46_1 203-204        ag3a_46_2 205            ag3a_47 206           
   ag3a_48 207              ag3a_49 208-211          ag3a_51 212-218       
   ag3a_52 219              ag3a_53_1 220-221        ag3a_53_2 222         
   ag3a_54 223              ag3a_55 224              ag3a_56 225-228       
   ag3a_58 229-235          ag3a_59_1 236-237        ag3a_59_2 238         
   ag3a_60 239              ag3a_62_1 240-243        ag3a_62_2 244         
   ag3a_63 245-251          ag3a_64 252              ag3a_65_1 253-254     
   ag3a_65_2 255            ag3a_65a 256             ag3a_65b_1 257-261    
   ag3a_65b_2 262           ag3a_65c 263-269         ag3a_65d 270          
   ag3a_65e_1 271-272       ag3a_65e_2 273           ag3a_66 274           
   ag3a_67_1 275            ag3a_67_2 276            ag3a_67_3 277         
   ag3a_67_4 278            ag3a_68 279-284          ag3a_69 285-291       
   ag3a_70_1 292-298        ag3a_70_2 299            ag3a_71_1 300-301     
   ag3a_71_2 302            ag3a_71a 303             ag3a_71b 304          
   ag3a_72a 305             ag3a_72b_1 306-307       ag3a_72b_2 308-309    
   ag3a_72b_3 310-311       ag3a_72b_4 312-313       ag3a_72b_5 314-315    
   ag3a_72b_6 316-317       ag3a_72b_7 318-319       ag3a_72b_8 320-321    
   ag3a_72b_9 322-323       ag3a_72b_10 324-325      ag3a_72c_1 326-327    
   ag3a_72c_2 328-329       ag3a_72c_3 330-331       ag3a_72c_4 332-333    
   ag3a_72c_5 334-335       ag3a_72c_6 336-337       ag3a_72c_7 338-339    
   ag3a_72c_8 340-341       ag3a_72c_9 342-343       ag3a_72c_10 344-345   
   ag3a_72d_1 346-347       ag3a_72d_2 348-349       ag3a_72d_3 350-351    
   ag3a_72d_4 352-353       ag3a_72d_5 354-355       ag3a_72d_6 356-357    
   ag3a_72d_7 358-359       ag3a_72d_8 360-361       ag3a_72d_9 362-363    
   ag3a_72d_10 364          ag3a_72e 365             ag3a_72f_1 366-367    
   ag3a_72f_2 368-369       ag3a_72f_3 370-371       ag3a_72f_4 372-373    
   ag3a_72f_5 374-375       ag3a_72f_6 376-377       ag3a_72f_7 378-379    
   ag3a_72f_8 380-381       ag3a_72f_9 382-383       ag3a_72f_10 384-385   
   ag3a_72g_1 386-387       ag3a_72g_2 388-390       ag3a_72g_3 391-392    
   ag3a_72g_4 393-394       ag3a_72g_5 395-396       ag3a_72g_6 397-398    
   ag3a_72g_7 399-400       ag3a_72g_8 401-402       ag3a_72g_9 403-404    
   ag3a_72g_10 405-406      ag3a_72h_1 407-408       ag3a_72h_2 409-410    
   ag3a_72h_3 411-412       ag3a_72h_4 413-414       ag3a_72h_5 415-416    
   ag3a_72h_6 417-418       ag3a_72h_7 419-420       ag3a_72h_8 421-422    
   ag3a_72h_9 423-424       ag3a_72h_10 425-426      ag3a_72i 427          
   ag3a_72j_1 428-429       ag3a_72j_2 430-431       ag3a_72j_3 432-433    
   ag3a_72j_4 434-435       ag3a_72j_5 436-437       ag3a_72j_6 438-439    
   ag3a_72j_7 440-441       ag3a_72j_8 442-443       ag3a_72j_9 444-445    
   ag3a_72j_10 446-447      ag3a_72k_1 448-450       ag3a_72k_2 451-453    
   ag3a_72k_3 454-456       ag3a_72k_4 457-459       ag3a_72k_5 460-462    
   ag3a_72k_6 463-464       ag3a_72k_7 465-466       ag3a_72k_8 467-468    
   ag3a_72k_9 469-470       ag3a_72k_10 471-472      ag3a_72l_1 473-474    
   ag3a_72l_2 475-477       ag3a_72l_3 478-479       ag3a_72l_4 480-481    
   ag3a_72l_5 482-483       ag3a_72l_6 484-485       ag3a_72l_7 486-487    
   ag3a_72l_8 488-489       ag3a_72l_9 490-491       ag3a_72l_10 492-493   
   ag3a_73 494              ag3a_74_1a 495-496       ag3a_74_1b 497-500    
   ag3a_74_1c 501-506       ag3a_74_1d 507-513       ag3a_74_2a 514-518    
   ag3a_74_2b 519-523       ag3a_74_2c 524-528       ag3a_74_2d 529-535    
   ag3a_74_3a 536-540       ag3a_74_3b 541-545       ag3a_74_3c 546-547    
   ag3a_74_3d 548-553       ag3a_75 554              ag3a_76 555           
   ag3a_77 556-558          ag3a_78 559              ag3a_79 560           
   ag3a_80 561              ag3a_81 562              ag3a_82 563-565       
   ag3a_83 566              ag3a_84 567              ag3a_85 568 .         


FORMATS
  ag3a_02_1 (F6.2) /       ag3a_02_2 (F5.2) /       ag3a_02_3 (F5.2) /     
  ag3a_42 (F8.1) /         ag3a_49 (F5.1) /         ag3a_56 (F5.1) /       
  ag3a_62_1 (F5.1) /       ag3a_65b_1 (F6.1) / .
 
VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   plot_id 'PLOT ID'
   plotname    'LIST ALL PLOTS OWNED OR CULTIVATED BY THE HOUSEHOLD IN LONG RAINY' +
   ' SEASON 2020'
   plot_desc 'Description / Location'
   prevplot_id 'Previous Plot Number NPSY4'
   ag3a_02_1 'What is the distance from [PLOT] to: HOME (KM)'
   ag3a_02_2 'What is the distance from [PLOT] to: ROAD (KM)'
   ag3a_02_3 'What is the distance from [PLOT] to: MARKET (KM)'
   ag3a_03 'How did you use [PLOT] during the long rainy season 2020?'
   ag3a_04    'Total income from renting out [PLOT] during the long rainy season' +
   ' 2020 (TSH)'
   ag3a_07    'What was the main crop cultivated on [PLOT] in the long rainy sea' +
   'son 2020?'
   ag3a_08a_1    'HH MEMBER: Decided what to plant on [PLOT] in long rainy season 2' +
   '020'
   ag3a_08a_2    'NON-HH MEMBER: Decided what to plant on [PLOT] in long rainy seas' +
   'on 2020'
   ag3a_08b_1    'Who decided what to plant on [PLOT] in the long rainy season 2020' +
   '? (ID 1)'
   ag3a_08b_2    'Who decided what to plant on [PLOT] in the long rainy season 2020' +
   '? (ID 2)'
   ag3a_08b_3    'Who decided what to plant on [PLOT] in the long rainy season 2020' +
   '? (ID 3)'
   ag3a_08c1    'Who decided what to plant on [PLOT] in long rainy season 2020? (N' +
   'ETWORK ID)'
   ag3a_08c2 'Where is [NETWORK] located? (NETWORK ROSTER LOCATION)'
   ag3a_09a_1    'HH MEMBER: Made decisions on input use on [PLOT] in long rainy se' +
   'ason 2020'
   ag3a_09a_2    'NON-HH MEMBER: Made decisions on input use on [PLOT] in long rain' +
   'y season 2020'
   ag3a_09b_1    'Who made decisions on input use on [PLOT] in the long rainy seaso' +
   'n 2020? (ID 1)'
   ag3a_09b_2    'Who made decisions on input use on [PLOT] in the long rainy seaso' +
   'n 2020? (ID 2)'
   ag3a_09b_3    'Who made decisions on input use on [PLOT] in the long rainy seaso' +
   'n 2020? (ID 3)'
   ag3a_09c1    'Who made decisions on input use on [PLOT] in long rainy season 20' +
   '20 (NETWORK ID)'
   ag3a_09c2 'Where is [NETWORK] located? (NETWORK ROSTER LOCATION)'
   ag3a_10 'What was the soil type of this plot?'
   ag3a_11 'What was the soil quality of this plot?'
   ag3a_12 'How do you know the quality of the soil?'
   ag3a_13    'Were there any problems with erosion on [PLOT] in the long rainy ' +
   'season 2020?'
   ag3a_14 'What was the cause of these erosion problems?'
   ag3a_15    'Erosion control/water harvesting facility on [PLOT] in long rainy' +
   ' season 2020'
   ag3a_16_1    'What type of erosion control/water harvesting facility was on thi' +
   's plot?'
   ag3a_16_2    'What type of erosion control/water harvesting facility was on thi' +
   's plot?'
   ag3a_17 'How steep is the slope of this plot?'
   ag3a_18 'Was [PLOT] irrigated in the long rainy season 2020?'
   ag3a_19 'What was the type of irrigation?'
   ag3a_20 'What was the method of obtaining water?'
   ag3a_21 'What was the source of water?'
   ag3a_22 'What was the most recent year in which the plot was left fallow?'
   ag3a_23    'For how many consecutive years was this plot left fallow this las' +
   't time?'
   ag3a_24 'What would the value of this plot be if it were sold today?'
   ag3a_25 'How was this plot acquired?'
   ag3a_26_1 'With whom do you co-own this plot? (NETWORK ROSTER ID)'
   ag3a_26_2 'Where is [NETWORK] located? (NETWORK ROSTER LOCATION)'
   ag3a_27 'What share does your household get of the output?'
   ag3a_28a    'What type of legal certificate does your household have for this ' +
   'plot?'
   ag3a_28b 'Would you like to apply for a CCRO/GRO for this plot?'
   ag3a_28c 'Would you be willing to pay for legal certification?'
   ag3a_28d    'What other types of ownership or legal documents does HHd have fo' +
   'r [PLOT]?'
   ag3a_29_1 'Who in the household owns this plot? (ID 1)'
   ag3a_29_2 'Who in the household owns this plot? (ID 2)'
   ag3a_30    'Does the owner/HH have the right to sell [PLOT] or use it as coll' +
   'ateral?'
   ag3a_31_1    'Who in HH can decide whether to sell [PLOT] or use it as collater' +
   'al? (ID 1)'
   ag3a_31_2    'Who in HH can decide whether to sell [PLOT] or use it as collater' +
   'al? (ID 2)'
   ag3a_31a    'If you were to sell [PLOT], do you need approval from other parti' +
   'es to sell it?'
   ag3a_32_1 'With whom do you co-rent this plot? (NETWORK ROSTER ID)'
   ag3a_32_2 'Where is [NETWORK] located? (NETWORK ROSTER LOCATION)'
   ag3a_33    'Amount paid to the owner for the use of [PLOT] in long rainy seas' +
   'on 2020 (TSH)'
   ag3a_34_1 'What period of time did this payment cover? (NUMBER OF UNITS)'
   ag3a_34_2 'What period of time did this payment cover? (UNITS)'
   ag3a_35    'Share of output from [PLOT] given as rent in long rainy season 20' +
   '20'
   ag3a_36_1 'Who owns the plot? (NETWORK ROSTER ID)'
   ag3a_36_2 'Who owns the plot? (NETWORK ROSTER LOCATION)'
   ag3a_37_1 'Who in the household has the rights to use this plot? (ID 1)'
   ag3a_37_2 'Who in the household has the rights to use this plot? (ID 2)'
   ag3a_38 'In which year was the plot acquired?'
   ag3a_38a    'Had any land dispute or disagreement with anyone over [PLOT] in l' +
   'ast 12 months'
   ag3a_39    'Comfortable leaving [PLOT] uncultivated for several months withou' +
   't being worried'
   ag3a_40    'CAPI: DID THE HOUSEHOLD CULTIVATE [PLOT] IN THE LONG RAINY SEASON' +
   ' 2020?'
   ag3a_41    'Did you use any ORGANIC FERTILIZER on [PLOT] in the long rainy se' +
   'ason 2020?'
   ag3a_42 'What was the quantity of organic fertilizer used? (KG)'
   ag3a_43 'Was any of this purchased?'
   ag3a_44 'How much was purchased? (KG)'
   ag3a_45 'What was the total value of organic fertilizer purchased? (TSH)'
   ag3a_46_1    'Where did you buy most of the organic fertilizer? (NETWORK ROSTER' +
   ' ID)'
   ag3a_46_2 'Where is [NETWORK] located? (NETWORK ROSTER LOCATION)'
   ag3a_47    'Did you use any INORGANIC FERTILIZER on [PLOT] in the long rainy ' +
   'season 2020?'
   ag3a_48    'What is the first type of INORGANIC FERTILIZER you used on this p' +
   'lot?'
   ag3a_49 'What quantity of [FERTILIZER] did you use? (KG)'
   ag3a_51 'What was the total value of [FERTILIZER] purchased? (TSH)'
   ag3a_52    'Why did you choose to use this specific type of inorganic fertili' +
   'zer?'
   ag3a_53_1 'Where did you buy most of the [FERTILIZER]? (NETWORK ROSTER ID)'
   ag3a_53_2 'Where is [NETWORK] located? (NETWORK ROSTER LOCATION)'
   ag3a_54    'Used a second type of INORGANIC FERTILIZER on [PLOT] in long rain' +
   'y season 2020'
   ag3a_55    'What is the second type of INORGANIC FERTILIZER you used on this ' +
   'plot?'
   ag3a_56 'What quantity of [FERTILIZER] did you use? (KG)'
   ag3a_58 'What was the total value of [FERTILIZER] purchased? (TSH)'
   ag3a_59_1 'Where did you buy most of the [FERTILIZER]? (NETWORK ROSTER ID)'
   ag3a_59_2 'Where is [NETWORK] located? (NETWORK ROSTER LOCATION)'
   ag3a_60    'Did you use any herbicide on [PLOT] in the long rainy season 2020' +
   '?'
   ag3a_62_1 'What quantity of this herbicide did you use? QUANTITY'
   ag3a_62_2 'What quantity of this herbicide did you use? UNIT'
   ag3a_63 'What was the total value of this herbicide purchased? (TSH)'
   ag3a_64    'Why did you choose to use this specific type of pesticide/herbici' +
   'de?'
   ag3a_65_1    'Where did you buy most of the pesticides/ herbicides? (NETWORK RO' +
   'STER ID)'
   ag3a_65_2    'Where did you buy most of the herbicides? (NETWORK ROSTER LOCATIO' +
   'N)'
   ag3a_65a    'Did you use any pesticide on [PLOT] in the long rainy season 2020' +
   '?'
   ag3a_65b_1 'What quantity of this pesticide did you use? QUANTITY'
   ag3a_65b_2 'What quantity of this pesticide did you use? UNIT'
   ag3a_65c 'What was the total value of this pesticide purchased? (TSH)'
   ag3a_65d 'Why did you choose to use this specific type of pesticide?'
   ag3a_65e_1 'Where did you buy most of the pesticides? (NETWORK ROSTER ID)'
   ag3a_65e_2 'Where is [NETWORK] located? (NETWORK ROSTER LOCATION)'
   ag3a_66    'Received seeds... for [PLOT] on credit during long rainy season 2' +
   '020'
   ag3a_67_1 'What were the types of input you received on credit? [SEEDS]'
   ag3a_67_2    'What were the types of input you received on credit? [ORGANIC FER' +
   'TILIZER]'
   ag3a_67_3    'What were the types of input you received on credit? [INORGANIC F' +
   'ERTILIZER]'
   ag3a_67_4    'What were the types of input you received on credit? [PESTICIDES/' +
   'HERBICIDES]'
   ag3a_68 'How much did you pay up front for these inputs? (TSH)'
   ag3a_69 'How much did you repay in cash later on for the inputs? (TSH)'
   ag3a_70_1 'How much did you repay in kind later on for the inputs? QUANTITY'
   ag3a_70_2 'How much did you repay in kind later on for the inputs? UNIT'
   ag3a_71_1    'From whom did you receive these inputs on credit? (NETWORK ROSTER' +
   ' ID)'
   ag3a_71_2 'Where is [NETWORK] located? (NETWORK ROSTER LOCATION)'
   ag3a_71a    'Did you use any mechanization on [PLOT] in the long rainy season ' +
   '2020?'
   ag3a_71b    'Did you use any animal traction on [PLOT] in the long rainy seaso' +
   'n 2020?'
   ag3a_72a 'HH member spent time on LAND PREPARATION & PLANTING on [PLOT]'
   ag3a_72b_1 'Which member? (ID 1)'
   ag3a_72b_2 'Which member? (ID 2)'
   ag3a_72b_3 'Which member? (ID 3)'
   ag3a_72b_4 'Which member? (ID 4)'
   ag3a_72b_5 'Which member? (ID 5)'
   ag3a_72b_6 'Which member? (ID 6)'
   ag3a_72b_7 'Which member? (ID 7)'
   ag3a_72b_8 'Which member? (ID 8)'
   ag3a_72b_9 'Which member? (ID 9)'
   ag3a_72b_10 'Which member? (ID 10)'
   ag3a_72c_1    'Number of days [NAME] spent on LAND PREPARATION & PLANTING (MEMBE' +
   'R 1)'
   ag3a_72c_2    'Number of days [NAME] spent on LAND PREPARATION & PLANTING (MEMBE' +
   'R 2)'
   ag3a_72c_3    'Number of days [NAME] spent on LAND PREPARATION & PLANTING (MEMBE' +
   'R 3)'
   ag3a_72c_4    'Number of days [NAME] spent on LAND PREPARATION & PLANTING (MEMBE' +
   'R 4)'
   ag3a_72c_5    'Number of days [NAME] spent on LAND PREPARATION & PLANTING (MEMBE' +
   'R 5)'
   ag3a_72c_6    'Number of days [NAME] spent on LAND PREPARATION & PLANTING (MEMBE' +
   'R 6)'
   ag3a_72c_7    'Number of days [NAME] spent on LAND PREPARATION & PLANTING (MEMBE' +
   'R 7)'
   ag3a_72c_8    'Number of days [NAME] spent on LAND PREPARATION & PLANTING (MEMBE' +
   'R 8)'
   ag3a_72c_9    'Number of days [NAME] spent on LAND PREPARATION & PLANTING (MEMBE' +
   'R 9)'
   ag3a_72c_10    'Number of days [NAME] spent on LAND PREPARATION & PLANTING (MEMBE' +
   'R 10)'
   ag3a_72d_1    'Number of hours per day [NAME] spent on LAND PREPARATION & PLANTI' +
   'NG (MEMBER 1)'
   ag3a_72d_2    'Number of hours per day [NAME] spent on LAND PREPARATION & PLANTI' +
   'NG (MEMBER 2)'
   ag3a_72d_3    'Number of hours per day [NAME] spent on LAND PREPARATION & PLANTI' +
   'NG (MEMBER 3)'
   ag3a_72d_4    'Number of hours per day [NAME] spent on LAND PREPARATION & PLANTI' +
   'NG (MEMBER 4)'
   ag3a_72d_5    'Number of hours per day [NAME] spent on LAND PREPARATION & PLANTI' +
   'NG (MEMBER 5)'
   ag3a_72d_6    'Number of hours per day [NAME] spent on LAND PREPARATION & PLANTI' +
   'NG (MEMBER 6)'
   ag3a_72d_7    'Number of hours per day [NAME] spent on LAND PREPARATION & PLANTI' +
   'NG (MEMBER 7)'
   ag3a_72d_8    'Number of hours per day [NAME] spent on LAND PREPARATION & PLANTI' +
   'NG (MEMBER 8)'
   ag3a_72d_9    'Number of hours per day [NAME] spent on LAND PREPARATION & PLANTI' +
   'NG (MEMBER 9)'
   ag3a_72d_10    'Number of hours per day [NAME] spent on LAND PREPARATION & PLANTI' +
   'NG (MEMBER 10)'
   ag3a_72e 'HH member spent time on WEEDING/RIDGING/FERTILIZING on [PLOT]'
   ag3a_72f_1 'Which member? (ID 1)'
   ag3a_72f_2 'Which member? (ID 2)'
   ag3a_72f_3 'Which member? (ID 3)'
   ag3a_72f_4 'Which member? (ID 4)'
   ag3a_72f_5 'Which member? (ID 5)'
   ag3a_72f_6 'Which member? (ID 6)'
   ag3a_72f_7 'Which member? (ID 7)'
   ag3a_72f_8 'Which member? (ID 8)'
   ag3a_72f_9 'Which member? (ID 9)'
   ag3a_72f_10 'Which member? (ID 10)'
   ag3a_72g_1    'Number of days [NAME] spent on WEEDING/RIDGING/FERTILIZING (MEMBE' +
   'R 1)'
   ag3a_72g_2    'Number of days [NAME] spent on WEEDING/RIDGING/FERTILIZING (MEMBE' +
   'R 2)'
   ag3a_72g_3    'Number of days [NAME] spent on WEEDING/RIDGING/FERTILIZING (MEMBE' +
   'R 3)'
   ag3a_72g_4    'Number of days [NAME] spent on WEEDING/RIDGING/FERTILIZING (MEMBE' +
   'R 4)'
   ag3a_72g_5    'Number of days [NAME] spent on WEEDING/RIDGING/FERTILIZING (MEMBE' +
   'R 5)'
   ag3a_72g_6    'Number of days [NAME] spent on WEEDING/RIDGING/FERTILIZING (MEMBE' +
   'R 6)'
   ag3a_72g_7    'Number of days [NAME] spent on WEEDING/RIDGING/FERTILIZING (MEMBE' +
   'R 7)'
   ag3a_72g_8    'Number of days [NAME] spent on WEEDING/RIDGING/FERTILIZING (MEMBE' +
   'R 8)'
   ag3a_72g_9    'Number of days [NAME] spent on WEEDING/RIDGING/FERTILIZING (MEMBE' +
   'R 9)'
   ag3a_72g_10    'Number of days [NAME] spent on WEEDING/RIDGING/FERTILIZING (MEMBE' +
   'R 10)'
   ag3a_72h_1    'Number of hours per day [NAME] spent on WEEDING/RIDGING/FERTILIZI' +
   'NG (MEMBER 1)'
   ag3a_72h_2    'Number of hours per day [NAME] spent on WEEDING/RIDGING/FERTILIZI' +
   'NG (MEMBER 2)'
   ag3a_72h_3    'Number of hours per day [NAME] spent on WEEDING/RIDGING/FERTILIZI' +
   'NG (MEMBER 3)'
   ag3a_72h_4    'Number of hours per day [NAME] spent on WEEDING/RIDGING/FERTILIZI' +
   'NG (MEMBER 4)'
   ag3a_72h_5    'Number of hours per day [NAME] spent on WEEDING/RIDGING/FERTILIZI' +
   'NG (MEMBER 5)'
   ag3a_72h_6    'Number of hours per day [NAME] spent on WEEDING/RIDGING/FERTILIZI' +
   'NG (MEMBER 6)'
   ag3a_72h_7    'Number of hours per day [NAME] spent on WEEDING/RIDGING/FERTILIZI' +
   'NG (MEMBER 7)'
   ag3a_72h_8    'Number of hours per day [NAME] spent on WEEDING/RIDGING/FERTILIZI' +
   'NG (MEMBER 8)'
   ag3a_72h_9    'Number of hours per day [NAME] spent on WEEDING/RIDGING/FERTILIZI' +
   'NG (MEMBER 9)'
   ag3a_72h_10    'Number of hours per day [NAME] spent on WEEDING/RIDGING/FERTILIZI' +
   'NG (MEMBER 10)'
   ag3a_72i 'HH member spent time on HARVESTING & THRESHING on [PLOT]'
   ag3a_72j_1 'Which member? (ID 1)'
   ag3a_72j_2 'Which member? (ID 2)'
   ag3a_72j_3 'Which member? (ID 3)'
   ag3a_72j_4 'Which member? (ID 4)'
   ag3a_72j_5 'Which member? (ID 5)'
   ag3a_72j_6 'Which member? (ID 6)'
   ag3a_72j_7 'Which member? (ID 7)'
   ag3a_72j_8 'Which member? (ID 8)'
   ag3a_72j_9 'Which member? (ID 9)'
   ag3a_72j_10 'Which member? (ID 10)'
   ag3a_72k_1 'Number of days [NAME] spent on HARVESTING & THRESHING (MEMBER 1)'
   ag3a_72k_2 'Number of days [NAME] spent on HARVESTING & THRESHING (MEMBER 2)'
   ag3a_72k_3 'Number of days [NAME] spent on HARVESTING & THRESHING (MEMBER 3)'
   ag3a_72k_4 'Number of days [NAME] spent on HARVESTING & THRESHING (MEMBER 4)'
   ag3a_72k_5 'Number of days [NAME] spent on HARVESTING & THRESHING (MEMBER 5)'
   ag3a_72k_6 'Number of days [NAME] spent on HARVESTING & THRESHING (MEMBER 6)'
   ag3a_72k_7 'Number of days [NAME] spent on HARVESTING & THRESHING (MEMBER 7)'
   ag3a_72k_8 'Number of days [NAME] spent on HARVESTING & THRESHING (MEMBER 8)'
   ag3a_72k_9 'Number of days [NAME] spent on HARVESTING & THRESHING (MEMBER 9)'
   ag3a_72k_10    'Number of days [NAME] spent on HARVESTING & THRESHING (MEMBER 10)'
   ag3a_72l_1    'Number of hours per day [NAME] spent on HARVESTING & THRESHING (M' +
   'EMBER 1)'
   ag3a_72l_2    'Number of hours per day [NAME] spent on HARVESTING & THRESHING (M' +
   'EMBER 2)'
   ag3a_72l_3    'Number of hours per day [NAME] spent on HARVESTING & THRESHING (M' +
   'EMBER 3)'
   ag3a_72l_4    'Number of hours per day [NAME] spent on HARVESTING & THRESHING (M' +
   'EMBER 4)'
   ag3a_72l_5    'Number of hours per day [NAME] spent on HARVESTING & THRESHING (M' +
   'EMBER 5)'
   ag3a_72l_6    'Number of hours per day [NAME] spent on HARVESTING & THRESHING (M' +
   'EMBER 6)'
   ag3a_72l_7    'Number of hours per day [NAME] spent on HARVESTING & THRESHING (M' +
   'EMBER 7)'
   ag3a_72l_8    'Number of hours per day [NAME] spent on HARVESTING & THRESHING (M' +
   'EMBER 8)'
   ag3a_72l_9    'Number of hours per day [NAME] spent on HARVESTING & THRESHING (M' +
   'EMBER 9)'
   ag3a_72l_10    'Number of hours per day [NAME] spent on HARVESTING & THRESHING (M' +
   'EMBER 10)'
   ag3a_73    'Did you hire any labor to work on [PLOT] in the long rainy season' +
   ' 2020?'
   ag3a_74_1a 'Land Preparation & Planting - Number of days [WOMAN]'
   ag3a_74_1b 'Land Preparation & Planting - Number of days [MAN]'
   ag3a_74_1c 'Land Preparation & Planting - Number of days [CHILD]'
   ag3a_74_1d 'Land Preparation & Planting - Total Wage Paid [TSH]'
   ag3a_74_2a 'Weeding, Ridging, Fertilizing, etc. - Number of days [WOMAN]'
   ag3a_74_2b 'Weeding, Ridging, Fertilizing, etc. - Number of days [MAN]'
   ag3a_74_2c 'Weeding, Ridging, Fertilizing, etc. - Number of days [CHILD]'
   ag3a_74_2d 'Weeding, Ridging, Fertilizing, etc. - Total Wage Paid [TSH]'
   ag3a_74_3a 'Harvesting & Threshing, etc. - Number of days [WOMAN]'
   ag3a_74_3b 'Harvesting & Threshing, etc. - Number of days [MAN]'
   ag3a_74_3c 'Harvesting & Threshing, etc. - Number of days [CHILD]'
   ag3a_74_3d 'Harvesting & Threshing, etc. - Total Wage Paid [TSH]'
   ag3a_75 'CAPI: WHEN WAS THE LAST SHORT RAINY SEASON?'
   ag3a_76 'Did you cultivate [PLOT] in the short rainy season 2019?'
   ag3a_77    'What was the main crop cultivated on [PLOT] in the short rainy se' +
   'ason 2019?'
   ag3a_78 'Did you have use of [PLOT] in the short rainy season 2019?'
   ag3a_79 'How did you acquire [PLOT] for the long rainy season 2020?'
   ag3a_80 'How did you use [PLOT] during the short rainy season 2019?'
   ag3a_81 'Did you cultivate [PLOT] in the short rainy season 2020?'
   ag3a_82    'What was the main crop cultivated on [PLOT] in the short rainy se' +
   'ason 2020?'
   ag3a_83 'Did you have use of [PLOT] in the short rainy season 2020?'
   ag3a_84    'Why did you not have [PLOT] (owned or cultivated) in short rainy ' +
   'season 2020?'
   ag3a_85 'How did you use [PLOT] during the short rainy season 2020?' .

VALUE LABELS
 ag3a_03
     1 'CULTIVATED'
     2 'RENTED OUT'
     3 'GIVEN OUT'
     4 'FALLOW'
     5 'FOREST'
     6 'OTHER (SPECIFY)' /
 ag3a_07
     11 'MAIZE'
     12 'PADDY'
     13 'SORGHUM'
     14 'BULRUSH MILLET'
     15 'FINGER MILLET'
     16 'WHEAT'
     17 'BARLEY'
     18 'BLACK PEPPER'
     19 'SEAWEED'
     21 'CASSAVA'
     22 'SWEET POTATOES'
     23 'IRISH POTATOES'
     24 'YAMS'
     25 'COCOYAMS'
     26 'ONIONS'
     27 'GINGER'
     31 'BEANS'
     32 'COWPEAS'
     33 'GREEN GRAM'
     34 'PIGEON PEA'
     35 'CHICK PEAS'
     36 'BAMBARA NUTS'
     37 'FIELD PEAS'
     38 'MALAY APPLE'
     39 'STAR FRUIT'
     41 'SUNFLOWER'
     42 'SESAME'
     43 'GROUNDNUT'
     44 'PALM OIL'
     45 'COCONUT'
     46 'CASHEW NUT'
     47 'SOYABEANS'
     48 'CASTER SEED'
     50 'COTTON'
     51 'TOBACCO'
     52 'PYRETHRUM'
     53 'SISAL'
     54 'COFFEE'
     55 'TEA'
     56 'COCOA'
     57 'RUBBER'
     58 'WATTLE'
     59 'KAPOK'
     60 'SUGAR CANE'
     61 'CARDAMOM'
     62 'JUTE'
     63 'TAMARIND'
     64 'CINNAMON'
     65 'NUTMEG'
     66 'CLOVE'
     67 'BREAD FRUIT'
     68 'POMELO'
     69 'JACK FRUIT'
     70 'PASSION FRUIT'
     71 'BANANA'
     72 'AVOCADO'
     73 'MANGO'
     74 'PAPAW'
     75 'PINEAPPLE'
     76 'ORANGE'
     77 'GRAPEFRUIT'
     78 'GRAPES'
     79 'MANDARIN'
     80 'GUAVA'
     81 'PLUMS'
     82 'APPLES'
     83 'PEARS'
     84 'PEACHES'
     86 'CABBAGE'
     87 'TOMATOES'
     88 'SPINACH'
     89 'CARROT'
     90 'CHILIES'
     91 'AMARANTHS'
     92 'PUMPKINS'
     93 'CUCUMBER'
     94 'EGG PLANT'
     95 'WATER MELLON'
     96 'CAULIFLOWER'
     97 'DURIAN'
     98 'BILIMBI'
     99 'RAMBUTAN'
     100 'OKRA'
     101 'FIWI'
     200 'CUSTARD APPLE'
     201 'GOD FRUIT'
     202 'MITOBO'
     203 'PLUM'
     204 'PEACHES'
     205 'POMEGRANATE'
     210 'DATE'
     211 'TUNGAMAA'
     212 'VANILLA'
     300 'GREEN TOMATO'
     301 'MONKEYBREAD'
     302 'BAMBOO'
     303 'FIREWOOD/FODDER'
     304 'TIMBER'
     305 'MEDICINAL PLANT'
     306 'FENCE TREE'
     851 'LIME'
     852 'LEMON'
     998 'OTHER (SPECIFY)' /
 ag3a_08a_1
     0 'NO'
     1 'YES' /
 ag3a_08a_2
     0 'NO'
     1 'YES' /
 ag3a_08c1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag3a_08c2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag3a_09a_1
     0 'NO'
     1 'YES' /
 ag3a_09a_2
     0 'NO'
     1 'YES' /
 ag3a_09c1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag3a_09c2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag3a_10
     1 'SANDY'
     2 'LOAM'
     3 'CLAY'
     4 'OTHER (SPECIFY)' /
 ag3a_11
     1 'GOOD'
     2 'AVERAGE'
     3 'BAD' /
 ag3a_12
     1 'SCIENTIFICALLY TESTED'
     2 'OWN EXPERIENCE'
     3 'OTHER (SPECIFY)' /
 ag3a_13
     1 'YES'
     2 'NO' /
 ag3a_14
     1 'WIND'
     2 'RAIN'
     3 'ANIMALS'
     4 'CULTIVATION WHICH DOES NOT COMPLY WITH SOIL CONSERVATION'
     5 'OTHER (SPECIFY)' /
 ag3a_15
     1 'YES'
     2 'NO' /
 ag3a_16_1
     1 'TERRACES'
     2 'EROSION CONTROL BUNDS'
     3 'GABIONS/SANDBAGS'
     4 'VETIVER GRASS'
     5 'TREE BELTS'
     6 'WATER HARVEST BUNDS'
     7 'DRAINAGE DITCHES'
     8 'DAM' /
 ag3a_16_2
     1 'TERRACES'
     2 'EROSION CONTROL BUNDS'
     3 'GABIONS/SANDBAGS'
     4 'VETIVER GRASS'
     5 'TREE BELTS'
     6 'WATER HARVEST BUNDS'
     7 'DRAINAGE DITCHES'
     8 'DAM' /
 ag3a_17
     1 'FLAT BOTTOM'
     2 'FLAT TOP'
     3 'SLIGHTLY SLOPED'
     4 'VERY STEEP' /
 ag3a_18
     1 'YES'
     2 'NO' /
 ag3a_19
     1 'FLOODING'
     2 'SPRINKLER'
     3 'DRIP IRRIGATION'
     4 'BUCKET/WATERING CAN'
     5 'WATER HOSE'
     6 'OTHER (SPECIFY)' /
 ag3a_20
     1 'GRAVITY'
     2 'HAND BUCKET'
     3 'HAND/FOOT PUMP'
     4 'MOTOR PUMP'
     5 'OTHER (SPECIFY)' /
 ag3a_21
     1 'WELL'
     2 'BOREHOLE'
     3 'POND/TANK'
     4 'RIVER/STREAM'
     5 'OTHER (SPECIFY)' /
 ag3a_22
     0 'NEVER'
     98 "DON'T KNOW" /
 ag3a_25
     1 'INHERITANCE'
     2 'GIFT'
     3 'BORROWING FROM FAMILY MEMBER'
     4 'LAND ALLOCATION FROM  VILLAGE COUNCIL'
     5 'PURCHASED'
     6 'USED FREE OF CHARGE'
     7 'RENTED IN'
     8 'SHARED - RENT'
     9 'SHARED - OWN'
     10 'SQUATTING, CLEARING'
     11 'OTHER, SPECIFY' /
 ag3a_26_1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag3a_26_2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag3a_27
     1 'NOTHING'
     2 'ALMOST NOTHING'
     3 'ONE QUARTER'
     4 'HALF'
     5 'THREE QUARTERS'
     6 'ALMOST ALL' /
 ag3a_28a
     1 'GRANTED RIGHT OF OCCUPANCY'
     2 'CERTIFICATE OF CUSTOMARY RIGHTS  OF OCCUPANCY'
     3 'NO CERTIFICATE' /
 ag3a_28b
     1 'YES'
     2 'NO' /
 ag3a_28c
     1 'YES'
     2 'NO' /
 ag3a_28d
     1 'VILLAGE-GOVERNMENT-WITNESSED PURCHASE AGREEMENT'
     2 'LOCAL-COURT-CERTIFIED PURCHASE AGREEMENT'
     3 'INHERITANCE LETTER'
     4 "LETTER OF ALLOCATION FROM VILLAGE GOV'T"
     5 'OTHER GOVERNMENT DOCUMENT'
     6 'OFFICIAL CORRESPONDENCE'
     7 'UTILITY OR OTHER BILL'
     8 'NO DOCUMENTATION' /
 ag3a_30
     1 'YES'
     2 'NO' /
 ag3a_31a
     1 'YES'
     2 'NO' /
 ag3a_32_1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag3a_32_2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag3a_33
     0 'NO PAYMENT' /
 ag3a_34_2
     1 'MONTHS'
     2 'YEARS' /
 ag3a_35
     1 'NONE'
     2 'ALMOST NONE'
     3 'ABOUT 25%'
     4 'ABOUT 50%'
     5 'ABOUT 75%'
     6 'ALMOST ALL' /
 ag3a_36_1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag3a_36_2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag3a_38a
     1 'YES'
     2 'NO' /
 ag3a_39
     1 'YES'
     2 'NO' /
 ag3a_40
     1 'YES'
     2 'NO' /
 ag3a_41
     1 'YES'
     2 'NO' /
 ag3a_43
     1 'YES'
     2 'NO' /
 ag3a_46_1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag3a_46_2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag3a_47
     1 'YES'
     2 'NO' /
 ag3a_48
     1 'DI-AMMOIUM PHOSPHATE (DAP)'
     2 'UREA'
     3 'TRIPLE SUPER PHOSPHATE (TSP)'
     4 'CALCIUM AMMONIUM NITRATE (CAN)'
     5 'SULPHATE OF AMMONIUM (SA)'
     6 'NITROGEN PHOSPHATE POTASSIUM (NPK)'
     7 'MINJINGU ROCK PHOSPHATE (MRP)'
     8 'OTHER (SPECIFY)' /
 ag3a_52
     1 'ADVICE BY AGRICULTURAL OFFICER'
     2 'RECEIVED VOUCHER'
     3 'OWN EXPERIENCE'
     4 'NEIGHBOUR ADVICE'
     5 'OTHER (SPECIFY)' /
 ag3a_53_1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag3a_53_2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag3a_54
     1 'YES'
     2 'NO' /
 ag3a_55
     1 'DI-AMMOIUM PHOSPHATE (DAP)'
     2 'UREA'
     3 'TRIPLE SUPER PHOSPHATE (TSP)'
     4 'CALCIUM AMMONIUM NITRATE (CAN)'
     5 'SULPHATE OF AMMONIUM (SA)'
     6 'NITROGEN PHOSPHATE POTASSIUM (NPK)'
     7 'MINJINGU ROCK PHOSPHATE (MRP)'
     8 'OTHER (SPECIFY)' /
 ag3a_59_1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag3a_59_2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag3a_60
     1 'YES'
     2 'NO' /
 ag3a_62_2
     1 'KG'
     2 'LITRE'
     3 'MILLILITRE'
     4 'OTHER (SPECIFY)' /
 ag3a_64
     1 'ADVICE BY AGRICULTURAL OFFICER'
     2 'RECEIVED VOUCHER'
     3 'OWN EXPERIENCE'
     4 'NEIGHBOUR ADVICE'
     5 'OTHER (SPECIFY)' /
 ag3a_65_1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag3a_65_2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag3a_65a
     1 'YES'
     2 'NO' /
 ag3a_65b_2
     1 'KG'
     2 'LITRE'
     3 'MILLILITRE'
     4 'OTHER,SPECIFY' /
 ag3a_65d
     1 'ADVICE BY AGRICULTURAL OFFICER'
     2 'RECEIVED VOUCHER'
     3 'OWN EXPERIENCE'
     4 'NEIGHBOUR ADVICE'
     5 'OTHER (SPECIFY)' /
 ag3a_65e_1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag3a_65e_2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag3a_66
     1 'YES'
     2 'NO' /
 ag3a_67_1 ag3a_67_2 ag3a_67_3 ag3a_67_4
     0 'NO'
     1 'YES' /
 ag3a_70_2
     1 'THIS CROP (KGs)'
     2 'LABOR (DAYS)'
     3 'OTHER (SPECIFY)' /
 ag3a_71_1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag3a_71_2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag3a_71a
     1 'YES'
     2 'NO' /
 ag3a_71b
     1 'YES'
     2 'NO' /
 ag3a_72a
     1 'YES'
     2 'NO' /
 ag3a_72e
     1 'YES'
     2 'NO' /
 ag3a_72i
     1 'YES'
     2 'NO' /
 ag3a_73
     1 'YES'
     2 'NO' /
 ag3a_75
     1 'OCT-DEC 2019'
     2 'OCT-DEC 2020' /
 ag3a_76
     1 'YES'
     2 'NO' /
 ag3a_77
     11 'MAIZE'
     12 'PADDY'
     13 'SORGHUM'
     14 'BULRUSH MILLET'
     15 'FINGER MILLET'
     16 'WHEAT'
     17 'BARLEY'
     18 'BLACK PEPPER'
     19 'SEAWEED'
     21 'CASSAVA'
     22 'SWEET POTATOES'
     23 'IRISH POTATOES'
     24 'YAMS'
     25 'COCOYAMS'
     26 'ONIONS'
     27 'GINGER'
     31 'BEANS'
     32 'COWPEAS'
     33 'GREEN GRAM'
     34 'PIGEON PEA'
     35 'CHICK PEAS'
     36 'BAMBARA NUTS'
     37 'FIELD PEAS'
     38 'MALAY APPLE'
     39 'STAR FRUIT'
     41 'SUNFLOWER'
     42 'SESAME'
     43 'GROUNDNUT'
     44 'PALM OIL'
     45 'COCONUT'
     46 'CASHEW NUT'
     47 'SOYABEANS'
     48 'CASTER SEED'
     50 'COTTON'
     51 'TOBACCO'
     52 'PYRETHRUM'
     53 'SISAL'
     54 'COFFEE'
     55 'TEA'
     56 'COCOA'
     57 'RUBBER'
     58 'WATTLE'
     59 'KAPOK'
     60 'SUGAR CANE'
     61 'CARDAMOM'
     62 'JUTE'
     63 'TAMARIND'
     64 'CINNAMON'
     65 'NUTMEG'
     66 'CLOVE'
     67 'BREAD FRUIT'
     68 'POMELO'
     69 'JACK FRUIT'
     70 'PASSION FRUIT'
     71 'BANANA'
     72 'AVOCADO'
     73 'MANGO'
     74 'PAPAW'
     75 'PINEAPPLE'
     76 'ORANGE'
     77 'GRAPEFRUIT'
     78 'GRAPES'
     79 'MANDARIN'
     80 'GUAVA'
     81 'PLUMS'
     82 'APPLES'
     83 'PEARS'
     84 'PEACHES'
     86 'CABBAGE'
     87 'TOMATOES'
     88 'SPINACH'
     89 'CARROT'
     90 'CHILIES'
     91 'AMARANTHS'
     92 'PUMPKINS'
     93 'CUCUMBER'
     94 'EGG PLANT'
     95 'WATER MELLON'
     96 'CAULIFLOWER'
     97 'DURIAN'
     98 'BILIMBI'
     99 'RAMBUTAN'
     100 'OKRA'
     101 'FIWI'
     200 'CUSTARD APPLE'
     201 'GOD FRUIT'
     202 'MITOBO'
     203 'PLUM'
     204 'PEACHES'
     205 'POMEGRANATE'
     210 'DATE'
     211 'TUNGAMAA'
     212 'VANILLA'
     300 'GREEN TOMATO'
     301 'MONKEYBREAD'
     302 'BAMBOO'
     303 'FIREWOOD/FODDER'
     304 'TIMBER'
     305 'MEDICINAL PLANT'
     306 'FENCE TREE'
     851 'LIME'
     852 'LEMON'
     998 'OTHER (SPECIFY)' /
 ag3a_78
     1 'YES'
     2 'NO' /
 ag3a_79
     1 'BOUGHT IT'
     2 'INHERITED'
     3 'STARTED RENTING/SHARECROPPING'
     4 'CLEARED IT'
     5 'DISTRIBUTED BY VILLAGE'
     6 'RECEIVED AS GIFT'
     7 'OCCUPIED' /
 ag3a_80
     1 'RENTED'
     2 'GIVEN'
     3 'FALLOW'
     4 'FOREST'
     5 'OTHER (SPECIFY)' /
 ag3a_81
     1 'YES'
     2 'NO' /
 ag3a_82
     11 'MAIZE'
     12 'PADDY'
     13 'SORGHUM'
     14 'BULRUSH MILLET'
     15 'FINGER MILLET'
     16 'WHEAT'
     17 'BARLEY'
     18 'BLACK PEPPER'
     19 'SEAWEED'
     21 'CASSAVA'
     22 'SWEET POTATOES'
     23 'IRISH POTATOES'
     24 'YAMS'
     25 'COCOYAMS'
     26 'ONIONS'
     27 'GINGER'
     31 'BEANS'
     32 'COWPEAS'
     33 'GREEN GRAM'
     34 'PIGEON PEA'
     35 'CHICK PEAS'
     36 'BAMBARA NUTS'
     37 'FIELD PEAS'
     38 'MALAY APPLE'
     39 'STAR FRUIT'
     41 'SUNFLOWER'
     42 'SESAME'
     43 'GROUNDNUT'
     44 'PALM OIL'
     45 'COCONUT'
     46 'CASHEW NUT'
     47 'SOYABEANS'
     48 'CASTER SEED'
     50 'COTTON'
     51 'TOBACCO'
     52 'PYRETHRUM'
     53 'SISAL'
     54 'COFFEE'
     55 'TEA'
     56 'COCOA'
     57 'RUBBER'
     58 'WATTLE'
     59 'KAPOK'
     60 'SUGAR CANE'
     61 'CARDAMOM'
     62 'JUTE'
     63 'TAMARIND'
     64 'CINNAMON'
     65 'NUTMEG'
     66 'CLOVE'
     67 'BREAD FRUIT'
     68 'POMELO'
     69 'JACK FRUIT'
     70 'PASSION FRUIT'
     71 'BANANA'
     72 'AVOCADO'
     73 'MANGO'
     74 'PAPAW'
     75 'PINEAPPLE'
     76 'ORANGE'
     77 'GRAPEFRUIT'
     78 'GRAPES'
     79 'MANDARIN'
     80 'GUAVA'
     81 'PLUMS'
     82 'APPLES'
     83 'PEARS'
     84 'PEACHES'
     86 'CABBAGE'
     87 'TOMATOES'
     88 'SPINACH'
     89 'CARROT'
     90 'CHILIES'
     91 'AMARANTHS'
     92 'PUMPKINS'
     93 'CUCUMBER'
     94 'EGG PLANT'
     95 'WATER MELLON'
     96 'CAULIFLOWER'
     97 'DURIAN'
     98 'BILIMBI'
     99 'RAMBUTAN'
     100 'OKRA'
     101 'FIWI'
     200 'CUSTARD APPLE'
     201 'GOD FRUIT'
     202 'MITOBO'
     203 'PLUM'
     204 'PEACHES'
     205 'POMEGRANATE'
     210 'DATE'
     211 'TUNGAMAA'
     212 'VANILLA'
     300 'GREEN TOMATO'
     301 'MONKEYBREAD'
     302 'BAMBOO'
     303 'FIREWOOD/FODDER'
     304 'TIMBER'
     305 'MEDICINAL PLANT'
     306 'FENCE TREE'
     851 'LIME'
     852 'LEMON'
     998 'OTHER (SPECIFY)' /
 ag3a_83
     1 'YES'
     2 'NO' /
 ag3a_84
     1 'SOLD IT'
     2 'ABANDONED'
     3 'TAKEN'
     4 'REDISTR BY VILLAGE'
     5 'GIVEN AWAY'
     6 'STOPPED RENTING/SHARECROPPING' /
 ag3a_85
     1 'RENTED'
     2 'GIVEN'
     3 'FALLOW'
     4 'FOREST'
     5 'OTHER (SPECIFY)' / .


SAVE OUTFILE='.\ag_sec_3a.sav'.
