/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\ag_sec_4b.dat" ENCODING="CP1252" / LRECL=130 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        plot_id 23            
   cropid 24-26             ag4b_01 27               ag4b_02 28            
   ag4b_03 29               ag4b_04 30               ag4b_05 31            
   ag4b_06 32-68 (A)        ag4b_08 69               ag4b_10_1 70-73       
   ag4b_10_2 74             ag4b_10a_1 75-78         ag4b_10a_2 79         
   ag4b_10b 80              ag4b_10c_1 81-84         ag4b_10c_2 85         
   ag4b_12 86-91            ag4b_13_1 92-93          ag4b_13_2 94          
   ag4b_17 95               ag4b_18 96               ag4b_19 97            
   ag4b_20 98               ag4b_21 99-102           ag4b_22 103           
   ag4b_23 104              ag4b_24_1 105-106        ag4b_24_2 107-108     
   ag4b_25 109              ag4b_26 110-111          ag4b_27 112-113       
   ag4b_28 114-118          ag4b_29 119-126          ag4b_30_1 127-128     
   ag4b_30_2 129-130 .   


FORMATS
  ag4b_10_1 (F5.2) /       ag4b_10a_1 (F5.2) /      ag4b_10c_1 (F5.1) /    
  ag4b_21 (F5.2) /         ag4b_28 (F6.1) / .
    
VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   plot_id 'PLOT ID'
   cropid 'CROP CODE'
   ag4b_01 'Was crop planted in entire area of plot?'
   ag4b_02 'Approximately, how much of the plot was planted with [CROP]?'
   ag4b_03 "Why didn't you plant the entire plot with [CROP]?"
   ag4b_04 'Was cultivation intercropped?'
   ag4b_05 'What is the reason for this intercropping?'
   ag4b_06    'What was the name of the main seed variety for this [CROP] on thi' +
   's plot?'
   ag4b_08 'Were the main seeds...'
   ag4b_10_1 'What was the total amount of seeds used? (QUANTITY)'
   ag4b_10_2 'What was the total amount of seeds used? (UNIT)'
   ag4b_10a_1    'What was the total seeds used on plot came from the previous seas' +
   'on? (QUANTITY)'
   ag4b_10a_2    'What was the total seeds used on plot came from the previous seas' +
   'on? (UNIT)'
   ag4b_10b 'What type of seed were the seeds from the previous season?'
   ag4b_10c_1    'How much of the total seed used on plot came from purchases? (QUA' +
   'NTITY)'
   ag4b_10c_2    'How much of the total seed used on plot came from purchases? (UNI' +
   'T)'
   ag4b_12 'What was the total amount paid for seeds? (TSH)'
   ag4b_13_1 'Where did you buy most of the seeds?'
   ag4b_13_2 'Where is [SELLER] located?'
   ag4b_17 'Were there any losses of crops before the harvest?'
   ag4b_18 'What was the cause of these losses?'
   ag4b_19    'Did you harvest any [CROP] on [PLOT] in the last short rainy seas' +
   'on?'
   ag4b_20 "Why didn't you harvest any [CROP] on this plot?"
   ag4b_21 'What was the area harvested in the last short rainy season?'
   ag4b_22 'Was area harvested less than area planted?'
   ag4b_23 'What was the reason it was less than the area planted?'
   ag4b_24_1 'What was the first and last month of the harvest period? (BEGIN)'
   ag4b_24_2 'What was the first and last month of the harvest period? (END)'
   ag4b_25 'Have you finished the harvest?'
   ag4b_26 'How many more days do you expect the harvest to last?'
   ag4b_27    'What fraction of the crop remains to be harvested in this period?'
   ag4b_28 'What was the quantity harvested?'
   ag4b_29 'What is the estimated value of the harvested crop?'
   ag4b_30_1    'Who in HH made the decisions concerning the use of the harvested ' +
   'crop? (ID 1)'
   ag4b_30_2    'Who in HH made the decisions concerning the use of the harvested ' +
   'crop? (ID 2)' .

VALUE LABELS
 cropid
     11 'MAIZE'
     12 'PADDY'
     13 'SORGHUM'
     14 'BULRUSH MILLET'
     15 'FINGER MILLET'
     16 'WHEAT'
     17 'BARLEY'
     18 'BLACK PEPPER'
     19 'SEAWEED'
     21 'CASSAVA'
     22 'SWEET POTATOES'
     23 'IRISH POTATOES'
     24 'YAMS'
     25 'COCOYAMS'
     26 'ONIONS'
     27 'GINGER'
     31 'BEANS'
     32 'COWPEAS'
     33 'GREEN GRAM'
     34 'PIGEON PEA'
     35 'CHICK PEAS'
     36 'BAMBARA NUTS'
     37 'FIELD PEAS'
     38 'MALAY APPLE'
     39 'STAR FRUIT'
     41 'SUNFLOWER'
     42 'SESAME'
     43 'GROUNDNUT'
     44 'PALM OIL'
     45 'COCONUT'
     46 'CASHEW NUT'
     47 'SOYABEANS'
     48 'CASTER SEED'
     50 'COTTON'
     51 'TOBACCO'
     52 'PYRETHRUM'
     53 'SISAL'
     54 'COFFEE'
     55 'TEA'
     56 'COCOA'
     57 'RUBBER'
     58 'WATTLE'
     59 'KAPOK'
     60 'SUGAR CANE'
     61 'CARDAMOM'
     62 'JUTE'
     63 'TAMARIND'
     64 'CINNAMON'
     65 'NUTMEG'
     66 'CLOVE'
     67 'BREAD FRUIT'
     68 'POMELO'
     69 'JACK FRUIT'
     70 'PASSION FRUIT'
     71 'BANANA'
     72 'AVOCADO'
     73 'MANGO'
     74 'PAPAW'
     75 'PINEAPPLE'
     76 'ORANGE'
     77 'GRAPEFRUIT'
     78 'GRAPES'
     79 'MANDARIN'
     80 'GUAVA'
     81 'PLUMS'
     82 'APPLES'
     83 'PEARS'
     84 'PEACHES'
     86 'CABBAGE'
     87 'TOMATOES'
     88 'SPINACH'
     89 'CARROT'
     90 'CHILIES'
     91 'AMARANTHS'
     92 'PUMPKINS'
     93 'CUCUMBER'
     94 'EGG PLANT'
     95 'WATER MELLON'
     96 'CAULIFLOWER'
     97 'DURIAN'
     98 'BILIMBI'
     99 'RAMBUTAN'
     100 'OKRA'
     101 'FIWI'
     200 'CUSTARD APPLE'
     201 'GOD FRUIT'
     202 'MITOBO'
     203 'PLUM'
     204 'PEACHES'
     205 'POMEGRANATE'
     210 'DATE'
     211 'TUNGAMAA'
     212 'VANILLA'
     300 'GREEN TOMATO'
     301 'MONKEYBREAD'
     302 'BAMBOO'
     303 'FIREWOOD/FODDER'
     304 'TIMBER'
     305 'MEDICINAL PLANT'
     306 'FENCE TREE'
     851 'LIME'
     852 'LEMON'
     998 'OTHER (SPECIFY)' /
 ag4b_01
     1 'YES'
     2 'NO' /
 ag4b_02
     1 '1/4'
     2 '1/2'
     3 '3/4' /
 ag4b_03
     1 'WAS DIVIDED'
     2 'DROUGHT'
     3 'LACK OF TOOLS/EQUIPMENTS'
     4 'LACK SEEDS'
     5 'FLOODS'
     6 'LOANS'
     7 'AG EQUIPMENTS'
     8 'OTHER, SPECIFY' /
 ag4b_04
     1 'YES'
     2 'NO' /
 ag4b_05
     1 'SUBSTITUTE IF EITHER CROP FAILS'
     2 'MORE FERTILE FOR THE SOIL'
     3 'OTHER (SPECIFY)' /
 ag4b_08
     1 'IMPROVED'
     2 'TRADITIONAL'
     3 'IMPROVED, RECYCLED'
     4 'OTHER (SPECIFY)' /
 ag4b_10_2
     1 'KG'
     2 '20 LITER BUCKET'
     3 'SMALL CUP'
     4 'LARGE CUP'
     5 'OTHER (SPECIFY)' /
 ag4b_10a_1
     0 'HAKUNA' /
 ag4b_10a_2
     1 'KG'
     2 '20 LITER BUCKET'
     3 'SMALL CUP'
     4 'LARGE CUP'
     5 'OTHER (SPECIFY)' /
 ag4b_10b
     1 'IMPROVED'
     2 'TRADITIONAL'
     3 'IMPROVED RECYCLED'
     4 'OTHER (SPECIFY)' /
 ag4b_10c_1
     0 'HAKUNA' /
 ag4b_10c_2
     1 'KG'
     2 '20 LITER BUCKET'
     3 'SMALL CUP'
     4 'LARGE CUP'
     5 'OTHER (SPECIFY)' /
 ag4b_13_1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag4b_13_2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag4b_17
     1 'YES'
     2 'NO' /
 ag4b_18
     1 'BIRDS'
     2 'ANIMALS'
     3 'INSECTS'
     4 'DISEASES'
     5 'THEFT'
     6 'OTHER (SPECIFY)'
     7 'FLOOD / RAIN'
     8 'DROUGHT' /
 ag4b_19
     1 'YES'
     2 'NO' /
 ag4b_20
     1 'NOT MINE TO HARVEST'
     2 'STILL IN PLOT'
     3 'DESTRUCTION'
     4 'OTHER (SPECIFY)' /
 ag4b_22
     1 'YES'
     2 'NO' /
 ag4b_23
     1 'DROUGHT'
     2 'RAINS'
     3 'FIRE'
     4 'INSECTS'
     5 'ANIMALS'
     6 'CROP THEFT'
     7 'DISEASES AND COMMUNITY PROBLEMS'
     8 'LACK OF CASUAL LABOR'
     9 'OTHER (SPECIFY)' /
 ag4b_24_1
     1 'JANUARY'
     2 'FEBRUARY'
     3 'MARCH'
     4 'APRIL'
     5 'MAY'
     6 'JUNE'
     7 'JULY'
     8 'AUGUST'
     9 'SEPTEMBER'
     10 'OCTOBER'
     11 'NOVEMBER'
     12 'DECEMBER' /
 ag4b_24_2
     0 'HARVEST NOT YET COMPLETE'
     1 'JANUARY'
     2 'FEBRUARY'
     3 'MARCH'
     4 'APRIL'
     5 'MAY'
     6 'JUNE'
     7 'JULY'
     8 'AUGUST'
     9 'SEPTEMBER'
     10 'OCTOBER'
     11 'NOVEMBER'
     12 'DECEMBER' /
 ag4b_25
     1 'YES'
     2 'NO' / .


SAVE OUTFILE='.\ag_sec_4b.sav'.
