/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\ag_sec_01.dat" ENCODING="CP1252" / LRECL=123 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        plot_id 23-24         
   plotname 25-40 (A)       ag01_01 41-43 (A)        ag01_02 44-59 (A)     
   ag01_03 60-75 (A)        ag01_04 76               ag01_05 77            
   ag01_06 78-79            ag01_07 80               ag01_08 81            
   ag01_09 82               ag01_10 83               ag01_11 84            
   ag01_12 85-92            ag01_13 93-100           ag01_16 101-116 (A)   
   ag01_17 117              ag01_18 118-119          ag01_19 120           
   ag01_20 121              ag01_21 122              ag01_22 123 .         

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   plot_id 'Plot ID'
   plotname 'Plot Name'
   ag01_01 'Previous Plot Number NPSY4'
   ag01_02 'Plot Name'
   ag01_03 'Description / Location'
   ag01_04 'Does the household still control this [PLOT]?'
   ag01_05    'Is this [PLOT] the piece of land on which the dwelling is located' +
   '?'
   ag01_06 'How was this [PLOT] acquired?'
   ag01_07 'Under which tenure system is this [PLOT]?'
   ag01_08 'What is the primary current use of this [PLOT]?'
   ag01_09    'In the last 12 months, has this [PLOT] been used for agriculture ' +
   'or for livestoc'
   ag01_10 'How is this plot currently being used?'
   ag01_11 'Why do you not have this [PLOT] (owned or cultivated) anymore?'
   ag01_12 'How much did you receive when you sold [PLOT]? (TSH)'
   ag01_13 'How much compensation did you receive for [PLOT]? (TSH)'
   ag01_16 'NEW PLOTS: Description / Location'
   ag01_17    'NEW PLOTS: Is this [PLOT] the piece of land on which the dwelling' +
   ' is located?'
   ag01_18 'NEW PLOTS: How was this [PLOT] acquired?'
   ag01_19 'NEW PLOTS: Under which tenure system is this [PLOT]?'
   ag01_20 'NEW PLOTS: What is the primary current use of this [PLOT]?'
   ag01_21    'NEW PLOTS: In the last 12 months, has this [PLOT] been used for a' +
   'griculture or f'
   ag01_22 'NEW PLOTS: How is this plot currently being used?' .

VALUE LABELS
 ag01_04
     1 'YES'
     2 'NO' /
 ag01_05
     1 'YES'
     2 'NO' /
 ag01_06
     1 'GRANTED BY CUSTOMARY/COMMUNITY AUTHORITIES'
     2 'ALLOCATED BY GOVERNMENT'
     3 'ALLOCATED BY FAMILY MEMBER'
     4 'INHERITED BY THE DEATH OF A FAMILY MEMBER'
     5 'PURCHASED'
     6 'RENTED IN, SHORT-TERM (< 3 YEARS)'
     7 'RENTED IN, LONG-TERM'
     8 'SHARECROPPED IN'
     9 'BORROWED FOR FREE'
     10 'BRIDE PRICE'
     11 'GIFT FROM NON-HOUSEHOLD MEMBER'
     12 'MOVED IN WITHOUT PERMISSION'
     13 'OTHER (SPECIFY)' /
 ag01_07
     1 'CUSTOMARY'
     2 'FREEHOLD'
     3 'LEASEHOLD'
     4 'STATE'
     5 'COMMUNITY/ GROUP RIGHT'
     6 'COOPERATIVES'
     7 'OTHER (SPECIFY)' /
 ag01_08
     1 'RESIDENTIAL'
     2 'AGRICULTURAL'
     3 'PASTORAL'
     4 'FOREST'
     5 'BUSINESS/COMMERCIAL'
     6 "DON'T KNOW"
     7 'OTHER (SPECIFY)' /
 ag01_09
     1 'YES'
     2 'NO' /
 ag01_10
     1 'CULTIVATED'
     2 'RENTED OUT'
     3 'GIVEN OUT'
     4 'FALLOW'
     5 'FOREST'
     6 'OTHER, SPECIFY' /
 ag01_11
     1 'SOLD IT'
     2 'ABANDONED'
     3 'TAKEN'
     4 'REDISTRIBUTED BY VILLAGE'
     5 'GIVEN AWAY'
     6 'STOPPED RENTING/SHARECROPPING' /
 ag01_17
     1 'YES'
     2 'NO' /
 ag01_18
     1 'GRANTED BY CUSTOMARY/COMMUNITY AUTHORITIES'
     2 'ALLOCATED BY GOVERNMENT'
     3 'ALLOCATED BY FAMILY MEMBER'
     4 'INHERITED BY THE DEATH OF A FAMILY MEMBER'
     5 'PURCHASED'
     6 'RENTED IN, SHORT-TERM (< 3 YEARS)'
     7 'RENTED IN, LONG-TERM.'
     8 'SHARECROPPED IN'
     9 'BORROWED FOR FREE'
     10 'BRIDE PRICE'
     11 'GIFT FROM NON-HOUSEHOLD MEMBER'
     12 'MOVED IN WITHOUT PERMISSION'
     13 'OTHER (SPECIFY)' /
 ag01_19
     1 'CUSTOMARY'
     2 'FREEHOLD'
     3 'LEASEHOLD'
     4 'STATE'
     5 'COMMUNITY/GROUPRIGHT'
     6 'COOPERATIVES'
     7 'OTHER (SPECIFY)' /
 ag01_20
     1 'RESIDENTIAL'
     2 'AGRICULTURAL'
     3 'PASTORAL'
     4 'FOREST'
     5 'BUSINESS/COMMERCIAL'
     6 "DON'T KNOW"
     7 'OTHER (SPECIFY)' /
 ag01_21
     1 'YES'
     2 'NO' /
 ag01_22
     1 'CULTIVATED'
     2 'RENTED OUT'
     3 'GIVEN OUT'
     4 'FALLOW'
     5 'FOREST'
     6 'OTHER (SPECIFY)' / .


SAVE OUTFILE='.\ag_sec_01.sav'.
