/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\ag_sec_02.dat" ENCODING="CP1252" / LRECL=163 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        plot_id 23-24         
   plotname 25-40 (A)       ag2a_03 41-56 (A)        ag2a_04 57-61         
   ag2a_05 62-64 (A)        ag2a_05a 65              ag2a_06 66            
   ag2a_07__Accuracy 67-82 (A)   ag2a_07__Altitude 83-98 (A)
   ag2a_07__Latitude 99-114 (A)   ag2a_07__Longitude 115-130 (A)
   ag2a_07__Timestamp 131-146 (A)   ag2a_07a 147-148      
   ag2a_07b 149             ag2a_07c_1 150-151       ag2a_07c_2 152-153    
   ag2a_07c_3 154-155       ag2a_08 156              ag2a_09 157-162       
   ag2a_10 163 .         


FORMATS
  ag2a_04 (F6.2) /         ag2a_09 (F7.2) / .
    
VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   plot_id 'Plot ID'
   plotname 'Plot Name'
   ag2a_03 'Description / Location'
   ag2a_04 'Area (Acres)'
   ag2a_05 'Previous Plot Number NPSY4'
   ag2a_05a    'Has any household member cultivated this field also in the short ' +
   'rainy season?'
   ag2a_06 'Was the plot measured?'
   ag2a_07__Accuracy 'PLOT LOCATION: GPS ACCURACY'
   ag2a_07__Altitude 'PLOT LOCATION: GPS ALTITUDE'
   ag2a_07__Latitude 'PLOT LOCATION: GPS LATITUDE'
   ag2a_07__Longitude 'PLOT LOCATION: GPS LONGITUDE'
   ag2a_07__Timestamp 'PLOT LOCATION: GPS TIME STAMP'
   ag2a_07a 'Who is the household identified and walked the plot?'
   ag2a_07b    'Was the resulting area calculation of [PLOT] shared with any HH m' +
   'ember?'
   ag2a_07c_1 'Who was the [PLOT] gps measurement calculation shared with? (1)'
   ag2a_07c_2 'Who was the [PLOT] gps measurement calculation shared with? (2)'
   ag2a_07c_3 'Who was the [PLOT] gps measurement calculation shared with? (3)'
   ag2a_08 'Why was the plot not measured?'
   ag2a_09 'Area (Acres) - GPS Measurement'
   ag2a_10 'Weather conditions at measurement?' .

VALUE LABELS
 ag2a_05a
     1 'YES'
     2 'NO' /
 ag2a_06
     1 'YES'
     2 'NO' /
 ag2a_07b
     1 'YES'
     2 'NO' /
 ag2a_08
     1 'TOO FAR'
     2 'REFUSED'
     3 'OTHER, SPECIFY' /
 ag2a_10
     1 'CLEAR / SUNNY'
     2 'MOSTLY CLEAR / MOSTLY SUNNY'
     3 'PARTLY CLOUDY / PARTLY SUNNY'
     4 'MOSTLY CLOUDY / CONSIDERABLE CLOUDINESS'
     5 'COMPLETELY CLOUDY'
     6 'RAINY' / .


SAVE OUTFILE='.\ag_sec_02.sav'.
