/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\ag_sec_12b.dat" ENCODING="CP1252" / LRECL=29 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        sourceid 23           
   ag12b_08 24              ag12b_09 25              ag12b_10 26-29 .      

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   sourceid 'Source ID'
   ag12b_08    'HH received information about agricultural prices from [SOURCE] i' +
   'n last 12months'
   ag12b_09 'Did you pay anything in order to receive the advice?'
   ag12b_10 'How much did you pay?' .

VALUE LABELS
 sourceid
     1 'GOVERNMENT EXTENSION'
     2 'NGO'
     3 "COOPERATIVE/FARMER'S ASSOCIATION"
     4 'LARGE SCALE FARMER'
     5 'RADIO'
     6 'PUBLICATION'
     7 'NEIGHBOUR'
     8 'OTHER (SPECIFY)' /
 ag12b_08
     1 'YES'
     2 'NO' /
 ag12b_09
     1 'YES'
     2 'NO' / .


SAVE OUTFILE='.\ag_sec_12b.sav'.
