/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\ag_sec_3b.dat" ENCODING="CP1252" / LRECL=480 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        plot_id 23-24         
   plotname 25-40 (A)       plot_desc 41-56 (A)      prevplot_id 57-59 (A) 
   ag3b_00 60               ag3b_02_1 61-64          ag3b_02_2 65-68       
   ag3b_02_3 69-72          ag3b_03 73               ag3b_04 74            
   ag3b_07 75-77            ag3b_08a_1 78            ag3b_08a_2 79         
   ag3b_08b_1 80-81         ag3b_08b_2 82-83         ag3b_08b_3 84         
   ag3b_08c1 85             ag3b_08c2 86             ag3b_09a_1 87         
   ag3b_09a_2 88            ag3b_09b_1 89-90         ag3b_09b_2 91-92      
   ag3b_09b_3 93            ag3b_09c1 94             ag3b_09c2 95          
   ag3b_10 96               ag3b_11 97               ag3b_12 98            
   ag3b_13 99               ag3b_14 100              ag3b_15 101           
   ag3b_16_1 102            ag3b_16_2 103            ag3b_17 104           
   ag3b_18 105              ag3b_19 106              ag3b_20 107           
   ag3b_21 108              ag3b_22 109-112          ag3b_23 113           
   ag3b_24 114-122          ag3b_25 123-124          ag3b_26_1 125         
   ag3b_26_2 126            ag3b_27 127              ag3b_28a 128          
   ag3b_28b 129             ag3b_28c 130             ag3b_28d 131          
   ag3b_29_1 132-133        ag3b_29_2 134-135        ag3b_30 136           
   ag3b_31_1 137-138        ag3b_31_2 139-140        ag3b_31a 141          
   ag3b_32_1 142            ag3b_32_2 143            ag3b_33 144-149       
   ag3b_34_1 150-151        ag3b_34_2 152            ag3b_35 153           
   ag3b_36_1 154-155        ag3b_36_2 156            ag3b_37_1 157         
   ag3b_37_2 158-159        ag3b_38 160-163          ag3b_38a 164          
   ag3b_39 165              ag3b_40 166              ag3b_41 167           
   ag3b_42 168-172          ag3b_43 173              ag3b_44 174-178       
   ag3b_45 179-184          ag3b_46_1 185            ag3b_46_2 186         
   ag3b_47 187              ag3b_48 188              ag3b_49 189-191       
   ag3b_51 192-197          ag3b_52 198              ag3b_53_1 199-200     
   ag3b_53_2 201            ag3b_54 202              ag3b_55 203           
   ag3b_56 204-206          ag3b_58 207-212          ag3b_59_1 213-214     
   ag3b_59_2 215            ag3b_60 216              ag3b_62_1 217-220     
   ag3b_62_2 221            ag3b_63 222-227          ag3b_64 228           
   ag3b_65_1 229-230        ag3b_65_2 231            ag3b_65a 232          
   ag3b_65b_1 233-237       ag3b_65b_2 238           ag3b_65c 239-244      
   ag3b_65d 245             ag3b_65e_1 246-247       ag3b_65e_2 248        
   ag3b_66 249              ag3b_67_1 250            ag3b_67_2 251         
   ag3b_67_3 252            ag3b_67_4 253            ag3b_68 254-259       
   ag3b_69 260-266          ag3b_70_1 267            ag3b_70_2 268         
   ag3b_71_1 269-270        ag3b_71_2 271            ag3b_71a 272          
   ag3b_71b 273             ag3b_72a 274             ag3b_72b_1 275-276    
   ag3b_72b_2 277-278       ag3b_72b_3 279-280       ag3b_72b_4 281-282    
   ag3b_72b_5 283-284       ag3b_72b_6 285-286       ag3b_72b_7 287-288    
   ag3b_72b_8 289-290       ag3b_72b_9 291-292       ag3b_72b_10 293-294   
   ag3b_72c_1 295-296       ag3b_72c_2 297-298       ag3b_72c_3 299-300    
   ag3b_72c_4 301-302       ag3b_72c_5 303-304       ag3b_72c_6 305-306    
   ag3b_72c_7 307-308       ag3b_72c_8 309-310       ag3b_72c_9 311-312    
   ag3b_72c_10 313-314      ag3b_72d_1 315-316       ag3b_72d_2 317-318    
   ag3b_72d_3 319-320       ag3b_72d_4 321-322       ag3b_72d_5 323-324    
   ag3b_72d_6 325-326       ag3b_72d_7 327           ag3b_72d_8 328        
   ag3b_72d_9 329           ag3b_72d_10 330          ag3b_72e 331          
   ag3b_72f_1 332-333       ag3b_72f_2 334-335       ag3b_72f_3 336-337    
   ag3b_72f_4 338-339       ag3b_72f_5 340-341       ag3b_72f_6 342-343    
   ag3b_72f_7 344-345       ag3b_72f_8 346-347       ag3b_72f_9 348-349    
   ag3b_72f_10 350-351      ag3b_72g_1 352-353       ag3b_72g_2 354-355    
   ag3b_72g_3 356-357       ag3b_72g_4 358-359       ag3b_72g_5 360-361    
   ag3b_72g_6 362-363       ag3b_72g_7 364-365       ag3b_72g_8 366-367    
   ag3b_72g_9 368-369       ag3b_72g_10 370-371      ag3b_72h_1 372-373    
   ag3b_72h_2 374-375       ag3b_72h_3 376-377       ag3b_72h_4 378-379    
   ag3b_72h_5 380-381       ag3b_72h_6 382           ag3b_72h_7 383        
   ag3b_72h_8 384           ag3b_72h_9 385           ag3b_72h_10 386       
   ag3b_72i 387             ag3b_72j_1 388-389       ag3b_72j_2 390-391    
   ag3b_72j_3 392-393       ag3b_72j_4 394-395       ag3b_72j_5 396-397    
   ag3b_72j_6 398-399       ag3b_72j_7 400-401       ag3b_72j_8 402-403    
   ag3b_72j_9 404-405       ag3b_72j_10 406-407      ag3b_72k_1 408-409    
   ag3b_72k_2 410-411       ag3b_72k_3 412-413       ag3b_72k_4 414-415    
   ag3b_72k_5 416-417       ag3b_72k_6 418-419       ag3b_72k_7 420-421    
   ag3b_72k_8 422-423       ag3b_72k_9 424-425       ag3b_72k_10 426-427   
   ag3b_72l_1 428-429       ag3b_72l_2 430-431       ag3b_72l_3 432-433    
   ag3b_72l_4 434-435       ag3b_72l_5 436-437       ag3b_72l_6 438-439    
   ag3b_72l_7 440-441       ag3b_72l_8 442           ag3b_72l_9 443        
   ag3b_72l_10 444-445      ag3b_73 446              ag3b_74_1a 447-448    
   ag3b_74_1b 449-450       ag3b_74_1c 451           ag3b_74_1d 452-458    
   ag3b_74_2a 459-460       ag3b_74_2b 461-462       ag3b_74_2c 463        
   ag3b_74_2d 464-469       ag3b_74_3a 470-471       ag3b_74_3b 472-473    
   ag3b_74_3c 474           ag3b_74_3d 475-480 .  


FORMATS
  ag3b_02_1 (F5.2) /       ag3b_02_2 (F5.2) /       ag3b_02_3 (F5.1) /     
  ag3b_56 (F4.1) /         ag3b_62_1 (F5.1) /       ag3b_65b_1 (F6.1) / .
 
VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   plot_id 'PLOT ID'
   plotname    'PLOTS OWNED OR CULTIVATED BY HH IN LAST COMPLETED SHORT RAINY SEA' +
   'SON'
   plot_desc 'Description / Location'
   prevplot_id 'Previous Plot Number NPSY4'
   ag3b_00 'Was plot cultivated in short rainy season 2019 or 2020?'
   ag3b_02_1 'What is the distance from [PLOT] to: HOME (KM)'
   ag3b_02_2 'What is the distance from [PLOT] to: ROAD (KM)'
   ag3b_02_3 'What is the distance from [PLOT] to: MARKET (KM)'
   ag3b_03    'How did you use [PLOT] during the last completed short rainy seas' +
   'on?'
   ag3b_04    'Total income from renting out [PLOT] during last completed short ' +
   'rainy season'
   ag3b_07    'What was main crop cultivated on [PLOT] in last completed short r' +
   'ainy season?'
   ag3b_08a_1 'HH MEMBER: Decided what to plant on [PLOT]'
   ag3b_08a_2 'NON-HH MEMBER: Decided what to plant on [PLOT]'
   ag3b_08b_1 'Who decided what to plant on [PLOT] ...? (ID 1)'
   ag3b_08b_2 'Who decided what to plant on [PLOT] ...? (ID 2)'
   ag3b_08b_3 'Who decided what to plant on [PLOT] ...? (ID 3)'
   ag3b_08c1 'Who decided what to plant on [PLOT]? (NETWORK ID)'
   ag3b_08c2 'Where is [NETWORK] located? (NETWORK ROSTER LOCATION)'
   ag3b_09a_1 'HH MEMBER: Made decisions on input use on [PLOT]'
   ag3b_09a_2 'NON-HH MEMBER: Made decisions on input use on [PLOT]'
   ag3b_09b_1 'Who made decisions on input use on [PLOT] ...? (ID 1)'
   ag3b_09b_2 'Who made decisions on input use on [PLOT] ...? (ID 2)'
   ag3b_09b_3 'Who made decisions on input use on [PLOT] ...? (ID 3)'
   ag3b_09c1 'Who made decisions on input use on [PLOT] (NETWORK ID)'
   ag3b_09c2 'Where is [NETWORK] located? (NETWORK ROSTER LOCATION)'
   ag3b_10 'What was the soil type of this plot?'
   ag3b_11 'What was the soil quality of this plot?'
   ag3b_12 'How do you know the quality of the soil?'
   ag3b_13    'Were there problems with erosion on [PLOT] in last completed shor' +
   't rainy season?'
   ag3b_14 'What was the cause of these erosion problems?'
   ag3b_15    'Erosion control... on [PLOT] in last completed short rainy season'
   ag3b_16_1    'What type of erosion control/water harvesting facility was on thi' +
   's plot?'
   ag3b_16_2    'What type of erosion control/water harvesting facility was on thi' +
   's plot?'
   ag3b_17 'How steep is the slope of this plot?'
   ag3b_18 'Was [PLOT] irrigated in the last completed short rainy season?'
   ag3b_19 'What was the type of irrigation?'
   ag3b_20 'What was the method of obtaining water?'
   ag3b_21 'What was the source of water?'
   ag3b_22 'What was the most recent year in which the plot was left fallow?'
   ag3b_23    'For how many consecutive years was this plot left fallow this las' +
   't time?'
   ag3b_24 'What would the value of this plot be if it were sold today?'
   ag3b_25 'How was this plot acquired?'
   ag3b_26_1 'With whom do you co-own this plot? (NETWORK ROSTER ID)'
   ag3b_26_2 'Where is [NETWORK] located? (NETWORK ROSTER LOCATION)'
   ag3b_27 'What share does your household get of the output?'
   ag3b_28a    'What type of legal certificate does your household have for this ' +
   'plot?'
   ag3b_28b 'Would you like to apply for a CCRO/GRO for this plot?'
   ag3b_28c 'Would you be willing to pay for legal certification?'
   ag3b_28d    'What other types of ownership or legal documents does HHd have fo' +
   'r [PLOT]?'
   ag3b_29_1 'Who in the household owns this plot? (ID 1)'
   ag3b_29_2 'Who in the household owns this plot? (ID 2)'
   ag3b_30    'Does the owner/HH have the right to sell [PLOT] or use it as coll' +
   'ateral?'
   ag3b_31_1    'Who in HH can decide whether to sell [PLOT] or use it as collater' +
   'al? (ID 1)'
   ag3b_31_2    'Who in HH can decide whether to sell [PLOT] or use it as collater' +
   'al? (ID 2)'
   ag3b_31a    'If you were to sell [PLOT], do you need approval from other parti' +
   'es to sell it?'
   ag3b_32_1 'With whom do you co-rent this plot? (NETWORK ROSTER ID)'
   ag3b_32_2 'Where is [NETWORK] located? (NETWORK ROSTER LOCATION)'
   ag3b_33    'Amount paid to owner for use of [PLOT] in last completed short ra' +
   'iny season'
   ag3b_34_1 'What period of time did this payment cover? (NUMBER OF UNITS)'
   ag3b_34_2 'What period of time did this payment cover? (UNITS)'
   ag3b_35    'Share of output from [PLOT] given as rent in last completed short' +
   ' rainy season'
   ag3b_36_1 'Who owns the plot? (NETWORK ROSTER ID)'
   ag3b_36_2 'Who owns the plot? (NETWORK ROSTER LOCATION)'
   ag3b_37_1 'Who in the household has the rights to use this plot? (ID 1)'
   ag3b_37_2 'Who in the household has the rights to use this plot? (ID 2)'
   ag3b_38 'In which year was the plot acquired?'
   ag3b_38a    'Had any land dispute or disagreement with anyone over [PLOT] in l' +
   'ast 12 months'
   ag3b_39    'Comfortable leaving [PLOT] uncultivated for several months withou' +
   't being worried'
   ag3b_40    'CAPI: DID HH CULTIVATE [PLOT] IN LAST COMPLETED SHORT RAINY SEASO' +
   'N?'
   ag3b_41    'Used ORGANIC FERTILIZER on [PLOT] in last completed short rainy s' +
   'eason'
   ag3b_42 'What was the quantity of organic fertilizer used? (KG)'
   ag3b_43 'Was any of this purchased?'
   ag3b_44 'How much was purchased? (KG)'
   ag3b_45 'What was the total value of organic fertilizer purchased? (TSH)'
   ag3b_46_1    'Where did you buy most of the organic fertilizer? (NETWORK ROSTER' +
   ' ID)'
   ag3b_46_2 'Where is [NETWORK] located? (NETWORK ROSTER LOCATION)'
   ag3b_47    'Used INORGANIC FERTILIZER on [PLOT] in last completed short rainy' +
   ' season'
   ag3b_48    'What is the first type of INORGANIC FERTILIZER you used on this p' +
   'lot?'
   ag3b_49 'What quantity of [FERTILIZER] did you use? (KG)'
   ag3b_51 'What was the total value of [FERTILIZER] purchased? (TSH)'
   ag3b_52    'Why did you choose to use this specific type of inorganic fertili' +
   'zer?'
   ag3b_53_1 'Where did you buy most of the [FERTILIZER]? (NETWORK ROSTER ID)'
   ag3b_53_2 'Where is [NETWORK] located? (NETWORK ROSTER LOCATION)'
   ag3b_54 'Used a 2nd type of INORGANIC FERTILIZER on [PLOT]'
   ag3b_55    'What is the second type of INORGANIC FERTILIZER you used on this ' +
   'plot?'
   ag3b_56 'What quantity of [FERTILIZER] did you use? (KG)'
   ag3b_58 'What was the total value of [FERTILIZER] purchased? (TSH)'
   ag3b_59_1 'Where did you buy most of the [FERTILIZER]? (NETWORK ROSTER ID)'
   ag3b_59_2 'Where is [NETWORK] located? (NETWORK ROSTER LOCATION)'
   ag3b_60    'Did you use any herbicide on [PLOT] in the last completed short r' +
   'ainy season?'
   ag3b_62_1 'What quantity of this herbicide did you use? QUANTITY'
   ag3b_62_2 'What quantity of this herbicide did you use? UNIT'
   ag3b_63 'What was the total value of this herbicide purchased? (TSH)'
   ag3b_64    'Why did you choose to use this specific type of pesticide/herbici' +
   'de?'
   ag3b_65_1    'Where did you buy most of the pesticides/ herbicides? (NETWORK RO' +
   'STER ID)'
   ag3b_65_2    'Where did you buy most of the herbicides? (NETWORK ROSTER LOCATIO' +
   'N)'
   ag3b_65a    'Did you use any pesticide on [PLOT] in the last completed short r' +
   'ainy season?'
   ag3b_65b_1 'What quantity of this pesticide did you use? QUANTITY'
   ag3b_65b_2 'What quantity of this pesticide did you use? UNIT'
   ag3b_65c 'What was the total value of this pesticide purchased? (TSH)'
   ag3b_65d 'Why did you choose to use this specific type of pesticide?'
   ag3b_65e_1 'Where did you buy most of the pesticides? (NETWORK ROSTER ID)'
   ag3b_65e_2 'Where is [NETWORK] located? (NETWORK ROSTER LOCATION)'
   ag3b_66    'Received seeds... for [PLOT] on credit during last completed shor' +
   't rainy season'
   ag3b_67_1 'What were the types of input you received on credit? (SEEDS)'
   ag3b_67_2    'What were the types of input you received on credit? (ORGANIC FER' +
   'TILIZER)'
   ag3b_67_3    'What were the types of input you received on credit? (INORGANIC F' +
   'ERTILIZER)'
   ag3b_67_4    'What were the types of input you received on credit? (PESTICIDES/' +
   'HERBICIDES)'
   ag3b_68 'How much did you pay up front for these inputs? (TSH)'
   ag3b_69 'How much did you repay in cash later on for the inputs? (TSH)'
   ag3b_70_1 'How much did you repay in kind later on for the inputs? QUANTITY'
   ag3b_70_2 'How much did you repay in kind later on for the inputs? UNIT'
   ag3b_71_1    'From whom did you receive these inputs on credit? (NETWORK ROSTER' +
   ' ID)'
   ag3b_71_2 'Where is [NETWORK] located? (NETWORK ROSTER LOCATION)'
   ag3b_71a    'Did you use any mechanization on [PLOT] in last completed short r' +
   'ainy season?'
   ag3b_71b    'Did you use any animal traction on [PLOT] in last completed short' +
   ' rainy season?'
   ag3b_72a 'HH member spent time on LAND PREPARATION & PLANTING on [PLOT]'
   ag3b_72b_1 'Which member? (ID 1)'
   ag3b_72b_2 'Which member? (ID 2)'
   ag3b_72b_3 'Which member? (ID 3)'
   ag3b_72b_4 'Which member? (ID 4)'
   ag3b_72b_5 'Which member? (ID 5)'
   ag3b_72b_6 'Which member? (ID 6)'
   ag3b_72b_7 'Which member? (ID 7)'
   ag3b_72b_8 'Which member? (ID 8)'
   ag3b_72b_9 'Which member? (ID 9)'
   ag3b_72b_10 'Which member? (ID 10)'
   ag3b_72c_1    'Number of days [NAME] spent on LAND PREPARATION & PLANTING (MEMBE' +
   'R 1)'
   ag3b_72c_2    'Number of days [NAME] spent on LAND PREPARATION & PLANTING (MEMBE' +
   'R 2)'
   ag3b_72c_3    'Number of days [NAME] spent on LAND PREPARATION & PLANTING (MEMBE' +
   'R 3)'
   ag3b_72c_4    'Number of days [NAME] spent on LAND PREPARATION & PLANTING (MEMBE' +
   'R 4)'
   ag3b_72c_5    'Number of days [NAME] spent on LAND PREPARATION & PLANTING (MEMBE' +
   'R 5)'
   ag3b_72c_6    'Number of days [NAME] spent on LAND PREPARATION & PLANTING (MEMBE' +
   'R 6)'
   ag3b_72c_7    'Number of days [NAME] spent on LAND PREPARATION & PLANTING (MEMBE' +
   'R 7)'
   ag3b_72c_8    'Number of days [NAME] spent on LAND PREPARATION & PLANTING (MEMBE' +
   'R 8)'
   ag3b_72c_9    'Number of days [NAME] spent on LAND PREPARATION & PLANTING (MEMBE' +
   'R 9)'
   ag3b_72c_10    'Number of days [NAME] spent on LAND PREPARATION & PLANTING (MEMBE' +
   'R 10)'
   ag3b_72d_1    'Number of hours per day [NAME] spent on LAND PREPARATION & PLANTI' +
   'NG (MEMBER 1)'
   ag3b_72d_2    'Number of hours per day [NAME] spent on LAND PREPARATION & PLANTI' +
   'NG (MEMBER 2)'
   ag3b_72d_3    'Number of hours per day [NAME] spent on LAND PREPARATION & PLANTI' +
   'NG (MEMBER 3)'
   ag3b_72d_4    'Number of hours per day [NAME] spent on LAND PREPARATION & PLANTI' +
   'NG (MEMBER 4)'
   ag3b_72d_5    'Number of hours per day [NAME] spent on LAND PREPARATION & PLANTI' +
   'NG (MEMBER 5)'
   ag3b_72d_6    'Number of hours per day [NAME] spent on LAND PREPARATION & PLANTI' +
   'NG (MEMBER 6)'
   ag3b_72d_7    'Number of hours per day [NAME] spent on LAND PREPARATION & PLANTI' +
   'NG (MEMBER 7)'
   ag3b_72d_8    'Number of hours per day [NAME] spent on LAND PREPARATION & PLANTI' +
   'NG (MEMBER 8)'
   ag3b_72d_9    'Number of hours per day [NAME] spent on LAND PREPARATION & PLANTI' +
   'NG (MEMBER 9)'
   ag3b_72d_10    'Number of hours per day [NAME] spent on LAND PREPARATION & PLANTI' +
   'NG (MEMBER 10)'
   ag3b_72e 'HH member spent time on WEEDING,... on [PLOT]'
   ag3b_72f_1 'Which member? (ID 1)'
   ag3b_72f_2 'Which member? (ID 2)'
   ag3b_72f_3 'Which member? (ID 3)'
   ag3b_72f_4 'Which member? (ID 4)'
   ag3b_72f_5 'Which member? (ID 5)'
   ag3b_72f_6 'Which member? (ID 6)'
   ag3b_72f_7 'Which member? (ID 7)'
   ag3b_72f_8 'Which member? (ID 8)'
   ag3b_72f_9 'Which member? (ID 9)'
   ag3b_72f_10 'Which member? (ID 10)'
   ag3b_72g_1 'Number of days [NAME] spent on WEEDING,... (MEMBER 1)'
   ag3b_72g_2 'Number of days [NAME] spent on WEEDING,... (MEMBER 2)'
   ag3b_72g_3 'Number of days [NAME] spent on WEEDING,... (MEMBER 3)'
   ag3b_72g_4 'Number of days [NAME] spent on WEEDING,... (MEMBER 4)'
   ag3b_72g_5 'Number of days [NAME] spent on WEEDING,... (MEMBER 5)'
   ag3b_72g_6 'Number of days [NAME] spent on WEEDING,... (MEMBER 6)'
   ag3b_72g_7 'Number of days [NAME] spent on WEEDING,... (MEMBER 7)'
   ag3b_72g_8 'Number of days [NAME] spent on WEEDING,... (MEMBER 8)'
   ag3b_72g_9 'Number of days [NAME] spent on WEEDING,... (MEMBER 9)'
   ag3b_72g_10 'Number of days [NAME] spent on WEEDING,... (MEMBER 10)'
   ag3b_72h_1 'Number of hours per day [NAME] spent on WEEDING,... (MEMBER 1)'
   ag3b_72h_2 'Number of hours per day [NAME] spent on WEEDING,... (MEMBER 2)'
   ag3b_72h_3 'Number of hours per day [NAME] spent on WEEDING,... (MEMBER 3)'
   ag3b_72h_4 'Number of hours per day [NAME] spent on WEEDING,... (MEMBER 4)'
   ag3b_72h_5 'Number of hours per day [NAME] spent on WEEDING,... (MEMBER 5)'
   ag3b_72h_6 'Number of hours per day [NAME] spent on WEEDING,... (MEMBER 6)'
   ag3b_72h_7 'Number of hours per day [NAME] spent on WEEDING,... (MEMBER 7)'
   ag3b_72h_8 'Number of hours per day [NAME] spent on WEEDING,... (MEMBER 8)'
   ag3b_72h_9 'Number of hours per day [NAME] spent on WEEDING,... (MEMBER 9)'
   ag3b_72h_10 'Number of hours per day [NAME] spent on WEEDING,... (MEMBER 10)'
   ag3b_72i 'HH member spent time on HARVESTING & THRESHING on [PLOT]'
   ag3b_72j_1 'Which member? (ID 1)'
   ag3b_72j_2 'Which member? (ID 2)'
   ag3b_72j_3 'Which member? (ID 3)'
   ag3b_72j_4 'Which member? (ID 4)'
   ag3b_72j_5 'Which member? (ID 5)'
   ag3b_72j_6 'Which member? (ID 6)'
   ag3b_72j_7 'Which member? (ID 7)'
   ag3b_72j_8 'Which member? (ID 8)'
   ag3b_72j_9 'Which member? (ID 9)'
   ag3b_72j_10 'Which member? (ID 10)'
   ag3b_72k_1 'Number of days [NAME] spent on HARVESTING & THRESHING (MEMBER 1)'
   ag3b_72k_2 'Number of days [NAME] spent on HARVESTING & THRESHING (MEMBER 2)'
   ag3b_72k_3 'Number of days [NAME] spent on HARVESTING & THRESHING (MEMBER 3)'
   ag3b_72k_4 'Number of days [NAME] spent on HARVESTING & THRESHING (MEMBER 4)'
   ag3b_72k_5 'Number of days [NAME] spent on HARVESTING & THRESHING (MEMBER 5)'
   ag3b_72k_6 'Number of days [NAME] spent on HARVESTING & THRESHING (MEMBER 6)'
   ag3b_72k_7 'Number of days [NAME] spent on HARVESTING & THRESHING (MEMBER 7)'
   ag3b_72k_8 'Number of days [NAME] spent on HARVESTING & THRESHING (MEMBER 8)'
   ag3b_72k_9 'Number of days [NAME] spent on HARVESTING & THRESHING (MEMBER 9)'
   ag3b_72k_10    'Number of days [NAME] spent on HARVESTING & THRESHING (MEMBER 10)'
   ag3b_72l_1    'Number of hours per day [NAME] spent on HARVESTING & THRESHING (M' +
   'EMBER 1)'
   ag3b_72l_2    'Number of hours per day [NAME] spent on HARVESTING & THRESHING (M' +
   'EMBER 2)'
   ag3b_72l_3    'Number of hours per day [NAME] spent on HARVESTING & THRESHING (M' +
   'EMBER 3)'
   ag3b_72l_4    'Number of hours per day [NAME] spent on HARVESTING & THRESHING (M' +
   'EMBER 4)'
   ag3b_72l_5    'Number of hours per day [NAME] spent on HARVESTING & THRESHING (M' +
   'EMBER 5)'
   ag3b_72l_6    'Number of hours per day [NAME] spent on HARVESTING & THRESHING (M' +
   'EMBER 6)'
   ag3b_72l_7    'Number of hours per day [NAME] spent on HARVESTING & THRESHING (M' +
   'EMBER 7)'
   ag3b_72l_8    'Number of hours per day [NAME] spent on HARVESTING & THRESHING (M' +
   'EMBER 8)'
   ag3b_72l_9    'Number of hours per day [NAME] spent on HARVESTING & THRESHING (M' +
   'EMBER 9)'
   ag3b_72l_10    'Number of hours per day [NAME] spent on HARVESTING & THRESHING (M' +
   'EMBER 10)'
   ag3b_73    'Did you hire any labor to work on [PLOT] in last completed short ' +
   'rainy season?'
   ag3b_74_1a 'Land Preparation & Planting - Number of days [WOMAN]'
   ag3b_74_1b 'Land Preparation & Planting - Number of days [MAN]'
   ag3b_74_1c 'Land Preparation & Planting - Number of days [CHILD]'
   ag3b_74_1d 'Land Preparation & Planting - Total Wage Paid [TSH]'
   ag3b_74_2a 'Weeding, Ridging, Fertilizing, etc. - Number of days [WOMAN]'
   ag3b_74_2b 'Weeding, Ridging, Fertilizing, etc. - Number of days [MAN]'
   ag3b_74_2c 'Weeding, Ridging, Fertilizing, etc. - Number of days [CHILD]'
   ag3b_74_2d 'Weeding, Ridging, Fertilizing, etc. - Total Wage Paid [TSH]'
   ag3b_74_3a 'Harvesting & Threshing, etc. - Number of days [WOMAN]'
   ag3b_74_3b 'Harvesting & Threshing, etc. - Number of days [MAN]'
   ag3b_74_3c 'Harvesting & Threshing, etc. - Number of days [CHILD]'
   ag3b_74_3d 'Harvesting & Threshing, etc. - Total Wage Paid [TSH]' .

VALUE LABELS
 ag3b_00
     1 'YES'
     2 'NO' /
 ag3b_03
     1 'CULTIVATED'
     2 'RENTED OUT'
     3 'GIVEN OUT'
     4 'FALLOW'
     5 'FOREST'
     6 'OTHER (SPECIFY)' /
 ag3b_07
     11 'MAIZE'
     12 'PADDY'
     13 'SORGHUM'
     14 'BULRUSH MILLET'
     15 'FINGER MILLET'
     16 'WHEAT'
     17 'BARLEY'
     18 'BLACK PEPPER'
     19 'SEAWEED'
     21 'CASSAVA'
     22 'SWEET POTATOES'
     23 'IRISH POTATOES'
     24 'YAMS'
     25 'COCOYAMS'
     26 'ONIONS'
     27 'GINGER'
     31 'BEANS'
     32 'COWPEAS'
     33 'GREEN GRAM'
     34 'PIGEON PEA'
     35 'CHICK PEAS'
     36 'BAMBARA NUTS'
     37 'FIELD PEAS'
     38 'MALAY APPLE'
     39 'STAR FRUIT'
     41 'SUNFLOWER'
     42 'SESAME'
     43 'GROUNDNUT'
     44 'PALM OIL'
     45 'COCONUT'
     46 'CASHEW NUT'
     47 'SOYABEANS'
     48 'CASTER SEED'
     50 'COTTON'
     51 'TOBACCO'
     52 'PYRETHRUM'
     53 'SISAL'
     54 'COFFEE'
     55 'TEA'
     56 'COCOA'
     57 'RUBBER'
     58 'WATTLE'
     59 'KAPOK'
     60 'SUGAR CANE'
     61 'CARDAMOM'
     62 'JUTE'
     63 'TAMARIND'
     64 'CINNAMON'
     65 'NUTMEG'
     66 'CLOVE'
     67 'BREAD FRUIT'
     68 'POMELO'
     69 'JACK FRUIT'
     70 'PASSION FRUIT'
     71 'BANANA'
     72 'AVOCADO'
     73 'MANGO'
     74 'PAPAW'
     75 'PINEAPPLE'
     76 'ORANGE'
     77 'GRAPEFRUIT'
     78 'GRAPES'
     79 'MANDARIN'
     80 'GUAVA'
     81 'PLUMS'
     82 'APPLES'
     83 'PEARS'
     84 'PEACHES'
     86 'CABBAGE'
     87 'TOMATOES'
     88 'SPINACH'
     89 'CARROT'
     90 'CHILIES'
     91 'AMARANTHS'
     92 'PUMPKINS'
     93 'CUCUMBER'
     94 'EGG PLANT'
     95 'WATER MELLON'
     96 'CAULIFLOWER'
     97 'DURIAN'
     98 'BILIMBI'
     99 'RAMBUTAN'
     100 'OKRA'
     101 'FIWI'
     200 'CUSTARD APPLE'
     201 'GOD FRUIT'
     202 'MITOBO'
     203 'PLUM'
     204 'PEACHES'
     205 'POMEGRANATE'
     210 'DATE'
     211 'TUNGAMAA'
     212 'VANILLA'
     300 'GREEN TOMATO'
     301 'MONKEYBREAD'
     302 'BAMBOO'
     303 'FIREWOOD/FODDER'
     304 'TIMBER'
     305 'MEDICINAL PLANT'
     306 'FENCE TREE'
     851 'LIME'
     852 'LEMON'
     998 'OTHER (SPECIFY)' /
 ag3b_08a_1
     0 'NO'
     1 'YES' /
 ag3b_08a_2
     0 'NO'
     1 'YES' /
 ag3b_08c1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag3b_08c2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag3b_09a_1
     0 'NO'
     1 'YES' /
 ag3b_09a_2
     0 'NO'
     1 'YES' /
 ag3b_09c1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag3b_09c2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag3b_10
     1 'SANDY'
     2 'LOAM'
     3 'CLAY'
     4 'OTHER (SPECIFY)' /
 ag3b_11
     1 'GOOD'
     2 'AVERAGE'
     3 'BAD' /
 ag3b_12
     1 'SCIENTIFICALLY TESTED'
     2 'OWN EXPERIENCE'
     3 'OTHER (SPECIFY)' /
 ag3b_13
     1 'YES'
     2 'NO' /
 ag3b_14
     1 'WIND'
     2 'RAIN'
     3 'ANIMALS'
     4 'CULTIVATION WHICH DOES NOT COMPLY WITH SOIL CONSERVATION'
     5 'OTHER (SPECIFY)' /
 ag3b_15
     1 'YES'
     2 'NO' /
 ag3b_16_1
     1 'TERRACES'
     2 'EROSION CONTROL BUNDS'
     3 'GABIONS/SANDBAGS'
     4 'VETIVER GRASS'
     5 'TREE BELTS'
     6 'WATER HARVEST BUNDS'
     7 'DRAINAGE DITCHES'
     8 'DAM' /
 ag3b_16_2
     1 'TERRACES'
     2 'EROSION CONTROL BUNDS'
     3 'GABIONS/SANDBAGS'
     4 'VETIVER GRASS'
     5 'TREE BELTS'
     6 'WATER HARVEST BUNDS'
     7 'DRAINAGE DITCHES'
     8 'DAM' /
 ag3b_17
     1 'FLAT BOTTOM'
     2 'FLAT TOP'
     3 'SLIGHTLY SLOPED'
     4 'VERY STEEP' /
 ag3b_18
     1 'YES'
     2 'NO' /
 ag3b_19
     1 'FLOODING'
     2 'SPRINKLER'
     3 'DRIP IRRIGATION'
     4 'BUCKET/WATERING CAN'
     5 'WATER HOSE'
     6 'OTHER (SPECIFY)' /
 ag3b_20
     1 'GRAVITY'
     2 'HAND BUCKET'
     3 'HAND/FOOT PUMP'
     4 'MOTOR PUMP'
     5 'OTHER (SPECIFY)' /
 ag3b_21
     1 'WELL'
     2 'BOREHOLE'
     3 'POND/TANK'
     4 'RIVER/STREAM'
     5 'OTHER (SPECIFY)' /
 ag3b_22
     0 'NEVER'
     98 "DON'T KNOW" /
 ag3b_25
     1 'INHERITANCE'
     2 'GIFT'
     3 'BORROWING FROM FAMILY MEMBER'
     4 'LAND ALLOCATION FROM  VILLAGE COUNCIL'
     5 'PURCHASED'
     6 'USED FREE OF CHARGE'
     7 'RENTED IN'
     8 'SHARED - RENT'
     9 'SHARED - OWN'
     10 'SQUATTING, CLEARING'
     11 'OTHER, SPECIFY' /
 ag3b_26_1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag3b_26_2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag3b_27
     1 'NOTHING'
     2 'ALMOST NOTHING'
     3 'ONE QUARTER'
     4 'HALF'
     5 'THREE QUARTERS'
     6 'ALMOST ALL' /
 ag3b_28a
     1 'GRANTED RIGHT OF OCCUPANCY'
     2 'CERTIFICATE OF CUSTOMARY RIGHTS  OF OCCUPANCY'
     3 'NO CERTIFICATE' /
 ag3b_28b
     1 'YES'
     2 'NO' /
 ag3b_28c
     1 'YES'
     2 'NO' /
 ag3b_28d
     1 'VILLAGE-GOVERNMENT-WITNESSED PURCHASE AGREEMENT'
     2 'LOCAL-COURT-CERTIFIED PURCHASE AGREEMENT'
     3 'INHERITANCE LETTER'
     4 "LETTER OF ALLOCATION FROM VILLAGE GOV'T"
     5 'OTHER GOVERNMENT DOCUMENT'
     6 'OFFICIAL CORRESPONDENCE'
     7 'UTILITY OR OTHER BILL'
     8 'NO DOCUMENTATION' /
 ag3b_30
     1 'YES'
     2 'NO' /
 ag3b_31a
     1 'YES'
     2 'NO' /
 ag3b_32_1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag3b_32_2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag3b_33
     0 'NO PAYMENT' /
 ag3b_34_2
     1 'MONTHS'
     2 'YEARS' /
 ag3b_35
     1 'NONE'
     2 'ALMOST NONE'
     3 'ABOUT 25%'
     4 'ABOUT 50%'
     5 'ABOUT 75%'
     6 'ALMOST ALL' /
 ag3b_36_1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag3b_36_2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag3b_38a
     1 'YES'
     2 'NO' /
 ag3b_39
     1 'YES'
     2 'NO' /
 ag3b_40
     1 'YES'
     2 'NO' /
 ag3b_41
     1 'YES'
     2 'NO' /
 ag3b_43
     1 'YES'
     2 'NO' /
 ag3b_46_1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag3b_46_2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag3b_47
     1 'YES'
     2 'NO' /
 ag3b_48
     1 'DI-AMMOIUM PHOSPHATE (DAP)'
     2 'UREA'
     3 'TRIPLE SUPER PHOSPHATE (TSP)'
     4 'CALCIUM AMMONIUM NITRATE (CAN)'
     5 'SULPHATE OF AMMONIUM (SA)'
     6 'NITROGEN PHOSPHATE POTASSIUM (NPK)'
     7 'MINJINGU ROCK PHOSPHATE (MRP)'
     8 'OTHER (SPECIFY)' /
 ag3b_52
     1 'ADVICE BY AGRICULTURAL OFFICER'
     2 'RECEIVED VOUCHER'
     3 'OWN EXPERIENCE'
     4 'NEIGHBOUR ADVICE'
     5 'OTHER (SPECIFY)' /
 ag3b_53_1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag3b_53_2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag3b_54
     1 'YES'
     2 'NO' /
 ag3b_55
     1 'DI-AMMOIUM PHOSPHATE (DAP)'
     2 'UREA'
     3 'TRIPLE SUPER PHOSPHATE (TSP)'
     4 'CALCIUM AMMONIUM NITRATE (CAN)'
     5 'SULPHATE OF AMMONIUM (SA)'
     6 'NITROGEN PHOSPHATE POTASSIUM (NPK)'
     7 'MINJINGU ROCK PHOSPHATE (MRP)'
     8 'OTHER (SPECIFY)' /
 ag3b_59_1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag3b_59_2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag3b_60
     1 'YES'
     2 'NO' /
 ag3b_62_2
     1 'KG'
     2 'LITRE'
     3 'MILLILITRE'
     4 'OTHER (SPECIFY)' /
 ag3b_64
     1 'ADVICE BY AGRICULTURAL OFFICER'
     2 'RECEIVED VOUCHER'
     3 'OWN EXPERIENCE'
     4 'NEIGHBOUR ADVICE'
     5 'OTHER (SPECIFY)' /
 ag3b_65_1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag3b_65_2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag3b_65a
     1 'YES'
     2 'NO' /
 ag3b_65b_2
     1 'KG'
     2 'LITRE'
     3 'MILLILITRE'
     4 'OTHER,SPECIFY' /
 ag3b_65d
     1 'ADVICE BY AGRICULTURAL OFFICER'
     2 'RECEIVED VOUCHER'
     3 'OWN EXPERIENCE'
     4 'NEIGHBOUR ADVICE'
     5 'OTHER (SPECIFY)' /
 ag3b_65e_1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag3b_65e_2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag3b_66
     1 'YES'
     2 'NO' /
 ag3b_67_1 ag3b_67_2 ag3b_67_3 ag3b_67_4
     0 'NO'
     1 'YES' /
 ag3b_70_2
     1 'THIS CROP (KGs)'
     2 'LABOR (DAYS)'
     3 'OTHER (SPECIFY)' /
 ag3b_71_1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag3b_71_2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag3b_71a
     1 'YES'
     2 'NO' /
 ag3b_71b
     1 'YES'
     2 'NO' /
 ag3b_72a
     1 'YES'
     2 'NO' /
 ag3b_72e
     1 'YES'
     2 'NO' /
 ag3b_72i
     1 'YES'
     2 'NO' /
 ag3b_73
     1 'YES'
     2 'NO' / .


SAVE OUTFILE='.\ag_sec_3b.sav'.
