/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\ag_sec_6b.dat" ENCODING="CP1252" / LRECL=69 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        plot_id 23-24         
   cropid 25-27             ag6b_02 28-32            ag6b_03 33-36         
   ag6b_04 37-41            ag6b_05 42               ag6b_06 43            
   ag6b_06a 44              ag6b_07_1 45-48          ag6b_07_2 49-50       
   ag6b_07_3 51-54          ag6b_07_4 55-56          ag6b_08_1 57-58       
   ag6b_08_2 59-60          ag6b_09 61-67            ag6b_10 68            
   ag6b_11 69 .          

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   plot_id 'PLOT ID'
   cropid 'CROP CODE'
   ag6b_02 'How many of these plants/trees are on this plot?'
   ag6b_03 'In what year were most of these plants/trees planted?'
   ag6b_04 'How many plants/trees were planted during the last 12 months?'
   ag6b_05 'Was cultivation intercropped during the past long rainy season?'
   ag6b_06 'What was the reason for intercropping?'
   ag6b_06a 'In the last 12 months, have you harvested [FRUIT] from [PLOT]?'
   ag6b_07_1    'What was the last completed production period for the [FRUIT]? (B' +
   'egin Year)'
   ag6b_07_2    'What was the last completed production period for the [FRUIT]? (B' +
   'egin Month)'
   ag6b_07_3    'What was the last completed production period for the [FRUIT]? (E' +
   'nd Year)'
   ag6b_07_4    'What was the last completed production period for the [FRUIT]? (E' +
   'nd Month)'
   ag6b_08_1    'Who in HH made decisions on use of [FRUIT] harvested in past 12 m' +
   'onths (ID 1)'
   ag6b_08_2    'Who in HH made decisions on use of [FRUIT] harvested in past 12 m' +
   'onths (ID 2)'
   ag6b_09    'What was the total amount of [FRUIT] harvested in the past 12 mon' +
   'ths? (KG)'
   ag6b_10 'Were there any losses of [FRUIT] before the harvest?'
   ag6b_11 'What was the cause of these losses?' .

VALUE LABELS
 cropid
     11 'MAIZE'
     12 'PADDY'
     13 'SORGHUM'
     14 'BULRUSH MILLET'
     15 'FINGER MILLET'
     16 'WHEAT'
     17 'BARLEY'
     18 'BLACK PEPPER'
     19 'SEAWEED'
     21 'CASSAVA'
     22 'SWEET POTATOES'
     23 'IRISH POTATOES'
     24 'YAMS'
     25 'COCOYAMS'
     26 'ONIONS'
     27 'GINGER'
     31 'BEANS'
     32 'COWPEAS'
     33 'GREEN GRAM'
     34 'PIGEON PEA'
     35 'CHICK PEAS'
     36 'BAMBARA NUTS'
     37 'FIELD PEAS'
     38 'MALAY APPLE'
     39 'STAR FRUIT'
     41 'SUNFLOWER'
     42 'SESAME'
     43 'GROUNDNUT'
     44 'PALM OIL'
     45 'COCONUT'
     46 'CASHEW NUT'
     47 'SOYABEANS'
     48 'CASTER SEED'
     50 'COTTON'
     51 'TOBACCO'
     52 'PYRETHRUM'
     53 'SISAL'
     54 'COFFEE'
     55 'TEA'
     56 'COCOA'
     57 'RUBBER'
     58 'WATTLE'
     59 'KAPOK'
     60 'SUGAR CANE'
     61 'CARDAMOM'
     62 'JUTE'
     63 'TAMARIND'
     64 'CINNAMON'
     65 'NUTMEG'
     66 'CLOVE'
     67 'BREAD FRUIT'
     68 'POMELO'
     69 'JACK FRUIT'
     70 'PASSION FRUIT'
     71 'BANANA'
     72 'AVOCADO'
     73 'MANGO'
     74 'PAPAW'
     75 'PINEAPPLE'
     76 'ORANGE'
     77 'GRAPEFRUIT'
     78 'GRAPES'
     79 'MANDARIN'
     80 'GUAVA'
     81 'PLUMS'
     82 'APPLES'
     83 'PEARS'
     84 'PEACHES'
     86 'CABBAGE'
     87 'TOMATOES'
     88 'SPINACH'
     89 'CARROT'
     90 'CHILIES'
     91 'AMARANTHS'
     92 'PUMPKINS'
     93 'CUCUMBER'
     94 'EGG PLANT'
     95 'WATER MELLON'
     96 'CAULIFLOWER'
     97 'DURIAN'
     98 'BILIMBI'
     99 'RAMBUTAN'
     100 'OKRA'
     101 'FIWI'
     200 'CUSTARD APPLE'
     201 'GOD FRUIT'
     202 'MITOBO'
     203 'PLUM'
     204 'PEACHES'
     205 'POMEGRANATE'
     210 'DATE'
     211 'TUNGAMAA'
     212 'VANILLA'
     300 'GREEN TOMATO'
     301 'MONKEYBREAD'
     302 'BAMBOO'
     303 'FIREWOOD/FODDER'
     304 'TIMBER'
     305 'MEDICINAL PLANT'
     306 'FENCE TREE'
     851 'LIME'
     852 'LEMON'
     998 'OTHER (SPECIFY)' /
 ag6b_03
     9999 "DON'T KNOW" /
 ag6b_05
     1 'YES'
     2 'NO' /
 ag6b_06
     1 'MORE FERTILE FOR SOIL'
     2 'SUBSTITUTE IF EITHER CROP FAILS'
     3 'OTHER (SPECIFY)' /
 ag6b_06a
     1 'YES'
     2 'NO' /
 ag6b_07_2
     1 'JANUARY'
     2 'FEBRUARY'
     3 'MARCH'
     4 'APRIL'
     5 'MAY'
     6 'JUNE'
     7 'JULY'
     8 'AUGUST'
     9 'SEPTEMBER'
     10 'OCTOBER'
     11 'NOVEMBER'
     12 'DECEMBER' /
 ag6b_07_4
     1 'JANUARY'
     2 'FEBRUARY'
     3 'MARCH'
     4 'APRIL'
     5 'MAY'
     6 'JUNE'
     7 'JULY'
     8 'AUGUST'
     9 'SEPTEMBER'
     10 'OCTOBER'
     11 'NOVEMBER'
     12 'DECEMBER' /
 ag6b_10
     1 'YES'
     2 'NO' /
 ag6b_11
     1 'BIRDS'
     2 'ANIMALS'
     3 'INSECTS'
     4 'DISEASES'
     5 'THEFT'
     6 'OTHER (SPECIFY)' / .


SAVE OUTFILE='.\ag_sec_6b.sav'.
