/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\ag_sec_10.dat" ENCODING="CP1252" / LRECL=125 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        cropid 23-24          
   ag10_02_1 25-40 (A)      ag10_02_2 41-43          ag10_02_3 44          
   ag10_03 45-46            ag10_02_2a 47-49         ag10_02_2b 50-52      
   ag10_02_2c 53-55         ag10_02_2d 56-58         ag10_02_2e 59-61      
   ag10_02_2f 62-64         ag10_02_2g 65-66         ag10_02_2h 67-68      
   ag10_02_2i 69-70         ag10_02_2j 71-73         ag10_04_1 74-78       
   ag10_04_2 79             ag10_05 80-84            ag10_06 85            
   ag10_07_1 86-90          ag10_07_2 91             ag10_08 92-97         
   ag10_09_1 98-99          ag10_09_2 100            ag10_10_1 101-102     
   ag10_10_2 103-104        ag10_11 105-112          ag10_12_1a 113-114    
   ag10_12_1b 115           ag10_12_2a 116-117       ag10_12_2b 118        
   ag10_13 119              ag10_14 120-125 .     

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   cropid 'Crop ID'
   ag10_02_1 'Crop Name'
   ag10_02_2 'Crop Code'
   ag10_02_3 'Processed / By-Product'
   ag10_03 'What is the by-product produced from this crop?'
   ag10_02_2a 'Crop Code 1 (additional crop listed)'
   ag10_02_2b 'Crop Code 2 (additional crop listed)'
   ag10_02_2c 'Crop Code 3 (additional crop listed)'
   ag10_02_2d 'Crop Code 4 (additional crop listed)'
   ag10_02_2e 'Crop Code 5 (additional crop listed)'
   ag10_02_2f 'Crop Code 6 (additional crop listed)'
   ag10_02_2g 'Crop Code 7 (additional crop listed)'
   ag10_02_2h 'Crop Code 8 (additional crop listed)'
   ag10_02_2i 'Crop Code 9 (additional crop listed)'
   ag10_02_2j 'Crop Code 10(additional crop listed)'
   ag10_04_1 'What is the quantity produced in the last 12 months?  AMOUNT'
   ag10_04_2 'What is the quantity produced in the last 12 months?  UNIT'
   ag10_05    'How much [CROP] did you use as input for [BY-PRODUCT] in last 12 ' +
   'months? (KG)'
   ag10_06 'Was any [BY-PRODUCT] sold?'
   ag10_07_1 'How much was sold? AMOUNT'
   ag10_07_2 'How much was sold? UNIT'
   ag10_08    'How much [CROP] did you use as input for the sold [BY-PRODUCT]? (' +
   'KG)'
   ag10_09_1    'Who in HH was responsible for negotiationg the sale of [BY-PRODUC' +
   'T]? (ID 1)'
   ag10_09_2    'Who in HH was responsible for negotiationg the sale of [BY-PRODUC' +
   'T]? (ID 2)'
   ag10_10_1    'Who in your household decided what to do with these earnings? (ID' +
   ' #1)'
   ag10_10_2    'Who in you household decided what to do with these earnings? (ID ' +
   '#2)'
   ag10_11 'What was total sales in shillings?'
   ag10_12_1a 'Where did you sell most of the [BY-PRODUCT] that you sold?'
   ag10_12_1b 'Where is [NETWORK 1] located?'
   ag10_12_2a 'Where did you sell most of the [BY-PRODUCT] that you sold?'
   ag10_12_2b 'Where is [NETWORK 2] located?'
   ag10_13 'Did you incur any other expenses in production of [BY-PRODUCT]?'
   ag10_14 'What were the total costs of these additional expenses? (TSH)' .

VALUE LABELS
 ag10_02_3
     1 'PROCESSED'
     2 'BY-PRODUCT' /
 ag10_03
     1 'FLOUR'
     2 'SEED'
     3 'PALM OIL'
     4 'JUICE'
     5 'THREAD'
     6 'PULP'
     7 'RUBBER'
     8 'OTHER (SPECIFY)'
     9 'MAIZE BRAN'
     10 'WET HUSK (WHEAT BARLEY)'
     11 'RICE COVER'
     12 'JUICE'
     13 'THREAD'
     14 'PULP'
     15 'PALM OIL'
     16 'OUTER COVER'
     17 'NO WASTE'
     18 'OTHER (SPECIFY)' /
 ag10_02_2a ag10_02_2b ag10_02_2c ag10_02_2d ag10_02_2e ag10_02_2f ag10_02_2g ag10_02_2h ag10_02_2i
     11 'MAIZE'
     12 'PADDY'
     13 'SORGHUM'
     14 'BULRUSH MILLET'
     15 'FINGER MILLET'
     16 'WHEAT'
     17 'BARLEY'
     18 'BLACK PEPPER'
     19 'SEAWEED'
     21 'CASSAVA'
     22 'SWEET POTATOES'
     23 'IRISH POTATOES'
     24 'YAMS'
     25 'COCOYAMS'
     26 'ONIONS'
     27 'GINGER'
     31 'BEANS'
     32 'COWPEAS'
     33 'GREEN GRAM'
     34 'PIGEON PEA'
     35 'CHICK PEAS'
     36 'BAMBARA NUTS'
     37 'FIELD PEAS'
     38 'MALAY APPLE'
     39 'STAR FRUIT'
     41 'SUNFLOWER'
     42 'SESAME'
     43 'GROUNDNUT'
     44 'PALM OIL'
     45 'COCONUT'
     46 'CASHEW NUT'
     47 'SOYABEANS'
     48 'CASTER SEED'
     50 'COTTON'
     51 'TOBACCO'
     52 'PYRETHRUM'
     53 'SISAL'
     54 'COFFEE'
     55 'TEA'
     56 'COCOA'
     57 'RUBBER'
     58 'WATTLE'
     59 'KAPOK'
     60 'SUGAR CANE'
     61 'CARDAMOM'
     62 'JUTE'
     63 'TAMARIND'
     64 'CINNAMON'
     65 'NUTMEG'
     66 'CLOVE'
     67 'BREAD FRUIT'
     68 'POMELO'
     69 'JACK FRUIT'
     70 'PASSION FRUIT'
     71 'BANANA'
     72 'AVOCADO'
     73 'MANGO'
     74 'PAPAW'
     75 'PINEAPPLE'
     76 'ORANGE'
     77 'GRAPEFRUIT'
     78 'GRAPES'
     79 'MANDARIN'
     80 'GUAVA'
     81 'PLUMS'
     82 'APPLES'
     83 'PEARS'
     84 'PEACHES'
     86 'CABBAGE'
     87 'TOMATOES'
     88 'SPINACH'
     89 'CARROT'
     90 'CHILIES'
     91 'AMARANTHS'
     92 'PUMPKINS'
     93 'CUCUMBER'
     94 'EGG PLANT'
     95 'WATER MELLON'
     96 'CAULIFLOWER'
     97 'DURIAN'
     98 'BILIMBI'
     99 'RAMBUTAN'
     100 'OKRA'
     101 'FIWI'
     200 'CUSTARD APPLE'
     201 'GOD FRUIT'
     202 'MITOBO'
     203 'PLUM'
     204 'PEACHES'
     205 'POMEGRANATE'
     210 'DATE'
     211 'TUNGAMAA'
     212 'VANILLA'
     300 'GREEN TOMATO'
     301 'MONKEYBREAD'
     302 'BAMBOO'
     303 'FIREWOOD/FODDER'
     304 'TIMBER'
     305 'MEDICINAL PLANT'
     306 'FENCE TREE'
     851 'LIME'
     852 'LEMON'
     998 'OTHER (SPECIFY)' /
 ag10_04_2
     1 'KG'
     2 'LITRE' /
 ag10_06
     1 'YES'
     2 'NO' /
 ag10_07_2
     1 'KG'
     2 'LITRE' /
 ag10_12_1a
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag10_12_1b
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag10_12_2a
     0 'NOT APPLICABLE'
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag10_12_2b
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag10_13
     1 'YES'
     2 'NO' / .


SAVE OUTFILE='.\ag_sec_10.sav'.
