/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\ag_sec_5a.dat" ENCODING="CP1252" / LRECL=183 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        cropid 23-25          
   ag5a_01 26               ag5a_02 27-32            ag5a_03 33-40         
   ag5a_04_1 41-42          ag5a_04_2 43             ag5a_05 44-49         
   ag5a_06 50-57            ag5a_07_1 58-59          ag5a_07_2 60-63       
   ag5a_08 64-68            ag5a_09_1 69-70          ag5a_09_2 71-72       
   ag5a_10_1 73-74          ag5a_10_2 75-76          ag5a_11a 77           
   ag5a_11_1 78-79          ag5a_11_2 80             ag5a_12 81-85         
   ag5a_13 86-92            ag5a_14_1 93-94          ag5a_14_2 95-98       
   ag5a_15 99               ag5a_16_1 100            ag5a_16_2 101         
   ag5a_17_1 102            ag5a_17_2 103            ag5a_18 104           
   ag5a_19 105-109          ag5a_20 110-113          ag5a_21 114           
   ag5a_22 115-121          ag5a_23 122              ag5a_24 123-128       
   ag5a_25 129              ag5a_26 130              ag5a_27 131           
   ag5a_28 132              ag5a_29 133              ag5a_30 134           
   ag5a_31 135-136          ag5a_32 137-143          ag5a_32a 144-149      
   ag5a_32b 150-155         ag5a_32c 156-159         ag5a_32d 160-164      
   ag5a_32e 165-168         ag5a_33 169              ag5a_34 170-173       
   ag5a_35 174-179          ag5a_36_1a 180           ag5a_36_1b 181        
   ag5a_36_2a 182           ag5a_36_2b 183 .      

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   cropid 'CROP CODE'
   ag5a_01    'Did you sell any of the [CROP] produced in the long rainy season ' +
   '2020?'
   ag5a_02 'What was the quantity sold? (KG)'
   ag5a_03 'What was the total value of the sales? (TSH)'
   ag5a_04_1    'To whom did you sell the largest amount of [CROP] to? (NETWORK ID' +
   ')'
   ag5a_04_2 'Where is [NETWORK] located? (NETWORK ROSTER LOCATION)'
   ag5a_05 'What quantity of [CROP] did you sell to [CUSTOMER #1]? (KG)'
   ag5a_06 'What was the total value of these sales to [CUSTOMER #1] (TSH)?'
   ag5a_07_1 'During which MONTH did you sell most of [CROP] to [CUSTOMER #1]?'
   ag5a_07_2 'During which YEAR did you sell most of [CROP] to [CUSTOMER #1]?'
   ag5a_08    'Approximate nb of transactions taken place while selling [CROP] t' +
   'o [CUSTOMER #1]'
   ag5a_09_1    'Who in HH is responsible for negotiating sale of [CROP] to [CUSTO' +
   'MER #1]? (ID 1)'
   ag5a_09_2    'Who in HH is responsible for negotiating sale of [CROP] to [CUSTO' +
   'MER #1]? (ID 2)'
   ag5a_10_1    'Who in your household decided what to do with these earnings? (ID' +
   ' 1)'
   ag5a_10_2    'Who in your household decided what to do with these earnings? (ID' +
   ' 2)'
   ag5a_11a 'Did you sell to another customer besides [CUSTOMER #1]?'
   ag5a_11_1    'To whom did you sell the second largest amount of [CROP] to? (NET' +
   'WORK ID)'
   ag5a_11_2 'Where is [NETWORK] located? (NETWORK ROSTER LOCATION)'
   ag5a_12 'What quantity of [CROP] did you sell to [CUSTOMER #2]? (KG)'
   ag5a_13 'What was the total value of these sales to [CUSTOMER #2]? (TSH)'
   ag5a_14_1 'During which MONTH did you sell most of [CROP] to [CUSTOMER #2]?'
   ag5a_14_2 'During which YEAR did you sell most of [CROP] to [CUSTOMER #2]?'
   ag5a_15    'Approximate nb of transactions taken place while selling [CROP] t' +
   'o [CUSTOMER #2]'
   ag5a_16_1    'Who in HH is responsible for negotiating sale of [CROP] to [CUSTO' +
   'MER #2]? (ID 1)'
   ag5a_16_2    'Who in HH is responsible for negotiating sale of [CROP] to [CUSTO' +
   'MER #2]? (ID 2)'
   ag5a_17_1    'Who in your household decided what to do with these earnings? (ID' +
   ' 1)'
   ag5a_17_2    'Who in your household decided what to do with these earnings? (ID' +
   ' 2)'
   ag5a_18 'Generally, did you transport [CROP] for sale?'
   ag5a_19    'What is the average distance you transported [CROP] for sale? (KM' +
   ')'
   ag5a_20    'How many times did you transport [CROP] for sale during long rain' +
   'y season 2020?'
   ag5a_21 'Generally, how did you transport [CROP]?'
   ag5a_22    'How much did you pay to transport [CROP] during long rainy season' +
   ' 2020? (TSH)'
   ag5a_23    'Do you have any of the harvest from the long rainy season 2020 in' +
   ' storage now?'
   ag5a_24 'How much of this harvest do you still have in storage? (KG)'
   ag5a_25 'What is your main method of storage?'
   ag5a_26 'Did you do anything to protect the stored crop?'
   ag5a_27 'What did you do?'
   ag5a_28    'When you store [CROP], what is usually the main purpose of storin' +
   'g it?'
   ag5a_29    'Any portion of production lost post-harvest to rotting, insects..' +
   '.'
   ag5a_30 'What was the reason for the loss?'
   ag5a_31 'Out of 10 units of [CROP], how many were lost?'
   ag5a_32 'What was the value of this lost crop? (TSH)'
   ag5a_32a 'How much of the harvest was consumed? (KG)'
   ag5a_32b    'How much of the harvest was stored as seed for the next planting ' +
   'season? (KG)'
   ag5a_32c    'How much of the harvest was given as payments for labour or non-l' +
   'abour payments?'
   ag5a_32d 'How much of the harvest was given away as gifts? (KG)'
   ag5a_32e 'How much of the harvest was used as animal feed? (KG)'
   ag5a_33 'What was done with the residue from this crop?'
   ag5a_34 'What was the quantity sold? (KG)'
   ag5a_35 'What was the total value of the sales? (TSH)'
   ag5a_36_1a    'To whom did you sell the most of the residue from [CROP] to? (NET' +
   'WORK ID 1)'
   ag5a_36_1b 'Where is this [NETWORK] located? (NR 1 LOCATION)'
   ag5a_36_2a    'To whom did you sell the most of the residue from [CROP] to? (NET' +
   'WORK ID 2)'
   ag5a_36_2b 'Where is this [NETWORK] located? (NR 2 LOCATION)' .

VALUE LABELS
 cropid
     11 'MAIZE'
     12 'PADDY'
     13 'SORGHUM'
     14 'BULRUSH MILLET'
     15 'FINGER MILLET'
     16 'WHEAT'
     17 'BARLEY'
     18 'BLACK PEPPER'
     19 'SEAWEED'
     21 'CASSAVA'
     22 'SWEET POTATOES'
     23 'IRISH POTATOES'
     24 'YAMS'
     25 'COCOYAMS'
     26 'ONIONS'
     27 'GINGER'
     31 'BEANS'
     32 'COWPEAS'
     33 'GREEN GRAM'
     34 'PIGEON PEA'
     35 'CHICK PEAS'
     36 'BAMBARA NUTS'
     37 'FIELD PEAS'
     38 'MALAY APPLE'
     39 'STAR FRUIT'
     41 'SUNFLOWER'
     42 'SESAME'
     43 'GROUNDNUT'
     44 'PALM OIL'
     45 'COCONUT'
     46 'CASHEW NUT'
     47 'SOYABEANS'
     48 'CASTER SEED'
     50 'COTTON'
     51 'TOBACCO'
     52 'PYRETHRUM'
     53 'SISAL'
     54 'COFFEE'
     55 'TEA'
     56 'COCOA'
     57 'RUBBER'
     58 'WATTLE'
     59 'KAPOK'
     60 'SUGAR CANE'
     61 'CARDAMOM'
     62 'JUTE'
     63 'TAMARIND'
     64 'CINNAMON'
     65 'NUTMEG'
     66 'CLOVE'
     67 'BREAD FRUIT'
     68 'POMELO'
     69 'JACK FRUIT'
     70 'PASSION FRUIT'
     71 'BANANA'
     72 'AVOCADO'
     73 'MANGO'
     74 'PAPAW'
     75 'PINEAPPLE'
     76 'ORANGE'
     77 'GRAPEFRUIT'
     78 'GRAPES'
     79 'MANDARIN'
     80 'GUAVA'
     81 'PLUMS'
     82 'APPLES'
     83 'PEARS'
     84 'PEACHES'
     86 'CABBAGE'
     87 'TOMATOES'
     88 'SPINACH'
     89 'CARROT'
     90 'CHILIES'
     91 'AMARANTHS'
     92 'PUMPKINS'
     93 'CUCUMBER'
     94 'EGG PLANT'
     95 'WATER MELLON'
     96 'CAULIFLOWER'
     97 'DURIAN'
     98 'BILIMBI'
     99 'RAMBUTAN'
     100 'OKRA'
     101 'FIWI'
     200 'CUSTARD APPLE'
     201 'GOD FRUIT'
     202 'MITOBO'
     203 'PLUM'
     204 'PEACHES'
     205 'POMEGRANATE'
     210 'DATE'
     211 'TUNGAMAA'
     212 'VANILLA'
     300 'GREEN TOMATO'
     301 'MONKEYBREAD'
     302 'BAMBOO'
     303 'FIREWOOD/FODDER'
     304 'TIMBER'
     305 'MEDICINAL PLANT'
     306 'FENCE TREE'
     851 'LIME'
     852 'LEMON'
     998 'OTHER (SPECIFY)' /
 ag5a_01
     1 'YES'
     2 'NO' /
 ag5a_04_1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag5a_04_2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag5a_07_1
     1 'JANUARY'
     2 'FEBRUARY'
     3 'MARCH'
     4 'APRIL'
     5 'MAY'
     6 'JUNE'
     7 'JULY'
     8 'AUGUST'
     9 'SEPTEMBER'
     10 'OCTOBER'
     11 'NOVEMBER'
     12 'DECEMBER' /
 ag5a_11a
     1 'NDIYO'
     2 'HAPANA' /
 ag5a_11_1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag5a_11_2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag5a_14_1
     1 'JANUARY'
     2 'FEBRUARY'
     3 'MARCH'
     4 'APRIL'
     5 'MAY'
     6 'JUNE'
     7 'JULY'
     8 'AUGUST'
     9 'SEPTEMBER'
     10 'OCTOBER'
     11 'NOVEMBER'
     12 'DECEMBER' /
 ag5a_18
     1 'YES'
     2 'NO' /
 ag5a_21
     1 'ON FOOT'
     2 'BICYCLE'
     3 'ANIMAL'
     4 'CAR'
     5 'OTHER (SPECIFY)'
     6 'MOTORCYCLE' /
 ag5a_23
     1 'YES'
     2 'NO' /
 ag5a_25
     1 'LOCALLY MADE TRADITIONAL STRUCTURE'
     2 'IMPROVED LOCALLY MADE STRUCTURE'
     3 'MODERN STORE'
     4 'SACKS / OPEN DRUM'
     5 'AIRTIGHT DRUM'
     6 'UNPROTECTED PILE'
     7 'CEILING'
     8 'OTHER (SPECIFY)' /
 ag5a_26
     1 'YES'
     2 'NO' /
 ag5a_27
     1 'SPRAYING'
     2 'SMOKING'
     3 'OTHER (SPECIFY)' /
 ag5a_28
     1 'FOOD FOR HOUSEHOLD'
     2 'TO SELL AT HIGHER PRICE'
     3 'SEED FOR PLANTING'
     4 'OTHER (SPECIFY)' /
 ag5a_29
     1 'YES'
     2 'NO' /
 ag5a_30
     1 'ROTTING'
     2 'INSECTS'
     3 'PESTS'
     4 'THEFT'
     5 'OTHER (SPECIFY)' /
 ag5a_33
     1 'CROP PRODUCES NO  RESIDUE'
     2 'RESIDUE WAS LEFT IN FIELD'
     3 'MULCHED'
     4 'FOR GRAZING OWN ANIMALS'
     5 "FOR GRAZING OTHERS' ANIMALS"
     6 'FEEDING OWN ANIMALS'
     7 'FOR SALE'
     8 'OTHER (SPECIFY)' /
 ag5a_36_1a
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag5a_36_1b
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag5a_36_2a
     0 'NOT APPLICABLE'
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag5a_36_2b
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' / .


SAVE OUTFILE='.\ag_sec_5a.sav'.
