/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\ag_sec_11.dat" ENCODING="CP1252" / LRECL=56 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        itemid 23-24          
   ag11_01 25-28            ag11_02 29-36            ag11_03 37            
   ag11_04 38               ag11_05 39               ag11_06 40            
   ag11_07 41-46            ag11_08_1 47-48          ag11_08_2 49          
   ag11_09 50-56 .       

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   itemid 'Item Code'
   ag11_01 'How many [ITEM] does the household own?'
   ag11_02 'What is the value of the [ITEM] if sold? (TSH)'
   ag11_03 'Did the household own [ITEM] during the last 12 months?'
   ag11_04 'Did you use [ITEM] in the last 12 months?'
   ag11_05 'What was the reason for not using [ITEM]?'
   ag11_06    'Did your household rent or borrow any [ITEM] for use in the last ' +
   '12 months?'
   ag11_07    'How many [ITEM] did the household rent or borrow in the last 12 m' +
   'onths?'
   ag11_08_1    'Where did your household rent or borrow [ITEM] from last 12 month' +
   's?'
   ag11_08_2 'Where is [NETWORK] located?'
   ag11_09    'How much did your household pay to rent or borrow [ITEM] last 12 ' +
   'months? (TSH)' .

VALUE LABELS
 itemid
     1 'HAND HOE'
     2 'HAND-POWERED SPRAYER'
     3 'OX PLOUGH'
     4 'OX SEED PLANTER'
     5 'OX CART'
     6 'TRACTOR'
     7 'TRACTOR PLOUGH'
     8 'TRACTOR HARROW'
     9 'SHELLER/THRESHER'
     10 'HAND MILL/GRINDER'
     11 'WATERING CAN'
     12 'FARM BUILDINGS/STORAGE FACILITIES'
     13 'GERI CANS/DRUMS'
     14 'POWER TILLER'
     15 'OTHER (SPECIFY)' /
 ag11_03
     1 'YES'
     2 'NO' /
 ag11_04
     1 'YES'
     2 'NO' /
 ag11_05
     1 'NO NEED FOR ONE'
     2 'NEEDS REPAIR/SICK'
     3 'LENT TO OTHERS'
     4 'RENTED TO OTHERS'
     5 'OTHER' /
 ag11_06
     1 'YES'
     2 'NO' /
 ag11_08_1
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag11_08_2
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' / .


SAVE OUTFILE='.\ag_sec_11.sav'.
