/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\ag_sec_12a.dat" ENCODING="CP1252" / LRECL=49 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        sourceid 23           
   ag12a_01_1 24            ag12a_01_2 25            ag12a_01_3 26         
   ag12a_01_4 27            ag12a_01_5 28            ag12a_01_6 29         
   ag12a_01_7 30            ag12a_01_8 31            ag12a_02 32           
   ag12a_03_1 33-34         ag12a_03_2 35-36         ag12a_03_3 37-38      
   ag12a_03_4 39            ag12a_04 40              ag12a_05 41           
   ag12a_06 42-47           ag12a_07 48-49 .      

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   sourceid 'Source ID'
   ag12a_01_1    'In last 12 months, received advice from [SOURCE] about [SEEDS / P' +
   'LANTING]'
   ag12a_01_2    'In last 12 months, received advice from [SOURCE] about [FERTILIZE' +
   'R]'
   ag12a_01_3    'In last 12 months, received advice from [SOURCE] about [LAND MANA' +
   'GEMENT]'
   ag12a_01_4    'In last 12 months, received advice from [SOURCE] about [AGRO-PROC' +
   'ESSING]'
   ag12a_01_5    'In last 12 months, received advice from [SOURCE] about [MARKETING' +
   ']'
   ag12a_01_6    'In last 12 months, received advice from [SOURCE] about [FISHING P' +
   'RODUCTION]'
   ag12a_01_7    'In last 12 months, received advice from [SOURCE] about [LIVESTOCK' +
   ' PRODUCTION]'
   ag12a_01_8    'In last 12 months, received advice from [SOURCE] about [LIVESTOCK' +
   ' DISEASES]'
   ag12a_02    'CAPI: DID THE RESPONDENT ANSWER YES FOR ANY TYPE OF ADVICE IN Q1?'
   ag12a_03_1 'Who in your household received advice from [SOURCE]? (ID #1)'
   ag12a_03_2 'Who in your household received advice from [SOURCE]? (ID #2)'
   ag12a_03_3 'Who in your household received advice from [SOURCE]? (ID #3)'
   ag12a_03_4 'Who in your household received advice from [SOURCE]? (ID #4)'
   ag12a_04 'How would you rate the advice received?'
   ag12a_05 'Did you pay anything in order to receive the advice?'
   ag12a_06 'How much did you pay?'
   ag12a_07    'How many times did someone from [SOURCE] visit your farm in the p' +
   'ast 12 months?' .

VALUE LABELS
 sourceid
     1 'GOVERNMENT EXTENSION'
     2 'NGO'
     3 "COOPERATIVE/FARMER'S ASSOCIATION"
     4 'LARGE SCALE FARMER'
     5 'OTHER' /
 ag12a_01_1
     1 'YES'
     2 'NO' /
 ag12a_01_2
     1 'YES'
     2 'NO' /
 ag12a_01_3
     1 'YES'
     2 'NO' /
 ag12a_01_4
     1 'YES'
     2 'NO' /
 ag12a_01_5
     1 'YES'
     2 'NO' /
 ag12a_01_6
     1 'YES'
     2 'NO' /
 ag12a_01_7
     1 'YES'
     2 'NO' /
 ag12a_01_8
     1 'YES'
     2 'NO' /
 ag12a_02
     1 'YES'
     2 'NO' /
 ag12a_04
     1 'GOOD'
     2 'AVERAGE'
     3 'BAD' /
 ag12a_05
     1 'YES'
     2 'NO' /
 ag12a_07
     0 'NEVER' / .


SAVE OUTFILE='.\ag_sec_12a.sav'.
