/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\ag_sec_7b.dat" ENCODING="CP1252" / LRECL=93 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        cropid 23-25          
   ag7b_02 26               ag7b_03 27-33            ag7b_04 34-41         
   ag7b_05_1 42-43          ag7b_05_2 44-45          ag7b_06_1 46-47       
   ag7b_06_2 48-49          ag7b_07_1a 50-51         ag7b_07_1b 52         
   ag7b_07_2a 53-54         ag7b_07_2b 55            ag7b_08 56            
   ag7b_09 57-60            ag7b_10 61               ag7b_11 62            
   ag7b_12 63               ag7b_13 64               ag7b_14 65            
   ag7b_15 66               ag7b_16 67-73            ag7b_17 74-79         
   ag7b_18 80-82            ag7b_19 83-85            ag7b_20 86-89         
   ag7b_21 90-93 .       

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   cropid 'Fruit Tree Crop Code'
   ag7b_02 'Did you sell any of the [FRUIT] collected?'
   ag7b_03 'What was the total quanity sold? (KG)'
   ag7b_04 'What was the total value of [FRUIT] sold? (TSH)'
   ag7b_05_1    'Who in HH was responsible for negotiating sale of [FRUIT]? (ID 1)'
   ag7b_05_2    'Who in HH was responsible for negotiating sale of [FRUIT]? (ID 2)'
   ag7b_06_1    'Who in your household decided what to do with these earnings? (HH' +
   ' ID 1)'
   ag7b_06_2    'Who in your household decided what to do with these earnings? (HH' +
   ' ID 2)'
   ag7b_07_1a 'Where did you sell most of the fruit? (NR ID 1)'
   ag7b_07_1b 'Where is [NETWORK] located? (NR 1 LOCATION)'
   ag7b_07_2a 'Where did you sell most of the fruit? (NR ID 2)'
   ag7b_07_2b 'Where is [NETWORK] located? (NR 2 LOCATION)'
   ag7b_08 'Do you have any of this harvest in storage now?'
   ag7b_09 'How much of this harvest do you still have in storage? (KG)'
   ag7b_10 'What is your main method of storage?'
   ag7b_11 'Did you do anything to protect the stored crop?'
   ag7b_12 'What did you do?'
   ag7b_13    'Portion of production lost post-harvest to rotting, insects, rode' +
   'nts, theft, etc'
   ag7b_14 'What was the reason for this loss?'
   ag7b_15 'Out of 10 units of [FRUIT], how many were lost?'
   ag7b_16 'What was the value of this lost [FRUIT]? (TSH)'
   ag7b_17 'How much of the harvest was consumed? (KG)'
   ag7b_18    'How much of the harvest was stored as seed for the next planting ' +
   'season? (KG)'
   ag7b_19    'How much of the harvest was given as payments for labour or non-l' +
   'abour payments?'
   ag7b_20 'How much of the harvest was given away as gifts? (KG)'
   ag7b_21 'How much of the harvest was used as animal feed? (KG)' .

VALUE LABELS
 cropid
     11 'MAIZE'
     12 'PADDY'
     13 'SORGHUM'
     14 'BULRUSH MILLET'
     15 'FINGER MILLET'
     16 'WHEAT'
     17 'BARLEY'
     18 'BLACK PEPPER'
     19 'SEAWEED'
     21 'CASSAVA'
     22 'SWEET POTATOES'
     23 'IRISH POTATOES'
     24 'YAMS'
     25 'COCOYAMS'
     26 'ONIONS'
     27 'GINGER'
     31 'BEANS'
     32 'COWPEAS'
     33 'GREEN GRAM'
     34 'PIGEON PEA'
     35 'CHICK PEAS'
     36 'BAMBARA NUTS'
     37 'FIELD PEAS'
     38 'MALAY APPLE'
     39 'STAR FRUIT'
     41 'SUNFLOWER'
     42 'SESAME'
     43 'GROUNDNUT'
     44 'PALM OIL'
     45 'COCONUT'
     46 'CASHEW NUT'
     47 'SOYABEANS'
     48 'CASTER SEED'
     50 'COTTON'
     51 'TOBACCO'
     52 'PYRETHRUM'
     53 'SISAL'
     54 'COFFEE'
     55 'TEA'
     56 'COCOA'
     57 'RUBBER'
     58 'WATTLE'
     59 'KAPOK'
     60 'SUGAR CANE'
     61 'CARDAMOM'
     62 'JUTE'
     63 'TAMARIND'
     64 'CINNAMON'
     65 'NUTMEG'
     66 'CLOVE'
     67 'BREAD FRUIT'
     68 'POMELO'
     69 'JACK FRUIT'
     70 'PASSION FRUIT'
     71 'BANANA'
     72 'AVOCADO'
     73 'MANGO'
     74 'PAPAW'
     75 'PINEAPPLE'
     76 'ORANGE'
     77 'GRAPEFRUIT'
     78 'GRAPES'
     79 'MANDARIN'
     80 'GUAVA'
     81 'PLUMS'
     82 'APPLES'
     83 'PEARS'
     84 'PEACHES'
     86 'CABBAGE'
     87 'TOMATOES'
     88 'SPINACH'
     89 'CARROT'
     90 'CHILIES'
     91 'AMARANTHS'
     92 'PUMPKINS'
     93 'CUCUMBER'
     94 'EGG PLANT'
     95 'WATER MELLON'
     96 'CAULIFLOWER'
     97 'DURIAN'
     98 'BILIMBI'
     99 'RAMBUTAN'
     100 'OKRA'
     101 'FIWI'
     200 'CUSTARD APPLE'
     201 'GOD FRUIT'
     202 'MITOBO'
     203 'PLUM'
     204 'PEACHES'
     205 'POMEGRANATE'
     210 'DATE'
     211 'TUNGAMAA'
     212 'VANILLA'
     300 'GREEN TOMATO'
     301 'MONKEYBREAD'
     302 'BAMBOO'
     303 'FIREWOOD/FODDER'
     304 'TIMBER'
     305 'MEDICINAL PLANT'
     306 'FENCE TREE'
     851 'LIME'
     852 'LEMON'
     998 'OTHER (SPECIFY)' /
 ag7b_02
     1 'YES'
     2 'NO' /
 ag7b_07_1a
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag7b_07_1b
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag7b_07_2a
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'GROCERY / LOCAL MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER, SPECIFY'
     21 'VILLAGE GOVERNMENT' /
 ag7b_07_2b
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 ag7b_08
     1 'YES'
     2 'NO' /
 ag7b_10
     1 'LOCALLY MADE TRADITIONAL STRUCTURE'
     2 'IMPROVED LOCALLY MADE STRUCTURE'
     3 'MODERN STRUCTURE'
     4 'SACKS/OPEN DRUM'
     5 'AIRTIGHT DRUM'
     6 'UNPROTECTED PILE'
     7 'OTHER (SPECIFY)' /
 ag7b_11
     1 'YES'
     2 'NO' /
 ag7b_12
     1 'SPRAYING'
     2 'SMOKING'
     3 'OTHER (SPECIFY)' /
 ag7b_13
     1 'YES'
     2 'NO' /
 ag7b_14
     1 'ROTTING'
     2 'INSECTS'
     3 'RODENTS, PESTS'
     4 'THEFT'
     5 'OTHER (SPECIFY)' / .


SAVE OUTFILE='.\ag_sec_7b.sav'.
