/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\cm_sec_f_id.dat" ENCODING="CP1252" / LRECL=69 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   interview__id 12-43 (A)   item_id 44-45         
   cm_f061 46               cm_f062 47-51            cm_f063 52-57         
   cm_f064 58               cm_f065 59-63            cm_f066 64-69 .       

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   interview__id 'Unique 32-character long identifier of the interview'
   item_id 'Food Item ID'
   cm_f061 'Unit (Village/MTAA)'
   cm_f062 'Weight (Village/MTAA)'
   cm_f063 'Price (Village/MTAA)'
   cm_f064 'Unit (District Capital)'
   cm_f065 'Weight (District Capital)'
   cm_f066 'Price (District Capital)' .

VALUE LABELS
 item_id
     1 'RICE (PADDY)'
     2 'RICE (HUSKED)'
     3 'MAIZE (GREEN, COB)'
     4 'MAIZE (GRAIN)'
     5 'MAIZE (FLOUR)'
     6 'MILLET (GRAIN)'
     7 'SORGHUM (GRAIN)'
     8 'MILLET (FLOUR)'
     9 'SORGHUM (FLOUR)'
     10 'BREAD'
     11 'BUNS'
     12 'CASSAVA FRESH'
     13 'CASSAVA (DRY)'
     14 'CASSAVA FLOUR'
     15 'SWEET POTATOES'
     16 'COCOYAMS'
     17 'YAMS'
     18 'IRISH POTATOES'
     19 'COOKING BANANAS'
     20 'SUGAR'
     21 'BEANS'
     22 'PEAS'
     23 'GROUNDNUTS'
     24 'COCONUTS'
     25 'CARROTS'
     26 'TOMATOES'
     27 'ONIONS'
     28 'SPINACH'
     29 'CABBAGE'
     30 'RIPE BANANAS'
     31 'CITRUS FRUITS'
     32 'PAPAYA'
     33 'MANGOES'
     34 'GOAT MEAT'
     35 'BEEF'
     36 'CHICKEN (LIVE)'
     37 'EGGS'
     38 'FRESH FISH'
     39 'DAGAA'
     40 'FRESH MILK'
     41 'CANNED MILK/POWDER'
     42 'COOKING OIL'
     43 'SALT'
     44 'TEA (DRY)'
     45 'LOCAL BREWS'
     46 'KEROSINE'
     47 'CHARCOAL'
     48 'MAIZE GRINDING COSTS'
     49 'FIREWOOD'
     50 'MATCHES'
     51 'CIGARETTES'
     52 'BATTERIES' /
 cm_f061
     1 'KILOGRAMS'
     2 'GRAMS'
     3 'LITRES'
     4 'MILLILITRES'
     5 'PIECES' /
 cm_f064
     1 'KILOGRAMS'
     2 'GRAMS'
     3 'LITRES'
     4 'MILLILITRES'
     5 'PIECES' / .


SAVE OUTFILE='.\cm_sec_f_id.sav'.
