/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\cm_sec_b.dat" ENCODING="CP1252" / LRECL=71 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   interview__id 12-43 (A)   service_id 44-45      
   cm_b01 46                cm_b02 47-51             cm_b03 52-55          
   cm_b04 56-71 (A) .    


FORMATS
  cm_b03 (F5.1) / .
     
VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   interview__id 'Unique 32-character long identifier of the interview'
   service_id 'Basic Service ID'
   cm_b01 'Is the service available?'
   cm_b02    'Cost of transport from the village centre, one way, per person, b' +
   'y public transp'
   cm_b03 'What is the distance to this service? [KM]'
   cm_b04 'Name of the service/institution' .

VALUE LABELS
 service_id
     1 'DISTANCE TO REGIONAL HEADQUARTERS'
     2 'DISTANCE TO DISTRICT HEADQUARTERS'
     3 'PRE-PRIMARY SCHOOL OR NURSERY SCHOOL - THE NEAREST'
     4 'GOVERNMENT PRIMARY SCHOOL - THE NEAREST'
     5 'PRIVATE PRIMARY SCHOOL - THE NEAREST'
     6 'GOVERNMENT SECONDARY SCHOOL - THE NEAREST'
     7 'PRIVATE SECONDARY SCHOOL - THE NEAREST'
     8 'GOVERNMENT HEALTH CENTRE OR DISPENSARY - THE NEAREST'
     9 'GOVERNMENT HOSPITAL - THE NEAREST'
     10 'PRIVATE HEALTH CENTRE OR CLINIC - THE NEAREST'
     11 'PRIVATE HOSPITAL - THE NEAREST'
     12 'MARKET (DAILY)'
     13 'MARKET (WEEKLY)'
     14 'MILLING MACHINE - THE NEAREST'
     15 'BANK - THE NEAREST'
     16 'ATM'
     17 'MOBILE MONEY AGENT POINT (MPESA, TIGO PESA, ETC)'
     18 'SACCOS - THE NEAREST'
     19 'VETERINARY SERVICES (DIPS AND OTHER VET SERVICES)'
     20 'BIRTH AND DEATH REGISTRATION SERVICES'
     21 'POLICE STATION OR POST - THE NEAREST'
     22 'COURT (PRIMARY) - THE NEAREST'
     23 'POST OFFICE - THE NEAREST'
     24 'COMMUNITY/PUBLICLY OWNED TAP WATER - THE NEAREST'
     25 'SLAUGHTER SLABS'
     26 'VETERINARY CENTRE/CLINIC'
     27 'DIP TANK'
     28 'PRIMARY MARKET FOR LIVESTOCK'
     29 'CHARCOS DAM'
     30 'HIDE AND SKIN BANDAS'
     31 'MILK COLLECTION CENTER' /
 cm_b01
     1 'YES, WITHIN VILLAGE/MTAA'
     2 'NO, NOT WITHIN VILLAGE/MTAA'
     3 'NOT APPLICABLE' /
 cm_b02
     0 'NONE/FREE'
     1 'NONE/FREE' / .


SAVE OUTFILE='.\cm_sec_b.sav'.
