/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\cm_sec_g.dat" ENCODING="CP1252" / LRECL=126 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   interview__id 12-43 (A)   item_id 44-45         
   obs_id 46                vil_item_avail 47        vil_unit_start 48     
   vil_loc_unit 49-50       vil_loc_unit_os 51-57 (A)   vil_loc_weight 58-62  
   vil_loc_price 63-67      vil_loc_photo 68-78 (A)   dist_item_avail 79    
   dist_unit_start 80       dist_loc_unit 81-82      dist_loc_unit_os 83-105 (A)
   dist_loc_weight 106-110   dist_loc_price 111-115
   dist_loc_photo 116-126 (A) .


FORMATS
  vil_loc_weight (F6.2) /  dist_loc_weight (F6.2) / .

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   interview__id 'Unique 32-character long identifier of the interview'
   item_id 'Food Item ID'
   obs_id 'Observation Number'
   vil_item_avail 'IS THE ITEM AVAILABLE AND SOLD IN A LOCAL UNIT?'
   vil_unit_start 'RECORD UNIT FOR ITEM'
   vil_loc_unit 'LOCAL UNIT'
   vil_loc_unit_os 'LOCAL UNIT (OTHER SPECIFY)'
   vil_loc_weight 'LOCAL UNIT WEIGHT (KGS)'
   vil_loc_price 'LOCAL UNIT PRICE'
   vil_loc_photo 'ITEM UNIT PHOTO'
   dist_item_avail 'IS THE ITEM AVAILABLE AND SOLD IN A LOCAL UNIT?'
   dist_unit_start 'RECORD UNIT FOR ITEM'
   dist_loc_unit 'LOCAL UNIT'
   dist_loc_unit_os 'LOCAL UNIT (OTHER SPECIFY)'
   dist_loc_weight 'LOCAL UNIT WEIGHT (KGS)'
   dist_loc_price 'LOCAL UNIT PRICE'
   dist_loc_photo 'ITEM UNIT PHOTO' .

VALUE LABELS
 item_id
     1 'RICE (PADDY)'
     2 'MAIZE (FLOUR)'
     3 'TOMATO'
     4 'BELL PEPPER'
     5 'ONION'
     6 'BEANS'
     7 'SPINACH'
     8 'MANGO'
     9 'AVOCADO'
     10 'CHICKEN'
     11 'BEEF'
     12 'FRESH FISH/SEAFOOD'
     13 'COOKING OIL'
     14 'FRESH/RAW CASSAVA'
     15 'SORGHUM FLOUR' /
 obs_id
     1 'OBSERVATION 1'
     2 'OBSERVATION 2'
     3 'OBSERVATION 3' /
 vil_item_avail
     1 'YES'
     2 'NO' /
 vil_unit_start
     1 'YES'
     2 'NO' /
 vil_loc_unit
     1 'Piece (Idadi)'
     2 'Heap (Fungu)'
     3 'Bunch (mkungu)'
     4 'Splinter (kichane)'
     5 'Spoon (Koroboi/Kibaba)'
     6 'Bowl (Bakuli)'
     7 'Cane (Kopo)'
     8 'Jug (Jagi)'
     9 'Tin container (Debe)'
     10 'Bucket (sandoline)'
     11 'Cup (Kikombe)'
     12 'Bottle (Chupa)'
     13 'Sack (Kiroba)'
     14 'Glass (Glasi)'
     15 'Basket (Tenga)'
     16 'Galon (kidumu)'
     17 'Crate (Sanduku)'
     18 'Other, Specify' /
 dist_item_avail
     1 'YES'
     2 'NO' /
 dist_unit_start
     1 'YES'
     2 'NO' /
 dist_loc_unit
     1 'Piece (Idadi)'
     2 'Heap (Fungu)'
     3 'Bunch (mkungu)'
     4 'Splinter (kichane)'
     5 'Spoon (Koroboi/Kibaba)'
     6 'Bowl (Bakuli)'
     7 'Cane (Kopo)'
     8 'Jug (Jagi)'
     9 'Tin container (Debe)'
     10 'Bucket (sandoline)'
     11 'Cup (Kikombe)'
     12 'Bottle (Chupa)'
     13 'Sack (Kiroba)'
     14 'Glass (Glasi)'
     15 'Basket (Tenga)'
     16 'Galon (kidumu)'
     17 'Crate (Sanduku)'
     18 'Other, Specify' / .


SAVE OUTFILE='.\cm_sec_g.sav'.
