/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\cm_sec_c.dat" ENCODING="CP1252" / LRECL=200 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   interview__id 12-43 (A)   project_id 44-45      
   cm_c01 46                cm_c02 47-56             cm_c03 57-65          
   cm_c04 66                cm_c04_os 67-118 (A)     cm_c05_1 119          
   cm_c05_2 120             cm_c05_3 121             cm_c05_4 122          
   cm_c05_5 123             cm_c05_6 124             cm_c05_7 125          
   cm_c05_8 126             cm_c05_os 127-200 (A) .

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   interview__id 'Unique 32-character long identifier of the interview'
   project_id 'Investment Project ID'
   cm_c01    'Has the village/MTAA implemented any of the following in 2018/201' +
   '9?'
   cm_c02 'How much money was raised in total for this project?'
   cm_c03    'What was the total amount of money contributed by community membe' +
   'rs?'
   cm_c04 'How were contributions raised?'
   cm_c04_os 'Other (specify)'
   cm_c05_1 'PEDP: Did funds come from [SOURCE]?'
   cm_c05_2 'TASAF: Did funds come from [SOURCE]?'
   cm_c05_3 'PADEP: Did funds come from [SOURCE]?'
   cm_c05_4 'DISTRICT/MUNICIPALITY/CITY: Did funds come from [SOURCE]?'
   cm_c05_5 'CENTRAL GOVERNMENT: Did funds come from [SOURCE]?'
   cm_c05_6 'NGO: Did funds come from [SOURCE]?'
   cm_c05_7 'INTERNATIONAL ORGANIZATION: Did funds come from [SOURCE]?'
   cm_c05_8 'OTHER (SPECIFY): Did funds come from [SOURCE]?'
   cm_c05_os 'Other (specify)' .

VALUE LABELS
 project_id
     1 'ROAD CONSTRUCTION, MAINTENANCE & REHABILITATION'
     2 'MARKETS: CONSTRUCTION, MAINTENANCE & REHABILITATION'
     3 'WATER SUPPLY: DIGGING WELL, INSTALLING PUMP, ETC'
     4 'SCHOOL CONSTRUCTION: PRE-PRIMARY'
     5 'SCHOOL MAINTENANCE: PRE-PRIMARY'
     6 'SCHOOL CONSTRUCTION: PRIMARY'
     7 'SCHOOL MAINTENANCE: PRIMARY'
     8 'SCHOOL CONSTRUCTION: SECONDARY'
     9 'SCHOOL MAINTENANCE: SECONDARY'
     10 'HEALTH CENTRE OR DISPENSARY: CONSTRUCTION'
     11 'HEALTH CENTRE OR DISPENSARY: MAINTENANCE'
     12 'IRRIGATION SCHEMES'
     13 'LIVESTOCK INFRASTRUCTURE (VET CENTRE, DIP TANKS, ETC)'
     14 'GRAIN STORAGE FACILITIES: COMMUNITY LEVEL' /
 cm_c01
     1 'YES'
     2 'NO'
     3 'NOT APPLICABLE' /
 cm_c04
     1 'VOLUNTARY'
     2 'COMPULSARY'
     3 'USER FEES FOR A SERVICE'
     4 'OTHER (SPECIFY)' /
 cm_c05_1
     0 'NO'
     1 'YES' /
 cm_c05_2
     0 'NO'
     1 'YES' /
 cm_c05_3
     0 'NO'
     1 'YES' /
 cm_c05_4
     0 'NO'
     1 'YES' /
 cm_c05_5
     0 'NO'
     1 'YES' /
 cm_c05_6
     0 'NO'
     1 'YES' /
 cm_c05_7
     0 'NO'
     1 'YES' /
 cm_c05_8
     0 'NO'
     1 'YES' / .


SAVE OUTFILE='.\cm_sec_c.sav'.
