/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\cm_sec_e.dat" ENCODING="CP1252" / LRECL=149 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   interview__id 12-43 (A)   cm_e01 44             
   cm_e02 45-46             cm_e03 47-50             cm_e04__1 51          
   cm_e04__2 52             cm_e04__3 53             cm_e04__4 54          
   cm_e05 55                cm_e06 56-60             cm_e07_1 61-99 (A)    
   cm_e07_2 100-103         cm_e08 104-109           cm_e09 110-113        
   cm_e10 114-117           cm_e11 118               cm_e12 119-122        
   cm_e13 123-126           cm_e14 127               cm_e15 128            
   cm_e16 129               cm_e17 130               cm_e18 131            
   cm_e19_b 132-133         cm_e19_c 134-136         cm_e20__1 137         
   cm_e20__2 138            cm_e20__3 139            cm_e20__4 140         
   cm_e20__5 141            cm_e20__6 142            cm_e20__7 143         
   cm_e20__8 144            cm_e20__9 145            cm_e20__10 146        
   cm_e20__11 147           cm_e20__12 148           cm_e21 149 .          


FORMATS
  cm_e07_2 (F5.1) / .
   
VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   interview__id 'Unique 32-character long identifier of the interview'
   cm_e01 'Are there any farmers cooperative groups in this village?'
   cm_e02 'How many different farmers groups are there in the community?'
   cm_e03 'How many farmers participate in these cooperatives in total?'
   cm_e04__1    '[BUY INPUTS] Which of the following activities do the cooperative' +
   ' members do as '
   cm_e04__2    '[SELL OUTPUT] Which of the following activities do the cooperativ' +
   'e members do as'
   cm_e04__3    '[IRRIGATION] Which of the following activities do the cooperative' +
   ' members do as '
   cm_e04__4    '[CROP STORAGE] Which of the following activities do the cooperati' +
   've members do a'
   cm_e05 'Is it possible to buy improved maize seeds in this village?'
   cm_e06    'During planting time, what is the price of improved maize seed pe' +
   'r KG in the vil'
   cm_e07_1    'Where is the nearest supplier of improved maize seeds outside the' +
   ' village? [VILL'
   cm_e07_2    'Where is the nearest supplier of improved maize seeds outside the' +
   ' village? [KM]'
   cm_e08    'During planting time, what is the price of improved maize seeds p' +
   'er KG at this p'
   cm_e09    'In the past 12 months, how many households have permanently migra' +
   'ted OUT of this'
   cm_e10    'In the past 12 months, how many households have permanently migra' +
   'ted INTO this v'
   cm_e11 'Are there any SACCOS in this village?'
   cm_e12 'How many members does the SACCOS have?'
   cm_e13 'Approximately how many female members does the SACCOS have?'
   cm_e14    'Would you say that the rains that this village had for the last V' +
   'ULI season were'
   cm_e15    'Would you say that the rains that this village had for the last V' +
   'ULI season came'
   cm_e16    'Would you say that the rains that this village had for the MASIKA' +
   ' season 2018 we'
   cm_e17    'Would you say that the rains that this village had for the MASIKA' +
   ' season 2018 ca'
   cm_e18    'Do any residents of this village migrate with their livestock for' +
   ' all or part of'
   cm_e19_b 'REGION'
   cm_e19_c 'DISTRICT'
   cm_e20__1    'JANUARY: During which months did the people travel outside the vi' +
   'llage with thei'
   cm_e20__2    'FEBRUARY: During which months did the people travel outside the v' +
   'illage with the'
   cm_e20__3    'MARCH: During which months did the people travel outside the vill' +
   'age with their '
   cm_e20__4    'APRIL: During which months did the people travel outside the vill' +
   'age with their '
   cm_e20__5    'MAY: During which months did the people travel outside the villag' +
   'e with their li'
   cm_e20__6    'JUNE: During which months did the people travel outside the villa' +
   'ge with their l'
   cm_e20__7    'JULY: During which months did the people travel outside the villa' +
   'ge with their l'
   cm_e20__8    'AUGUST: During which months did the people travel outside the vil' +
   'lage with their'
   cm_e20__9    'SEPTEMBER: During which months did the people travel outside the ' +
   'village with th'
   cm_e20__10    'OCTOBER: During which months did the people travel outside the vi' +
   'llage with thei'
   cm_e20__11    'NOVEMBER: During which months did the people travel outside the v' +
   'illage with the'
   cm_e20__12    'DECEMBER: During which months did the people travel outside the v' +
   'illage with the'
   cm_e21    'Compared to what has historically happened in this village, do pe' +
   'ople today migr' .

VALUE LABELS
 cm_e01
     1 'YES'
     2 'NO' /
 cm_e05
     1 'YES'
     2 'NO' /
 cm_e11
     1 'YES'
     2 'NO' /
 cm_e14
     1 'FAR TOO MUCH'
     2 'A BIT TOO MUCH'
     3 'NEITHER TOO MUCH NOR TOO LITTLE'
     4 'A BIT TOO LITTLE'
     5 'FAR TOO LITTLE'
     6 'HAKUNA KABISA' /
 cm_e15
     1 'FAR TOO EARLY'
     2 'A BIT TOO EARLY'
     3 'NEITHER TOO EARLY NOR TOO LATE'
     4 'A BIT TOO LATE'
     5 'FAR TOO LATE'
     6 'ZILICHELEWA MNO' /
 cm_e16
     1 'FAR TOO MUCH'
     2 'A BIT TOO MUCH'
     3 'NEITHER TOO MUCH NOR TOO LITTLE'
     4 'A BIT TOO LITTLE'
     5 'FAR TOO LITTLE'
     6 'HAKUNA KABISA' /
 cm_e17
     1 'MAPEMA MNO'
     2 'MAPEMA KIDOGO'
     3 'SIO MAPEMA SANA NA HAZIKUCHELEWA SANA'
     4 'ZIMECHELEWA KIASI'
     5 'ZILICHELEWA MNO' /
 cm_e18
     1 'YES'
     2 'NO' /
 cm_e19_b
     1 'DODOMA'
     2 'ARUSHA'
     3 'KILIMANJARO'
     4 'TANGA'
     5 'MOROGORO'
     6 'PWANI'
     7 'DAR ES SALAAM'
     8 'LINDI'
     9 'MTWARA'
     10 'RUVUMA'
     11 'IRINGA'
     12 'MBEYA'
     13 'SINGIDA'
     14 'TABORA'
     15 'RUKWA'
     16 'KIGOMA'
     17 'SHINYANGA'
     18 'KAGERA'
     19 'MWANZA'
     20 'MARA'
     21 'MANYARA'
     22 'NJOMBE'
     23 'KATAVI'
     24 'SIMIYU'
     25 'GEITA'
     51 'KASKAZINI UNGUJA'
     52 'KUSINI UNGUJA'
     53 'MJINI MAGHARIBI UNGUJA'
     54 'KASKAZINI PEMBA'
     55 'KUSINI PEMBA'
     99 'NJE YA TANZANIA' /
 cm_e19_c
     11 'KONDOA'
     12 'MPWAPWA'
     13 'KONGWA'
     14 'CHAMWINO'
     15 'DODOMA URBAN'
     16 'BAHI'
     17 'CHEMBA'
     21 'MONDULI'
     22 'MERU'
     23 'ARUSHA URBAN'
     24 'KARATU'
     25 'NGORONGORO'
     26 'ARUSHA RURAL'
     27 'LONGIDO'
     31 'ROMBO'
     32 'MWANGA'
     33 'SAME'
     34 'MOSHI RURAL'
     35 'HAI'
     36 'MOSHI URBAN'
     37 'SIHA'
     41 'LUSHOTO'
     42 'KOROGWE RURAL'
     43 'MUHEZA'
     44 'TANGA URBAN'
     45 'PANGANI'
     46 'HANDENI'
     47 'KILINDI'
     48 'MKINGA'
     49 'KOROGWE URBAN'
     51 'KILOSA'
     52 'MOROGORO RURAL'
     53 'KILOMBERO'
     54 'ULANGA'
     55 'MOROGORO URBAN'
     56 'MVOMERO'
     57 'GAIRO'
     61 'BAGAMOYO'
     62 'KIBAHA RURAL'
     63 'KISARAWE'
     64 'MKURANGA'
     65 'RUFIJI'
     66 'MAFIA'
     67 'KIBAHA URBAN'
     71 'KINONDONI'
     72 'ILALA'
     73 'TEMEKE'
     81 'KILWA'
     82 'LINDI RURAL'
     83 'NACHINGWEA'
     84 'LIWALE'
     85 'RUANGWA'
     86 'LINDI URBAN'
     91 'MTWARA RURAL'
     92 'NEWALA'
     93 'MASASI RURAL'
     94 'TANDAHIMBA'
     95 'MTWARA MIKINDANI'
     96 'NANYUMBU'
     97 'MASASI URBAN'
     101 'TUNDURU'
     102 'SONGEA RURAL'
     103 'MBINGA'
     104 'SONGEA URBAN'
     105 'NAMTUMBO'
     106 'NYASA'
     111 'IRINGA RURAL'
     112 'MUFINDI'
     113 'IRINGA URBAN'
     114 'KILOLO'
     115 'MAFINGA'
     121 'CHUNYA'
     122 'MBEYA RURAL'
     123 'KYELA'
     124 'RUNGWE'
     125 'ILEJE'
     126 'MBOZI'
     127 'MBALALI'
     128 'MBEYA URBAN'
     129 'MOMBA'
     131 'IRAMBA'
     132 'SINGIDA RURAL'
     133 'MANYONI'
     134 'SINGIDA URBAN'
     135 'IKUNGI'
     136 'MKALAMA'
     141 'NZEGA'
     142 'IGUNGA'
     143 'UYUI'
     144 'URAMBA'
     145 'SIKONGE'
     146 'TABORA URBAN'
     147 'KALIUA'
     151 'KALAMBO'
     152 'SUMBAWANGA RURAL'
     153 'NKASI'
     154 'SUMBAWANGA URBAN'
     162 'KIBONDO'
     163 'KASULU RURAL'
     164 'KIGOMA RURAL'
     165 'KIGOMA URBAN'
     166 'UVINZA'
     167 'BUHIGWE'
     168 'KAKONKO'
     169 'KASULU URBAN'
     171 'SHINYANGA RURAL'
     172 'KISHAPU'
     173 'SHINYANGA URBAN'
     174 'KAHAMA RURAL'
     175 'KAHAMA URBAN'
     181 'KARAGWE'
     182 'BUKOBA RURAL'
     183 'MULEBA'
     184 'BIHARAMULO'
     185 'NGARA'
     186 'BUKOBA URBAN'
     187 'MISSENYI'
     188 'KYERWA'
     191 'UKEREWE'
     192 'MAGU'
     193 'NYAMAGANA'
     194 'KWIMBA'
     195 'SENGEREMA'
     196 'ILEMELA'
     197 'MISUNGWI'
     201 'TARIME'
     202 'SERENGETI'
     203 'MUSOMA RURAL'
     204 'BUNDA'
     205 'MUSOMA URBAN'
     206 'RORYA'
     207 'BUTIAMA'
     211 'BABATI RURAL'
     212 'HANANG'
     213 'MBULU'
     214 'SIMANJIRO'
     215 'KITETO'
     216 'BABATI URBAN'
     221 'NJOMBE URBAN'
     222 "WANGING'OMBE"
     223 'MAKETE'
     224 'NJOMBE RURAL'
     225 'LUDEWA'
     226 'MAKAMBAKO'
     231 'MPANDA URBAN'
     232 'MPANDA RURAL'
     233 'MLELE'
     241 'BARIADI'
     242 'ITILIMA'
     243 'MEATU'
     244 'MASWA'
     245 'BUSEGA'
     251 'GEITA'
     252 "NYANG'HWALE"
     253 'MBOGWE'
     254 'BUKOMBE'
     255 'CHATO'
     410 'HANDENI URBAN'
     511 'KASKAZINI A'
     512 'KASKAZINI B'
     521 'KATI'
     522 'KUSINI'
     531 'MAGHARIBI'
     532 'MJINI'
     541 'WETE'
     542 'MICHWEWENI'
     551 'CHAKECHAKE'
     552 'MKOANI'
     1210 'TUNDUMA' /
 cm_e20__1 cm_e20__2 cm_e20__3 cm_e20__4 cm_e20__5 cm_e20__6 cm_e20__7 cm_e20__8 cm_e20__9 cm_e20__10 cm_e20__11 cm_e20__12
     0 'NO'
     1 'YES' /
 cm_e21
     1 'MORE FREQUENTLY'
     2 'LESS FREQUENTLY'
     3 'ABOUT THE SAME' / .


SAVE OUTFILE='.\cm_sec_e.sav'.
