/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\cm_sec_d.dat" ENCODING="CP1252" / LRECL=114 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   interview__id 12-43 (A)   cm_d01a1 44-50        
   cm_d01a2 51-53           cm_d01b1 54-58           cm_d01b2 59-60        
   cm_d01c1 61-68           cm_d01c2 69-70           cm_d01d1 71-76        
   cm_d01d2 77-78           cm_d01e1 79-82           cm_d01e2 83-84        
   cm_d01f1 85-90           cm_d01f2 91-93           cm_d01g1 94-98        
   cm_d01g2 99-100          cm_d01h1 101-105         cm_d01h2 106-107      
   cm_d02 108               cm_d03m 109-110          cm_d03y 111-114 .     


FORMATS
  cm_d01a1 (F8.1) /        cm_d01b1 (F6.1) /        cm_d01c1 (F9.1) /      
  cm_d01d1 (F7.1) /        cm_d01e1 (F5.1) /        cm_d01f1 (F7.1) /      
  cm_d01g1 (F6.3) /        cm_d01h1 (F6.1) / .
   
VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   interview__id 'Unique 32-character long identifier of the interview'
   cm_d01a1 'Cultivation by villages (ACRES)'
   cm_d01a2 'Cultivation by villages (%)'
   cm_d01b1 'Agro-business/plantation farming by outsiders (ACRES)'
   cm_d01b2 'Agro-business/plantation farming by outsiders (%)'
   cm_d01c1 'Forest (ACRES)'
   cm_d01c2 'Forest (%)'
   cm_d01d1 'Grazing land for livestock (ACRES)'
   cm_d01d2 'Grazing land for livestock (%)'
   cm_d01e1 'Wetland (ACRES)'
   cm_d01e2 'Wetland (%)'
   cm_d01f1 'Residential (ACRES)'
   cm_d01f2 'Residential (%)'
   cm_d01g1 'Business (ACRES)'
   cm_d01g2 'Business (%)'
   cm_d01h1 'Other (ACRES)'
   cm_d01h2 'Other (%)'
   cm_d02 'Does the village have a Certificate of Village Lands?'
   cm_d03m 'MONTH'
   cm_d03y 'YEAR' .

VALUE LABELS
 cm_d02
     1 'YES'
     2 'NO' /
 cm_d03m
     1 'JANUARY'
     2 'FEBRUARY'
     3 'MARCH'
     4 'APRIL'
     5 'MAY'
     6 'JUNE'
     7 'JULY'
     8 'AUGUST'
     9 'SEPTEMBER'
     10 'OCTOBER'
     11 'NOVEMBER'
     12 'DECEMBER'
     99 "DON'T KNOW" / .


SAVE OUTFILE='.\cm_sec_d.sav'.
