/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\cm_sec_d2.dat" ENCODING="CP1252" / LRECL=62 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   interview__id 12-43 (A)   event_id 44           
   cm_d04 45                cm_d05m 46-47            cm_d05y 48-51         
   cm_d06 52-54             cm_d07 55-62 .        

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   interview__id 'Unique 32-character long identifier of the interview'
   event_id 'Major Land-Related Event ID'
   cm_d04    'In the last 12 months, has any land been re-allocated for the fol' +
   'lowing reasons?'
   cm_d05m 'Month'
   cm_d05y 'Year'
   cm_d06 'How many households were affected?'
   cm_d07    'What was the value of compensation that each household received, ' +
   'if any? (TSH)' .

VALUE LABELS
 event_id
     1 'APPROPRIATION OF LAND FOR OUTSIDE INVESTORS'
     2 "DISTRICT OR CENTRAL GOVERNMENT DECLARING LAND IN THE VILLAGE AS 'RESERVE LAND'"
     3 'ALLOCATION OF LAND CULTIVATED OR INHABITED BY VILLAGES FOR PUBLIC USE (INCL. PASTURE OR SERVICES)' /
 cm_d04
     0 'NO'
     1 'YES' /
 cm_d05m
     1 'JANUARY'
     2 'FEBRUARY'
     3 'MARCH'
     4 'APRIL'
     5 'MAY'
     6 'JUNE'
     7 'JULY'
     8 'AUGUST'
     9 'SEPTEMBER'
     10 'OCTOBER'
     11 'NOVEMBER'
     12 'DECEMBER'
     99 "DON'T KNOW" / .


SAVE OUTFILE='.\cm_sec_d2.sav'.
