/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\consumption_real_y5.dat" ENCODING="CP1252" / LRECL=488 .

DATA LIST FILE=DATA/
   y5_hhid 1-11 (A)         booster 12               cluster 13-24         
   strata 25                hhweight2 26-41          urban 42              
   area 43                  region 44-45             district 46-48        
   month 49-50              quarter 51               mainland 52           
   femalehead 53            hhsize 54-55             adulteq 56-72         
   intyear 73-76            intmonth 77-78           hhweight_pan 79-94    
   hhweight 95-110          nf_clothing 111-117      nf_utilities 118-125  
   nf_hhexpenses 126-133    nf_transport 134-142     nf_communic 143-150   
   nf_recreat 151-156       nf_other 157-163         dur_exp 164-179       
   rent_exp 180-194         foodIN 195-207           foodOUT 208-215       
   educa 216-223            health 224-232           expm 233-246          
   fisherb4c4 247-263       foodINR_pae 264-279      foodOUTR_pae 280-295  
   educaR_pae 296-311       healthR_pae 312-327      nf_clothingR_pae 328-343
   nf_utilitiesR_pae 344-359   nf_hhexpensesR_pae 360-375
   nf_transportR_pae 376-391   nf_communicR_pae 392-408
   nf_recreatR_pae 409-424   nf_otherR_pae 425-440    dur_expR_pae 441-456  
   rent_expR_pae 457-472    expmR_pae 473-488 .   


FORMATS
  hhweight2 (F17.13) /     adulteq (F18.15) /       hhweight_pan (F17.13) /
  hhweight (F17.13) /      dur_exp (F17.12) /       rent_exp (F16.9) /     
  foodIN (F14.7) /         expm (F15.8) /           fisherb4c4 (F18.15) /  
  foodINR_pae (F17.12) /   foodOUTR_pae (F17.13) /  educaR_pae (F17.13) /  
  healthR_pae (F17.13) /   nf_clothingR_pae (F17.13) /
  nf_utilitiesR_pae (F17.14) /  nf_hhexpensesR_pae (F17.13) /
  nf_transportR_pae (F17.13) /  nf_communicR_pae (F18.15) /
  nf_recreatR_pae (F17.14) /  nf_otherR_pae (F17.13) /  dur_expR_pae (F17.14) /
  rent_expR_pae (F17.12) /  expmR_pae (F17.11) / .

VARIABLE LABELS
   y5_hhid 'Unique Household Identification NPSY5'
   booster 'Household sample type'
   cluster 'Cluster'
   strata 'Strata'
   hhweight2 'Sampling weights, y5_crossweight'
   urban 'NPSY5 Rural-Urban'
   area 'Area'
   region 'Region Code'
   district 'District Code'
   month 'Month'
   quarter 'Quarter of fieldwork'
   mainland 'Mainland or Zanzibar'
   femalehead 'Female headed household'
   hhsize 'Household size'
   adulteq 'Adult-equivalents in the household'
   intyear 'Year of interview'
   intmonth 'Month of interview'
   hhweight_pan 'Sampling weights, y5_panelweight'
   hhweight 'Sampling weights, y5_crossweight'
   nf_clothing 'Clothing and footwear, annual, nominal, hh'
   nf_utilities 'Utilities: water, kerosene, lighting, annual, nominal, hh'
   nf_hhexpenses 'Furnishings and household expenses, annual, nominal, hh'
   nf_transport 'Transportation, annual, nominal, hh'
   nf_communic 'Communications, annual, nominal, hh'
   nf_recreat 'Recreation, annual, nominal, hh'
   nf_other 'Other consumption, annual, nominal, hh'
   dur_exp 'Durables expenditures (user cost), annual, nominal, hh'
   rent_exp 'Housing/rent (imputed), annual, nominal, hh'
   foodIN 'Food, beverages, alcohol: at home, annual, nominal, hh'
   foodOUT    'Food, beverages, alcohol and tobacco: outside of home, annual, no' +
   'minal, hh'
   educa 'Education, annual, nominal, hh'
   health 'Health, annual, nominal, hh'
   expm 'Total consumption, annual, nominal, hh'
   fisherb4c4 'Fisher,    base NPS5, comparison NPS5 by area and quarter'
   foodINR_pae    'Food, beverages, alcohol: at home, real, per 28 days, per adult e' +
   'quivalent '
   foodOUTR_pae    'Food, beverages, alcohol and tobacco: outside of home, real, per ' +
   '28 days, per ad'
   educaR_pae 'Education, real, per 28 days, per adult equivalent '
   healthR_pae 'Health, real, per 28 days, per adult equivalent '
   nf_clothingR_pae 'Clothing and footwear, real, per 28 days, per adult equivalent '
   nf_utilitiesR_pae    'Utilities: water, kerosene, lighting, real, per 28 days, per adul' +
   't equivalent '
   nf_hhexpensesR_pae    'Furnishings and household expenses, real, per 28 days, per adult ' +
   'equivalent '
   nf_transportR_pae 'Transportation, real, per 28 days, per adult equivalent '
   nf_communicR_pae 'Communications, real, per 28 days, per adult equivalent '
   nf_recreatR_pae 'Recreation, real, per 28 days, per adult equivalent '
   nf_otherR_pae 'Other consumption, real, per 28 days, per adult equivalent '
   dur_expR_pae    'Durables expenditures (user cost), real, per 28 days, per adult e' +
   'quivalent '
   rent_expR_pae 'Housing/rent (imputed), real, per 28 days, per adult equivalent '
   expmR_pae 'Total consumption, real, per 28 days, per adult equivalent ' .

VALUE LABELS
 booster
     0 'Panel household'
     1 'New (booster) sample' /
 strata
     1 'Dar es Salaam'
     2 'Rest of urban'
     3 'Rural'
     4 'Zanzibar' /
 urban
     1 'RURAL'
     2 'URBAN' /
 area
     1 'Dar es Salaam'
     2 'Rest of urban'
     3 'Rural'
     4 'Zanzibar' /
 region
     1 'DODOMA'
     2 'ARUSHA'
     3 'KILIMANJARO'
     4 'TANGA'
     5 'MOROGORO'
     6 'PWANI'
     7 'DAR ES SALAAM'
     8 'LINDI'
     9 'MTWARA'
     10 'RUVUMA'
     11 'IRINGA'
     12 'MBEYA'
     13 'SINGIDA'
     14 'TABORA'
     15 'RUKWA'
     16 'KIGOMA'
     17 'SHINYANGA'
     18 'KAGERA'
     19 'MWANZA'
     20 'MARA'
     21 'MANYARA'
     22 'NJOMBE'
     23 'KATAVI'
     24 'SIMIYU'
     25 'GEITA'
     26 'SONGWE'
     51 'KASKAZINI UNGUJA'
     52 'KUSINI UNGUJA'
     53 'MJINI MAGHARIBI UNGUJA'
     54 'KASKAZINI PEMBA'
     55 'KUSINI PEMBA' /
 district
     11 'KONDOA'
     12 'MPWAPWA'
     13 'KONGWA'
     14 'CHAMWINO'
     15 'DODOMA URBAN'
     16 'BAHI'
     17 'CHEMBA'
     18 'KONGWA TOWNSHIP'
     19 'KONDOA URBAN'
     21 'MONDULI'
     22 'MERU'
     23 'ARUSHA URBAN'
     24 'KARATU'
     25 'NGORONGORO'
     26 'ARUSHA RURAL'
     27 'LONGIDO'
     31 'ROMBO'
     32 'MWANGA'
     33 'SAME'
     34 'MOSHI RURAL'
     35 'HAI'
     36 'MOSHI URBAN'
     37 'SIHA'
     41 'LUSHOTO'
     42 'KOROGWE RURAL'
     43 'MUHEZA'
     44 'TANGA URBAN'
     45 'PANGANI'
     46 'HANDENI'
     47 'KILINDI'
     48 'MKINGA'
     49 'KOROGWE URBAN'
     51 'KILOSA'
     52 'MOROGORO RURAL'
     53 'KILOMBERO'
     54 'ULANGA'
     55 'MOROGORO URBAN'
     56 'MVOMERO'
     57 'GAIRO'
     58 'MALINYI'
     59 'IFAKARA URBAN'
     61 'BAGAMOYO'
     62 'KIBAHA RURAL'
     63 'KISARAWE'
     64 'MKURANGA'
     65 'RUFIJI'
     66 'MAFIA'
     67 'KIBAHA URBAN'
     68 'CHALINZE'
     69 'KIBITI'
     71 'KINONDONI'
     72 'ILALA'
     73 'TEMEKE'
     74 'UBUNGO'
     75 'KIGAMBONI'
     81 'KILWA'
     82 'LINDI RURAL'
     83 'NACHINGWEA'
     84 'LIWALE'
     85 'RUANGWA'
     86 'LINDI URBAN'
     87 'KILWA KIVINJE TOWNSHIP'
     91 'MTWARA RURAL'
     92 'NEWALA'
     93 'MASASI RURAL'
     94 'TANDAHIMBA'
     95 'MTWARA MIKINDANI'
     96 'NANYUMBU'
     97 'MASASI URBAN'
     98 'NEWALA TOWN'
     99 'NANYAMBA TOWN'
     101 'TUNDURU'
     102 'SONGEA RURAL'
     103 'MBINGA'
     104 'SONGEA URBAN'
     105 'NAMTUMBO'
     106 'NYASA'
     107 'MBINGA TOWN'
     108 'MADABA'
     111 'IRINGA RURAL'
     112 'MUFINDI'
     113 'IRINGA URBAN'
     114 'KILOLO'
     115 'MAFINGA TOWN'
     121 'CHUNYA'
     122 'MBEYA RURAL'
     123 'KYELA'
     124 'RUNGWE'
     127 'MBALALI'
     128 'MBEYA URBAN'
     129 'BUSOKELO'
     131 'IRAMBA'
     132 'SINGIDA RURAL'
     133 'MANYONI'
     134 'SINGIDA URBAN'
     135 'IKUNGI'
     136 'MKALAMA'
     137 'ITIGI'
     141 'NZEGA'
     142 'IGUNGA'
     143 'UYUI'
     144 'URAMBO'
     145 'SIKONGE'
     146 'TABORA URBAN'
     147 'KALIUA'
     148 'NZEGA TOWN'
     151 'KALAMBO'
     152 'SUMBAWANGA RURAL'
     153 'NKASI'
     154 'SUMBAWANGA URBAN'
     161 'KIBONDO'
     162 'KASULU RURAL'
     163 'KIGOMA RURAL'
     164 'KIGOMA UJIJI URBAN'
     165 'UVINZA'
     166 'BUHIGWE'
     167 'KAKONKO'
     168 'KASULU TOWN'
     171 'SHINYANGA URBAN'
     172 'KISHAPU'
     173 'SHINYANGA RURAL'
     174 'KAHAMA RURAL'
     175 'KAHAMA TOWN'
     176 'USHETU'
     177 'MSALALA'
     181 'KARAGWE'
     182 'BUKOBA RURAL'
     183 'MULEBA'
     184 'BIHARAMULO'
     185 'NGARA'
     186 'BUKOBA URBAN'
     187 'MISSENYI'
     188 'KYERWA'
     191 'UKEREWE'
     192 'MAGU'
     193 'MWANZA URBAN'
     194 'KWIMBA'
     195 'SENGEREMA'
     196 'ILEMELA'
     197 'MISUNGWI'
     198 'BUCHOSA'
     201 'TARIME'
     202 'SERENGETI'
     203 'MUSOMA RURAL'
     204 'BUNDA'
     205 'MUSOMA URBAN'
     206 'RORYA'
     207 'BUTIAMA'
     208 'TARIME TOWN'
     209 'BUNDA TOWN'
     211 'BABATI RURAL'
     212 'HANANG'
     213 'MBULU'
     214 'SIMANJIRO'
     215 'KITETO'
     216 'BABATI TOWN'
     217 'MBULU TOWN'
     221 'NJOMBE TOWN'
     222 "WANGING'OMBE"
     223 'MAKETE'
     224 'NJOMBE RURAL'
     225 'LUDEWA'
     226 'MAKAMBAKO TOWN'
     231 'MPANDA URBAN'
     232 'MPANDA RURAL'
     233 'MLELE'
     234 'MPIMBWE'
     235 'NSIMBO'
     241 'BARIADI'
     242 'ITILIMA'
     243 'MEATU'
     244 'MASWA'
     245 'BUSEGA'
     246 'BARIADI TOWN'
     251 'GEITA'
     252 "NYANG'HWALE"
     253 'MBOGWE'
     254 'BUKOMBE'
     255 'CHATO'
     256 'GEITA TOWN'
     261 'SONGWE'
     262 'MBOZI'
     263 'ILEJE'
     264 'TUNDUMA'
     265 'MOMBA'
     410 'HANDENI URBAN'
     411 'BUMBULI'
     511 'KASKAZINI �A�'
     512 'KASKAZINI �B�'
     521 'KATI'
     522 'KUSINI'
     531 'MAGHARIBI'
     532 'MJINI'
     541 'WETE'
     542 'MICHEWENI'
     551 'CHAKECHAKE'
     552 'MKOANI' /
 month
     1 'January 2021'
     2 'February'
     3 'March'
     4 'April'
     5 'May'
     6 'June'
     7 'July'
     8 'August'
     9 'September'
     10 'October'
     11 'November'
     12 'December 2021' /
 quarter
     1 'Jan-Mar 2021'
     2 'Apr-May 2021'
     3 'Jul-Sep 2021'
     4 'Oct-Dec 2021' /
 mainland
     1 'Mainland'
     2 'Zanzibar' / .


SAVE OUTFILE='.\consumption_real_y5.sav'.
