/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\consumption_real_y4.dat" ENCODING="CP1252" / LRECL=458 .

DATA LIST FILE=DATA/
   y4_hhid 1-8 (A)          cluster 9-20             strata 21             
   hhweight 22-37           region 38-39             district 40           
   ward 41-43               village 44-45            ea 46-48              
   month 49-50              quarter 51               urban 52              
   area 53                  mainland 54              femalehead 55         
   hhsize 56-57             adulteq 58-74            intyear 75-78         
   intmonth 79-80           nf_clothing 81-87        nf_utilities 88-95    
   nf_hhexpenses 96-103     nf_transport 104-112     nf_communic 113-119   
   nf_recreat 120-127       nf_other 128-135         dur_exp 136-151       
   rent_exp 152-166         foodIN 167-179           foodOUT 180-187       
   educa 188-196            health 197-205           expm 206-217          
   fisherb4c4 218-234       foodINR_pae 235-250      foodOUTR_pae 251-266  
   educaR_pae 267-282       healthR_pae 283-298      nf_clothingR_pae 299-314
   nf_utilitiesR_pae 315-330   nf_hhexpensesR_pae 331-346
   nf_transportR_pae 347-362   nf_communicR_pae 363-378
   nf_recreatR_pae 379-394   nf_otherR_pae 395-410    dur_expR_pae 411-426  
   rent_expR_pae 427-442    expmR_pae 443-458 .   


FORMATS
  hhweight (F17.12) /      adulteq (F18.15) /       dur_exp (F17.13) /     
  rent_exp (F16.9) /       foodIN (F14.7) /         expm (F13.5) /         
  fisherb4c4 (F18.15) /    foodINR_pae (F17.13) /   foodOUTR_pae (F17.13) /
  educaR_pae (F17.13) /    healthR_pae (F17.13) /   nf_clothingR_pae (F17.14) /
  nf_utilitiesR_pae (F17.13) /  nf_hhexpensesR_pae (F17.13) /
  nf_transportR_pae (F17.13) /  nf_communicR_pae (F17.13) /
  nf_recreatR_pae (F17.14) /  nf_otherR_pae (F17.13) /  dur_expR_pae (F17.14) /
  rent_expR_pae (F17.12) /  expmR_pae (F17.10) / .

VARIABLE LABELS
   y4_hhid 'Unique Household Identification NPS Y4'
   cluster 'Cluster'
   strata 'Strata'
   hhweight 'Sampling weights, y4_weight'
   region 'Region Code'
   district 'District Code'
   ward 'Ward Code'
   village 'Village Code'
   ea 'Village / Enumeration Area Code'
   month 'Month'
   quarter 'Quarter of fieldwork'
   urban 'Urban or Rural areas'
   area 'Area'
   mainland 'Mainland or Zanzibar'
   femalehead 'Female headed household'
   hhsize 'Household size'
   adulteq 'Adult-equivalents in the household'
   intyear 'Year of interview'
   intmonth 'Month of interview'
   nf_clothing 'Clothing and footwear, annual, nominal, hh'
   nf_utilities 'Utilities: water, kerosene, lighting, annual, nominal, hh'
   nf_hhexpenses 'Furnishings and household expenses, annual, nominal, hh'
   nf_transport 'Transportation, annual, nominal, hh'
   nf_communic 'Communications, annual, nominal, hh'
   nf_recreat 'Recreation, annual, nominal, hh'
   nf_other 'Other consumption, annual, nominal, hh'
   dur_exp 'Durables expenditures (user cost), annual, nominal, hh'
   rent_exp 'Housing/rent (imputed), annual, nominal, hh'
   foodIN 'Food, beverages, alcohol: at home, annual, nominal, hh'
   foodOUT    'Food, beverages, alcohol and tobacco: outside of home, annual, no' +
   'minal, hh'
   educa 'Education, annual, nominal, hh'
   health 'Health, annual, nominal, hh'
   expm 'Total consumption, annual, nominal, hh'
   fisherb4c4 'Fisher,    base NPS4, comparison NPS4 by area and quarter'
   foodINR_pae    'Food, beverages, alcohol: at home, real, per 28 days, per adult e' +
   'quivalent '
   foodOUTR_pae    'Food, beverages, alcohol and tobacco: outside of home, real, per ' +
   '28 days, per ad'
   educaR_pae 'Education, real, per 28 days, per adult equivalent '
   healthR_pae 'Health, real, per 28 days, per adult equivalent '
   nf_clothingR_pae 'Clothing and footwear, real, per 28 days, per adult equivalent '
   nf_utilitiesR_pae    'Utilities: water, kerosene, lighting, real, per 28 days, per adul' +
   't equivalent '
   nf_hhexpensesR_pae    'Furnishings and household expenses, real, per 28 days, per adult ' +
   'equivalent '
   nf_transportR_pae 'Transportation, real, per 28 days, per adult equivalent '
   nf_communicR_pae 'Communications, real, per 28 days, per adult equivalent '
   nf_recreatR_pae 'Recreation, real, per 28 days, per adult equivalent '
   nf_otherR_pae 'Other consumption, real, per 28 days, per adult equivalent '
   dur_expR_pae    'Durables expenditures (user cost), real, per 28 days, per adult e' +
   'quivalent '
   rent_expR_pae 'Housing/rent (imputed), real, per 28 days, per adult equivalent '
   expmR_pae 'Total consumption, real, per 28 days, per adult equivalent ' .

VALUE LABELS
 region
     1 'DODOMA'
     2 'ARUSHA'
     3 'KILIMANJARO'
     4 'TANGA'
     5 'MOROGORO'
     6 'PWANI'
     7 'DAR ES SALAAM'
     8 'LINDI'
     9 'MTWARA'
     10 'RUVUMA'
     11 'IRINGA'
     12 'MBEYA'
     13 'SINGIDA'
     14 'TABORA'
     15 'RUKWA'
     16 'KIGOMA'
     17 'SHINYANGA'
     18 'KAGERA'
     19 'MWANZA'
     20 'MARA'
     21 'MANYARA'
     22 'NJOMBE'
     23 'KATAVI'
     24 'SIMIYU'
     25 'GEITA'
     51 'KASKAZINI UNGUJA'
     52 'KUSINI UNGUJA'
     53 'MJINI/MAGHARIBI UNGUJA'
     54 'KASKAZINI PEMBA'
     55 'KUSINI PEMBA' /
 month
     1 'October 2014'
     2 'November'
     3 'December'
     4 'January'
     5 'February'
     6 'March'
     7 'April'
     8 'May'
     9 'June'
     10 'July'
     11 'August'
     12 'September 2015' /
 quarter
     1 'Oct-Dec 2014'
     2 'Jan-Mar 2015'
     3 'Apr-Jun 2015'
     4 'Jul-Sep 2015' /
 urban
     1 'Rural'
     2 'Urban' /
 area
     1 'Dar es Salaam'
     2 'Rest of urban'
     3 'Rural'
     4 'Zanzibar' /
 mainland
     1 'Mainland'
     2 'Zanzibar' / .


SAVE OUTFILE='.\consumption_real_y4.sav'.
