/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_i.dat" ENCODING="CP1252" / LRECL=127 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        hh_i01 23             
   hh_i02 24-25             hh_i03 26-31             hh_i04 32-38          
   hh_i05 39-46             hh_i06 47-54             hh_i07_1 55-56        
   hh_i07_2 57-58           hh_i08 59                hh_i09 60             
   hh_i10 61                hh_i11 62-63             hh_i11a 64-69         
   hh_i12 70                hh_i12a 71               hh_i12b 72            
   hh_i12c 73               hh_i12d 74               hh_i13 75             
   hh_i14 76-77             hh_i15 78-79             hh_i16 80             
   hh_i16_1 81              hh_i17 82-83             hh_i18 84             
   hh_i19 85-86             hh_i20 87                hh_i21 88-89          
   hh_i22 90-92             hh_i23 93-95             hh_i24_1 96           
   hh_i24_2 97              hh_i25 98-99             hh_i26 100-105        
   hh_i27 106               hh_i28 107               hh_i29 108-109        
   hh_i30 110               hh_i31 111-112           hh_i32 113-115        
   hh_i33 116-118           hh_i34_1 119             hh_i34_2 120          
   hh_i35 121-122           hh_i36 123-127 .      

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   hh_i01 'What is the HH tenure status of main residence?'
   hh_i02 'Do you have any documentation of ownership of the dwelling?'
   hh_i03    'How much does this household pay per month to rent this dwelling?' +
   ' TSH'
   hh_i04    'Estimate the rent you could receive if you rented this dwelling? ' +
   'TSH'
   hh_i05    'In the past year, how much have you paid on repairs to your dwell' +
   'ing? TSH'
   hh_i06    'In the past year, how much have you paid on improvements to your ' +
   'home (excluding'
   hh_i07_1    'How many habitable rooms in each unit does this household occupy?' +
   ' MAIN DWELLING'
   hh_i07_2    'How many habitable rooms in each unit does this household occupy?' +
   ' OTHER DWELLING'
   hh_i08    'The walls of the main dwelling are predominantly made of what mat' +
   'erials?'
   hh_i09    'The roof of the main dwelling is predominantly made of what mater' +
   'ials?'
   hh_i10    'The floor of the main dwelling is predominantly made of what mate' +
   'rials?'
   hh_i11 'How does the household dispose of its garbage?'
   hh_i11a    'Typically, how much money do households spend per month to pay fo' +
   'r waste disposa'
   hh_i12    'What kind of toilet facility do members of your household general' +
   'ly use?'
   hh_i12a 'Where does this toilet flush to?'
   hh_i12b 'Has your [TOILET FACILITY] ever been emptied?'
   hh_i12c    'The last time it was emptied, where were its contents emptied to?'
   hh_i12d 'Where is this toilet facility located?'
   hh_i13 'Do you share this toilet facility with other households?'
   hh_i14 'How many other households use this toilet facility?'
   hh_i15    'The last time the youngest child in the household passed stools, ' +
   'what was done t'
   hh_i16 'Major fuel used for cooking?'
   hh_i16_1 'What type of stove does this household mainly use for cooking?'
   hh_i17 'Major fuel used for lighting?'
   hh_i18 "What is the household's main source of electricity?"
   hh_i19    "What is the household's main source of drinking water in the rain" +
   'y season?'
   hh_i20 'Where is that water source located?'
   hh_i21    'Who usually fetches water for your household in the rainy season?'
   hh_i22    'How long does it take [NAME] to get water from the main source of' +
   ' drinking water'
   hh_i23 'Out of these minutes, how long does [NAME] spend waiting?'
   hh_i24_1    'What do you usually do to the water to make it safer to drink in ' +
   'the rainy seaso'
   hh_i24_2    'What do you usually do to the water to make it safer to drink in ' +
   'the rainy seaso'
   hh_i25    'What is the main source of water used by your household for other' +
   ' purposes, such'
   hh_i26    'How much on average does your household spend on all water used i' +
   'n the household'
   hh_i27    'During the dry season, is the main source of drinking water for m' +
   'embers of your '
   hh_i28    'What is the main reason your change sources of drinking water in ' +
   'the dry season?'
   hh_i29    "What is the household's main source of drinking water in the dry " +
   'season?'
   hh_i30 'Where is that water source located?'
   hh_i31 'Who usually fetches water for your household in the dry season?'
   hh_i32    'How long does it take [NAME] to get water from the main source of' +
   ' drinking water'
   hh_i33 'Out of these minutes, how long does [NAME] spend waiting?'
   hh_i34_1    'What do you usually do to the water to make it safer to drink in ' +
   'the dry season?'
   hh_i34_2    'What do you usually do to the water to make it safer to drink in ' +
   'the dry season?'
   hh_i35    'What is the main source of water used by your household for other' +
   ' purposes, such'
   hh_i36    'How much on average does your household spend on all water used i' +
   'n the household' .

VALUE LABELS
 hh_i01
     1 'OWNER OCCUPIED'
     2 'EMPLOYER PROVIDED - SUBSIDIZED'
     3 'EMPLOYER PROVIDED - FREE'
     4 'RENTED'
     5 'FREE'
     6 'NOMADS' /
 hh_i02
     1 'OFFER OF THE RIGHT OF OCCUPANCY'
     2 'TITLE DEED FOR LAND'
     3 "LETTER OR ALLOCATION FROM VILLAGE GOV'T"
     4 'SETTLEMENT/RESIDENTIAL PERMIT'
     5 'TRADITIONAL RIGHT OF OCCUPANCY'
     6 'LAND SALE AGREEMENT'
     7 'INHERITANCE LETTER'
     8 'OTHER TITLE (SPECIFY)'
     10 'NO DOCUMENTATION AT ALL'
     11 'RESIDENTIAL LICENSES'
     12 'CERTIFICATE OF CUSTOMARY RIGHT OF OCCUPANCY' /
 hh_i08
     1 'POLES (INCLUDING BAMBOO), BRANCHES, GRASS'
     2 'POLES AND MUD/MUD AND STONES'
     3 'MUD ONLY'
     4 'MUD BRICKS'
     5 'BAKED/BURNT BRICKS'
     6 'CONCRETE SLAB, SAND/CEMENT BLOCKS, STONES'
     7 'OTHER, SPECIFY' /
 hh_i09
     1 'GRASS, LEAVES,  BAMBOO, THATCH'
     2 'MUD AND GRASS'
     3 'CONCRETE SLAB (FLAT ROOF)'
     4 'IRON SHEET'
     5 'ASBESTOS SHEETS'
     6 'TILES'
     7 'OTHER, SPECIFY' /
 hh_i10
     1 'EARTH'
     2 'CONCRETE SLAB'
     3 'SAND/CEMENT'
     4 'TILES'
     5 'TIMBER'
     6 'OTHER, SPECIFY' /
 hh_i11
     1 'COLLECTED BY GOV / MUNICIPALITY'
     2 'COLLECTED BY PRIVATE COMPANY'
     3 'TAKEN TO GOV / MUNICIPAL BIN / FACILITY'
     4 'BURIED IN COMPOUND'
     5 'BURNT IN COMPOND'
     6 'HEAPED IN COMPOUND'
     7 'BURIED ELSEWHERE'
     8 'BURNT ELSEWHERE'
     9 'HEAPED ELSEWHERE'
     10 'INFORMAL PUBLIC COLLECTORS'
     11 'OTHER, SPECIFY' /
 hh_i12
     1 'NO TOILET'
     2 'PIT LATRINE WITHOUT SLAB/OPEN PIT'
     3 'PIT LATRINE WITH SLAB (NOT WASHABLE)'
     4 'PIT LATRINE WITH SLAB (WASHABLE)'
     5 'VIP'
     6 'POUR FLUSH'
     7 'FLUSH TOILET'
     8 'ECOSAN'
     9 'OTHER, SPECIFY' /
 hh_i12a
     1 'PIPED SEWER SYSTEM'
     2 'SEPTIC TANK'
     3 'PIT LATRINE'
     4 'FLUSH TO OPEN DRAIN'
     5 "DON'T KNOW" /
 hh_i12b
     1 'YES, EMPTIED: WITHIN THE LAST 5 YEARS'
     2 'YES, EMPTIED: MORE THAN 5 YEARS AGO'
     3 "YES, EMPTIED BUT DON'T KNOW WHEN"
     4 'NO, NEVER EMPTIED'
     5 "DON'T KNOW" /
 hh_i12c
     1 'REMOVED BY SERVICE PROVIDER - TO A TREATMENT PLANT'
     2 'REMOVED BY SERVICE PROVIDER - BURIED IN COVERED PIT'
     3 "REMOVED BY SERVICE PROVIDER - DON'T KNOW WHERE"
     4 'EMPTIED BY HOUSEHOLD - BURIED IN COVERED PIT'
     5 'EMPTIED BY HOUSEHOLD - TO UNCOVERED PIT, OPEN GROUND, WATER BODY, ELSEWHERE, OTHER'
     6 'OTHER, SPECIFY'
     7 "DON'T KNOW" /
 hh_i12d
     1 'WITHIN OWN DWELLING'
     2 'WITHIN OWN YARD/PLOT'
     3 'ELSEWHERE' /
 hh_i13
     1 'YES'
     2 'NO' /
 hh_i15
     1 'CHILD USED TOILET OR LATRINE'
     2 'PUT/RINSED INTO TOILET OR LATRINE'
     3 'PUT/RINSED INTO DRAIN/DITCH'
     4 'THROWN INTO GARBAGE'
     5 'BURIED'
     6 'LEFT IN OPEN'
     7 'OTHER, SPECIFY'
     8 'NO CHILDREN'
     9 'WASHABLE DIAPERS'
     10 'DISPOSABLE DIAPERS (LIKE PAMPERS)' /
 hh_i16
     1 'FIREWOOD'
     2 'PARAFFIN'
     3 'ELECTRICITY'
     4 'GAS'
     5 'CHARCOAL'
     6 'ANIMAL RESIDUAL'
     7 'GAS (BIOGAS)'
     8 'OTHER, SPECIFY' /
 hh_i16_1
     1 'STONE / OPEN FIRE STOVE'
     2 'OTHER SELF-BUILT STOVE'
     3 'MANUFACTURED STOVE'
     4 'OTHER, SPECIFY' /
 hh_i17
     1 'ELECTRICITY'
     2 'SOLAR'
     3 'GAS'
     4 'GAS (BIOGAS)'
     5 'LAMP OIL'
     6 'CANDLE'
     7 'FIREWOOD'
     8 'PRIVATE GENERATOR'
     9 'TORCH'
     10 'OTHER, SPECIFY' /
 hh_i18
     1 'TANESCO'
     2 'COMMUNITY GENERATOR'
     3 'SOLAR PANELS'
     4 'OWN GENERATOR'
     5 'CAR BATTERY'
     6 'MOTORCYCLE'
     7 'BATTERY' /
 hh_i19
     1 'PIPED WATER'
     2 'TUBEWELL/BOREHOLE'
     3 'PROTECTED DUG WELL'
     4 'UNPROTECTED DUGWELL'
     5 'PROTECTED SPRING'
     6 'UNPROTECTED SPRING'
     7 'RAINWATER COLLECTION'
     8 'BOTTLED WATER'
     9 'CART WITH SMALL TANK/DRUM'
     10 'TANKER-TRUCK'
     11 'SURFACE WATER (RIVER, DAM, LAKE, POND, STREAM, CANAL, IRRIGATION CHANNELS)'
     12 'OTHER, SPECIFY' /
 hh_i20
     1 'IN OWN DWELLING'
     2 'IN OWN YARD/PLOT'
     3 "IN NEIGHBOR'S COMPOUND"
     4 'ELSEWHERE' /
 hh_i24_1
     1 'NONE'
     2 'BOIL'
     3 'ADD BLEACH/CHLORINE'
     4 'USE A WATER FILTER'
     5 'SOLAR DISINFECTION'
     6 'LET IT STAND AND SETTLE'
     7 'OTHER (SPECIFY)' /
 hh_i24_2
     1 'NONE'
     2 'BOIL'
     3 'ADD BLEACH/CHLORINE'
     4 'USE A WATER FILTER'
     5 'SOLAR DISINFECTION'
     6 'LET IT STAND AND SETTLE'
     7 'OTHER (SPECIFY)' /
 hh_i25
     1 'PIPED WATER'
     2 'TUBEWELL/BOREHOLE'
     3 'PROTECTED DUG WELL'
     4 'UNPROTECTED DUGWELL'
     5 'PROTECTED SPRING'
     6 'UNPROTECTED SPRING'
     7 'RAINWATER COLLECTION'
     8 'BOTTLED WATER'
     9 'CART WITH SMALL TANK/DRUM'
     10 'TANKER-TRUCK'
     11 'SURFACE WATER (RIVER, DAM, LAKE, POND, STREAM, CANAL, IRRIGATION CHANNELS)'
     12 'OTHER, SPECIFY' /
 hh_i27
     1 'YES'
     2 'NO' /
 hh_i28
     1 'COST'
     2 'AVAILABILITY'
     3 'CONVENIENCE'
     4 'SAFETY IN COLLECTING THE WATER'
     5 'SAFETY OF CONSUMING THE WATER'
     6 'OTHER, SPECIFY' /
 hh_i29
     1 'PIPED WATER'
     2 'TUBEWELL/BOREHOLE'
     3 'PROTECTED DUG WELL'
     4 'UNPROTECTED DUGWELL'
     5 'PROTECTED SPRING'
     6 'UNPROTECTED SPRING'
     7 'RAINWATER COLLECTION'
     8 'BOTTLED WATER'
     9 'CART WITH SMALL TANK/DRUM'
     10 'TANKER-TRUCK'
     11 'SURFACE WATER (RIVER, DAM, LAKE, POND, STREAM, CANAL, IRRIGATION CHANNELS)'
     12 'OTHER,SPECIFY' /
 hh_i30
     1 'IN OWN DWELLING'
     2 'IN OWN YARD/PLOT'
     3 "IN NEIGHBOR'S COMPOUND"
     4 'ELSEWHERE' /
 hh_i34_1
     1 'NONE'
     2 'BOIL'
     3 'ADD BLEACH/CHLORINE'
     4 'USE A WATER FILTER'
     5 'SOLAR DISINFECTION'
     6 'LET IT STAND AND SETTLE'
     7 'OTHER (SPECIFY)' /
 hh_i34_2
     1 'NONE'
     2 'BOIL'
     3 'ADD BLEACH/CHLORINE'
     4 'USE A WATER FILTER'
     5 'SOLAR DISINFECTION'
     6 'LET IT STAND AND SETTLE'
     7 'OTHER (SPECIFY)' /
 hh_i35
     1 'PIPED WATER'
     2 'TUBEWELL/BOREHOLE'
     3 'PROTECTED DUG WELL'
     4 'UNPROTECTED DUGWELL'
     5 'PROTECTED SPRING'
     6 'UNPROTECTED SPRING'
     7 'RAINWATER COLLECTION'
     8 'BOTTLED WATER'
     9 'CART WITH SMALL TANK/DRUM'
     10 'TANKER-TRUCK'
     11 'SURFACE WATER (RIVER, DAM, LAKE, POND, STREAM, CANAL, IRRIGATION CHANNELS)'
     12 'OTHER,SPECIFY' / .


SAVE OUTFILE='.\hh_sec_i.sav'.
