/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_o2.dat" ENCODING="CP1252" / LRECL=79 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        hh_o08 23             
   indidy5 24               hh_o10 25-32             hh_o11_1 33           
   hh_o11_2 34-38           hh_o12 39-45             hh_o13_1 46-47        
   hh_o13_2 48-51           hh_o14 52-59             hh_o15 60-66          
   hh_o16 67-68             hh_o17_1 69-76           hh_o17_2 77           
   hh_o18 78-79 .        

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   hh_o08    'Is anyone in the household a member of a credit or savings group ' +
   '(SACCOS)?'
   indidy5 'Individual ID'
   hh_o10 "What is [NAME]'s total balance with the group?"
   hh_o11_1 'How often does [NAME] contribute to the group? FREQUENCY'
   hh_o11_2 'How often does [NAME] contribute to the group? UNIT'
   hh_o12 'How much does [NAME] give each time? (TSH)'
   hh_o13_1 'When was the last time [NAME] withdrew money? MONTH'
   hh_o13_2 'When was the last time [NAME] withdrew money? YEAR'
   hh_o14 'How much did [NAME] withdraw? (TSH)'
   hh_o15 'What was the balance just before the withdrawal? (TSH)'
   hh_o16 'What was the main reason [NAME] took money out this last time?'
   hh_o17_1 'How much will [NAME] pay for this loan per [PERIOD]? TSH'
   hh_o17_2 'How much will [NAME] pay for this loan per [PERIOD]? PERIOD'
   hh_o18 'How long will it take [NAME] to repay the loan? MONTHS' .

VALUE LABELS
 hh_o08
     1 'YES'
     2 'NO' /
 hh_o11_1
     1 'DAY'
     2 'WEEK'
     3 'MONTH'
     4 'YEAR' /
 hh_o13_1
     0 "DON'T KNOW"
     1 'JANUARY'
     2 'FEBRUARY'
     3 'MARCH'
     4 'APRIL'
     5 'MAY'
     6 'JUNE'
     7 'JULY'
     8 'AUGUST'
     9 'SEPTEMBER'
     10 'OCTOBER'
     11 'NOVEMBER'
     12 'DECEMBER' /
 hh_o13_2
     0 "DON'T KNOW" /
 hh_o16
     1 'SUBSISTENCE NEEDS'
     2 'MEDICAL COST'
     3 'SCHOOL FEES'
     4 'CEREMONY/WEDDING'
     5 'PURCHASE LAND'
     6 'PURCHASE AGRICULTURAL INPUTS'
     7 'OTHER BUSINESS INPUTS'
     8 'PURCHASE AGRICULTURAL MACHINERY'
     9 'PURCHASE/CONSTRUCTION OF DWELLING'
     10 'OTHER, SPECIFY' /
 hh_o17_2
     1 'DAY'
     2 'WEEK'
     3 'MONTH'
     4 'YEAR' / .


SAVE OUTFILE='.\hh_sec_o2.sav'.
