/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_e3.dat" ENCODING="CP1252" / LRECL=55 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        indidy5 23-24         
   hh_e301 25               hh_e302 26               hh_e303 27-28         
   hh_e304 29               hh_e305 30-32            hh_e306 33            
   hh_e307 34-35            hh_e308 36               hh_e309 37-40         
   hh_e310 41               hh_e311 42-44            hh_e312 45            
   hh_e313 46-47            hh_e314 48               hh_e315 49-51         
   hh_e316 52               hh_e317 53-55 .       


FORMATS
  hh_e305 (F4.1) /         hh_e309 (F5.2) /         hh_e311 (F4.1) / .
    
VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   indidy5 'Individual ID'
   hh_e301 'CAPI: Is [NAME] 5 years old or older?'
   hh_e302 'Is this person answering for himself/herself?'
   hh_e303 'Who is reporting the information for the individual?'
   hh_e304    'In the last 7 days, did [NAME] gather foodstuffs (e.g. wild berri' +
   'es, nuts, mushr'
   hh_e305 'How many hours did [NAME] spend doing this in the last 7 days?'
   hh_e306    'In the last 7 days, did [NAME] go hunting for bush meat for the h' +
   'ousehold?'
   hh_e307 'How many hours did [NAME] spend doing this in the last 7 days?'
   hh_e308    'In the last 7 days, did [NAME] prepare preserved food or drinks f' +
   'or storage such'
   hh_e309 'How many hours did [NAME] spend doing this in the last 7 days?'
   hh_e310    'In the last 7 days, did [NAME] do any construction work to build,' +
   ' renovate, or e'
   hh_e311 'How many hours did [NAME] spend doing this in the last 7 days?'
   hh_e312    'In the last 7 days, did [NAME] spend any time making goods for us' +
   'e by your house'
   hh_e313 'How many hours did [NAME] spend doing this in the last 7 days?'
   hh_e314    'In the last 7 days, did [NAME] fetch water from natural or public' +
   ' sources for us'
   hh_e315    'How many hours did [NAME] spend doing this in the last 7 days? [I' +
   'NCLUDING WAITIN'
   hh_e316    'In the last 7 days, did [NAME] collect firewood or other natural ' +
   'products for us'
   hh_e317 'How many hours did [NAME] spend doing this in the last 7 days?' .

VALUE LABELS
 hh_e301
     1 'YES'
     2 'NO' /
 hh_e302
     1 'YES'
     2 'NO' /
 hh_e304
     1 'YES'
     2 'NO' /
 hh_e306
     1 'YES'
     2 'NO' /
 hh_e308
     1 'YES'
     2 'NO' /
 hh_e310
     1 'YES'
     2 'NO' /
 hh_e312
     1 'YES'
     2 'NO' /
 hh_e314
     1 'YES'
     2 'NO' /
 hh_e316
     1 'YES'
     2 'NO' / .


SAVE OUTFILE='.\hh_sec_e3.sav'.
