/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_p.dat" ENCODING="CP1252" / LRECL=74 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        hh_p01 23             
   loanid 24                hh_p02 25-40 (A)         hh_p03 41-42          
   hh_p04 43                hh_p05 44                hh_p06 45-52          
   hh_p06a 53               hh_p07 54                hh_p08_1 55-56        
   hh_p08_2 57-60           hh_p09 61-68             hh_p10_1 69-70        
   hh_p10_2 71-72           hh_p10_3 73-74 .      

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   hh_p01    'Over the past 12 months, did you or anyone else in this household' +
   ' borrow from...'
   loanid 'Loan / Credit ID'
   hh_p02    'What are the names of the persons or institutions from whom you o' +
   'r anyone else i'
   hh_p03 'CODE SOURCE OF LOAN'
   hh_p04 'Which household member was responsible for the loan?'
   hh_p05 'Was this a cash loan or goods on credit?'
   hh_p06 'How much was borrowed or what was the value of the credit?'
   hh_p06a    'Did you use land owning certificate or CCRO as collateral for loa' +
   'n?'
   hh_p07 'Is the loan/credit re-paid?'
   hh_p08_1 'Approximately when do you expect to pay back the money?'
   hh_p08_2 'Approximately when do you expect to pay back the money?'
   hh_p09 'Total amount to be paid on the loan including interest.'
   hh_p10_1 'What did you use this loan/credit for?'
   hh_p10_2 'What did you use this loan/credit for?'
   hh_p10_3 'What did you use this loan/credit for?' .

VALUE LABELS
 hh_p01
     1 'YES'
     2 'NO' /
 hh_p03
     1 'COMMERCIAL BANKS'
     2 'MICRO-FINANCE INST'
     3 'BUILDING SOC./MORTGAGE'
     4 'INSURANCE COMPANIES'
     5 'OTHER FINANCIAL INST'
     6 'NEIGHBOURS / FRIENDS'
     7 'GROCERY/LOCAL MERCHANT'
     8 'MONEY LENDER'
     9 'EMPLOYER'
     10 'RELIGIOUS INST'
     11 'NGO'
     12 'SELF-HELP GROUPS'
     13 'OTHER (SPECIFY)' /
 hh_p05
     1 'CASH'
     2 'GOODS' /
 hh_p06a
     1 'YES, LAND OWNING CERTIFCIATE'
     2 'YES, CERTIFICATE OF CUSTOMARY RIGHT OF OCCUPANCY'
     3 'NO' /
 hh_p07
     1 'YES'
     2 'NO' /
 hh_p08_1
     1 'JANUARY'
     2 'FEBRUARY'
     3 'MARCH'
     4 'APRIL'
     5 'MAY'
     6 'JUNE'
     7 'JULY'
     8 'AUGUST'
     9 'SEPTEMBER'
     10 'OCTOBER'
     11 'NOVEMBER'
     12 'DECEMBER' /
 hh_p10_1
     1 'SUBSISTENCE NEEDS'
     2 'MEDICAL COST'
     3 'SCHOOL FEES'
     4 'CEREMONY/WEDDING'
     5 'PURCHASE LAND'
     6 'PURCHASE AGRIC. INPUTS'
     7 'OTHER BUSINESS INPUTS'
     8 'PURCHASE AGRIC. MACHINERY'
     9 'BUY/BUILD DWELLING'
     10 'OTHER (SPECIFY)'
     11 'NO REASON' /
 hh_p10_2
     1 'SUBSISTENCE NEEDS'
     2 'MEDICAL COST'
     3 'SCHOOL FEES'
     4 'CEREMONY/WEDDING'
     5 'PURCHASE LAND'
     6 'PURCHASE AGRIC. INPUTS'
     7 'OTHER BUSINESS INPUTS'
     8 'PURCHASE AGRIC. MACHINERY'
     9 'BUY/BUILD DWELLING'
     10 'OTHER (SPECIFY)'
     11 'NO REASON' /
 hh_p10_3
     1 'SUBSISTENCE NEEDS'
     2 'MEDICAL COST'
     3 'SCHOOL FEES'
     4 'CEREMONY/WEDDING'
     5 'PURCHASE LAND'
     6 'PURCHASE AGRIC. INPUTS'
     7 'OTHER BUSINESS INPUTS'
     8 'PURCHASE AGRIC. MACHINERY'
     9 'BUY/BUILD DWELLING'
     10 'OTHER (SPECIFY)'
     11 'NO REASON' / .


SAVE OUTFILE='.\hh_sec_p.sav'.
