/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_s.dat" ENCODING="CP1252" / LRECL=83 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        y4_hhid 23-30 (A)     
   hh_s01 31                personid 32-33 (A)       hh_s02 34-49 (A)      
   hh_s03 50-51             hh_s04_1 52              hh_s04_2 53-54        
   hh_s05 55                hh_s06 56                hh_s07_1 57-59        
   hh_s07_2 60-61           hh_s08 62-63             hh_s09 64             
   hh_s10 65                hh_s11_1 66-67           hh_s11_2 68-69        
   hh_s12_1 70-71           hh_s12_2 72              hh_s13 73             
   hh_s14 74                hh_s15 75-82             int_result 83 .       

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   y4_hhid 'NPS4 HHID'
   hh_s01    'Over the past 2 years, did any member of your household die, incl' +
   'uding any infan'
   personid 'Serial NO'
   hh_s02 'Name of deceased'
   hh_s03 'Relation to head of household'
   hh_s04_1 'Was [NAME] a member of the household in NPS4 (2014/2015)?'
   hh_s04_2    'If this member was present at last survey, enter Y4 HHID number f' +
   'rom tracking fo'
   hh_s05 'Sex'
   hh_s06 'Was this event registered with the death registration system?'
   hh_s07_1 'Age at Death [YEARS]'
   hh_s07_2 'Age at Death [MONTHS]'
   hh_s08 'What kind of work did [NAME] do for most of his/her life?'
   hh_s09 'Did [NAME] die of old age, an illness, or of some other cause?'
   hh_s10 "What was the non-illness cause of [NAME]'s death?"
   hh_s11_1 "What was the illness that caused [NAME]'s death? 1ST ILLNESS"
   hh_s11_2 "What was the illness that caused [NAME]'s death? 2ND ILLNESS"
   hh_s12_1    'For how long was [NAME] suffering from this illness before he/she' +
   ' died? AMOUNT'
   hh_s12_2    'For how long was [NAME] suffering from this illness before he/she' +
   ' died? UNIT'
   hh_s13    'Was this cause of death diagnosed, or is this only your own perce' +
   'ption?'
   hh_s14    'After this person died, did you or members of your household lose' +
   ' any land or ot'
   hh_s15 'What was the value of the land or assets lost? TSH'
   int_result 'WHAT IS THE FINAL RESULT OF THE INTERVIEW?' .

VALUE LABELS
 hh_s01
     1 'YES'
     2 'NO' /
 hh_s03
     1 'HEAD'
     2 'SPOUSE'
     3 'CHILD OF HEAD'
     4 'NIECE/NEPHEW'
     5 'BROTHER/SISTER'
     6 'GRANDCHILD OF THE HEAD'
     7 'PARENT OF THE HEAD'
     8 'OTHER RELATIVE'
     9 'SERVANT'
     10 'OTHER, SPECIFY' /
 hh_s04_1
     1 'YES'
     2 'NO' /
 hh_s05
     1 'MALE'
     2 'FEMALE' /
 hh_s06
     1 'YES'
     2 'NO' /
 hh_s08
     1 'AGRICULTURE/LIVESTOCK'
     2 'FISHING'
     3 'MINING'
     4 'TOURISM'
     5 'GOVERNMENT'
     6 'PARASTATAL'
     7 'PRIVATE SECTOR'
     8 'NGO / RELIGIOUS'
     9 'SELF-EMPLOYED (NOT AGRICULTURE): WITH EMPLOYEES'
     10 'SELF-EMPLOYED (NOT AGRICULTURE):  W/OUT EMPLOYEES'
     11 'SELF-EMPLOYED (NOT AGRICULTURE):  UNPAID HOUSEHOLD  LABOUR'
     12 'JOB SEEKERS'
     13 'STUDENT'
     14 'DISABLED'
     15 'NO JOB' /
 hh_s09
     1 'OLD AGE'
     2 'ILLNESS'
     3 'OTHER CAUSE' /
 hh_s10
     1 'TRAFFIC ACCIDENT'
     2 'OTHER ACCIDENT OR INJURY'
     3 'CHILDBIRTH OR COMPLICATIONS'
     4 'MURDER'
     5 'SUICIDE'
     6 'WITCHCRAFT/ SORCERY'
     7 'OTHER (SPECIFY)' /
 hh_s11_1
     1 'MALARIA'
     2 'DIARRHEA'
     3 'VOMITING'
     4 'FLU'
     5 'ASTHMA'
     6 'HEADACHE'
     7 'BACKACHE'
     8 'TB'
     9 'DIABETES'
     10 'STDs'
     11 'BURN'
     12 'FRACTURE'
     13 'HIV/AIDS'
     14 'EAR/NOSE/THROAT'
     15 'TYPHOID'
     16 'POISONING'
     17 'DENTAL'
     18 'URINATING IS PAINFUL'
     19 'MENTAL DISORDER'
     20 'STOMACH DISORDER'
     21 'PROLONGED WOUND'
     22 'SKIN PROBLEM'
     23 'PREGNANCY RELATED'
     24 'CANCER'
     25 'LOWER RESPIRATORY'
     26 'UPPER RESPIRATORY'
     27 'HEART PROBLEM/BP'
     28 'UNSPECIFIED LONG TERM ILLNESS'
     29 'BILHARZIA/SCHISTOSOMIASIS'
     30 'ARTHRITIS/NERVE DISORDER'
     31 'RHEUMATISM'
     32 'EYE PROBLEM'
     33 'WITCHCRAFT'
     34 'OTHER (SPECIFY)' /
 hh_s11_2
     1 'MALARIA'
     2 'DIARRHEA'
     3 'VOMITING'
     4 'FLU'
     5 'ASTHMA'
     6 'HEADACHE'
     7 'BACKACHE'
     8 'TB'
     9 'DIABETES'
     10 'STDs'
     11 'BURN'
     12 'FRACTURE'
     13 'HIV/AIDS'
     14 'EAR/NOSE/THROAT'
     15 'TYPHOID'
     16 'POISONING'
     17 'DENTAL'
     18 'URINATING IS PAINFUL'
     19 'MENTAL DISORDER'
     20 'STOMACH DISORDER'
     21 'PROLONGED WOUND'
     22 'SKIN PROBLEM'
     23 'PREGNANCY RELATED'
     24 'CANCER'
     25 'LOWER RESPIRATORY'
     26 'UPPER RESPIRATORY'
     27 'HEART PROBLEM/BP'
     28 'UNSPECIFIED LONG TERM ILLNESS'
     29 'BILHARZIA/SCHISTOSOMIASIS'
     30 'ARTHRITIS/NERVE DISORDER'
     31 'RHEUMATISM'
     32 'EYE PROBLEM'
     33 'WITCHCRAFT'
     34 'OTHER (SPECIFY)' /
 hh_s12_2
     1 'DAY'
     2 'WEEK'
     3 'MONTH'
     4 'YEAR' /
 hh_s13
     1 'MEDICAL DIAGNOSIS'
     2 'NON MEDICAL DIAGNOSIS'
     3 'OWN PERCEPTION' /
 hh_s14
     1 'YES'
     2 'NO' /
 int_result
     1 'COMPLETE'
     2 'PARTIALLY COMPLETE (REFUSED)'
     3 'PARTIALLY COMPLETE (UNAVAILABLE)'
     4 'UNABLE TO IDENTIFY HOUSEHOLD'
     5 'HOUSEHOLD HAS MOVED AWAY'
     6 'LONG TERM UNAVAILABLE'
     7 'REFUSED' / .


SAVE OUTFILE='.\hh_sec_s.sav'.
