/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_f.dat" ENCODING="CP1252" / LRECL=69 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        indidy5 23-24         
   hh_f01 25                hh_f02 26                hh_f03 27-32          
   hh_f04 33                hh_f05 34-38             hh_f06 39             
   hh_f07 40-44             hh_f08 45                hh_f09 46-51          
   hh_f10 52                hh_f11 53-57             hh_f12 58             
   hh_f13 59-63             hh_f14 64                hh_f15 65-69 .        

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   indidy5 'Individual ID'
   hh_f01    'Did [NAME] consume any meals/ snacks/ drinks outside the househol' +
   'd in the past 7'
   hh_f02    'In the past 7 days did [NAME] consume any full meals (breakfast, ' +
   'lunch or dinner'
   hh_f03 'What was the value of this consumption? (TSH)'
   hh_f04    'In the past 7 days did [NAME] consume any barbecued meat, chips, ' +
   'roast bananas a'
   hh_f05 'What was the value of this consumption? (TSH)'
   hh_f06    'In the past 7 days did [NAME] consume any kibuku and other local ' +
   'brews outside o'
   hh_f07 'What was the value of this consumption? (TSH)'
   hh_f08    'In the past 7 days did [NAME] consume any wine, commercial beer a' +
   'nd spirits outs'
   hh_f09 'What was the value of this consumption? (TSH)'
   hh_f10    'In the past 7 days did [NAME] consume any sodas and other non-alc' +
   'oholic drinks o'
   hh_f11 'What was the value of this consumption? (TSH)'
   hh_f12    'In the past 7 days did [NAME] consume any sweets, ice-cream outsi' +
   'de of the house'
   hh_f13 'What was the value of this consumption? (TSH)'
   hh_f14    'In the past 7 days did [NAME] consume any tea, coffee, samosa, ca' +
   'ke and other ho'
   hh_f15 'What was the value of this consumption? (TSH)' .

VALUE LABELS
 hh_f01
     1 'YES'
     2 'NO' /
 hh_f02
     1 'YES'
     2 'NO' /
 hh_f04
     1 'YES'
     2 'NO' /
 hh_f06
     1 'YES'
     2 'NO' /
 hh_f08
     1 'YES'
     2 'NO' /
 hh_f10
     1 'YES'
     2 'NO' /
 hh_f12
     1 'YES'
     2 'NO' /
 hh_f14
     1 'YES'
     2 'NO' / .


SAVE OUTFILE='.\hh_sec_f.sav'.
