/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_j4.dat" ENCODING="CP1252" / LRECL=29 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        hh_j09 23             
   agegroup 24              hh_j10 25-26             hh_j11 27-29 .        

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   hh_j09    'Over the past one week (7 days), did any people that you did not ' +
   'list as househo'
   agegroup 'Age Group'
   hh_j10    'How many [AGE GROUP] were meals shared with over the past 7 days?' +
   ' [# OF PEOPLE]'
   hh_j11    'What was the total number of meals that were shared over the past' +
   ' 7 days? [# OF ' .

VALUE LABELS
 hh_j09
     1 'YES'
     2 'NO' /
 agegroup
     1 'A. CHILDREN 0-5 YEARS'
     2 'B. CHILDREN 6-15 YEARS'
     3 'C. ADULTS 16-65 YEARS'
     4 'D. PEOPLE OVER 65 YEARS OLD' / .


SAVE OUTFILE='.\hh_sec_j4.sav'.
