/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_c.dat" ENCODING="CP1252" / LRECL=136 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        indidy5 23-24         
   hh_c01 25                hh_c01_1 26              hh_c01_2 27-28        
   hh_c02 29                hh_c03 30                hh_c03_1 31-32        
   hh_c04 33-34             hh_c05 35                hh_c05a 36-37         
   hh_c06 38                hh_c07 39-40             hh_c08 41-44          
   hh_c09 45-46             hh_c10 47-48             hh_c11 49             
   hh_c12 50                hh_c13 51                hh_c14 52             
   hh_c15 53-55             hh_c16 56                hh_c17 57             
   hh_c18 58-59             hh_c19 60                hh_c20_1 61-62        
   hh_c20_2 63-64           hh_c21_1 65              hh_c21_2 66           
   hh_c22 67                hh_c23 68                hh_c24 69             
   hh_c25 70-73             hh_c26 74                hh_c27 75             
   hh_c28_0 76              hh_c28_1 77-84           hh_c28_2 85-91        
   hh_c28_3 92-98           hh_c28_4 99-105          hh_c28_5 106-111      
   hh_c28_6 112-117         hh_c28_7 118-124         hh_c28_8 125-132      
   hh_c29 133               hh_c30 134-135           hh_c01_3 136 .        

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   indidy5 'Individual ID'
   hh_c01 'CAPI: Is [NAME] 5 years or above?'
   hh_c01_1 'Is this person answering for himself/herself?'
   hh_c01_2 'Who is reporting the information for [NAME]?'
   hh_c02 'Can [NAME] read and write?'
   hh_c03 'Did [NAME] ever go to school?'
   hh_c03_1 'What was the main reason [NAME] never attended school?'
   hh_c04 'At what age did [NAME] start school?'
   hh_c05 'Is [NAME] currently in school?'
   hh_c05a 'What is the main reason for [NAME] not attending school?'
   hh_c06 'Was [NAME] in school last year?'
   hh_c07 'What is the highest grade completed by [NAME]?'
   hh_c08 'What year did [NAME] leave school for the last time?'
   hh_c09 'What grade is [NAME] currently attending?'
   hh_c10 'What grade was [NAME] attending last year?'
   hh_c11 'CAPI: Is [NAME] currently attending school?'
   hh_c12 'Who owns the school [NAME] attends?'
   hh_c13 'Is this school a boarding school?'
   hh_c14 'How does [NAME] usually travel to school?'
   hh_c15    'How long does it take [NAME] to get to school by this means of tr' +
   'ansportation?'
   hh_c16 'Does [NAME] get meals at the school (school feeding )?'
   hh_c17 'Has [NAME] missed school in the last two schooling weeks?'
   hh_c18 'Why was [NAME] absent from school?'
   hh_c19 'What is the status of the textbooks [NAME] uses for school?'
   hh_c20_1    'In the last week, approximately how many HOURS did [NAME] spend o' +
   'n homework or s'
   hh_c20_2    'In the last week, approximately how many MINUTES did [NAME] spend' +
   ' on homework or'
   hh_c21_1 'Has [NAME] had any problems at school? [1ST]'
   hh_c21_2 'Has [NAME] had any problems at school? [2ND]'
   hh_c22 'Did [NAME] take the Primary School Leaving Exam [PSLE]?'
   hh_c23 'How did [NAME] score in the exam?'
   hh_c24 'Did [NAME] take the Form 4 or Form 6 exam?'
   hh_c25 'In what year did [NAME] take the exam?'
   hh_c26 'Will you show me the exam certificate?'
   hh_c27 'How did [NAME] score in the exam?'
   hh_c28_0    'INTERVIEWER: IF THE RESPONDENT CANNOT DIVIDE SCHOOL EXPENSES INTO' +
   ' VARIOUS CATEGO'
   hh_c28_1    "How much was spent on [NAME]'s education in the last 12 months fo" +
   'r School Fees?'
   hh_c28_2    "How much was spent on [NAME]'s education in the last 12 months fo" +
   'r Books and Mat'
   hh_c28_3    "How much was spent on [NAME]'s education in the last 12 months fo" +
   'r Uniforms?'
   hh_c28_4    "How much was spent on [NAME]'s education in the last 12 months fo" +
   'r Transportatio'
   hh_c28_5    "How much was spent on [NAME]'s education in the last 12 months fo" +
   'r Extra Tuition'
   hh_c28_6    "How much was spent on [NAME]'s education in the last 12 months fo" +
   'r Other Contrib'
   hh_c28_7    "How much was spent on [NAME]'s education in the last 12 months fo" +
   'r Meals Cost?'
   hh_c28_8    "How much was spent on [NAME]'s education in the last 12 months in" +
   ' Total?'
   hh_c29 'Has [NAME] ever attended an adult literacy class? Which one?'
   hh_c30 'How many months did [NAME] attend this adult literacy class?'
   hh_c01_3 'CODE FOR ABILITY FOR RESPONDENT TO BE INTERVIEWED ALONE:' .

VALUE LABELS
 hh_c01_1
     1 'YES'
     2 'NO' /
 hh_c02
     1 'KISWAHILI'
     2 'ENGLISH'
     3 'KISWAHILI & ENGLISH'
     4 'ANY OTHER LANGUAGE'
     5 'NO' /
 hh_c03
     1 'YES'
     2 'NO' /
 hh_c03_1
     1 'TOO YOUNG'
     2 'TOO FAR AWAY'
     3 'TOO EXPENSIVE'
     4 'WORKING (AT HOME OR AT A JOB)'
     5 'LACK OF MONEY'
     6 'DEATH OF PARENT(S)'
     7 'SEPARATION OF PARENTS'
     8 'DOES NOT HAVE INTEREST'
     9 'PARENTS DO NOT THINK IT IS IMPORTANT'
     10 'ILLNESS'
     11 'DISABILITY'
     12 'OTHER (SPECIFY)' /
 hh_c05
     1 'YES'
     2 'NO' /
 hh_c05a
     1 'FINANCIAL CONSTRAINTS'
     2 'SCHOOL TOO FAR AWAY'
     3 'ILLNESS/SICKNESS'
     4 'PREGANCY RELATED'
     5 'SATISFIED'
     6 'REFUSAL'
     7 'EXPULSION'
     8 'TO WORK/LOOKING FOR WORK'
     9 'CARING FOR THE SICK/CHILDREN'
     10 'MARRIAGE'
     11 'OTHER (SPECIFY)' /
 hh_c06
     1 'YES'
     2 'NO' /
 hh_c07
     1 'PP'
     2 'MS+ COURSE'
     11 'ADULT'
     12 'D1'
     13 'D2'
     14 'D3'
     15 'D4'
     16 'D5'
     17 'D6'
     18 'D7'
     19 'D8'
     20 'OSC'
     21 'F1'
     22 'F2'
     23 'F3'
     24 'F4'
     25 "'O'+COURSE"
     31 'F5'
     32 'F6'
     33 "'A'+COURSE"
     34 'DIPLOMA'
     41 'U1'
     42 'U2'
     43 'U3'
     44 'U4'
     45 'U5&+' /
 hh_c08
     9999 "DON'T KNOW" /
 hh_c09
     1 'PP'
     2 'MS+COURSE'
     11 'ADULT'
     12 'D1'
     13 'D2'
     14 'D3'
     15 'D4'
     16 'D5'
     17 'D6'
     18 'D7'
     19 'D8'
     20 'OSC'
     21 'F1'
     22 'F2'
     23 'F3'
     24 'F4'
     25 "'O'+COURSE"
     31 'F5'
     32 'F6'
     33 "'A'+COURSE"
     34 'DIPLOMA'
     41 'U1'
     42 'U2'
     43 'U3'
     44 'U4'
     45 'U5&+' /
 hh_c10
     1 'PP'
     2 'MS+COURSE'
     11 'ADULT'
     12 'D1'
     13 'D2'
     14 'D3'
     15 'D4'
     16 'D5'
     17 'D6'
     18 'D7'
     19 'D8'
     20 'OSC'
     21 'F1'
     22 'F2'
     23 'F3'
     24 'F4'
     25 "'O'+COURSE"
     31 'F5'
     32 'F6'
     33 "'A'+COURSE"
     34 'DIPLOMA'
     41 'U1'
     42 'U2'
     43 'U3'
     44 'U4'
     45 'U5&+'
     90 'NOT YET STARTED'
     91 'NOT ATTENDING' /
 hh_c11
     1 'YES'
     2 'NO' /
 hh_c12
     1 'LOCAL GOVERNMENT'
     3 'LOCAL PEOPLE'
     4 'FOREIGN PEOPLE'
     5 'RELIGIOUS'
     6 'CHARITABLE ORG'
     7 'PRIVATE ORG'
     8 'OTHER (SPECIFY)' /
 hh_c13
     1 'YES'
     2 'NO' /
 hh_c14
     1 'ON FOOT'
     2 'BY BIKE'
     3 'BY PRIVATE CAR/VEHICLE'
     4 'BY PUBLIC VEHICLE/MINIBUS'
     5 'MOTORCYCLE'
     6 'SCHOOL BUS'
     7 'OTHER (SPECIFY)' /
 hh_c16
     1 'YES'
     2 'NO' /
 hh_c17
     1 'YES'
     2 'NO' /
 hh_c18
     1 'PUBLIC HOLIDAY'
     2 'SCHOOL CLOSED NOT IN BREAK'
     3 'SCHOOL CLOSED IN BREAK'
     4 'ABSENCE TEACHER'
     5 'ILLNESS CHILD'
     6 'ILNESS HH MEMBER'
     7 'FUNERAL'
     8 'DISCIPLINARY ACTION'
     9 'CANNOT MEET COSTS'
     10 'CHILD REFUSED'
     11 'CHILD HAD TO WORK'
     12 'OTHER (SPECIFY)' /
 hh_c19
     1 'NO TEXTBOOKS USED'
     2 "ALL BORROWED FROM SCHOOL BUT CAN'T TAKE HOME"
     3 'ALL BORROWED FROM SCHOOL, SOME/ALL CAN TAKE HOME'
     4 'SOME OWNED BY HOUSEHOLD'
     5 'OTHER (SPECIFY)' /
 hh_c20_1
     0 'NONE' /
 hh_c20_2
     0 'NONE' /
 hh_c21_1
     1 'NO PROBLEMS (SATISFIED)'
     2 'INADEQUATE BOOKS/TOOLS'
     3 'POOR TEACHING'
     4 'INADEQUATE TEACHERS'
     5 'POOR ATTENDANCE OF TEACHERS'
     6 'OVERCROWDED CLASSROOMS'
     7 'TOO EXPENSIVE'
     8 'OTHER (SPECIFY)' /
 hh_c21_2
     1 'NO PROBLEMS (SATISFIED)'
     2 'INADEQUATE BOOKS/TOOLS'
     3 'POOR TEACHING'
     4 'INADEQUATE TEACHERS'
     5 'POOR ATTENDANCE OF TEACHERS'
     6 'OVERCROWDED CLASSROOMS'
     7 'TOO EXPENSIVE'
     8 'OTHER (SPECIFY)' /
 hh_c22
     1 'YES'
     2 'NO' /
 hh_c23
     1 'PASS'
     2 'FAIL'
     3 "DON'T KNOW" /
 hh_c24
     1 'YES, FORM 4'
     2 'YES, FORM 6'
     3 'NO, DID NOT TAKE' /
 hh_c25
     9999 "DON'T KNOW" /
 hh_c26
     1 'YES, IT WAS SHOWN'
     2 'NOT SHOWN, HOUSEHOLD HAS BUT REFUSED'
     3 'NOT FOUND' /
 hh_c27
     1 'DIVISION 1'
     2 'DIVISION 2'
     3 'DIVISION 3'
     4 'DIVISION 4'
     5 'FAIL'
     6 "DON'T KNOW" /
 hh_c28_0
     1 'BREAKDOWN'
     2 'TOTAL' /
 hh_c28_1
     0 'NONE' /
 hh_c28_2
     0 'NONE' /
 hh_c28_3
     0 'NONE' /
 hh_c28_4
     0 'NONE' /
 hh_c28_5
     0 'NONE' /
 hh_c28_6
     0 'NONE' /
 hh_c28_7
     0 'NONE' /
 hh_c28_8
     0 'NONE' /
 hh_c29
     1 'KCM (MUKEJA)'
     2 'KCK (MUKEJA)'
     3 'OTHER (NOT MUKEJA), SPECIFY'
     4 'NEVER ATTENDED' /
 hh_c01_3
     1 'ALONE'
     2 'WITH ADULT FEMALES PRESENT'
     3 'WITH ADULT MALES PRESENT'
     4 'WITH ADULTS MIXED SEX PRESENT'
     5 'WITH CHILDREN PRESENT'
     6 'WITH ADULTS MIXED SEX AND CHILDREN PRESENT' / .


SAVE OUTFILE='.\hh_sec_c.sav'.
