/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_h.dat" ENCODING="CP1252" / LRECL=88 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        hh_h01 23             
   hh_h02a 24               hh_h02b 25               hh_h02c 26            
   hh_h02d 27               hh_h02e 28               hh_h02f 29            
   hh_h02g 30               hh_h02h 31               hh_h03_1 32           
   hh_h03_2 33-34           hh_h04_1 35-36           hh_h04_2 37-38        
   hh_h05_1 39-40           hh_h05_2 41-42           hh_h06 43             
   hh_h07_1 44              hh_h07_2 45              hh_h07_3 46           
   hh_h08 47                hh_h09_1 48 (A)          hh_h09_2 49 (A)       
   hh_h09_3 50 (A)          hh_h09_4 51 (A)          hh_h09_5 52 (A)       
   hh_h09_6 53 (A)          hh_h09_7 54 (A)          hh_h09_8 55 (A)       
   hh_h09_9 56 (A)          hh_h09_10 57 (A)         hh_h09_11 58 (A)      
   hh_h09_12 59 (A)         hh_h09_13 60 (A)         hh_h09_14 61 (A)      
   hh_h09_15 62 (A)         hh_h09_16 63 (A)         hh_h09_17 64 (A)      
   hh_h09_18 65 (A)         hh_h09_19 66 (A)         hh_h09_20 67 (A)      
   hh_h09_21 68 (A)         hh_h09_22 69 (A)         hh_h09_23 70 (A)      
   hh_h09_24 71 (A)         hh_h09_25 72 (A)         hh_h09_26 73 (A)      
   hh_h09_27 74 (A)         hh_h09_28 75 (A)         hh_h09_29 76 (A)      
   hh_h09_30 77 (A)         hh_h09_31 78 (A)         hh_h09_32 79 (A)      
   hh_h09_33 80 (A)         hh_h09_34 81 (A)         hh_h10_1 82-83        
   hh_h10_2 84-85           hh_h10_3 86-87           hh_h11 88 .           

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   hh_h01    'In the past 7 days, did you worry that your household would not h' +
   'ave enough food'
   hh_h02a    'In the past 7 days, how many days had to: RELY ON LESS PREFERRED ' +
   'FOOD?'
   hh_h02b    'In the past 7 days, how many days had to: LIMIT THE VARIETY OF FO' +
   'ODS EATEN?'
   hh_h02c    'In the past 7 days, how many days had to: LIMIT PORTION SIZE AT M' +
   'EAL-TIMES?'
   hh_h02d    'In the past 7 days, how many days had to: REDUCE THE NUMBER OF ME' +
   'ALS EATEN IN A '
   hh_h02e    'In the past 7 days, how many days had to: RESTRICT CONSUMPTION BY' +
   ' ADULTS FOR SMA'
   hh_h02f    'In the past 7 days, how many days had to: BORROW FOOD, OR RELY ON' +
   ' HELP FROM A FR'
   hh_h02g    'In the past 7 days, how many days: HAD NO FOOD OF ANY KIND IN YOU' +
   'R HOUSEHOLD?'
   hh_h02h    'In the past 7 days, how many days had to: GO A WHOLE DAY AND NIGH' +
   'T WITHOUT EATIN'
   hh_h03_1    'How many meals, including breakfast, are taken per day in your ho' +
   'usehold? NUMBER'
   hh_h03_2    'How many meals, including breakfast, are taken per day in your ho' +
   'usehold? CHILDR'
   hh_h04_1 'What did your children below 5 years old have for breakfast?'
   hh_h04_2 'What did your children below 5 years old have for breakfast?'
   hh_h05_1    'What did your children between 5-13 years old have for breakfast?'
   hh_h05_2    'What did your children between 5-13 years old have for breakfast?'
   hh_h06 'Do all household members eat roughly the same diet?'
   hh_h07_1    'Who in the HH usually eats a more diverse / less diverse variety ' +
   'of foods? MEN'
   hh_h07_2    'Who in the HH usually eats a more diverse / less diverse variety ' +
   'of foods? WOMEN'
   hh_h07_3    'Who in the HH usually eats a more diverse / less diverse variety ' +
   'of foods? CHILD'
   hh_h08    'In the last 12 months, have you been faced with a situation when ' +
   'you did not hav'
   hh_h09_1 'When did you experience this? AUGUST 2019'
   hh_h09_2 'When did you experience this? SEPTEMBER 2019'
   hh_h09_3 'When did you experience this? OCTOBER 2019'
   hh_h09_4 'When did you experience this? NOVEMBER 2019'
   hh_h09_5 'When did you experience this? DECEMBER 2019'
   hh_h09_6 'When did you experience this? JANUARY 2020'
   hh_h09_7 'When did you experience this? FEBRUARY 2020'
   hh_h09_8 'When did you experience this? MARCH 2020'
   hh_h09_9 'When did you experience this? APRIL 2020'
   hh_h09_10 'When did you experience this? MAY 2020'
   hh_h09_11 'When did you experience this? JUNE 2020'
   hh_h09_12 'When did you experience this? JULY 2020'
   hh_h09_13 'When did you experience this? AUGUST 2020'
   hh_h09_14 'When did you experience this? SEPTEMBER 2020'
   hh_h09_15 'When did you experience this? OCTOBER 2020'
   hh_h09_16 'When did you experience this? NOVEMBER 2020'
   hh_h09_17 'When did you experience this? DECEMBER 2020'
   hh_h09_18 'When did you experience this? JANUARY 2021'
   hh_h09_19 'When did you experience this? FEBRUARY 2021'
   hh_h09_20 'When did you experience this? MARCH 2021'
   hh_h09_21 'When did you experience this? APRIL 2021'
   hh_h09_22 'When did you experience this? MAY 2021'
   hh_h09_23 'When did you experience this? JUNE 2021'
   hh_h09_24 'When did you experience this? JULY 2021'
   hh_h09_25 'When did you experience this? AUGUST 2021'
   hh_h09_26 'When did you experience this? SEPTEMBER 2021'
   hh_h09_27 'When did you experience this? OCTOBER 2021'
   hh_h09_28 'When did you experience this? NOVEMBER 2021'
   hh_h09_29 'When did you experience this? DECEMBER 2021'
   hh_h09_30 'When did you experience this? JANUARY 2022'
   hh_h09_31 'When did you experience this? FEBRUARY 2022'
   hh_h09_32 'When did you experience this? MARCH 2022'
   hh_h09_33 'When did you experience this? APRIL 2022'
   hh_h09_34 'When did you experience this? MAY 2022'
   hh_h10_1 'What was the [1ST] cause of this situation?'
   hh_h10_2 'What was the [2ND] cause of this situation?'
   hh_h10_3 'What was the [3RD] cause of this situation?'
   hh_h11    'In the last month, has there been any time when your household di' +
   'd not have suff' .

VALUE LABELS
 hh_h01
     1 'YES'
     2 'NO' /
 hh_h04_1
     1 'TEA/DRINK WITH SUGAR'
     2 'MILK/MILK TEA WITH SUGAR'
     3 'SOLID FOOD ONLY'
     4 'TEA/DRINK WITH SOLID FOOD'
     5 'PORRIDGE WITH GROUNDNUT FLOUR'
     6 'PORRIDGE WITH SOLID FOOD'
     7 'PORRIDGE WITH SUGAR'
     8 'PORRIDGE WITH MILK'
     9 'PORRIDGE WITHOUT SUGAR'
     10 'BREASTMILK'
     11 'NOTHING'
     12 'OTHER (SPECIFY)' /
 hh_h04_2
     1 'TEA/DRINK WITH SUGAR'
     2 'MILK/MILK TEA WITH SUGAR'
     3 'SOLID FOOD ONLY'
     4 'TEA/DRINK WITH SOLID FOOD'
     5 'PORRIDGE WITH GROUNDNUT FLOUR'
     6 'PORRIDGE WITH SOLID FOOD'
     7 'PORRIDGE WITH SUGAR'
     8 'PORRIDGE WITH MILK'
     9 'PORRIDGE WITHOUT SUGAR'
     10 'BREASTMILK'
     11 'NOTHING'
     12 'OTHER (SPECIFY)' /
 hh_h05_1
     0 'NO CHILDREN 5-13 YEARS OLD'
     1 'TEA/DRINK WITH SUGAR'
     2 'MILK/MILK TEA WITH SUGAR'
     3 'SOLID FOOD ONLY'
     4 'TEA/DRINK WITH SOLID FOOD'
     5 'PORRIDGE WITH GROUNDNUT FLOUR'
     6 'PORRIDGE WITH SOLID FOOD'
     7 'PORRIDGE WITH SUGAR'
     8 'PORRIDGE WITH MILK'
     9 'PORRIDGE WITHOUT SUGAR'
     10 'BREASTMILK'
     11 'NOTHING'
     12 'OTHER, SPECIFY' /
 hh_h05_2
     0 'NO CHILDREN 5-13 YEARS OLD'
     1 'TEA/DRINK WITH SUGAR'
     2 'MILK/MILK TEA WITH SUGAR'
     3 'SOLID FOOD ONLY'
     4 'TEA/DRINK WITH SOLID FOOD'
     5 'PORRIDGE WITH GROUNDNUT FLOUR'
     6 'PORRIDGE WITH SOLID FOOD'
     7 'PORRIDGE WITH SUGAR'
     8 'PORRIDGE WITH MILK'
     9 'PORRIDGE WITHOUT SUGAR'
     10 'BREASTMILK'
     11 'NOTHING'
     12 'OTHER, SPECIFY' /
 hh_h06
     1 'YES'
     2 'NO' /
 hh_h07_1
     0 'NONE'
     1 'MORE DIVERSE'
     2 'LESS DIVERSE' /
 hh_h07_2
     0 'NONE'
     1 'MORE DIVERSE'
     2 'LESS DIVERSE' /
 hh_h07_3
     0 'NONE'
     1 'MORE DIVERSE'
     2 'LESS DIVERSE' /
 hh_h08
     1 'YES'
     2 'NO' /
 hh_h10_1
     1 'INADEQUATE HOUSEHOLD STOCKS DUE TO DROUGHT/POOR RAINS'
     2 'INADEQUATE HOUSEHOLD FOOD STOCKS DUE TO CROP PEST DAMAGE'
     3 'INADEQUATE HOUSEHOLD FOOD STOCKS DUE TO SMALL LAND SIZE'
     4 'INADEQUATE HOUSEHOLD FOOD STOCKS DUE TO LACK OF FARM INPUTS'
     5 'FOOD IN THE MARKET WAS VERY EXPENSIVE'
     6 'NOT ABLE TO REACH THE MARKET DUE TO HIGH TRANSPORTATION COSTS'
     7 'NO FOOD IN THE MARKET'
     8 'FLOODS/WATER LOGGING/HAILSTORM'
     9 'NO MONEY'
     10 'OTHER (SPECIFY)' /
 hh_h10_2
     1 'INADEQUATE HOUSEHOLD STOCKS DUE TO DROUGHT/POOR RAINS'
     2 'INADEQUATE HOUSEHOLD FOOD STOCKS DUE TO CROP PEST DAMAGE'
     3 'INADEQUATE HOUSEHOLD FOOD STOCKS DUE TO SMALL LAND SIZE'
     4 'INADEQUATE HOUSEHOLD FOOD STOCKS DUE TO LACK OF FARM INPUTS'
     5 'FOOD IN THE MARKET WAS VERY EXPENSIVE'
     6 'NOT ABLE TO REACH THE MARKET DUE TO HIGH TRANSPORTATION COSTS'
     7 'NO FOOD IN THE MARKET'
     8 'FLOODS/WATER LOGGING/HAILSTORM'
     9 'NO MONEY'
     10 'OTHER (SPECIFY)' /
 hh_h10_3
     1 'INADEQUATE HOUSEHOLD STOCKS DUE TO DROUGHT/POOR RAINS'
     2 'INADEQUATE HOUSEHOLD FOOD STOCKS DUE TO CROP PEST DAMAGE'
     3 'INADEQUATE HOUSEHOLD FOOD STOCKS DUE TO SMALL LAND SIZE'
     4 'INADEQUATE HOUSEHOLD FOOD STOCKS DUE TO LACK OF FARM INPUTS'
     5 'FOOD IN THE MARKET WAS VERY EXPENSIVE'
     6 'NOT ABLE TO REACH THE MARKET DUE TO HIGH TRANSPORTATION COSTS'
     7 'NO FOOD IN THE MARKET'
     8 'FLOODS/WATER LOGGING/HAILSTORM'
     9 'NO MONEY'
     10 'OTHER (SPECIFY)' /
 hh_h11
     1 'YES, AT LEAST ONCE'
     2 'NO, ALWAYS SUFFICIENT' / .


SAVE OUTFILE='.\hh_sec_h.sav'.
