/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_u2.dat" ENCODING="CP1252" / LRECL=29 .

DATA LIST FILE=DATA/
   occ1 1                   interview__key 2-12 (A)   y5_hhid 13-23 (A)     
   hh_u201 24               hh_u202 25               hh_u203 26            
   hh_u204 27               hh_u206 28               ag2a_11 29 .          

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   hh_u201 'Does anyone in the household cultivate any plot?'
   hh_u202    'Does anyone in the household own a farm plot that they do not cul' +
   'tivate?'
   hh_u203    'Did anyone in the household own or cultivate a plot during the lo' +
   'ng rainy season'
   hh_u204    'Did anyone in the household own or cultivate any plot during the ' +
   'last completed '
   hh_u206    'Did anyone in the household own any livestock during the last 12 ' +
   'months?'
   ag2a_11 'What year was the last completed short rainy season?' .

VALUE LABELS
 hh_u201
     1 'YES'
     2 'NO' /
 hh_u202
     1 'YES'
     2 'NO' /
 hh_u203
     1 'YES'
     2 'NO' /
 hh_u204
     1 'YES'
     2 'NO' /
 hh_u206
     1 'YES'
     2 'NO' /
 ag2a_11
     1 'OCT-DEC 2019'
     2 'OCT-DEC 2020' / .


SAVE OUTFILE='.\hh_sec_u2.sav'.
