/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_r.dat" ENCODING="CP1252" / LRECL=32 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        shockid 23-25         
   hh_r01 26                hh_r02 27                hh_r03 28             
   hh_r04_1 29-30           hh_r04_2 31-32 .      

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   shockid 'Shock ID'
   hh_r01    'Over the past two years, was your household severely affected neg' +
   'atively by any '
   hh_r02 'Rank the three most significant shocks you experienced'
   hh_r03 'Did [SHOCK] cause a reduction in household income and/or assets?'
   hh_r04_1    'What did your household do in response to this [SHOCK] to try to ' +
   'regain your for'
   hh_r04_2    'What did your household do in response to this [SHOCK] to try to ' +
   'regain your for' .

VALUE LABELS
 shockid
     101 'DROUGHT OR FLOODS'
     102 'CROP DISEASE OR CROP PESTS'
     103 'LIVESTOCK DIED OR WERE STOLEN'
     104 'HOUSEHOLD BUSINESS FAILURE'
     105 'LOSS OF SALARIED EMPLOYMENT OR NON-PAYMENT OF SALARY'
     106 'LARGE FALL IN SALE PRICES FOR CROPS'
     107 'LARGE RISE IN PRICE OF FOOD'
     108 'LARGE RISE IN AGRICULTURAL INPUT PRICES'
     109 'SEVERE WATER SHORTAGE'
     110 'LOSS OF LAND'
     111 'CHRONIC/SEVERE ILLNESS OR ACCIDENT OF HOUSEHOLD MEMBER'
     112 'DEATH OF A MEMBER OF HOUSEHOLD'
     113 'DEATH OF OTHER FAMILY MEMBER'
     114 'BREAK-UP OF THE HOUSEHOLD'
     117 'HIJACKING/ROBBERY/BURGLARY/ASSAULT'
     118 'DWELLING DAMAGED, DESTROYED'
     119 'OTHER (SPECIFY)' /
 hh_r01
     1 'YES'
     2 'NO' /
 hh_r02
     1 'MOST SEVERE'
     2 'SECOND MOST SEVERE'
     3 'THIRD MOST SEVERE' /
 hh_r03
     1 'INCOME LOSS'
     2 'ASSET LOSS'
     3 'LOSS OF BOTH'
     4 'NEITHER' /
 hh_r04_1
     1 'RELIED ON OWN-SAVINGS'
     2 'RECEIVED UNCONDITIONAL HELP FROM RELATIVES/FRIENDS'
     3 'RECEIVED UNCONDITIONAL HELP FROM GOVERNMENT'
     5 'CHANGED EATING PATTERNS'
     6 'EMPLOYED HOUSEHOLD MEMBERS TOOK ON MORE EMPLOYMENT'
     7 'ADULT HOUSEHOLD MEMBERS WHO WERE PREVIOUSLY NOT WORKING HAD TO FIND WORK'
     10 'OBTAINED CREDIT'
     11 'SOLD AGRICULTURAL ASSETS'
     12 'SOLD DURABLE ASSETS'
     13 'SOLD LAND/BUILDING'
     14 'SOLD CROP STOCK'
     15 'SOLD LIVESTOCK'
     18 'ENGAGED IN SPIRITUAL EFFORTS'
     19 'DID NOT DO ANYTHING'
     20 'OTHER (SPECIFY)' /
 hh_r04_2
     1 'RELIED ON OWN-SAVINGS'
     2 'RECEIVED UNCONDITIONAL HELP FROM RELATIVES/FRIENDS'
     3 'RECEIVED UNCONDITIONAL HELP FROM GOVERNMENT'
     5 'CHANGED EATING PATTERNS'
     6 'EMPLOYED HOUSEHOLD MEMBERS TOOK ON MORE EMPLOYMENT'
     7 'ADULT HOUSEHOLD MEMBERS WHO WERE PREVIOUSLY NOT WORKING HAD TO FIND WORK'
     10 'OBTAINED CREDIT'
     11 'SOLD AGRICULTURAL ASSETS'
     12 'SOLD DURABLE ASSETS'
     13 'SOLD LAND/BUILDING'
     14 'SOLD CROP STOCK'
     15 'SOLD LIVESTOCK'
     18 'ENGAGED IN SPIRITUAL EFFORTS'
     19 'DID NOT DO ANYTHING'
     20 'OTHER (SPECIFY)' / .


SAVE OUTFILE='.\hh_sec_r.sav'.
