/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_ja1.dat" ENCODING="CP1252" / LRECL=83 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        itemcode 23-27        
   hh_ja01 28               hh_ja02_1 29-30          hh_ja02_2 31-36       
   hh_ja02a_1 37            hh_ja02b_1 38            hh_ja02b_2 39-44      
   hh_ja03_1 45-46          hh_ja03_2 47-51          hh_ja04 52-57         
   hh_ja05_1 58-59          hh_ja05_2 60-65          hh_ja06_1 66-67       
   hh_ja06_2 68-72          hh_ja07 73               hh_ja08_1 74          
   hh_ja08_2 75             hh_ja08_9 76             hh_ja09_1 77          
   hh_ja09_2 78-83 .     


FORMATS
  hh_ja02_2 (F7.2) /       hh_ja02b_2 (F7.2) /      hh_ja03_2 (F6.3) /     
  hh_ja05_2 (F7.2) /       hh_ja06_2 (F6.2) /       hh_ja09_2 (F7.2) / .
  
VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   itemcode 'Item Code'
   hh_ja01    'Within the past 7 days, did the members of this household eat/dri' +
   'nk any [...] '
   hh_ja02_1    'How much in total did your household consume in the past 7 days? ' +
   'UNIT'
   hh_ja02_2    'How much in total did your household consume in the past 7 days? ' +
   'QUANTITY'
   hh_ja02a_1 'Size'
   hh_ja02b_1    '2b. Approximately how many kilograms/grams [Litres/Millilitres] w' +
   'as the.. (Unit)'
   hh_ja02b_2    '2b. Approximately how many kilograms/grams [litres/millilitres] w' +
   'as the [QUANITY'
   hh_ja03_1 'How much came from purchases during the past 7 days? UNIT'
   hh_ja03_2 'How much came from purchases during the past 7 days? QUANTITY'
   hh_ja04 'How much did you spend? (TSH)'
   hh_ja05_1 'How much came from own-production? UNIT'
   hh_ja05_2 'How much came from own-production? QUANTITY'
   hh_ja06_1 'How much came from gifts and other sources? UNIT'
   hh_ja06_2 'How much came from gifts and other sources? QUANTITY'
   hh_ja07 'ENUMERATOR: WEIGHT ITEM AT HOUSEHOLD'
   hh_ja08_1 'ENUMERATOR: REASON NOT WEIGHED AT HH:FOOD ITEM NO LONGER IN HH'
   hh_ja08_2    'ENUMERATOR: REASON NOT WEIGHED AT HH:MEASURING UNIT NOT AVAILABLE'
   hh_ja08_9 'ENUMERATOR: REASON NOT WEIGHED AT HH:OTHER (SPECIFY)'
   hh_ja09_1 'WEIGHT OF ITEM AS WEIGHED (UNIT)'
   hh_ja09_2 'WEIGHT OF ITEM AS WEIGHED' .

VALUE LABELS
 itemcode
     101 'RICE (PADDY)'
     102 'RICE (HUSKED)'
     103 'MAIZE (GREEN, COB)'
     104 'MAIZE (GRAIN)'
     105 'MAIZE (FLOUR)'
     106 'MILLET AND SORGHUM (GRAIN)'
     107 'MILLET AND SORGHUM (FLOUR)'
     109 'BREAD'
     111 'MACARONI, SPAGHETTI'
     112 'OTHER CEREAL PRODUCTS'
     201 'CASSAVA FRESH'
     202 'CASSAVA DRY/FLOUR'
     203 'SWEET POTATOES'
     204 'YAMS/COCOYAMS'
     205 'IRISH POTATOES'
     206 'COOKING BANANAS, PLANTAINS'
     207 'OTHER STARCHES'
     301 'SUGAR'
     302 'SWEETS'
     303 'HONEY, SYRUPS, JAMS, MARMALADE, JELLIES, CANNED FRUITS'
     501 'GROUNDNUTS IN SHELL/SHELLED'
     502 'COCONUTS (MATURE/IMMATURE)'
     503 'CASHEW, ALMONDS AND OTHER NUTS'
     504 'SEEDS AND PRODUCTS FROM NUTS/SEEDS (EXCL. COOKING OIL)'
     603 'CANNED, DRIED, AND WILD VEGETABLES'
     701 'RIPE BANANAS'
     704 'SUGARCANE'
     801 'GOAT MEAT'
     802 'BEEF (INCLUDING MINCED SAUSAGE)'
     803 'PORK (INCLUDING SAUSAGES AND BACON)'
     805 'WILD BIRDS AND INSECTS'
     806 'OTHER DOMESTIC/WILD MEAT PRODUCTS'
     807 'EGGS'
     809 'DRIED/SALTED/CANNED FISH AND SEAFOOD (INCL. DAGAA)'
     810 'PACKAGED/CANNED FISH'
     901 'FRESH MILK'
     902 'MILK PRODUCTS (LIKE CREAM, CHEESE, YOGHURT ETC)'
     903 'CANNED MILK/MILK POWDER'
     1001 'COOKING OIL'
     1002 'BUTTER, MARGARINE, GHEE AND OTHER FAT PRODUCTS'
     1003 'SALT'
     1004 'OTHER SPICES'
     1081 'WHEAT FLOUR'
     1082 'BARLEY GRAIN AND OTHER CEREALS'
     1101 'TEA DRY'
     1102 'COFFEE AND COCOA'
     1103 'OTHER RAW MATERIALS FOR DRINKS'
     1104 'BOTTLED/CANNED SOFT DRINKS (SODA, JUICE, WATER)'
     1105 'PREPARED TEA, COFFEE'
     1106 'BOTTLED BEER'
     1107 'LOCAL BREWS'
     1108 'WINE AND SPIRITS'
     4011 'PEAS'
     4012 'GREEN BEANS'
     4013 'OTHER BEANS, LENTILS, AND PULSES'
     6011 'ONIONS'
     6012 'TOMATOES'
     6013 'CARROTS AND GREEN PEPPER, OTHER VIUNGO'
     6021 'CABBAGE'
     6022 'CHINESS/SPINACH'
     6023 'OTHER GREEN VEGETABLE'
     7021 'LEMON/LIME'
     7022 'ORANGE/TANGERINE'
     7023 'OTHER CITRUS FRUITS'
     7031 'MANGOES'
     7032 'AVOCADO'
     7033 'OTHER FRUITS'
     8041 'CHICKEN'
     8042 'OTHER POULTRY'
     8081 'DAGAA (FRESH)'
     8082 'KOLEKOLE (FRESH)'
     8083 'TILAPIA (FRESH)'
     8084 'OTHER FRESH FISH AND SEAFOOD'
     11011 'BUNS'
     11021 'CAKES AND BISCUITS' /
 hh_ja01
     1 'YES'
     2 'NO' /
 hh_ja02_1
     1 'KILOGRAM'
     2 'GRAM'
     3 'LITRE'
     4 'MILILITRE'
     5 'PIECE'
     6 'HEAP'
     7 'BUNCH'
     8 'SPLINTER'
     9 'SPOON'
     10 'BOWL'
     11 'CANE'
     12 'JUG'
     13 'TIN'
     14 'BUCKET'
     15 'CUP'
     16 'BOTTLE'
     17 'GLASS'
     18 'BASKET'
     19 'GALLON'
     20 'OTHER (SPECIFY)' /
 hh_ja02a_1
     1 'SMALL'
     2 'MEDIUM'
     3 'LARGE' /
 hh_ja02b_1
     1 'KILOGRAMS'
     2 'GRAMS'
     3 'LITRES'
     4 'MILLILITRES' /
 hh_ja03_1
     1 'KILOGRAMS'
     2 'GRAMS'
     3 'LITRES'
     4 'MILLILITRES' /
 hh_ja03_2
     0 'HAKUNA' /
 hh_ja05_1
     1 'KILOGRAMS'
     2 'GRAMS'
     3 'LITRES'
     4 'MILLILITRES' /
 hh_ja05_2
     0 'HAKUNA' /
 hh_ja06_1
     1 'KILOGRAMS'
     2 'GRAMS'
     3 'LITRES'
     4 'MILLILITRES' /
 hh_ja06_2
     0 'HAKUNA' /
 hh_ja07
     1 'YES'
     2 'NO' /
 hh_ja09_1
     1 'KILOGRAMS'
     2 'GRAMS'
     3 'LITRES'
     4 'MILLILITRES' / .


SAVE OUTFILE='.\hh_sec_ja1.sav'.
