/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_j3.dat" ENCODING="CP1252" / LRECL=25 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        itemcode 23-24        
   hh_j08 25 .           

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   itemcode 'Item Code'
   hh_j08    'Over the past one week (7 days), how many days did you or others ' +
   'in your househo' .

VALUE LABELS
 itemcode
     1 'A. CEREALS, GRAINS AND CEREAL PRODUCTS'
     2 'B. ROOTS, TUBERS, AND PLANTAINS'
     3 'C. NUTS AND PULSES'
     4 'D. VEGETABLES'
     5 'E. MEAT, FISH AND ANIMAL PRODUCTS'
     6 'F. FRUITS'
     7 'G. MILK/MILK PRODUCTS'
     8 'H. FATS/OIL'
     9 'I. SUGAR/SUGAR PRODUCTS/HONEY'
     10 'J. SPICES/CONDIMENTS' / .


SAVE OUTFILE='.\hh_sec_j3.sav'.
