/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_j1.dat" ENCODING="CP1252" / LRECL=60 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        itemcode 23-26        
   hh_j01 27                hh_j02_1 28              hh_j02_2 29-34        
   hh_j03_1 35              hh_j03_2 36-40           hh_j04 41-46          
   hh_j05_1 47              hh_j05_2 48-53           hh_j06_1 54           
   hh_j06_2 55-59           j1_selection 60 .     


FORMATS
  hh_j02_2 (F7.2) /        hh_j03_2 (F6.2) /        hh_j05_2 (F7.2) /      
  hh_j06_2 (F6.2) / .
   
VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   itemcode 'Item Code'
   hh_j01    'Within the past 7 days, did the members of this household eat/dri' +
   'nk any [...] '
   hh_j02_1    'How much in total did your household consume in the past 7 days? ' +
   'UNIT'
   hh_j02_2    'How much in total did your household consume in the past 7 days? ' +
   'QUANTITY'
   hh_j03_1 'How much came from purchases during the past 7 days? UNIT'
   hh_j03_2 'How much came from purchases during the past 7 days? QUANTITY'
   hh_j04 'How much did you spend? (TSH)'
   hh_j05_1 'How much came from own-production? UNIT'
   hh_j05_2 'How much came from own-production? QUANTITY'
   hh_j06_1 'How much came from gifts and other sources? UNIT'
   hh_j06_2 'How much came from gifts and other sources? QUANTITY'
   j1_selection 'HH selected for J1A Alternate Consumption' .

VALUE LABELS
 itemcode
     101 'RICE (PADDY)'
     102 'RICE (HUSKED)'
     103 'MAIZE (GREEN, COB)'
     104 'MAIZE (GRAIN)'
     105 'MAIZE (FLOUR)'
     106 'MILLET AND SORGHUM (GRAIN)'
     107 'MILLET AND SORGHUM (FLOUR)'
     109 'BREAD'
     110 'BUNS, CAKES AND BISCUITS'
     111 'MACARONI, SPAGHETTI'
     112 'OTHER CEREAL PRODUCTS'
     201 'CASSAVA FRESH'
     202 'CASSAVA DRY/FLOUR'
     203 'SWEET POTATOES'
     204 'YAMS/COCOYAMS'
     205 'IRISH POTATOES'
     206 'COOKING BANANAS, PLANTAINS'
     207 'OTHER STARCHES'
     301 'SUGAR'
     302 'SWEETS'
     303 'HONEY, SYRUPS, JAMS, MARMALADE, JELLIES, CANNED FRUITS'
     401 'PEAS, BEANS, LENTILS AND OTHER PULSES'
     501 'GROUNDNUTS IN SHELL/SHELLED'
     502 'COCONUTS (MATURE/IMMATURE)'
     503 'CASHEW, ALMONDS AND OTHER NUTS'
     504 'SEEDS AND PRODUCTS FROM NUTS/SEEDS (EXCL. COOKING OIL)'
     601 'ONIONS, TOMATOES, CARROTS AND GREEN PEPPER, OTHER VIUNGO'
     602 'SPINACH, CABBAGE AND OTHER GREEN VEGETABLES'
     603 'CANNED, DRIED AND WILD VEGETABLES'
     701 'RIPE BANANAS'
     702 'CITRUS FRUITS (ORANGES, LEMON, TANGERINES, ETC.)'
     703 'MANGOES, AVOCADOES AND OTHER FRUITS'
     704 'SUGARCANE'
     801 'GOAT MEAT'
     802 'BEEF INCLUDING MINCED SAUSAGE'
     803 'PORK INCLUDING SAUSAGES AND BACON'
     804 'CHICKEN AND OTHER POULTRY'
     805 'WILD BIRDS AND INSECTS'
     806 'OTHER DOMESTIC/WILD MEAT PRODUCTS'
     807 'EGGS'
     808 'FRESH FISH AND SEAFOOD (INCLUDING DAGAA)'
     809 'DRIED/SALTED/CANNED FISH AND SEAFOOD (INCL. DAGAA)'
     810 'PACKAGE FISH'
     901 'FRESH MILK'
     902 'MILK PRODUCTS (LIKE CREAM, CHEESE, YOGHURT ETC)'
     903 'CANNED MILK/MILK POWDER'
     1001 'COOKING OIL'
     1002 'BUTTER, MARGARINE, GHEE AND OTHER FAT PRODUCTS'
     1003 'SALT'
     1004 'OTHER SPICES'
     1081 'WHEAT FLOUR'
     1082 'WHEAT, BARLEY GRAIN AND OTHER CEREALS'
     1101 'TEA DRY'
     1102 'COFFEE AND COCOA'
     1103 'OTHER RAW MATERIALS FOR DRINKS'
     1104 'BOTTLED/CANNED SOFT DRINKS (SODA, JUICE, WATER)'
     1105 'PREPARED TEA, COFFEE'
     1106 'BOTTLED BEER'
     1107 'LOCAL BREWS'
     1108 'WINE AND SPIRITS' /
 hh_j02_1
     1 'KILOGRAM'
     2 'GRAM'
     3 'LITRE'
     4 'MILILITRE'
     5 'PIECE' /
 hh_j03_1
     1 'KILOGRAM'
     2 'GRAM'
     3 'LITRE'
     4 'MILILITRE'
     5 'PIECE' /
 hh_j03_2
     0 'HAKUNA' /
 hh_j05_1
     1 'KILOGRAM'
     2 'GRAM'
     3 'LITRE'
     4 'MILILITRE'
     5 'PIECE' /
 hh_j05_2
     0 'HAKUNA' /
 hh_j06_1
     1 'KILOGRAM'
     2 'GRAM'
     3 'LITRE'
     4 'MILILITRE'
     5 'PIECE' /
 hh_j06_2
     0 'NONE' /
 j1_selection
     1 'YES'
     2 'NO' / .


SAVE OUTFILE='.\hh_sec_j1.sav'.
