/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_k.dat" ENCODING="CP1252" / LRECL=33 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        itemcode 23-25        
   hh_k01 26                hh_k02 27-33 .        

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   itemcode 'Item Code'
   hh_k01    'Over the past 7 days (101-103)/30 days (201-223) did you purchase' +
   ' any [ITEM]?'
   hh_k02 'How much did you pay in total?' .

VALUE LABELS
 itemcode
     101 'CIGARETTES OR TOBACCO'
     102 'MATCHES'
     103 'PUBLIC TRANSPORT'
     201 'KEROSENE'
     202 'ELECTRICITY, INCLUDING ELECTRICITY VOUCHERS'
     203 'GAS (FOR LIGHTING/COOKING)'
     204 'WATER'
     205 'PETROL OR DIESEL'
     206 'CELL PHONE VOUCHER'
     207 'CHARCOAL'
     208 'MILLING FEES, GRAIN'
     209 'BAR SOAP (BODY SOAP OR CLOTHES SOAP)'
     210 'CLOTHES SOAP (POWDER)'
     211 'TOOTHPASTE, TOOTHBRUSH'
     212 'TOILET PAPER'
     213 'GLYCERINE, VASELINE, SKIN CREAMS'
     214 'OTHER PERSONAL PRODUCTS (SHAMPOO, RAZORBLADES, COSMETICS, HAIR PRODUCTS, ETC.)'
     215 'HOUSEHOLD CLEANING PRODUCTS (DISH SOAP, TOILET CLEANSERS, ETC.)'
     216 'LIGHT BULBS'
     217 'PHONE, INTERNET, POSTAGE STAMPS OR OTHER POSTAL FEES'
     218 'DONATION - TO CHURCH, CHARITY, BEGGAR, ETC.'
     219 'MOTOR VEHICLE SERVICE, REPAIR, OR PARTS'
     220 'BICYCLE SERVICE, REPAIR, OR PARTS'
     221 'WAGES PAID TO SERVANTS'
     222 'MORTGAGE - REGULAR PAYMENT TO PURCHASE HOUSE'
     223 'REPAIRS TO HOUSEHOLD AND PERSONAL ITEMS (RADIOS, WATCHES, ETC.)' /
 hh_k01
     1 'YES'
     2 'NO' / .


SAVE OUTFILE='.\hh_sec_k.sav'.
