/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_l.dat" ENCODING="CP1252" / LRECL=49 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        itemcode 23-25        
   hh_l01 26                hh_l02a 27-35            hh_l02b 36-42         
   hh_l03 43-49 .        

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   itemcode 'Item Code'
   hh_l01    'Over the past 12 months did you gather, purchase, or pay for any ' +
   '[...]?'
   hh_l02a 'How much did you pay in total? (TSH)'
   hh_l02b 'What was the estimated total value of [ITEM] consumed? (TSH)'
   hh_l03 'What was the cost of that which you purchased? (TSH)' .

VALUE LABELS
 itemcode
     301 'CARPET, RUGS, DRAPES, CURTAINS'
     302 'LINEN - TOWELS, SHEETS, BLANKETS'
     303 'MAT - SLEEPING OR FOR DRYING MAIZE FLOUR'
     304 'MOSQUITO NET'
     305 'MATTRESS'
     306 'SPORTS & HOBBY EQUIPMENT, MUSICAL INSTRUMENTS, TOYS'
     307 'FILM, FILM PROCESSING, CAMERA'
     308 'BUILDING ITEMS - CEMENT, BRICKS, TIMBER, IRON SHEETS, TOOLS, ETC.'
     309 'COUNCIL RATES'
     310 'INSURANCE - HEALTH (MASM, ETC.), AUTO,  HOME, LIFE'
     311 'LOSSES TO THEFT (VALUE OF ITEMS OR CASH LOST)'
     312 'FINES OR LEGAL FEES'
     313 'BRIDE PRICE/MARRIAGE COSTS'
     314 'FUNERAL COSTS'
     315 'OTHER COSTS NOT STATED ELSEWHERE'
     316 'REPAIRS TO CONSUMER DURABLES'
     317 'TAXES FOR INCOME, PROPERTY, ETC.'
     318 'REPAIRS & MAINTENANCE TO DWELLING'
     319 'GARMENTS FOR MEN'
     320 'GARMENTS FOR WOMEN'
     321 'GARMENTS FOR CHILDREN & BABIES'
     322 'FOOTWEAR FOR MEN'
     323 'FOOTWEAR FOR WOMEN'
     324 'FOOTWEAR FOR CHILDREN AND BABIES'
     325 'WOOD POLES, BAMBOO'
     326 'GRASS FOR THATCHING ROOF OR OTHER USE'
     1001 'HOUSEHOLD CONTRIBUTIONS TO INFORMAL SOCIAL SECURITY INSTITUTIONS'
     1002 'CONTRIBUTIONS TO COMMUNITY DEVELOPMENT ACTIVITIES'
     1003 'CONTRIBUTIONS TO SOCIAL AND POLITICAL ACTIVITIES' /
 hh_l01
     1 'YES'
     2 'NO' / .


SAVE OUTFILE='.\hh_sec_l.sav'.
