/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_q1.dat" ENCODING="CP1252" / LRECL=85 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        hh_q01_1 23           
   hh_q01_2 24              hh_q01_3 25              hh_q01_4 26           
   hh_q01_5 27              hh_q01_6 28              hh_q02 29             
   hh_q03_1 30              hh_q03_2 31              hh_q03_3 32           
   hh_q03_4 33              hh_q03_5 34              hh_q03_6 35           
   hh_q03_7 36              hh_q03_8 37              hh_q03_9 38           
   hh_q04 39                hh_q05_1 40-41           hh_q05_2 42-43        
   hh_q06 44-51             hh_q07 52-59             hh_q08 60-67          
   hh_q09_1 68              hh_q09_2 69              hh_q09_3 70           
   hh_q10 71                hh_q11_1 72-73           hh_q11_2 74-75        
   hh_q11_3 76-77           hh_q12 78-81             hh_q13_1 82           
   hh_q13_2 83              hh_q13_3 84              hh_q14 85 .           

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   hh_q01_1 'M-PESA'
   hh_q01_2 'EZY-PESA (Z-PESA)'
   hh_q01_3 'AIRTEL (ZAP)'
   hh_q01_4 'TIGO PESA'
   hh_q01_5 'T PESA'
   hh_q01_6 'HALLO PESA'
   hh_q02 'How often does your household use this service?'
   hh_q03_1 'Did you use this service to buy airtime for yourself'
   hh_q03_2 'Did you use this service to buy airtime for someone else'
   hh_q03_3 'Did you use this service to send money'
   hh_q03_4 'Did you use this service to receive money'
   hh_q03_5    'Did you use this service to have someone pay you for a good or se' +
   'rvice'
   hh_q03_6 'Did you use this service to store/save for emergencies'
   hh_q03_7    'Did you use this service to store/save for other everyday expense' +
   's'
   hh_q03_8    'Did you use this service to store/save money for unusually large ' +
   'purchases'
   hh_q03_9 'Did you use this service as credit?'
   hh_q04 'Which of these was the most important use of this service?'
   hh_q05_1 'Which is the household main source of cash income? 1ST SOURCE'
   hh_q05_2 'Which is the household main source of cash income? 2ND SOURCE'
   hh_q06    'What is the total amount of income your household has received in' +
   ' the form of re'
   hh_q07    'What is the total amount of income your household has received in' +
   ' the form of pr'
   hh_q08    'What is the total amount of income your household has received in' +
   ' the form of ot'
   hh_q09_1    'What was the type of other income that your household received in' +
   ' the last 12 mo'
   hh_q09_2    'What was the type of other income that your household received in' +
   ' the last 12 mo'
   hh_q09_3    'What was the type of other income that your household received in' +
   ' the last 12 mo'
   hh_q10    'Do you or anyone else in your household have a bank account, eith' +
   'er with a comme'
   hh_q11_1    'Please list up to 3 institutions with whom you or a member of you' +
   'r household has'
   hh_q11_2    'Please list up to 3 institutions with whom you or a member of you' +
   'r household has'
   hh_q11_3    'Please list up to 3 institutions with whom you or a member of you' +
   'r household has'
   hh_q12 'In what year did you open your first bank account?'
   hh_q13_1 'Why do you not have a bank account? 1ST'
   hh_q13_2 'Why do you not have a bank account? 2ND'
   hh_q13_3 'Why do you not have a bank account? 3RD'
   hh_q14    'Have you or anyone in your household received remittances or fina' +
   'ncial assistanc' .

VALUE LABELS
 hh_q01_1
     1 'YES'
     2 'NO' /
 hh_q01_2
     1 'YES'
     2 'NO' /
 hh_q01_3
     1 'YES'
     2 'NO' /
 hh_q01_4
     1 'YES'
     2 'NO' /
 hh_q01_5
     1 'YES'
     2 'NO' /
 hh_q01_6
     1 'YES'
     2 'NO' /
 hh_q02
     1 'DAILY'
     2 'WEEKLY'
     3 'EVERY 2 WEEKS'
     4 'MONTHLY'
     5 'EVERY 3 MONTHS'
     6 'EVERY 6 MONTHS'
     7 'LESS OFTEN'
     8 'NEVER' /
 hh_q03_1
     1 'YES'
     2 'NO' /
 hh_q03_2
     1 'YES'
     2 'NO' /
 hh_q03_3
     1 'YES'
     2 'NO' /
 hh_q03_4
     1 'YES'
     2 'NO' /
 hh_q03_5
     1 'YES'
     2 'NO' /
 hh_q03_6
     1 'YES'
     2 'NO' /
 hh_q03_7
     1 'YES'
     2 'NO' /
 hh_q03_8
     1 'YES'
     2 'NO' /
 hh_q03_9
     1 'YES'
     2 'NO' /
 hh_q04
     1 'Buy airtime for yourself'
     2 'Buy airtime for someone else'
     3 'Send money'
     4 'Receive money'
     5 'Have someone pay you for a good or service'
     6 'Store/ save for emergencies'
     7 'Store/save for other everyday expenses'
     8 'Store/save money for unusually large purchases'
     9 'Credit' /
 hh_q05_1
     1 'SALE OF FOOD CROPS'
     2 'SALE OF LIVESTOCK'
     3 'SALE OF LIVESTOCK PRODUCTS'
     4 'SALE OF CASH CROPS'
     5 'BUSINESS INCOME'
     6 'WAGES OR SALARIES IN CASH'
     7 'OTHER CASUAL CASH EARNINGS'
     8 'CASH REMITTANCES'
     9 'FISHING'
     10 'OTHER (SPECIFY)' /
 hh_q05_2
     1 'SALE OF FOOD CROPS'
     2 'SALE OF LIVESTOCK'
     3 'SALE OF LIVESTOCK PRODUCTS'
     4 'SALE OF CASH CROPS'
     5 'BUSINESS INCOME'
     6 'WAGES OR SALARIES IN CASH'
     7 'OTHER CASUAL CASH EARNINGS'
     8 'CASH REMITTANCES'
     9 'FISHING'
     10 'OTHER (SPECIFY)' /
 hh_q06
     0 'NONE' /
 hh_q07
     0 'NONE' /
 hh_q08
     0 'NONE' /
 hh_q09_1
     1 'SAVINGS, INTEREST OR INVESTMENT'
     2 'REAL ESTATE SALES'
     3 'NON-AGRICULTURAL ASSET SALES'
     4 'AGRICULTURAL/FISHING ASSET SALES'
     5 'INHERITANCE'
     6 'LOTTERY/GAMBLING'
     7 'OTHER (SPECIFY)' /
 hh_q09_2
     1 'SAVINGS, INTEREST OR INVESTMENT'
     2 'REAL ESTATE SALES'
     3 'NON-AGRICULTURAL ASSET SALES'
     4 'AGRICULTURAL/FISHING ASSET SALES'
     5 'INHERITANCE'
     6 'LOTTERY/GAMBLING'
     7 'OTHER (SPECIFY)' /
 hh_q09_3
     1 'SAVINGS, INTEREST OR INVESTMENT'
     2 'REAL ESTATE SALES'
     3 'NON-AGRICULTURAL ASSET SALES'
     4 'AGRICULTURAL/FISHING ASSET SALES'
     5 'INHERITANCE'
     6 'LOTTERY/GAMBLING'
     7 'OTHER (SPECIFY)' /
 hh_q10
     1 'YES'
     2 'NO' /
 hh_q11_1 hh_q11_2 hh_q11_3
     1 'AKIBA COMMERCIAL BANK (ACB)'
     2 'ACCESS BANK'
     3 'AMANA BANK'
     4 'AZANIA BANK'
     5 'BARCLAYS'
     6 'BANK OF AFRICA (BOA)'
     7 'BRAC'
     8 'CRDB'
     9 'DIAMOND TRUST BANK (DTB)'
     10 'EQUITY BANK'
     11 'EXIM BANK'
     12 'FINCA'
     13 'FNB'
     14 'KCB'
     15 'MKOMBOZI BANK'
     16 'NMB'
     17 'NBC'
     18 'PBZ ISLAMIC BANK'
     19 'POSTA BANK'
     20 'PRIDE'
     21 'STANBIC BANK'
     22 'STANDARD CHARTER'
     23 'UMOJA BANK'
     24 'VIKOBA'
     25 'OTHER (SPECIFY)' /
 hh_q13_1
     1 'NO MONEY TO SAVE'
     2 'DO NOT TRUST FINANCIAL INSTITUTIONS'
     3 'DIFFICULT TO PRODUCE REQUIRED DOCUMENTATION (ID CARD, ETC)'
     4 "USE SOMEONE ELSE'S ACCOUNT"
     5 'TOO FAR AWAY'
     6 "DON'T WANT TO PAY USERS FEES"
     7 'OTHER (SPECIFY)' /
 hh_q13_2
     1 'NO MONEY TO SAVE'
     2 'DO NOT TRUST FINANCIAL INSTITUTIONS'
     3 'DIFFICULT TO PRODUCE REQUIRED DOCUMENTATION (ID CARD, ETC)'
     4 "USE SOMEONE ELSE'S ACCOUNT"
     5 'TOO FAR AWAY'
     6 "DON'T WANT TO PAY USERS FEES"
     7 'OTHER (SPECIFY)' /
 hh_q13_3
     1 'NO MONEY TO SAVE'
     2 'DO NOT TRUST FINANCIAL INSTITUTIONS'
     3 'DIFFICULT TO PRODUCE REQUIRED DOCUMENTATION (ID CARD, ETC)'
     4 "USE SOMEONE ELSE'S ACCOUNT"
     5 'TOO FAR AWAY'
     6 "DON'T WANT TO PAY USERS FEES"
     7 'OTHER (SPECIFY)' /
 hh_q14
     1 'YES'
     2 'NO' / .


SAVE OUTFILE='.\hh_sec_q1.sav'.
