/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_q2.dat" ENCODING="CP1252" / LRECL=81 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        hh_q14 23             
   sourceid 24              hh_q15 25-40 (A)         hh_q16 41-42          
   hh_q17 43-44             hh_q18 45                hh_q19 46-47          
   hh_q20 48-49             hh_q21_1 50              hh_q21_2 51-52        
   hh_q22_1 53-54           hh_q22_2 55-56           hh_q22_3 57-58        
   hh_q23 59-65             hh_q25_1 66              hh_q25_2 67-68        
   hh_q26 69-75             hh_q27_1 76              hh_q27_2 77-78        
   hh_q24_1 79              hh_q24_2 80              hh_q24_3 81 .         

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   hh_q14    'Have you or anyone in your household received remittances or fina' +
   'ncial assistanc'
   sourceid 'Source ID'
   hh_q15 'What is the name of [SOURCE]?'
   hh_q16 'What is the relationship of [SOURCE] to the household head?'
   hh_q17 'How old is [SOURCE]?'
   hh_q18 'Sex of [SOURCE]?'
   hh_q19 'What is the highest grade completed by [SOURCE]?'
   hh_q20 'From what location did [SOURCE] send these remittances?'
   hh_q21_1 'How long has [SOURCE] lived in his/her present location? (UNIT)'
   hh_q21_2    'How long has [SOURCE] lived in his/her present location? (NUMBER)'
   hh_q22_1    'Which of the following remittances channels did [SOURCE] use in t' +
   'he past 12 mont'
   hh_q22_2    'Which of the following remittances channels did [SOURCE] use in t' +
   'he past 12 mont'
   hh_q22_3    'Which of the following remittances channels did [SOURCE] use in t' +
   'he past 12 mont'
   hh_q23    'How much in total did you receive in cash from [SOURCE] during th' +
   'e last 12 month'
   hh_q25_1    'Who in the household decides on the use of thes cash send by [SOU' +
   'RCE] in the las'
   hh_q25_2    'Who in the household decides on the use of thes cash send by [SOU' +
   'RCE] in the las'
   hh_q26    'What is the total value of all those items which you received in ' +
   'kind in the las'
   hh_q27_1    'Who in the household decides on the use of the in-kind items sent' +
   ' by [SOURCE] in'
   hh_q27_2    'Who in the household decides on the use of the in-kind items sent' +
   ' by [SOURCE] in'
   hh_q24_1    'For what did you or anyone in your household use the cash sent fr' +
   'om [SOURCE] in '
   hh_q24_2    'For what did you or anyone in your household use the cash sent fr' +
   'om [SOURCE] in '
   hh_q24_3    'For what did you or anyone in your household use the cash sent fr' +
   'om [SOURCE] in ' .

VALUE LABELS
 hh_q14
     1 'YES'
     2 'NO' /
 hh_q16
     1 'SPOUSE'
     2 'PARENT'
     3 'DAUGHTER'
     4 'SON'
     5 'SISTER'
     6 'BROTHER'
     7 'OTHER RELATIVE'
     8 'BUSINESS ASSOCIATE'
     9 'FRIEND'
     10 'OTHER, SPECIFY'
     11 'IN LAW'
     12 'NGO OR RELIGIOUS INSTITUTION' /
 hh_q18
     1 'MALE'
     2 'FEMALE' /
 hh_q19
     1 'PP'
     2 'ADULT'
     11 'D1'
     12 'D2'
     13 'D3'
     14 'D4'
     15 'D5'
     16 'D6'
     17 'D7'
     18 'D8'
     19 'OSC'
     20 'MS+COURSE'
     21 'F1'
     22 'F2'
     23 'F3'
     24 'F4'
     25 "'O'+COURSE"
     31 'F5'
     32 'F6'
     33 "'A'+COURSE"
     34 'DIPLOMA'
     41 'U1'
     42 'U2'
     43 'U3'
     44 'U4'
     45 'U5 & +'
     46 'NO EDUCATION' /
 hh_q20
     1 'DODOMA'
     2 'ARUSHA'
     3 'KILIMANJARO'
     4 'TANGA'
     5 'MOROGORO'
     6 'PWANI'
     7 'DAR ES SALAAM'
     8 'LINDI'
     9 'MTWARA'
     10 'RUVUMA'
     11 'IRINGA'
     12 'MBEYA'
     13 'SINGIDA'
     14 'TABORA'
     15 'RUKWA'
     16 'KIGOMA'
     17 'SHINYANGA'
     18 'KAGERA'
     19 'MWANZA'
     20 'MARA'
     21 'MANYARA'
     22 'NJOMBE'
     23 'KATAVI'
     24 'SIMIYU'
     25 'GEITA'
     26 'SONGWE'
     51 'KASKAZINI UNGUJA'
     52 'KUSINI UNGUJA'
     53 'MJINI/MAGHARIBI UNGUJA'
     54 'KASKAZINI PEMBA'
     55 'KUSINI PEMBA'
     61 'INTERNATIONAL: USA'
     62 'INTERNATIONAL: UK'
     63 'INTERNATIONAL: UAE'
     64 'INTERNATIONAL: SOUTH AFRICA'
     65 'INTERNATIONAL: JAPAN'
     66 'INTERNATIONAL: INDIA'
     67 'INTERNATIONAL: KENYA'
     68 'INTERNATIONAL: UGANDA'
     69 'INTERNATIONAL: GERMANY'
     70 'INTERNATIONAL: CANADA'
     71 'OTHER, SPECIFY' /
 hh_q22_1
     1 'BANK ACCOUNT'
     2 'WESTERN UNION'
     3 'MONEYGRAM'
     4 'POST OFFICE'
     5 'FRIENDS/RELATIVES'
     6 'M-PESA'
     7 'TIGO PESA'
     8 'EZY PESA'
     9 'AIRTEL MONEY'
     10 'OTHER (SPECIFY)' /
 hh_q22_2
     1 'BANK ACCOUNT'
     2 'WESTERN UNION'
     3 'MONEYGRAM'
     4 'POST OFFICE'
     5 'FRIENDS/RELATIVES'
     6 'M-PESA'
     7 'TIGO PESA'
     8 'EZY PESA'
     9 'AIRTEL MONEY'
     10 'OTHER (SPECIFY)' /
 hh_q22_3
     1 'BANK ACCOUNT'
     2 'WESTERN UNION'
     3 'MONEYGRAM'
     4 'POST OFFICE'
     5 'FRIENDS/RELATIVES'
     6 'M-PESA'
     7 'TIGO PESA'
     8 'EZY PESA'
     9 'AIRTEL MONEY'
     10 'OTHER (SPECIFY)' /
 hh_q26
     0 'NONE' /
 hh_q24_1
     1 'HOUSEHOLD CONSUMPTION'
     2 'EDUCATION'
     3 'HEALTH'
     4 'INVESTMENT'
     5 'BUSINESS'
     6 'FARMING'
     7 'CEREMONY'
     8 'OTHER (SPECIFY)' /
 hh_q24_2
     1 'HOUSEHOLD CONSUMPTION'
     2 'EDUCATION'
     3 'HEALTH'
     4 'INVESTMENT'
     5 'BUSINESS'
     6 'FARMING'
     7 'CEREMONY'
     8 'OTHER (SPECIFY)' /
 hh_q24_3
     1 'HOUSEHOLD CONSUMPTION'
     2 'EDUCATION'
     3 'HEALTH'
     4 'INVESTMENT'
     5 'BUSINESS'
     6 'FARMING'
     7 'CEREMONY'
     8 'OTHER (SPECIFY)' / .


SAVE OUTFILE='.\hh_sec_q2.sav'.
