/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_d.dat" ENCODING="CP1252" / LRECL=178 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        indidy5 23-24         
   hh_d01 25                hh_d01_1 26-27           hh_d02 28             
   hh_d03_1 29-30           hh_d03_2 31-32           provider1 33-48 (A)   
   provider2 49-64 (A)      hh_d04_1 65              hh_d04_2 66           
   hh_d05_1 67-73           hh_d05_2 74-79           hh_d06_1 80           
   hh_d06_2 81              hh_d07 82-88             hh_d08 89-94          
   hh_d09 95-100            hh_d10 101               hh_d11_1 102-103      
   hh_d11_2 104-106         hh_d12_1 107-108         hh_d12_2 109-110      
   hh_d13 111-117           hh_d14 118               hh_d15 119-124        
   hh_d16 125               hh_d17 126               hh_d18 127-128        
   hh_d19 129               hh_d20 130-131           hh_d21 132            
   hh_d22 133-135           hh_d23 136               hh_d24 137-139        
   hh_d25 140               hh_d26 141-143           hh_d27 144            
   hh_d28 145-146           hh_d29_1 147             hh_d29_2 148          
   hh_d29_3 149             hh_d30 150-151           hh_d31 152            
   hh_d32 153               hh_d33 154-159           hh_d34 160            
   hh_d35 161               hh_d36 162               hh_d36a 163-164       
   hh_d37 165               hh_d38 166               hh_d39 167            
   hh_d40 168               hh_d41 169               hh_d42 170            
   hh_d43 171               hh_d44 172               hh_d45 173            
   hh_d46 174               hh_d47 175               hh_d48 176            
   hh_d49 177-178 .      

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   indidy5 'Individual ID'
   hh_d01 'Is this person answering for himself/herself?'
   hh_d01_1 'Who is reporting the information for the individual?'
   hh_d02 'Has [NAME] visited a health care provider in the last 4 weeks?'
   hh_d03_1 'What type of 1ST health provider did [NAME] visit?'
   hh_d03_2 'What type of 2ND health provider did [NAME] visit?'
   provider1 'First health provider'
   provider2 'Second health provider'
   hh_d04_1 'How was the 1ST treatment financed?'
   hh_d04_2 'How was the 2ND treatment financed?'
   hh_d05_1 'How much did [NAME] spend visiting the 1ST health provider?'
   hh_d05_2 'How much did [NAME] spend visiting the 2ND health provider?'
   hh_d06_1    'Did [NAME] have any problems during the visit to the 1ST health p' +
   'rovider?'
   hh_d06_2    'Did [NAME] have any problems during the visit to the 2ND health p' +
   'rovider?'
   hh_d07    'How much in total did the household spend on [NAME] in the past 4' +
   ' weeks for all '
   hh_d08    'How much in total did the household spend on [NAME] in the past 4' +
   ' weeks for medi'
   hh_d09    'How much in total did the household spend on [NAME] in the past 4' +
   ' weeks for non-'
   hh_d10    'During the last 12 months, was [NAME] hospitalized or did [NAME] ' +
   'have an overnig'
   hh_d11_1 'How many stays was [NAME] hospitalized?'
   hh_d11_2 'For how many total nights was [NAME] hospitalized?'
   hh_d12_1 '[1ST] Illness or injury that led [NAME] to hospitalization'
   hh_d12_2 '[1ST] Illness or injury that led [NAME] to hospitalization'
   hh_d13    "What was the total cost of [NAME]'s hospitalization(s) or overnig" +
   'ht stay(s) in a'
   hh_d14    'During the last 12 months, did [NAME] stay overnight(s) at a trad' +
   'itional or fait'
   hh_d15    "What was the total cost of [NAME]'s stay(s) at the traditional or" +
   ' faith healer?'
   hh_d16    'CAPI: Is the respondent a child of under 5 years old? (less than ' +
   '60 months)'
   hh_d17    'Does [NAME] have difficulty seeing, even if he/she is wearing gla' +
   'sses?'
   hh_d18 'How old was [NAME] when the difficulty seeing began?'
   hh_d19    'Does [NAME] have difficulty hearing, even if he/she is wearing a ' +
   'hearing aid?'
   hh_d20 'How old was [NAME] when the difficulty hearing began?'
   hh_d21 'Does [NAME] have difficulty walking or climbing steps?'
   hh_d22    'How old was [NAME] when the difficulty walking or climbing stairs' +
   ' began?'
   hh_d23 'Does [NAME] have difficulty remembering or concentrating?'
   hh_d24    'How old was [NAME] when the difficulty remembering or concentrati' +
   'ng began?'
   hh_d25    'Does [NAME] have difficulty with self care (such as washing all o' +
   'ver or dressing'
   hh_d26 'How old was [NAME] when the difficulty began?'
   hh_d27    'Using their usual language, does [NAME] have difficulty communica' +
   'ting?'
   hh_d28 'How old was [NAME] when the difficulty communicating began?'
   hh_d29_1    'Does this difficulty reduce the amount of work [NAME] can do at h' +
   'ome?'
   hh_d29_2    'Does this difficulty reduce the amount of work [NAME] can do at s' +
   'chool?'
   hh_d29_3    'Does this difficulty reduce the amount of work [NAME] can do at w' +
   'ork?'
   hh_d30    'During the past 12 months, what measures were taken to improve [N' +
   "AME]'s performa"
   hh_d31 'Did [NAME] sleep under a bednet yesterday?'
   hh_d32 'How did the household obtain this bednet?'
   hh_d33 'How much did the household pay for the bednet?'
   hh_d34 'Does [NAME] possess their birth certificate?'
   hh_d35    'In the last year, did [NAME] access a medical exemption at a publ' +
   'ic health facil'
   hh_d36 'CAPI: Is the respondent a woman aged 12 to 49 years?'
   hh_d36a 'Is [NAME] currently pregnant?'
   hh_d37    'In the past 24 months, did [NAME] give birth to a child, even if ' +
   'born dead?'
   hh_d38    'Did [NAME] regularly go to a health clinic when she was pregnant ' +
   'with her last c'
   hh_d39    "Where did [NAME] deliver [NAME]'s last child born in the last 24 " +
   'months?'
   hh_d40 'Who delivered this child?'
   hh_d41 'Was this birth registered with civil authorities?'
   hh_d42    'CAPI: Is the respondent a child of under 5 years old (less than 6' +
   '0 months old)?'
   hh_d43 'Has [NAME] had diarrhea in the last two weeks?'
   hh_d44    'When [NAME] had diarrhea, was he/she offered less than usual to d' +
   'rink, about the'
   hh_d45    'When [NAME] had diarrhea, was he/she offered less than usual to e' +
   'at, about the s'
   hh_d46 'Was he/she given any Oral Rehydration Salts (ORS) to drink?'
   hh_d47    'Was he/she given any health-worker recommended home-made fluid to' +
   ' drink?'
   hh_d48 'Did [NAME] seek advice or treatment for the diarrhea?'
   hh_d49 'Where did [NAME] seek advice or treatment?' .

VALUE LABELS
 hh_d01
     1 'YES'
     2 'NO' /
 hh_d02
     1 'YES'
     2 'NO' /
 hh_d03_1
     1 'GOV PARASTATAL: REFERRAL/SPEC HOSP'
     2 'GOV PARASTATAL: REGIONAL HOSPITAL'
     3 'GOV PARASTATAL: DISTRICT HOSPITAL'
     4 'GOV PARASTATAL: HEALTH CENTER'
     5 'GOV PARASTATAL: DISPENSARY'
     6 'GOV PARASTATAL: VILLAGE HEALTH POST (WORKER)'
     7 'GOV PARASTATAL: CBD WORKER'
     8 'RELIGIOUS/VOLUNTARY: REFERRAL/SPEC HOSP'
     9 'RELIGIOUS/VOLUNTARY: DISTRICT HOSPITAL'
     10 'RELIGIOUS/VOLUNTARY: HEALTH CENTER'
     11 'RELIGIOUS/VOLUNTARY DISPENSARY'
     12 'PRIVATE: SPECIALISED HOSPITAL'
     13 'PRIVATE: HEALTH CENTER'
     14 'PRIVATE: DISPENSARY'
     15 'OTHER: PHARMACY'
     16 'OTHER: NGO'
     17 'OTHER (SPECIFY)' /
 hh_d03_2
     1 'GOV PARASTATAL: REFERRAL/SPEC HOSP'
     2 'GOV PARASTATAL: REGIONAL HOSPITAL'
     3 'GOV PARASTATAL: DISTRICT HOSPITAL'
     4 'GOV PARASTATAL: HEALTH CENTER'
     5 'GOV PARASTATAL: DISPENSARY'
     6 'GOV PARASTATAL: VILLAGE HEALTH POST (WORKER)'
     7 'GOV PARASTATAL: CBD WORKER'
     8 'RELIGIOUS/VOLUNTARY: REFERRAL/SPEC HOSP'
     9 'RELIGIOUS/VOLUNTARY: DISTRICT HOSPITAL'
     10 'RELIGIOUS/VOLUNTARY: HEALTH CENTER'
     11 'RELIGIOUS/VOLUNTARY DISPENSARY'
     12 'PRIVATE: SPECIALISED HOSPITAL'
     13 'PRIVATE: HEALTH CENTER'
     14 'PRIVATE: DISPENSARY'
     15 'OTHER: PHARMACY'
     16 'OTHER: NGO'
     17 'OTHER (SPECIFY)' /
 hh_d04_1
     1 'FREE TREATMENT'
     2 'HEALTH INSURANCE'
     3 'OWN CASH'
     4 'HAD TO WORK FOR PROVIDER'
     5 'USE OF ASSET'
     6 'TOOK LOAN'
     7 'GOT ASSISTANCE'
     8 'DIFFERED BY PROVIDER'
     9 'OTHER (SPECIFY)' /
 hh_d04_2
     1 'FREE TREATMENT'
     2 'HEALTH INSURANCE'
     3 'OWN CASH'
     4 'HAD TO WORK FOR PROVIDER'
     5 'USE OF ASSET'
     6 'TOOK LOAN'
     7 'GOT ASSISTANCE'
     8 'DIFFERED BY PROVIDER'
     9 'OTHER (SPECIFY)' /
 hh_d05_1
     0 'NONE/FREE' /
 hh_d05_2
     0 'HAKUNA' /
 hh_d06_1
     1 'NO PROBLEMS (SATISFIED)'
     2 'POOR BUILDING/TOOLS'
     3 'LONG WAITING TIME'
     4 'INADEQUATE TRAINED STAFF'
     5 'TOO EXPENSIVE'
     6 'LACK OF MEDICINE'
     7 'OTHER (SPECIFY)' /
 hh_d06_2
     1 'NO PROBLEMS (SATISFIED)'
     2 'POOR BUILDING/TOOLS'
     3 'LONG WAITING TIME'
     4 'INADEQUATE TRAINED STAFF'
     5 'TOO EXPENSIVE'
     6 'LACK OF MEDICINE'
     7 'OTHER (SPECIFY)' /
 hh_d07
     0 'NONE' /
 hh_d08
     0 'NONE' /
 hh_d09
     0 'NONE' /
 hh_d10
     1 'YES'
     2 'NO' /
 hh_d12_1 hh_d12_2
     1 'FEVER'
     2 'MALARIA'
     3 'STOMACH'
     4 'DIARRHEA'
     5 'HEADACHE'
     6 'HEART'
     7 'LUNG'
     8 'BROKEN BONE'
     9 'MATERNITY/PREGNANCY/DELIVERY'
     10 'HIV/ADIS/STD'
     11 'TUBERCULOSIS'
     12 'ACCIDENT'
     13 'OTHER (SPECIFY)' /
 hh_d13
     0 'NONE' /
 hh_d14
     1 'YES'
     2 'NO' /
 hh_d16
     1 'YES'
     2 'NO' /
 hh_d17
     1 'NO, NOT AT ALL'
     2 'NO, NO DIFFICULTY WITH ASSISTIVE DEVICE'
     3 'YES, SOME DIFFICULTY'
     4 'YES, A LOT OF DIFFICULTY'
     5 'CANNOT PERFORM' /
 hh_d18
     0 'LESS THAN 1 YEAR OLD' /
 hh_d19
     1 'NO, NOT AT ALL'
     2 'NO, NO DIFFICULTY WITH ASSISTIVE DEVICE'
     3 'YES, SOME DIFFICULTY'
     4 'YES, A LOT OF DIFFICULTY'
     5 'CANNOT PERFORM' /
 hh_d20
     0 'LESS THAN 1 YEAR OLD' /
 hh_d21
     1 'NO, NOT AT ALL'
     2 'NO, NO DIFFICULTY WITH ASSISTIVE DEVICE'
     3 'YES, SOME DIFFICULTY'
     4 'YES, A LOT OF DIFFICULTY'
     5 'CANNOT PERFORM' /
 hh_d22
     0 'LESS THAN 1 YEAR OLD' /
 hh_d23
     1 'NO, NOT AT ALL'
     2 'NO, NO DIFFICULTY WITH ASSISTIVE DEVICE'
     3 'YES, SOME DIFFICULTY'
     4 'YES, A LOT OF DIFFICULTY'
     5 'CANNOT PERFORM' /
 hh_d24
     0 'LESS THAN 1 YEAR OLD' /
 hh_d25
     1 'NO, NOT AT ALL'
     2 'NO, NO DIFFICULTY WITH ASSISTIVE DEVICE'
     3 'YES, SOME DIFFICULTY'
     4 'YES, A LOT OF DIFFICULTY'
     5 'CANNOT PERFORM' /
 hh_d26
     0 'LESS THAN 1 YEAR OLD' /
 hh_d27
     1 'NO, NOT AT ALL'
     2 'NO, NO DIFFICULTY WITH ASSISTIVE DEVICE'
     3 'YES, SOME DIFFICULTY'
     4 'YES, A LOT OF DIFFICULTY'
     5 'CANNOT PERFORM' /
 hh_d28
     0 'LESS THAN 1 YEAR OLD' /
 hh_d29_1
     1 'YES, ALL THE TIME'
     2 'YES, SOMETIMES'
     3 'NO' /
 hh_d29_2
     1 'YES, ALL THE TIME'
     2 'YES, SOMETIMES'
     3 'NO'
     4 'N/A (IF NOT WORKING OR ATTENDING SCHOOL)' /
 hh_d29_3
     1 'YES, ALL THE TIME'
     2 'YES, SOMETIMES'
     3 'NO'
     4 'N/A (IF NOT WORKING OR ATTENDING SCHOOL)' /
 hh_d30
     1 'NONE'
     2 'SURGICAL OPERATION'
     3 'MEDICATION'
     4 'ASSISTIVE DEVICES (GLASSES, WHEELCHAIR, BRACES, HEARING AID, ARTIFICIAL LIMB)'
     5 'SPECIAL EDUCATION'
     6 'SKILLS TRAINING (VOCATIONAL)'
     7 'ACTIVITY OF DAILY LIVING (ADL) TRAINING'
     8 'COUNSELING'
     9 'SPIRITUAL/TRADITIONAL'
     10 'OTHER (SPECIFY)' /
 hh_d31
     1 'YES, UNTREATED NET'
     2 'YES, TREATED NET < 6 MONTHS'
     3 'YES, TREATED NET > 6 MONTHS'
     4 'NO'
     5 'DONT KNOW'
     6 'YES, DONT KNOW IF IS A TREATED NET' /
 hh_d32
     1 'FREE GIFT'
     2 'PURCHASED'
     3 'PURCHASED WITH VOUCHER' /
 hh_d34
     1 'HAS CERTIFICATE'
     2 'REGISTERED'
     3 'NEITHER'
     4 "DON'T KNOW" /
 hh_d35
     1 'YES'
     2 'NO'
     3 "DON'T KNOW" /
 hh_d36
     1 'YES'
     2 'NO' /
 hh_d36a
     1 'YES'
     2 'NO'
     98 "DON'T KNOW" /
 hh_d37
     1 'YES'
     2 'NO' /
 hh_d38
     1 'YES'
     2 'NO' /
 hh_d39
     1 'HOSPITAL / MATERNITY'
     2 'CLINIC'
     3 'AT HOME'
     4 'HEALTH CENTRE'
     5 'DISPENSARY'
     6 'OTHER (SPECIFY)' /
 hh_d40
     1 'DOCTOR OR CLINICAL OFFICER'
     2 'NURSE'
     3 'MIDWIFE'
     4 'TRADITIONAL BIRTH ATTENDANT'
     5 'FRIEND OR RELATIVE'
     6 'SELF'
     7 'OTHER (SPECIFY)' /
 hh_d41
     1 'YES'
     2 'NO' /
 hh_d42
     1 'YES'
     2 'NO' /
 hh_d43
     1 'YES'
     2 'NO' /
 hh_d44
     1 'MUCH LESS'
     2 'SOMEWHAT LESS'
     3 'ABOUT THE SAME'
     4 'MORE'
     5 'NOTHING TO DRINK'
     6 "DON'T KNOW" /
 hh_d45
     1 'MUCH LESS'
     2 'SOMEWHAT LESS'
     3 'ABOUT THE SAME'
     4 'MORE'
     5 'NOTHING TO DRINK'
     6 "DON'T KNOW" /
 hh_d46
     1 'YES'
     2 'NO' /
 hh_d47
     1 'YES'
     2 'NO' /
 hh_d48
     1 'YES'
     2 'NO' /
 hh_d49
     1 'GOVT PARASTATAL: REFERRAL/SPEC HOSPITAL'
     2 'GOVT PARASTATAL: REGIONAL HOSPITAL'
     3 'GOVT PARASTATAL: DISTRICT HOSPITAL'
     4 'GOVT PARASTATAL: HEALTH CENTER'
     5 'GOVT PARASTATAL: DISPENSARY'
     6 'GOVT PARASTATAL: VILLAGE HEALTH POST (WORKER)'
     7 'GOVT PARASTATAL: CBD WORKER'
     8 'RELIGIOUS/VOLUNTARY: REFERRAL/SPEC HOSPITAL'
     9 'RELIGIOUS/VOLUNTARY: DISTRICT HOSPITAL'
     10 'RELIGIOUS/VOLUNTARY: HEALTH CENTER'
     11 'RELIGIOUS/VOLUNTARY: DISPENSARY'
     12 'PRIVATE: SPECIALISED HOSP'
     13 'PRIVATE: HEALTH CENTER'
     14 'PRIVATE: DISPENSARY'
     15 'OTHER: PHARMACY'
     16 'OTHER: NGO'
     17 'OTHER: OTHER, SPECIFY' / .


SAVE OUTFILE='.\hh_sec_d.sav'.
