/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_i2.dat" ENCODING="CP1252" / LRECL=26 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        hh_i201 23            
   hh_i202 24               hh_i203 25               hh_i204 26 .          

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   hh_i201    'Is there a place for household members to wash their hands in the' +
   ' dwelling, yard'
   hh_i202 'Where do members of this household wash their hands?'
   hh_i203 'Presence of water'
   hh_i204 'Presence of soap' .

VALUE LABELS
 hh_i201
     1 'YES'
     2 'NO' /
 hh_i202
     1 'OBSERVED: FIXED FACILITY (SINK / TAP) - IN DWELLING'
     2 'OBSERVED: FIXED FACILITY (SINK / TAP) - IN YARD / PLOT'
     3 'MOBILE OBJECT OBSERVED (BUCKET/JUG/KETTLE)'
     4 'NOT OBSERVED: NO HAND WASHING PLACE IN DWELLING/YARD'
     5 'NOT OBSERVED: NO PERMISSION TO SEE'
     6 'OTHER REASON, SPECIFY' /
 hh_i203
     1 'WATER IS AVAILABLE'
     2 'WATER IS NOT AVAILABLE' /
 hh_i204
     1 'YES, SOAP IS PRESENT'
     2 'NO, SOAP IS NOT PRESENT' / .


SAVE OUTFILE='.\hh_sec_i2.sav'.
