/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_m.dat" ENCODING="CP1252" / LRECL=55 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        itemcode 23-25        
   hh_m00 26                hh_m01 27-32             hh_m02 33-37          
   hh_m03 38-46             hh_m04 47-55 .        

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   itemcode 'Item Code'
   hh_m00 'Does your household own [ITEM]?'
   hh_m01 'How many [ITEMS] does your household own?'
   hh_m02 'What is the age of this [ITEM]?'
   hh_m03 'At what price did you purchase [ITEM]?'
   hh_m04    'If you wanted to sell one of this [ITEM] today, how much would yo' +
   'u receive?' .

VALUE LABELS
 itemcode
     401 'RADIO AND RADIO CASSETTE'
     402 'TELEPHONE(LANDLINE)'
     403 'TELEPHONE(MOBILE)'
     404 'REFRIDGERATOR OR FREEZER'
     405 'SEWING MACHINE'
     406 'TELEVISION'
     407 'VIDEO / DVD'
     408 'CHAIRS'
     409 'SOFAS'
     410 'TABLES'
     411 'WATCHES'
     412 'BEDS'
     413 'CUPBOARDS, CHEST-OF-DRAWERS, BOXES, WARDROBES, BOOKCASES'
     414 'LANTERNS'
     415 'COMPUTER'
     416 'COOKING POTS, CUPS, OTHER KITCHEN UTENSILS'
     417 'MOSQUITO NET'
     418 'IRON (CHARCOAL OR ELECTRIC)'
     419 'ELECTRIC/GAS STOVE'
     420 'OTHER STOVE'
     421 'WATER-HEATER'
     422 'RECORD/CASSETTE PLAYER, TAPE RECORDER'
     423 'COMPLETE MUSIC SYSTEM'
     424 'BOOKS (NOT SCHOOL BOOKS)'
     425 'MOTOR VEHICLES'
     426 'MOTORCYCLE'
     427 'BICYCLE'
     428 'CARTS'
     429 'ANIMAL-DRAWN CART'
     430 'BOAT/CANOE'
     431 'WHEEL BARROW'
     432 'LIVESTOCK'
     433 'POULTRY'
     434 'OUTBOARD ENGINE'
     435 'DONKEYS'
     436 'FIELDS/LAND'
     437 'HOUSE(S)'
     438 'FAN/AIR CONDITIONER'
     439 'DISH ANTENA/DECODER'
     440 'HOES'
     441 'SPRAYING MACHINE'
     442 'WATER PUMPING SET'
     443 'REAPERS'
     444 'TRACTOR'
     445 'TRAILER FOR TRACTORS ETC.'
     446 'PLOUGH ETC.'
     447 'HARROW'
     448 'MILKING MACHINE'
     449 'HARVESTING AND THRESHING MACHINE'
     450 'HAND MILLING MACHINE'
     451 'COFFEE PULPING MACHINE'
     452 'FERTILIZER DISTRIBUTOR'
     453 'POWER TILLER'
     454 'BAJAJ/TOYO'
     455 'GUTA'
     456 'INCUBATOR' /
 hh_m00
     1 'YES'
     2 'NO' /
 hh_m02
     0 'LESS THAN 1 YEAR' / .


SAVE OUTFILE='.\hh_sec_m.sav'.
