/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_g.dat" ENCODING="CP1252" / LRECL=42 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        indidy5 23-24         
   hh_g01 25                hh_g02 26                hh_g03_1 27           
   hh_g03_2 28              hh_g03_3 29              hh_g03_4 30           
   hh_g03_5 31              hh_g03_6 32              hh_g03_7 33           
   hh_g03_8 34              hh_g03_9 35              hh_g04 36             
   hh_g05 37                hh_g06 38                hh_g07 39             
   hh_g08 40                hh_g09 41                hh_g10 42 .           

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   indidy5 'Individual ID'
   hh_g01 'Is this person answering for himself/herself?'
   hh_g02 'CAPI: Is name 15 years or older?'
   hh_g03_1    'How satisfied or dissatisfied would you say you are with YOUR HEA' +
   'LTH?'
   hh_g03_2    'How satisfied or dissatisfied would you say you are with YOUR FIN' +
   'ANCIAL SITUATIO'
   hh_g03_3    'How satisfied or dissatisfied would you say you are with YOUR HOU' +
   'SING?'
   hh_g03_4    'How satisfied or dissatisfied would you say you are with YOUR JOB' +
   '?'
   hh_g03_5    'How satisfied or dissatisfied would you say you are with THE HEAL' +
   'TH CARE AVAILAB'
   hh_g03_6    'How satisfied or dissatisfied would you say you are with THE EDUC' +
   'ATION AVAILABLE'
   hh_g03_7    'How satisfied or dissatisfied would you say you are with YOUR PRO' +
   'TECTION AGAINST'
   hh_g03_8    'How satisfied or dissatisfied would you say you are with YOUR SAF' +
   'ETY IN TRANSPOR'
   hh_g03_9    'How satisfied or dissatisfied would you say you are with YOUR LIF' +
   'E AS A WHOLE?'
   hh_g04    'Just thinking about your current finanical circumstances, would y' +
   'ou describe you'
   hh_g05    'Just thinking about your circumstances that you were living in tw' +
   'o years ago, wo'
   hh_g06 'CAPI: Is name 12 years or older?'
   hh_g07 'In the last 12 months, has [NAME] been a victim of a crime?'
   hh_g08 'What was the type of crime?'
   hh_g09 'Did [NAME] or someone else report this crime to the police?'
   hh_g10 'Why was this crime not reported to the police?' .

VALUE LABELS
 hh_g01
     1 'YES'
     2 'NO' /
 hh_g02
     1 'YES'
     2 'NO' /
 hh_g03_1
     1 'VERY SATISFIED'
     2 'SATISFIED'
     3 'SOMEWHAT SATISFIED'
     4 'NEITHER SATISFIED NOR DISSATISFIED'
     5 'SOMEWHAT DISSATISFIED'
     6 'DISSATISFIED'
     7 'VERY DISSATISFIED'
     8 'NOT APPLICABLE' /
 hh_g03_2
     1 'VERY SATISFIED'
     2 'SATISFIED'
     3 'SOMEWHAT SATISFIED'
     4 'NEITHER SATISFIED NOR DISSATISFIED'
     5 'SOMEWHAT DISSATISFIED'
     6 'DISSATISFIED'
     7 'VERY DISSATISFIED'
     8 'NOT APPLICABLE' /
 hh_g03_3
     1 'VERY SATISFIED'
     2 'SATISFIED'
     3 'SOMEWHAT SATISFIED'
     4 'NEITHER SATISFIED NOR DISSATISFIED'
     5 'SOMEWHAT DISSATISFIED'
     6 'DISSATISFIED'
     7 'VERY DISSATISFIED'
     8 'NOT APPLICABLE' /
 hh_g03_4
     1 'VERY SATISFIED'
     2 'SATISFIED'
     3 'SOMEWHAT SATISFIED'
     4 'NEITHER SATISFIED NOR DISSATISFIED'
     5 'SOMEWHAT DISSATISFIED'
     6 'DISSATISFIED'
     7 'VERY DISSATISFIED'
     8 'NOT APPLICABLE' /
 hh_g03_5
     1 'VERY SATISFIED'
     2 'SATISFIED'
     3 'SOMEWHAT SATISFIED'
     4 'NEITHER SATISFIED NOR DISSATISFIED'
     5 'SOMEWHAT DISSATISFIED'
     6 'DISSATISFIED'
     7 'VERY DISSATISFIED'
     8 'NOT APPLICABLE' /
 hh_g03_6
     1 'VERY SATISFIED'
     2 'SATISFIED'
     3 'SOMEWHAT SATISFIED'
     4 'NEITHER SATISFIED NOR DISSATISFIED'
     5 'SOMEWHAT DISSATISFIED'
     6 'DISSATISFIED'
     7 'VERY DISSATISFIED'
     8 'NOT APPLICABLE' /
 hh_g03_7
     1 'VERY SATISFIED'
     2 'SATISFIED'
     3 'SOMEWHAT SATISFIED'
     4 'NEITHER SATISFIED NOR DISSATISFIED'
     5 'SOMEWHAT DISSATISFIED'
     6 'DISSATISFIED'
     7 'VERY DISSATISFIED'
     8 'NOT APPLICABLE' /
 hh_g03_8
     1 'VERY SATISFIED'
     2 'SATISFIED'
     3 'SOMEWHAT SATISFIED'
     4 'NEITHER SATISFIED NOR DISSATISFIED'
     5 'SOMEWHAT DISSATISFIED'
     6 'DISSATISFIED'
     7 'VERY DISSATISFIED'
     8 'NOT APPLICABLE' /
 hh_g03_9
     1 'VERY SATISFIED'
     2 'SATISFIED'
     3 'SOMEWHAT SATISFIED'
     4 'NEITHER SATISFIED NOR DISSATISFIED'
     5 'SOMEWHAT DISSATISFIED'
     6 'DISSATISFIED'
     7 'VERY DISSATISFIED'
     8 'NOT APPLICABLE' /
 hh_g04
     1 'VERY RICH'
     2 'RICH'
     3 'COMFORTABLE'
     4 'CAN MANAGE TO GET BY'
     5 'NEVER HAVE QUITE ENOUGH'
     6 'POOR'
     7 'DESTITUTE'
     8 'NO OPINION' /
 hh_g05
     1 'VERY RICH'
     2 'RICH'
     3 'COMFORTABLE'
     4 'CAN MANAGE TO GET BY'
     5 'NEVER HAVE QUITE ENOUGH'
     6 'POOR'
     7 'DESTITUTE'
     8 'NO OPINION' /
 hh_g06
     1 'YES'
     2 'NO' /
 hh_g07
     1 'YES'
     2 'NO' /
 hh_g08
     1 'CAR THEFT'
     2 'MOTORBIKE THEFT'
     3 'BICYCLE THEFT'
     4 'THEFT OF PERSONAL PROPERTY (SUCH AS MOBILE, PURSE/WALLET, JEWELRY, LAPTOP)'
     5 'LIVESTOCK THEFT'
     6 'CROP THEFT'
     7 'HOME BURGLARY'
     8 'ASSAULT'
     9 'OTHER (SPECIFY)' /
 hh_g09
     1 'YES'
     2 'NO' /
 hh_g10
     1 'CRIME NOT SERIOUS'
     2 'POLICE TOO FAR'
     3 'POLICE CORRUPT'
     4 'REPORTING WOULD CAUSE TROUBLE'
     5 'NEIGHBORHOOD ISSUE, DID NOT WANT POLICE INVOLVED'
     6 'OTHER (SPECIFY)' / .


SAVE OUTFILE='.\hh_sec_g.sav'.
