/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_n.dat" ENCODING="CP1252" / LRECL=344 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        hh_n01a 23            
   enterprise_id 24         hh_n02_2 25-213 (A)      hh_n02_3a 214-215     
   hh_n02_3 216-219         hh_n03_1 220-221         hh_n03_2 222-223      
   hh_n03_3 224             hh_n03_4 225-226         hh_n03_5 227          
   hh_n03_6 228             hh_n04a 229-230          hh_n04b 231-232       
   hh_n04_1 233-234         hh_n04_2 235             hh_n04_3 236          
   hh_n05_1 237-238         hh_n05_2 239-240         hh_n06 241-242        
   hh_n07_1 243-246         hh_n07_2 247-249         hh_n08_1 250-251      
   hh_n08_2 252-253         hh_n08_3 254             hh_n09_1 255          
   hh_n09_2 256             hh_n10 257-265           hh_n11 266-273        
   hh_n12 274-282           hh_n13_1 283             hh_n13_2 284-292      
   hh_n14_1 293             hh_n14_2 294-301         hh_n15 302-306        
   hh_n16 307-314           hh_n17 315-322           hh_n18 323-330        
   hh_n19 331-332           hh_n20 333-340           hh_n21_1 341          
   hh_n21_2 342             hh_n21_3 343             hh_n21_4 344 .        

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   hh_n01a    'Over the past 12 months, has anyone in your houshold operated any' +
   ' non-agricultur'
   enterprise_id 'Enterprise ID'
   hh_n02_2    'Please provide details on the main product or service of each [EN' +
   'TERPRISE]...'
   hh_n02_3a    'Please provide details on the main product or service of each [EN' +
   'TERPRISE] that'
   hh_n02_3    'Please provide details on the main product or service of each [EN' +
   'TERPRISE]...'
   hh_n03_1 'Which members of the household are engaged in this [ENTERPRISE]?'
   hh_n03_2 'Which members of the household are engaged in this [ENTERPRISE]?'
   hh_n03_3 'Which members of the household are engaged in this [ENTERPRISE]?'
   hh_n03_4 'Which members of the household are engaged in this [ENTERPRISE]?'
   hh_n03_5 'Which members of the household are engaged in this [ENTERPRISE]?'
   hh_n03_6 'Which members of the household are engaged in this [ENTERPRISE]?'
   hh_n04a    'Who in the household manages this business or is most familiar wi' +
   'th it? ID MANAG'
   hh_n04b    'Who in the household manages this business or is most familiar wi' +
   'th it? ID MANAG'
   hh_n04_1 'Who is the respondent for this [ENTERPRISE]?'
   hh_n04_2    'Is the respondent for this [ENTERPRISE] one of the managers liste' +
   'd in Q4?'
   hh_n04_3    'If the respondent for this [ENTERPRISE] is NOT one of the manager' +
   's listed, pleas'
   hh_n05_1 'Who in the household owns this [ENTERPRISE]? ID OWNER 1'
   hh_n05_2 'Who is the household owns this [ENTERPRISE]? ID OWNER 2'
   hh_n06 'Where do you do business?'
   hh_n07_1 'How long has this [ENTERPRISE] existed? NUMBER OF YEARS'
   hh_n07_2 'How long has this [ENTERPRISE] existed? NUMBER OF MONTHS'
   hh_n08_1    'What was the main source of start-up capital for this income-gene' +
   'rating activity'
   hh_n08_2    'What was the main source of start-up capital for this income-gene' +
   'rating activity'
   hh_n08_3    'What was the main source of start-up capital for this income-gene' +
   'rating activity'
   hh_n09_1 'To whom do you sell your products or services?'
   hh_n09_2 'To whom do you sell your products or services?'
   hh_n10    'What is the total value of your physical capital stock, including' +
   ' all tools, equ'
   hh_n11    'What is the total value of your current stock of inputs or suppli' +
   'es? (TSH)'
   hh_n12    'What is the total value of your current stock of finished merchan' +
   'dise (goods for'
   hh_n13_1    'What gross income/takings did you get from your [ENTERPRISE] in t' +
   'he last week/mo'
   hh_n13_2    'What gross income/takings did you get from your [ENTERPRISE] in t' +
   'he last week/mo'
   hh_n14_1    'What was the net income (profit) from your [ENTERPRISE] in the la' +
   'st week/month? '
   hh_n14_2    'What was the net income (profit) from your [ENTERPRISE] in the la' +
   'st week/month? '
   hh_n15 'How many employees do you have who are not household members?'
   hh_n16    'What was your total expenditure on wages/salary in the last month' +
   '? (TSH)'
   hh_n17    'What was your total expenditure on raw amterials in the last mont' +
   'h? (TSH)'
   hh_n18    'How much were your other operating expenses (for this [ENTERPRISE' +
   ']) such as fuel'
   hh_n19    'How many months during the last 12 months did you operate this [E' +
   'NTERPRISE]?'
   hh_n20    'What was your AVERAGE net monthly income (profit) during the mont' +
   'hs when you ope'
   hh_n21_1    'Is this company officially registered with the [REGISTRAR OF COMP' +
   'ANIES]?'
   hh_n21_2 'Is this company officially registered with the [TAX AUTHORITY]?'
   hh_n21_3    'Is this company officially registered with the [LOCAL AUTHORITY]?'
   hh_n21_4 'Is this company officially registered with the [OTHER, SPECIFY]?' .

VALUE LABELS
 hh_n01a
     1 'YES'
     2 'NO' /
 hh_n02_3a
     1 'Agriculture, forestry and fishing'
     2 'Mining and quarrying'
     3 'Manufacturing'
     4 'Electricity gas steam and air conditioning supply'
     5 'Water supply, sewage, waste management and remediation activities'
     6 'Construction'
     7 'Wholesale and retail trade, repair of motor vehicles and motorcycles'
     8 'Transportation and storage'
     9 'Accommodation and food service activities'
     10 'Information and communication'
     11 'Financial and insurance activities'
     12 'Real estate activities'
     13 'Professional scientific and technical activities'
     14 'Administrative and support service activities'
     15 'Public administration and defense, compulsory social security'
     16 'Education'
     17 'Human health and social work activities'
     18 'Arts; entertainment and recreation'
     19 'Other service activities'
     20 'Activities of households as employers, undifferentiated goods, and services-producing activities of households for own use'
     21 'Activities of extraterritorial organizations and bodies' /
 hh_n02_3
     1 'Crop and animal production, hunting and related service activities'
     2 'Forestry and logging'
     3 'Fishing and aquaculture'
     5 'Mining of coal and lignite'
     6 'Extraction of crude petroleum and natural gas'
     7 'Mining of metal ores'
     8 'Other mining and quarrying'
     9 'Mining support service activities'
     10 'Manufacture of food products'
     11 'Manufacture of beverages'
     12 'Manufacture of tobacco products'
     13 'Manufacture of textiles'
     14 'Manufacture of wearing apparel'
     15 'Manufacture of leather and related products'
     16 'Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials'
     17 'Manufacture of paper and paper products'
     18 'Printing and reproduction of recorded media'
     19 'Manufacture of coke and refined petroleum products'
     20 'Manufacture of chemicals and chemical products'
     21 'Manufacture of basic pharmaceutical products and pharmaceutical preparations'
     22 'Manufacture of rubber and plastics products'
     23 'Manufacture of other non-metallic mineral products'
     24 'Manufacture of basic metals'
     25 'Manufacture of fabricated metal products, except machinery and equipment'
     26 'Manufacture of computer, electronic and optical products'
     27 'Manufacture of electrical equipment'
     28 'Manufacture of machinery and equipment n.e.c.'
     29 'Manufacture of motor vehicles, trailers and semi-trailers'
     30 'Manufacture of other transport equipment'
     31 'Manufacture of furniture'
     32 'Other manufacturing'
     33 'Repair and installation of machinery and equipment'
     35 'Electricity, gas, steam and air conditioning supply'
     36 'Water collection, treatment and supply'
     37 'Sewerage'
     38 'Waste collection, treatment and disposal activities, materials recovery'
     39 'Remediation activities and other waste management services'
     41 'Construction of buildings'
     42 'Civil engineering'
     43 'Specialized construction activities'
     45 'Wholesale and retail trade and repair of motor vehicles and motorcycles'
     46 'Wholesale trade, except of motor vehicles and motorcycles'
     47 'Retail trade, except of motor vehicles and motorcycles'
     49 'Land transport and transport via pipelines'
     50 'Water transport'
     51 'Air transport'
     52 'Warehousing and support activities for transportation'
     53 'Postal and courier activities'
     55 'Accommodation'
     56 'Food and beverage service activities'
     58 'Publishing activities'
     59 'Motion picture, video and television programme production, sound recording and music publishing activities'
     60 'Programming and broadcasting activities'
     61 'Telecommunications'
     62 'Computer programming - consultancy and related activities'
     63 'Information service activities'
     64 'Financial service activities, except insurance and pension funding'
     65 'Insurance; reinsurance and pension funding, except compulsory social security'
     66 'Activities auxiliary to financial service and insurance activities'
     68 'Real estate activities'
     69 'Legal and accounting activities'
     70 'Activities of head offices, management consultancy activities'
     71 'Architectural and engineering activities, technical testing and analysis'
     72 'Scientific research and development'
     73 'Advertising and market research'
     74 'Other professional, scientific and technical activities'
     75 'Veterinary activities'
     77 'Rental and leasing activities'
     78 'Employment activities'
     79 'Travel agency, tour operator, reservation service and related activities'
     80 'Security and investigation activities'
     81 'Services to buildings and landscape activities'
     82 'Office administrative, office support and other business support activities'
     84 'Public administration and defense, compulsory social security'
     85 'Education'
     86 'Human health activities'
     87 'Residential care activities'
     88 'Social work activities without accommodation'
     90 'Creative - arts and entertainment activities'
     91 'Libraries, archives, museums and other cultural activities'
     92 'Gambling and betting activities'
     93 'Sports activities and amusement and recreation activities'
     94 'Activities of membership organizations'
     95 'Repair of computers and personal and household goods'
     96 'Other personal service activities'
     97 'Activities of households as employers of domestic personnel'
     98 'Undifferentiated goods and services producing activities of private households for own use'
     99 'Activities of extraterritorial organizations and bodies'
     101 'Processing and preserving of meat'
     102 'Processing and preserving of fish, crustaceans and mollusks'
     103 'Processing and preserving of fruit and vegetables'
     104 'Manufacture of vegetable and animal oils and fats'
     105 'Manufacture of dairy products'
     106 'Manufacture of grain mill products, starches and starch products'
     107 'Manufacture of other food products'
     108 'Manufacture of prepared animal feeds'
     471 'Retail sale in non-specialized stores'
     472 'Retail sale of food, beverages and tobacco in specialized stores'
     473 'Retail sale of automotive fuel in specialized stores'
     474 'Retail sale of information and communications equipment in specialized stores'
     475 'Retail sale of other household equipment in specialized stores'
     476 'Retail sale of cultural and recreation goods in specialized stores'
     477 'Retail sale of other goods in specialized stores'
     478 'Retail sale via stalls and markets'
     479 'Retail trade not in stores, stalls or markets'
     491 'Transport via railways'
     492 'Other land transport'
     493 'Transport via pipeline'
     561 'Restaurants and mobile food service activities'
     562 'Event catering and other food service activities'
     563 'Beverage serving activities'
     4921 'Urban and suburban passenger land transport'
     4922 'Other passenger land transport'
     4923 'Freight transport by road' /
 hh_n04_2
     1 'YES'
     2 'NO' /
 hh_n04_3
     1 'NOT AVAILABLE DURING TIME IN EA'
     2 'REFUSED'
     3 'OTHER, SPECIFY' /
 hh_n06
     1 "W/IN OWN OR BUS.  PARTNER'S HOME - WITH SPECIAL BUS. SPACE"
     2 "W/IN OWN OR BUS.  PARTNER'S HOME - WITHOUT SPECIAL BUS. SPACE"
     3 "STRUCTURE ATTACHED TO/OUTSIDE OWN OR BUS.  PARTNER'S HOUSE"
     4 'PERMANENT BLDG  OTHER THAN HOME'
     5 'FIXED STALL/KIOSK - IN MARKET'
     6 'VEHICLE, CART, TEMP  STALL - IN MARKET'
     7 'FIXED STALL/KIOSK  - STREET'
     8 'VEHICLE,CART,TEMP STALL - STREET'
     9 'OTHER TEMP  STRUCTURE'
     10 'CONSTRUCTION SITE'
     11 "CLIENT'S/EMPLOYER'S HOUSE"
     12 'NO FIXED LOCATION/MOBILE'
     13 'OTHER, SPECIFY' /
 hh_n08_1
     1 'LOAN FROM FAMILY/FRIENDS'
     2 'GIFT FROM FAMILY/FRIENDS'
     3 'SALE OF ASSETS OWNED'
     4 'PROCEEDS FROM NON-AG BUSINESS'
     5 'PROCEEDS FROM ANOTHER AGRICULTURAL BUSINESS'
     6 'OWN SAVINGS'
     7 'LOAN FROM SACCOS'
     8 'NON-AGRICULTURAL CREDIT'
     9 'BANK OR OTHER INSTITUTION'
     10 'LOAN FROM MONEY LENDER'
     11 'INHERITED'
     12 'OTHER (SPECIFY)'
     13 'NO START-UP COST' /
 hh_n08_2
     1 'LOAN FROM FAMILY/FRIENDS'
     2 'GIFT FROM FAMILY/FRIENDS'
     3 'SALE OF ASSETS OWNED'
     4 'PROCEEDS FROM NON-AG BUSINESS'
     5 'PROCEEDS FROM ANOTHER AGRICULTURAL BUSINESS'
     6 'OWN SAVINGS'
     7 'LOAN FROM SACCOS'
     8 'NON-AGRICULTURAL CREDIT'
     9 'BANK OR OTHER INSTITUTION'
     10 'LOAN FROM MONEY LENDER'
     11 'INHERITED'
     12 'OTHER (SPECIFY)'
     13 'NO START-UP COST' /
 hh_n08_3
     1 'LOAN FROM FAMILY/FRIENDS'
     2 'GIFT FROM FAMILY/FRIENDS'
     3 'SALE OF ASSETS OWNED'
     4 'PROCEEDS FROM NON-AG BUSINESS'
     5 'PROCEEDS FROM ANOTHER AGRICULTURAL BUSINESS'
     6 'OWN SAVINGS'
     7 'LOAN FROM SACCOS'
     8 'NON-AGRICULTURAL CREDIT'
     9 'BANK OR OTHER INSTITUTION'
     10 'LOAN FROM MONEY LENDER'
     11 'INHERITED'
     12 'OTHER (SPECIFY)'
     13 'NO START-UP COST' /
 hh_n09_1
     1 'FINAL CONSUMERS'
     2 'SMALL BUSINESS'
     3 'LARGE ESTABLISHED BUSINESS'
     4 'INSTITUTIONS'
     5 'EXPORT'
     6 'MANUFACTURERS'
     7 'GOVERNEMENT'
     8 'OTHER (SPECIFY)' /
 hh_n09_2
     1 'FINAL CONSUMERS'
     2 'SMALL BUSINESS'
     3 'LARGE ESTABLISHED BUSINESS'
     4 'INSTITUTIONS'
     5 'EXPORT'
     6 'MANUFACTURERS'
     7 'GOVERNEMENT'
     8 'OTHER (SPECIFY)' /
 hh_n13_1
     1 'WEEK'
     2 'MONTH' /
 hh_n14_1
     1 'WEEK'
     2 'MONTH' /
 hh_n21_1
     1 'NO'
     2 'YES' /
 hh_n21_2
     1 'NO'
     2 'YES' /
 hh_n21_3
     1 'NO'
     2 'YES' /
 hh_n21_4
     1 'NO'
     2 'YES' / .


SAVE OUTFILE='.\hh_sec_n.sav'.
