/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_o1.dat" ENCODING="CP1252" / LRECL=65 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        assist_id 23          
   hh_o01 24                hh_o02 25-40 (A)         hh_o03 41-47          
   hh_o04 48-53             hh_o05 54-60             hh_o06_1 61           
   hh_o06_2 62              hh_o06_3 63              hh_o07_1 64           
   hh_o07_2 65 .         

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   assist_id 'Assistance Type Code'
   hh_o01    'Did you or members of your household receive any [...] in the pas' +
   't 12 months fro'
   hh_o02    'What is the name of the organization/program who provided this as' +
   'sistance?'
   hh_o03    'How much cash did your household receive from this organization i' +
   'n the last 12 m'
   hh_o04    'What was the value of food the household received from this organ' +
   'ization in the '
   hh_o05    'What was the value of any other in-kind assistance received in th' +
   'e last 12 month'
   hh_o06_1    'Which members of the household participated in this program? ID 1'
   hh_o06_2    'Which members of the household participated in this program? ID 2'
   hh_o06_3    'Which members of the household participated in this program? ID 3'
   hh_o07_1    'Who in your household controls/decides on the use of assistance f' +
   'rom the program'
   hh_o07_2    'Who in your household controls/decides on the use of assistance f' +
   'rom the program' .

VALUE LABELS
 assist_id
     1 'FREE FOOD/MAIZE DISTRIBUTION'
     2 'FOOD-FOR-WORK PROGRAMME OR CASH-FOR-WORK PROGRAMME'
     3 'INPUTS-FOR WORK PROGRAMME'
     4 'SCHOLARSHIPS OR BURSARIES FOR PRIMARY SCHOOL'
     5 'SCHOLARSHIPS OR BURSARIES FOR SECONDARY SCHOOL'
     6 'OTHER ASSISTANCE (NOT LISTED ABOVE), SPECIFY' /
 hh_o01
     1 'YES'
     2 'NO' / .


SAVE OUTFILE='.\hh_sec_o1.sav'.
