/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_v.dat" ENCODING="CP1252" / LRECL=45 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        indidy5 23-24         
   hh_v01 25                hh_v02 26                hh_v03 27             
   hh_v04 28                hh_v05 29-33             hh_v06 34-38          
   hh_v07 39                hh_v08 40                hh_v09 41-44          
   int_result 45 .       


FORMATS
  hh_v05 (F6.1) /          hh_v06 (F6.1) /          hh_v09 (F5.1) / .
     
VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   indidy5 'Individual ID'
   hh_v01 'CAPI: Is [NAME] a woman ages 15-49?'
   hh_v02 'CAPI: Is [NAME] over age 15?'
   hh_v03 'Was [NAME] measured?'
   hh_v04 'Why was [NAME] not measured?'
   hh_v05 'Weight (KG)'
   hh_v06 'Height (CM)'
   hh_v07 'Height / length measured with child standing or lying down?'
   hh_v08 'CAPI: Is [NAME] 5 years or younger'
   hh_v09 'Upper arm circumference (CM)'
   int_result 'WHAT IS THE FINAL RESULT OF THE INTERVIEW?' .

VALUE LABELS
 hh_v01
     1 'YES'
     2 'NO' /
 hh_v02
     1 'YES'
     2 'NO' /
 hh_v03
     1 'YES'
     2 'NO' /
 hh_v04
     1 'CURRENTLY NOT HOME'
     2 'TOO ILL'
     3 'UNWILLING'
     4 'OTHER (SPECIFY)' /
 hh_v07
     1 'STANDING'
     2 'LYING DOWN' /
 hh_v08
     1 'YES'
     2 'NO' /
 int_result
     1 'COMPLETE'
     2 'PARTIALLY COMPLETE (REFUSED)'
     3 'PARTIALLY COMPLETE (UNAVAILABLE)'
     4 'UNABLE TO IDENTIFY HOUSEHOLD'
     5 'HOUSEHOLD HAS MOVED AWAY'
     6 'LONG TERM UNAVAILABLE'
     7 'REFUSED' / .


SAVE OUTFILE='.\hh_sec_v.sav'.
