/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\hh_sec_e2.dat" ENCODING="CP1252" / LRECL=35 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        indidy5 23-24         
   hh_e201_1 25             hh_e201 26               hh_e202 27-28         
   hh_e203 29               hh_e204 30               hh_e205 31            
   hh_e206 32               hh_e207a 33              hh_e207b 34-35 .      

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   indidy5 'Individual ID'
   hh_e201_1 'CAPI: Is the household member 5 years or above?'
   hh_e201 'Is this person answering for himself/herself?'
   hh_e202 'Who is reporting the information for the individual?'
   hh_e203    'In the last 12 months, did [NAME] work as an employee for a wage,' +
   ' salary, commis'
   hh_e204    'In the last 12 months, did [NAME] run a non-farm business of any ' +
   'size for themse'
   hh_e205    'In the last 12 months, did [NAME] work on household agricultural ' +
   'activities (inc'
   hh_e206    'In the last 12 months, did [NAME] work as an unpaid apprentice ev' +
   'en if for one h'
   hh_e207a    'In what type of economic activity did [NAME] spend most of their ' +
   'time in the las'
   hh_e207b    'In what type of economic activity did [NAME] spend most of their ' +
   'time in the las' .

VALUE LABELS
 hh_e201_1
     1 'YES'
     2 'NO' /
 hh_e201
     1 'YES'
     2 'NO' /
 hh_e203
     1 'YES'
     2 'NO' /
 hh_e204
     1 'YES'
     2 'NO' /
 hh_e205
     1 'YES'
     2 'NO' /
 hh_e206
     1 'YES'
     2 'NO' /
 hh_e207a
     1 'A PAID EMPLOYEE'
     2 'SELF-EMPLOYED (NON-AG): WITH EMPLOYEES'
     3 'SELF-EMPLOYED (NON-AG): WITHOUT EMPLOYEES'
     4 'UNPAID FAMILY HELPER (NON-AG)'
     5 'UNPAID FAMILY HELPER (AGRICULTURE)'
     6 'ON YOUR OWN FARM OR SHAMBA'
     7 'UNPAID APPRENTICESHIP'
     8 'PAID APPRENTICESHIP'
     9 'OTHER (SPECIFY)' /
 hh_e207b
     1 'A PAID EMPLOYEE'
     2 'SELF-EMPLOYED (NON-AG): WITH EMPLOYEES'
     3 'SELF-EMPLOYED (NON-AG): WITHOUT EMPLOYEES'
     4 'UNPAID FAMILY HELPER (NON-AG)'
     5 'UNPAID FAMILY HELPER (AGRICULTURE)'
     6 'ON YOUR OWN FARM OR SHAMBA'
     7 'UNPAID APPRENTICESHIP'
     8 'PAID APPRENTICESHIP'
     99 'NO SECONDARY ECONOMIC ACTIVITY' / .


SAVE OUTFILE='.\hh_sec_e2.sav'.
