/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\lf_sec_04.dat" ENCODING="CP1252" / LRECL=69 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        lvstckid 23           
   lf04_01_1 24             lf04_01_2 25             lf04_02 26            
   lf04_03_1 27 (A)         lf04_03_2 28 (A)         lf04_03_3 29 (A)      
   lf04_03_4 30 (A)         lf04_03_5 31 (A)         lf04_03_6 32 (A)      
   lf04_03_7 33 (A)         lf04_03_8 34 (A)         lf04_03_9 35 (A)      
   lf04_03_10 36 (A)        lf04_03_11 37 (A)        lf04_03_12 38 (A)     
   lf04_04 39-45            lf04_05 46               lf04_06_1 47-48       
   lf04_06_2 49-50          lf04_06a1 51-54          lf04_06a2 55-58       
   lf04_07 59               lf04_09 60-65            lf04_11 66            
   lf04_12 67               lf04_13_1 68             lf04_13_2 69 .        

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   lvstckid 'Livestock Category Code'
   lf04_01_1    'What have been for this household the major feeding practices for' +
   ' [ANIMAL] in th'
   lf04_01_2    'What have been for this household the major feeding practices for' +
   ' [ANIMAL] in th'
   lf04_02    'Did you purchase any feed/fodder for your [ANIMAL] in the past 12' +
   ' months?'
   lf04_03_1 'In which months did you purchase feed/fodder? (Jan)'
   lf04_03_2 'In which months did you purchase feed/fodder? (Feb)'
   lf04_03_3 'In which months did you purchase feed/fodder? (Mar)'
   lf04_03_4 'In which months did you purchase feed/fodder? (Apr)'
   lf04_03_5 'In which months did you purchase feed/fodder? (May)'
   lf04_03_6 'In which months did you purchase feed/fodder? (Jun)'
   lf04_03_7 'In which months did you purchase feed/fodder? (Jul)'
   lf04_03_8 'In which months did you purchase feed/fodder? (Aug)'
   lf04_03_9 'In which months did you purchase feed/fodder? (Sep)'
   lf04_03_10 'In which months did you purchase feed/fodder? (Oct)'
   lf04_03_11 'In which months did you purchase feed/fodder? (Nov)'
   lf04_03_12 'In which months did you purchase feed/fodder? (Dec)'
   lf04_04    'How much has this household paid to feed the [ANIMAL] in the past' +
   ' 12 months? (TS'
   lf04_05    'How frequently, on average, has this household watered [ANIMAL] i' +
   'n the past 12 m'
   lf04_06_1    'What have been the main sources of water for [ANIMAL] in the past' +
   ' 12 months? 1ST'
   lf04_06_2    'What have been the main sources of water for [ANIMAL] in the past' +
   ' 12 months? 2ND'
   lf04_06a1    'In Average, how much time in minutes was used to reach the water ' +
   'source for [ANI'
   lf04_06a2    'In Average, how much time in minutes was used to reach the water ' +
   'source for [ANI'
   lf04_07    'Has this household ever paid to water [ANIMAL] in the past 12 mon' +
   'ths?'
   lf04_09    'How much has this household paid to access the main water sources' +
   ' for [ANIMAL] i'
   lf04_11    'What housing system for [ANIMAL] has this household mainly used i' +
   'n the past 12 m'
   lf04_12    'Has this household practiced any controlled mating or other breed' +
   'ing strategy fo'
   lf04_13_1    'Was have been the main controlled mating or breeding strategies u' +
   'sed by this hou'
   lf04_13_2    'Was have been the main controlled mating or breeding strategies u' +
   'sed by this hou' .

VALUE LABELS
 lvstckid
     1 'LARGE RUMINANTS'
     2 'SMALL RUMINANTS'
     3 'PIGS'
     4 'POULTRY' /
 lf04_01_1
     1 'ONLY GRAZING/SCAVENGING'
     2 'MAINLY GRAZING/SCAVENGING WITH SOME FEEDING'
     3 'MAINLY FEEDING WITH SOME GRAZING/SCAVENGING'
     4 'ONLY FEEDING (NO GRAZING AND NO SCAVENGING)'
     5 'TETHERING'
     6 'OTHER, SPECIFY' /
 lf04_01_2
     1 'ONLY GRAZING/SCAVENGING'
     2 'MAINLY GRAZING/SCAVENGING WITH SOME FEEDING'
     3 'MAINLY FEEDING WITH SOME GRAZING/SCAVENGING'
     4 'ONLY FEEDING (NO GRAZING AND NO SCAVENGING)'
     5 'TETHERING'
     6 'OTHER, SPECIFY' /
 lf04_02
     1 'YES'
     2 'NO' /
 lf04_05
     1 'ANIMALS GET ON THEIR OWN FROM AVAILABLE SOURCES'
     2 'ONCE A DAY'
     3 'TWICE A DAY'
     4 'THREE TIMES A DAY'
     5 'THROUGHOUT THE DAY'
     6 'OTHER (SPECIFY)' /
 lf04_06_1
     1 'TAP WATER'
     2 'BOREHOLE'
     3 'DAM'
     4 'WELL'
     5 'RIVER'
     6 'SPRING'
     7 'STREAM'
     8 'CONSTRUCTED WATER POINTS'
     9 'RAINWATER HARVESTING'
     10 'OTHER (SPECIFY)' /
 lf04_06_2
     1 'TAP WATER'
     2 'BOREHOLE'
     3 'DAM'
     4 'WELL'
     5 'RIVER'
     6 'SPRING'
     7 'STREAM'
     8 'CONSTRUCTED WATER POINTS'
     9 'RAINWATER HARVESTING'
     10 'OTHER (SPECIFY)' /
 lf04_07
     1 'YES'
     2 'NO' /
 lf04_11
     1 'NONE'
     2 'CONFINED IN SHEDS'
     3 'CONFINED IN PADDOCKS'
     4 'CONFINED FENCES'
     5 'CAGE'
     6 'BASKET'
     7 'OTHER (SPECIFY)'
     8 'INSIDE THE HOUSE' /
 lf04_12
     1 'YES'
     2 'NO' /
 lf04_13_1
     1 'NONE'
     2 'NATURAL MATING, SIRE SELECTED FROM WITHIN HERD'
     3 'NATURAL MATING, SIRE PURCHASED'
     4 'NATURAL MATING, SIRE EXCHANGED'
     5 'ARTIFICIAL INSEMINATION'
     6 'DAM PURCHASED'
     7 'DAM EXCHANGED'
     8 'NONE BREEDING MALES CASTRATED'
     9 'OTHER (SPECIFY)' /
 lf04_13_2
     1 'NONE'
     2 'NATURAL MATING, SIRE SELECTED FROM WITHIN HERD'
     3 'NATURAL MATING, SIRE PURCHASED'
     4 'NATURAL MATING, SIRE EXCHANGED'
     5 'ARTIFICIAL INSEMINATION'
     6 'DAM PURCHASED'
     7 'DAM EXCHANGED'
     8 'NONE BREEDING MALES CASTRATED'
     9 'OTHER (SPECIFY)' / .


SAVE OUTFILE='.\lf_sec_04.sav'.
