/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\lf_sec_03.dat" ENCODING="CP1252" / LRECL=56 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        lvstckid 23           
   lf03_01 24               lf03_02_1 25-26          lf03_02_2 27-28       
   lf03_02_3 29-30          lf03_02_4 31-32          lf03_03 33            
   lf03_04 34               lf03_05_1 35-36          lf03_05_2 37-38       
   lf03_05_3 39-40          lf03_05_4 41             lf03_06 42            
   lf03_07 43               lf03_08 44               lf03_09 45            
   lf03_10 46               lf03_11 47               lf03_12 48            
   lf03_13 49               lf03_14 50-56 .       

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   lvstckid 'Livestock Category Code'
   lf03_01 'CAPI: DID THE HOUSEHOLD OWN ANY OF THESE TYPES OF ANIMALS?'
   lf03_02_1    'What kind of diseases did [ANIMAL] suffer in the past 12 months? ' +
   '(#1)'
   lf03_02_2    'What kind of diseases did [ANIMAL] suffer in the past 12 months? ' +
   '(#2)'
   lf03_02_3    'What kind of diseases did [ANIMAL] suffer in the past 12 months? ' +
   '(#3)'
   lf03_02_4    'What kind of diseases did [ANIMAL] suffer in the past 12 months? ' +
   '(#4)'
   lf03_03 'Did you vaccinate your [ANIMAL] in the past 12 months?'
   lf03_04 'Who provided the vaccine (or vaccinated) your [ANIMAL]?'
   lf03_05_1 'Against which diseases did you vaccinate your [ANIMAL]? (#1)'
   lf03_05_2 'Against which diseases did you vaccinate your [ANIMAL]? (#2)'
   lf03_05_3 'Against which diseases did you vaccinate your [ANIMAL]? (#3)'
   lf03_05_4 'Against which diseases did you vaccinate your [ANIMAL]? (#4)'
   lf03_06    'During the last 12 months have you used dewormers on your [ANIMAL' +
   ']?'
   lf03_07 'Who administered the dewormer treatment to your [ANIMAL]?'
   lf03_08    'During the last 12 months, have you taken any preventative measur' +
   'es for you [ANI'
   lf03_09 'What preventative measures did you take for your [ANIMAL]?'
   lf03_10    'During the last 12 months has your [ANIMAL] been treated against ' +
   'ticks?'
   lf03_11 'Who administered the tick treatment to you [ANIMAL]?'
   lf03_12    'During the last 12 months has your [ANIMAL] received some curativ' +
   'e treatments?'
   lf03_13 'Who administered the curative treatment to your [ANIMAL]?'
   lf03_14    'How much did you spend in total on vaccines, treatments and other' +
   ' veterinary cos' .

VALUE LABELS
 lvstckid
     1 'LARGE RUMINANTS'
     2 'SMALL RUMINANTS'
     3 'PIGS'
     4 'POULTRY'
     6 'DOGS' /
 lf03_01
     1 'YES'
     2 'NO' /
 lf03_02_1
     1 'BRUCELOSIS (UGONJWA WA KUTUPA MIMBA)'
     2 'CBPP (HOMA YA MAPAFU)'
     3 'LUMPY SKIN DISEASE (MAPELENGOZI)'
     4 'CCPP (HOMA YA MAPAFU KWA MBUZI)'
     5 'ECF (NDIGANA KALI)'
     6 'RABIES (KICHAA CHA MBWA)'
     7 'FMD (UGONWA WA MIGUU NA MIDOMO)'
     8 'ANTHRAX (KIMETA)'
     9 'BQ (CHAMBAVU)'
     10 'NEW CASTLE DISEASE (KIDELI/MDONDO)'
     11 'SMALL POX (NDUI)'
     12 'GOMBORO (GUMBORO)'
     13 'HELMINTHIOSIS'
     14 'ASF (HOMA YA NGURUWE)'
     15 'TICK BORNE DISEASE'
     16 'TYPANOSOMIASIS'
     17 'FOOT ROT'
     18 'TETANUS'
     19 'MANGE'
     20 'ANAEMIA'
     21 'CANINE DISTEMPER'
     22 'NOT SICK'
     23 'OTHER (SPECIFY)' /
 lf03_02_2
     1 'BRUCELOSIS (UGONJWA WA KUTUPA MIMBA)'
     2 'CBPP (HOMA YA MAPAFU)'
     3 'LUMPY SKIN DISEASE (MAPELENGOZI)'
     4 'CCPP (HOMA YA MAPAFU KWA MBUZI)'
     5 'ECF (NDIGANA KALI)'
     6 'RABIES (KICHAA CHA MBWA)'
     7 'FMD (UGONWA WA MIGUU NA MIDOMO)'
     8 'ANTHRAX (KIMETA)'
     9 'BQ (CHAMBAVU)'
     10 'NEW CASTLE DISEASE (KIDELI/MDONDO)'
     11 'SMALL POX (NDUI)'
     12 'GOMBORO (GUMBORO)'
     13 'HELMINTHIOSIS'
     14 'ASF (HOMA YA NGURUWE)'
     15 'TICK BORNE DISEASE'
     16 'TYPANOSOMIASIS'
     17 'FOOT ROT'
     18 'TETANUS'
     19 'MANGE'
     20 'ANAEMIA'
     21 'CANINE DISTEMPER'
     22 'NOT SICK'
     23 'OTHER (SPECIFY)' /
 lf03_02_3
     1 'BRUCELOSIS (UGONJWA WA KUTUPA MIMBA)'
     2 'CBPP (HOMA YA MAPAFU)'
     3 'LUMPY SKIN DISEASE (MAPELENGOZI)'
     4 'CCPP (HOMA YA MAPAFU KWA MBUZI)'
     5 'ECF (NDIGANA KALI)'
     6 'RABIES (KICHAA CHA MBWA)'
     7 'FMD (UGONWA WA MIGUU NA MIDOMO)'
     8 'ANTHRAX (KIMETA)'
     9 'BQ (CHAMBAVU)'
     10 'NEW CASTLE DISEASE (KIDELI/MDONDO)'
     11 'SMALL POX (NDUI)'
     12 'GOMBORO (GUMBORO)'
     13 'HELMINTHIOSIS'
     14 'ASF (HOMA YA NGURUWE)'
     15 'TICK BORNE DISEASE'
     16 'TYPANOSOMIASIS'
     17 'FOOT ROT'
     18 'TETANUS'
     19 'MANGE'
     20 'ANAEMIA'
     21 'CANINE DISTEMPER'
     22 'NOT SICK'
     23 'OTHER (SPECIFY)' /
 lf03_02_4
     1 'BRUCELOSIS (UGONJWA WA KUTUPA MIMBA)'
     2 'CBPP (HOMA YA MAPAFU)'
     3 'LUMPY SKIN DISEASE (MAPELENGOZI)'
     4 'CCPP (HOMA YA MAPAFU KWA MBUZI)'
     5 'ECF (NDIGANA KALI)'
     6 'RABIES (KICHAA CHA MBWA)'
     7 'FMD (UGONWA WA MIGUU NA MIDOMO)'
     8 'ANTHRAX (KIMETA)'
     9 'BQ (CHAMBAVU)'
     10 'NEW CASTLE DISEASE (KIDELI/MDONDO)'
     11 'SMALL POX (NDUI)'
     12 'GOMBORO (GUMBORO)'
     13 'HELMINTHIOSIS'
     14 'ASF (HOMA YA NGURUWE)'
     15 'TICK BORNE DISEASE'
     16 'TYPANOSOMIASIS'
     17 'FOOT ROT'
     18 'TETANUS'
     19 'MANGE'
     20 'ANAEMIA'
     21 'CANINE DISTEMPER'
     22 'NOT SICK'
     23 'OTHER (SPECIFY)' /
 lf03_03
     1 'YES, ALL ANIMALS AT LEAST ONCE'
     2 'YES, SOME'
     3 'NO' /
 lf03_04
     1 'PRIVATE CLINIC'
     2 'DISTRICT VET CLINIC'
     3 'NGO/PROJECT'
     4 'OTHER (SPECIFY)' /
 lf03_05_1
     1 'BRUCELOSIS (UGONJWA WA KUTUPA MIMBA)'
     2 'CBPP (HOMA YA MAPAFU)'
     3 'LUMPY SKIN DISEASE (MAPELENGOZI)'
     4 'CCPP (HOMA YA MAPAFU KWA MBUZI)'
     5 'ECF (NDIGANA KALI)'
     6 'RABIES (KICHAA CHA MBWA)'
     7 'FMD (UGONWA WA MIGUU NA MIDOMO)'
     8 'ANTHRAX (KIMETA)'
     9 'BQ (CHAMBAVU)'
     10 'NEW CASTLE DISEASE (KIDELI/MDONDO)'
     11 'SMALL POX (NDUI)'
     12 'GOMBORO (GUMBORO)'
     13 'NOT VACCINATED'
     14 'OTHER (SPECIFY)' /
 lf03_05_2
     1 'BRUCELOSIS (UGONJWA WA KUTUPA MIMBA)'
     2 'CBPP (HOMA YA MAPAFU)'
     3 'LUMPY SKIN DISEASE (MAPELENGOZI)'
     4 'CCPP (HOMA YA MAPAFU KWA MBUZI)'
     5 'ECF (NDIGANA KALI)'
     6 'RABIES (KICHAA CHA MBWA)'
     7 'FMD (UGONWA WA MIGUU NA MIDOMO)'
     8 'ANTHRAX (KIMETA)'
     9 'BQ (CHAMBAVU)'
     10 'NEW CASTLE DISEASE (KIDELI/MDONDO)'
     11 'SMALL POX (NDUI)'
     12 'GOMBORO (GUMBORO)'
     13 'NOT VACCINATED'
     14 'OTHER (SPECIFY)' /
 lf03_05_3
     1 'BRUCELOSIS (UGONJWA WA KUTUPA MIMBA)'
     2 'CBPP (HOMA YA MAPAFU)'
     3 'LUMPY SKIN DISEASE (MAPELENGOZI)'
     4 'CCPP (HOMA YA MAPAFU KWA MBUZI)'
     5 'ECF (NDIGANA KALI)'
     6 'RABIES (KICHAA CHA MBWA)'
     7 'FMD (UGONWA WA MIGUU NA MIDOMO)'
     8 'ANTHRAX (KIMETA)'
     9 'BQ (CHAMBAVU)'
     10 'NEW CASTLE DISEASE (KIDELI/MDONDO)'
     11 'SMALL POX (NDUI)'
     12 'GOMBORO (GUMBORO)'
     13 'NOT VACCINATED'
     14 'OTHER (SPECIFY)' /
 lf03_05_4
     1 'BRUCELOSIS (UGONJWA WA KUTUPA MIMBA)'
     2 'CBPP (HOMA YA MAPAFU)'
     3 'LUMPY SKIN DISEASE (MAPELENGOZI)'
     4 'CCPP (HOMA YA MAPAFU KWA MBUZI)'
     5 'ECF (NDIGANA KALI)'
     6 'RABIES (KICHAA CHA MBWA)'
     7 'FMD (UGONWA WA MIGUU NA MIDOMO)'
     8 'ANTHRAX (KIMETA)'
     9 'BQ (CHAMBAVU)'
     10 'NEW CASTLE DISEASE (KIDELI/MDONDO)'
     11 'SMALL POX (NDUI)'
     12 'GOMBORO (GUMBORO)'
     13 'NOT VACCINATED'
     14 'OTHER (SPECIFY)' /
 lf03_06
     1 'YES, ALL ANIMALS AT LEAST ONCE'
     2 'YES, SOME'
     3 'NO' /
 lf03_07
     1 'PRIVATE VET CLINIC'
     2 'DISTRICT VET CLINIC'
     3 'NGO/PROJECT'
     4 'OTHER (SPECIFY)'
     5 'OWN HOUSEHOLD MEMBER' /
 lf03_08
     1 'YES, ALL ANIMALS AT LEAST ONCE'
     2 'YES, SOME'
     3 'NO' /
 lf03_09
     1 'DIPPING / DIP TANK'
     2 'SPRAYING'
     3 'OTHER (SPECIFY)' /
 lf03_10
     1 'YES, ALL ANIMALS AT LEAST ONCE'
     2 'YES, SOME'
     3 'NO' /
 lf03_11
     1 'PRIVATE VET CLINIC'
     2 'DISTRICT VET CLINIC'
     3 'NGO/PROJECT'
     4 'OTHER (SPECIFY)'
     5 'OWN HOUSEHOLD MEMBER' /
 lf03_12
     1 'YES, ALL ANIMALS AT LEAST ONCE'
     2 'YES, SOME'
     3 'NO' /
 lf03_13
     1 'PRIVATE VET CLINIC'
     2 'DISTRICT VET CLINIC'
     3 'NGO/PROJECT'
     4 'OTHER (SPECIFY)'
     5 'OWN HOUSEHOLD MEMBER' / .


SAVE OUTFILE='.\lf_sec_03.sav'.
