/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\lf_sec_04a.dat" ENCODING="CP1252" / LRECL=47 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        sourceid 23           
   lf04a_01_1 24            lf04a_01_2 25            lf04a_01_3 26         
   lf04a_01_4 27            lf04a_01_5 28            lf04a_01_6 29         
   lf04a_01_7 30            lf04a_02 31              lf04a_03_1 32-33      
   lf04a_03_2 34-35         lf04a_03_3 36            lf04a_03_4 37         
   lf04a_04 38              lf04a_05 39              lf04a_06 40-45        
   lf04a_07 46-47 (A) .  

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   sourceid 'Source ID'
   lf04a_01_1    'In the last 12 months, did you receive any advice from [SOURCE] a' +
   'bout animal bre'
   lf04a_01_2    'In the last 12 months, did you receive any advice from [SOURCE] a' +
   'bout feeds and '
   lf04a_01_3    'In the last 12 months, did you receive any advice from [SOURCE] a' +
   'bout housing an'
   lf04a_01_4    'In the last 12 months, did you receive any advice from [SOURCE] a' +
   'bout livestock '
   lf04a_01_5    'In the last 12 months, did you receive any advice from [SOURCE] a' +
   'bout processing'
   lf04a_01_6    'In the last 12 months, did you receive any advice from [SOURCE] a' +
   'bout livestock '
   lf04a_01_7    'In the last 12 months, did you receive any advice from [SOURCE] a' +
   'bout prevention'
   lf04a_02    'CAPI: DID THE RESPONDENT ANSWER YES FOR ANY TYPE OF ADVICE IN QUE' +
   'STION 1?'
   lf04a_03_1 'Who in your household received advice from [SOURCE]? HH ID 1'
   lf04a_03_2 'Who in your household received advice from [SOURCE]? HH ID 2'
   lf04a_03_3 'Who in your household received advice from [SOURCE]? HH ID 3'
   lf04a_03_4 'Who in your household received advice from [SOURCE]? HH ID 4'
   lf04a_04 'How would you rate the advice received from [SOURCE]?'
   lf04a_05    'Did you pay anything in order to receive the advice from [SOURCE]' +
   '?'
   lf04a_06 'How much did you pay? (TSH)?'
   lf04a_07    'How many times did an Extension Advisor from [SOURCE] visit your ' +
   'farm in the las' .

VALUE LABELS
 sourceid
     1 'GOVERNMENT'
     2 'NGO'
     3 "COOPERATIVE/FARMER'S ASSOCIATION"
     4 'LARGE SCALE FARMER'
     5 'OTHER (SPECIFY)' /
 lf04a_01_1
     1 'YES'
     2 'NO' /
 lf04a_01_2
     1 'YES'
     2 'NO' /
 lf04a_01_3
     1 'YES'
     2 'NO' /
 lf04a_01_4
     1 'YES'
     2 'NO' /
 lf04a_01_5
     1 'YES'
     2 'NO' /
 lf04a_01_6
     1 'YES'
     2 'NO' /
 lf04a_01_7
     1 'YES'
     2 'NO' /
 lf04a_02
     1 'YES'
     2 'NO' /
 lf04a_04
     1 'GOOD'
     2 'AVERAGE'
     3 'BAD' /
 lf04a_05
     1 'YES'
     2 'NO' / .


SAVE OUTFILE='.\lf_sec_04a.sav'.
