/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\lf_sec_07.dat" ENCODING="CP1252" / LRECL=40 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        lvstckid 23           
   lf07_01 24               lf07_02_1 25             lf07_02_2 26          
   lf07_03 27-32            lf07_04_1 33-37          lf07_04_2 38          
   lf07_05 39               lf07_06 40 .          

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   lvstckid 'Livestock Category Code'
   lf07_01    'Has the household made any use of the dung produced by [ANIMAL] i' +
   'n the past 12 m'
   lf07_02_1    'What have been the major uses of the dung from [ANIMAL] in the la' +
   'st 12 months? ('
   lf07_02_2    'What have been the major uses of the dung from [ANIMAL] in the la' +
   'st 12 months? ('
   lf07_03    'What was the total value of sales of the dung from [ANIMLA] in th' +
   'e last 12 month'
   lf07_04_1    'What was the total quantity of dung produced per month form [ANIM' +
   'AL] over the la'
   lf07_04_2    'What was the total quantity of dung produced per month from [ANIM' +
   'AL] over the la'
   lf07_05    'Has the household used any of its [ANIMAL] for its own transporta' +
   'tion in the pas'
   lf07_06    'Has this household used any of its [ANIMAL] for ploughing its own' +
   ' field in the p' .

VALUE LABELS
 lvstckid
     1 'LARGE RUMINANTS'
     2 'SMALL RUMINANTS'
     3 'PIGS'
     4 'POULTRY'
     5 'DONKEYS'
     6 'OTHER ANIMALS' /
 lf07_01
     1 'YES'
     2 'NO' /
 lf07_02_1
     1 'MANURE'
     2 'COOKING FUEL'
     3 'FEED TO OTHER ANIMALS'
     4 'CONSTRUCTION OF BUILDING'
     5 'SALES'
     6 'OTHER (SPECIFY)' /
 lf07_02_2
     1 'MANURE'
     2 'COOKING FUEL'
     3 'FEED TO OTHER ANIMALS'
     4 'CONSTRUCTION OF BUILDING'
     5 'SALES'
     6 'OTHER (SPECIFY)' /
 lf07_04_2
     1 'KG'
     2 'LITER' /
 lf07_05
     1 'YES'
     2 'NO' /
 lf07_06
     1 'YES'
     2 'NO' / .


SAVE OUTFILE='.\lf_sec_07.sav'.
