/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\lf_sec_02.dat" ENCODING="CP1252" / LRECL=139 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        lvstckid 23-24        
   lf02_01 25               lf02_02 26-28            lf02_03 29-32         
   lf02_04_1 33-35          lf02_04_2 36-39          lf02_05 40-42         
   lf02_06 43               lf02_07 44-47            lf02_08 48-54         
   lf02_09 55               lf02_10 56-57            lf02_11 58            
   lf02_12 59               lf02_13 60-61            lf02_14 62            
   lf02_15 63               lf02_16 64-66            lf02_17 67-74         
   lf02_18 75               lf02_19 76-77            lf02_20 78-84         
   lf02_21 85               lf02_22 86-88            lf02_23 89-95         
   lf02_24 96               lf02_25 97-102           lf02_26 103-110       
   lf02_27_1 111-112        lf02_27_2 113-114        lf02_28a 115-116      
   lf02_28b 117             lf02_29 118              lf02_30 119-120       
   lf02_31 121-126          lf02_32 127              lf02_33 128-134       
   lf02_34a 135-136         lf02_34b 137             lf02_35_1 138         
   lf02_35_2 139 .       


FORMATS
  lf02_31 (F7.1) / .
    
VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   lvstckid 'Livestock ID'
   lf02_01 'Did this household own any [ANIMAL] in the last 12 months?'
   lf02_02 'Number of [ANIMAL] owned at the time of the last survey.'
   lf02_03 'Number of [ANIMAL] owned 12 months ago.'
   lf02_04_1 'How many [ANIMAL] does this household currently own? Indigenous'
   lf02_04_2    'How many [ANIMAL] does this household currently own? Improved / E' +
   'xotic'
   lf02_05 'How many [ANIMAL] were born in the past 12 months?'
   lf02_06 'Have you bought any [ANIMAL] alive in the past 12 months?'
   lf02_07 'How many [ANIMAL] have you bought alive in the last 12 months?'
   lf02_08 'What was the total value of these purchases? (TSH)'
   lf02_09 'Did you receive any [ANIMAL] as a gift in the last 12 months?'
   lf02_10    'How many [ANIMAL] did you receive as gifts or payment for some se' +
   'rvices provided'
   lf02_11 'From whom did you receive most of these [ANIMAL]?'
   lf02_12    'Did you give any [ANIMAL] as gift or payment for some services pr' +
   'ovided in the l'
   lf02_13    'How many [ANIMAL] did you give as gift or payment for some servic' +
   'es provided in '
   lf02_14 'To whom did you give most of these [ANIMAL]?'
   lf02_15 'Have you lost any [ANIMAL] to DISEASE in the past 12 months?'
   lf02_16    'How many [ANIMAL] have you lost to DISEASE in the past 12 months?'
   lf02_17 'What was the value of these [ANIMAL]s lost to disease? (TSH)'
   lf02_18 'Have you lost any [ANIMAL] to THEFT in the past 12 months?'
   lf02_19 'How many [ANIMAL] have you lost to THEFT in the past 12 months?'
   lf02_20 'What was the value of these [ANIMAL]s lost to THEFT?'
   lf02_21    'Have you last any [ANIMAL] to INJURY/ACCIDENT/NATURAL CALAMITY in' +
   ' the past 12 mo'
   lf02_22    'How many [ANIMAL] have you lost to INJURY/ACCIDENT/NATURAL CALAMI' +
   'TY in the past '
   lf02_23    'What was the value of these [ANIMAL] lost to INJURY/ACCIDENT/NATU' +
   'RAL CALAMITY in'
   lf02_24 'Have you sold any [ANIMAL] alive in the past 12 months?'
   lf02_25 'How many [ANIMAL] have you sold alive in the past 12 months?'
   lf02_26 'What was the total value of sales? (TSH)'
   lf02_27_1    'Who in your household decided what to do with these earnings? (ID' +
   ' #1)'
   lf02_27_2    'Who in your household decided what to do with these earnings? (ID' +
   ' #2)'
   lf02_28a 'Where did you sell most [ANIMAL] that you sold? (NR ID 1)'
   lf02_28b    'Where did you sell most [ANIMAL] that you sold? (NR ID 1 LOCATION' +
   ')'
   lf02_29 'Did you slaughter any [ANIMAL] in the past 12 months?'
   lf02_30 'How many [ANIMAL] did you slaughter in the past 12 months?'
   lf02_31    'What was the live weight, on average, of the [ANIMAL] that you sl' +
   'aughtered? (KG/'
   lf02_32 'How many of the [ANIMAL] slaughtered did you sell?'
   lf02_33 'What was the total value of the sold slaughtered [ANIMAL]? (TSH)'
   lf02_34a 'Where did you sell most [ANIMAL] that you slaughtered? (NR ID 1)'
   lf02_34b    'Where did you sell most [ANIMAL] that you slaughtered? (NR ID 1 L' +
   'OCATION)'
   lf02_35_1    'Who in your household decided what to do with these earnings? (ID' +
   ' #1)'
   lf02_35_2    'Who in your household decided what to do with these earnings? (ID' +
   ' #2)' .

VALUE LABELS
 lvstckid
     1 'BULLS'
     2 'COWS'
     3 'STEERS'
     4 'HEIFERS'
     5 'MALE CALVES'
     6 'FEMALE CALVES'
     7 'GOATS'
     8 'SHEEP'
     9 'PIGS'
     10 'CHICKENS'
     11 'DUCKS'
     12 'OTHER POULTRY'
     13 'RABBITS'
     14 'DONKEYS'
     15 'DOGS'
     16 'CATS'
     17 'OTHER' /
 lf02_01
     1 'YES'
     2 'NO' /
 lf02_06
     1 'YES'
     2 'NO' /
 lf02_09
     1 'YES'
     2 'NO' /
 lf02_11
     1 'FRIENDS/RELATIVE'
     2 'NGO'
     3 'OTHER (SPECIFY)' /
 lf02_12
     1 'YES'
     2 'NO' /
 lf02_14
     1 'FRIEND / RELATIVE'
     2 'NGO'
     3 'OTHER (SPECIFY)' /
 lf02_15
     1 'YES'
     2 'NO' /
 lf02_18
     1 'YES'
     2 'NO' /
 lf02_21
     1 'YES'
     2 'NO' /
 lf02_24
     1 'YES'
     2 'NO' /
 lf02_28a
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION    OFFICER'
     20 'OTHER (SPECIFY)' /
 lf02_28b
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' /
 lf02_29
     1 'YES'
     2 'NO' /
 lf02_32
     0 'NONE' /
 lf02_34a
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION    OFFICER'
     20 'OTHER (SPECIFY)' /
 lf02_34b
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' / .


SAVE OUTFILE='.\lf_sec_02.sav'.
