/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\lf_sec_05.dat" ENCODING="CP1252" / LRECL=66 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        lvstckid 23           
   lf05_01_1 24-25          lf05_01_2 26-27          lf05_02_1 28-29       
   lf05_02_2 30-31          lf05_03_1 32-33          lf05_03_2 34-35       
   lf05_04_1 36-37          lf05_04_2 38-39          lf05_05 40            
   lf05_05a1 41-46          lf05_05a2 47             lf05_06_1 48 (A)      
   lf05_06_2 49 (A)         lf05_06_3 50 (A)         lf05_06_4 51 (A)      
   lf05_06_5 52 (A)         lf05_06_6 53 (A)         lf05_06_7 54 (A)      
   lf05_06_8 55 (A)         lf05_06_9 56 (A)         lf05_06_10 57 (A)     
   lf05_06_11 58 (A)        lf05_06_12 59 (A)        lf05_07 60-66 .       

VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   lvstckid 'Livestock Category Code'
   lf05_01_1 'In principal, who is responsible for keeping [ANIMAL]? (ID #1)'
   lf05_01_2 'In principal, who is responsible for keeping [ANIMAL]? (ID #2)'
   lf05_02_1    'Who in your household provided labor for feeding/watering of [ANI' +
   'MAL]? (ID #1)'
   lf05_02_2    'Who in your household provided labor for feeding/watering of [ANI' +
   'MAL]? (ID #2)'
   lf05_03_1    'Who in your household provided the labour for selling the animals' +
   ' and animal pro'
   lf05_03_2    'Who in your household provided the labour for selling the animals' +
   ' and animal pro'
   lf05_04_1    'Who in your household mainly provided labour for grazing of [ANIM' +
   'AL]? (ID #1)'
   lf05_04_2    'Who in your household mainly provided labour for grazing of [ANIM' +
   'AL]? (ID #2)'
   lf05_05    'Did you hire any labor to help you with the [ANIMAL] in the past ' +
   '12 months?'
   lf05_05a1    '5.a1. How many person did you hire to help keeping [ANIMAL] in th' +
   'e past 12 month'
   lf05_05a2    '5.a2. How many person did you hire to help keeping [ANIMAL] in th' +
   'e past 12 month'
   lf05_06_1 'In which months did you hire help? (JAN)'
   lf05_06_2 'In which months did you hire help? (FEB)'
   lf05_06_3 'In which months did you hire help? (MAR)'
   lf05_06_4 'In which months did you hire help? (APR)'
   lf05_06_5 'In which months did you hire help? (MAY)'
   lf05_06_6 'In which months did you hire help? (JUNE)'
   lf05_06_7 'In which months did you hire help? (JULY)'
   lf05_06_8 'In which months did you hire help? (AUG)'
   lf05_06_9 'In which months did you hire help? (SEPT)'
   lf05_06_10 'In which months did you hire help? (OCT)'
   lf05_06_11 'In which months did you hire help? (NOV)'
   lf05_06_12 'In which months did you hire help? (DEC)'
   lf05_07    'What was the total cost of this labor for [ANIMAL] in the past 12' +
   ' months? (TSH)' .

VALUE LABELS
 lvstckid
     1 'LARGE RUMINANTS'
     2 'SMALL RUMINANTS'
     3 'PIGS'
     4 'POULTRY'
     5 'DONKEYS'
     6 'DOGS' /
 lf05_02_1
     99 'NONE' /
 lf05_03_1
     99 'NONE' /
 lf05_04_1
     99 'NONE' /
 lf05_05
     1 'YES'
     2 'NO' / .


SAVE OUTFILE='.\lf_sec_05.sav'.
