/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\lf_sec_06.dat" ENCODING="CP1252" / LRECL=66 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        lvstckid 23           
   lf06_01 24-25            lf06_02 26-27            lf06_03 28-31         
   lf06_04_1 32-33          lf06_04_2 34-36          lf06_05_1 37-38       
   lf06_05_2 39-41          lf06_06 42               lf06_07 43-45         
   lf06_08 46-49            lf06_09 50-52            lf06_10 53-54         
   lf06_11 55-59            lf06_12a 60-61           lf06_12b 62           
   lf06_13_1 63-64          lf06_13_2 65-66 .     


FORMATS
  lf06_03 (F5.1) /         lf06_04_2 (F4.1) /       lf06_05_2 (F4.1) /     
  lf06_08 (F5.1) /         lf06_09 (F4.1) / .
    
VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   lvstckid 'Livestock Category Code'
   lf06_01 'How many [ANIMAL] were milked in the last 12 months?'
   lf06_02 'How many months on average, were [ANIMAL] milked for?'
   lf06_03    'What was the average milk production per day per milked [ANIMAL] ' +
   'durning this pe'
   lf06_04_1    'During this period in which months was milk production per animal' +
   ' the highest?'
   lf06_04_2 'LITRES/DAY during this period'
   lf06_05_1    'During this period in which month was milk production per animal ' +
   'the lowest?'
   lf06_05_2 'LITRES/DAY during this period'
   lf06_06    'In general, were your [ANIMAL] suckling during the time the [ANIM' +
   'AL] were being '
   lf06_07    'During this period, how much of the milk produced by [ANIMAL] was' +
   ' consumed by yo'
   lf06_08    'During this period how many litres of [ANIMAL] liquid milk did yo' +
   'u sell per day?'
   lf06_09    'During this period, how much of the milk produced by [ANIMAL] did' +
   ' you convert ea'
   lf06_10    'How much of this production of processed dairy products did you s' +
   'ell per day?'
   lf06_11    'How much did you earn on average per day from these sales of milk' +
   ' and processed '
   lf06_12a    'Where did you sell most of the milk from [ANIMAL] that you sold? ' +
   '(NR ID 1)'
   lf06_12b    'Where did you sell most of the milk from [ANIMAL] that you sold? ' +
   '(NR ID 1 LOCATI'
   lf06_13_1    'Who in your household decided what to do with these earnings? (HH' +
   ' ID 1)'
   lf06_13_2    'Who in your household decided what to do with these earnings? (HH' +
   ' ID 2)' .

VALUE LABELS
 lvstckid
     1 'LARGE RUMINANTS'
     2 'SMALL RUMINANTS'
     3 'PIGS'
     4 'POULTRY'
     5 'DONKEYS'
     6 'DOGS' /
 lf06_01
     0 'HAPANA' /
 lf06_04_1
     1 'JANUARY'
     2 'FEBRUARY'
     3 'MARCH'
     4 'APRIL'
     5 'MAY'
     6 'JUNE'
     7 'JULY'
     8 'AUGUST'
     9 'SEPTEMBER'
     10 'OCTOBER'
     11 'NOVEMBER'
     12 'DECEMBER' /
 lf06_05_1
     1 'JANUARY'
     2 'FEBRUARY'
     3 'MARCH'
     4 'APRIL'
     5 'MAY'
     6 'JUNE'
     7 'JULY'
     8 'AUGUST'
     9 'SEPTEMBER'
     10 'OCTOBER'
     11 'NOVEMBER'
     12 'DECEMBER' /
 lf06_06
     1 'LIMITED SUCKLING'
     2 'UNLIMITED SUCKLING'
     3 ' NONE, NOT SUCKLED' /
 lf06_09
     0 'NONE' /
 lf06_12a
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION    OFFICER'
     20 'OTHER (SPECIFY)' /
 lf06_12b
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' / .


SAVE OUTFILE='.\lf_sec_06.sav'.
