/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\lf_sec_08.dat" ENCODING="CP1252" / LRECL=53 .

DATA LIST FILE=DATA/
   interview__key 1-11 (A)   y5_hhid 12-22 (A)        productid 23          
   lf08_01 24               lf08_02 25-26            lf08_03_1 27-30       
   lf08_03_2 31             lf08_04 32               lf08_05_1 33-39       
   lf08_05_2 40             lf08_06 41-48            lf08_07_a 49-50       
   lf08_07_c 51             lf08_08_1 52             lf08_08_2 53 .        


FORMATS
  lf08_03_1 (F5.2) / .
  
VARIABLE LABELS
   interview__key 'Interview key (identifier in XX-XX-XX-XX format)'
   y5_hhid 'Unique Household Identification NPSY5'
   productid 'Product Code'
   lf08_01 'Did your household produce any [PRODUCT] in the last 12 months?'
   lf08_02    'During the last 12 months, for how many months did your household' +
   ' produce any [P'
   lf08_03_1    'During these months, what was the average quantity of [PRODUCT] p' +
   'roduced per mon'
   lf08_03_2    'During these months, what was the average quantity of [PRODUCT] p' +
   'roduced per mon'
   lf08_04    'Did you sell any of the [PRODUCT] that you produced in the last 1' +
   '2 months?'
   lf08_05_1    'How much of the [PRODUCT] produced did you sell in the last 12 mo' +
   'nths? (QTY)'
   lf08_05_2    'How much of the [PRODUCT] produced did you sell in the last 12 mo' +
   'nths? (UNIT)'
   lf08_06    'What was the total value of sales of [PRODUCT] in the last 12 mon' +
   'ths? (TSH)'
   lf08_07_a 'Where did you sell most [PRODUCT] that you sold? (NR ID 1)'
   lf08_07_c 'Where did you sell most [PRODUCT] that you sold? (NR LOCATION)'
   lf08_08_1    'Who in your household decided what to do with these earnings? HH ' +
   'ID 1'
   lf08_08_2    'Who in your household decided what to do with these earnings? HH ' +
   'ID 2' .

VALUE LABELS
 productid
     1 'EGGS'
     2 'HONEY'
     3 'SKIN/HIDES'
     4 'OTHER' /
 lf08_01
     1 'YES'
     2 'NO' /
 lf08_03_2
     1 'LITRES'
     2 'KGs'
     3 'PIECES' /
 lf08_04
     1 'YES'
     2 'NO' /
 lf08_05_2
     1 'LITRES'
     2 'KGs'
     3 'PIECES' /
 lf08_07_a
     1 'RELATIVE'
     2 'NEIGHBOR'
     3 'FRIEND'
     4 'MARKET'
     5 'OPEN MARKET'
     6 'COOPERATIVE UNION'
     7 'FARMERS PARTY'
     8 'MAIN PLOT/FARM'
     9 'PRIVATE BUSINESS PERSON'
     10 'MAIN MARKET'
     11 'BUSINESS CONTACT'
     12 'ABATTORI / FACTORY'
     13 'EMPLOYER'
     14 'RELIGIOUS INSTITUTION'
     15 'BANK (COMMERCIAL)'
     16 'MERCHANT'
     17 'MONEY LENDER'
     18 'NGO'
     19 'DISTRIBUTION OFFICER'
     20 'OTHER (SPECIFY)' /
 lf08_07_c
     1 'WITHIN THE VILLAGE'
     2 'NEAR THE VILLAGE'
     3 'NEAR THE TOWN'
     4 'OTHER DISTRICT'
     5 'OTHER REGION'
     6 'ACROSS THE BORDER' / .


SAVE OUTFILE='.\lf_sec_08.sav'.
