/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\npsy5.panel.key.dat" ENCODING="CP1252" / LRECL=28 .

DATA LIST FILE=DATA/
   UPI 1-5                  y4_hhid 6-13 (A)         indidy4 14-15         
   y5_hhid 16-26 (A)        indidy5 27-28 .       

VARIABLE LABELS
   UPI 'Unique Panel Identifier NPSY5'
   y4_hhid 'Unique Household Identification NPS Y4'
   indidy4 'Individual ID'
   y5_hhid 'Unique Household Identification NPSY5'
   indidy5 'Individual ID' .

VALUE LABELS
 indidy4
     99 'NOT PREVIOUSLY PRESENT' / .


SAVE OUTFILE='.\npsy5.panel.key.sav'.
