/* This SPSS program was automatically generated by Stat/Transfer ver.15.1.1454.0311 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\npsy5.child.anthro.dat" ENCODING="CP1252" / LRECL=23 .

DATA LIST FILE=DATA/
   y5_hhid 1-11 (A)         indidy5 12-13            age_months 14-15      
   v03 16                   outlier 17               zwxa 18               
   zhxa 19                  zwxh 20                  under 21              
   stunt 22                 waste 23 .            

VARIABLE LABELS
   y5_hhid 'Unique Household Identification NPSY5'
   indidy5 'Individual ID'
   age_months 'Age (months)'
   v03 'Was [NAME] measured?'
   outlier    'Outlier as determined by WHO; limited information for these indiv' +
   'iduals'
   zwxa 'Z-scores Weight-for-Age'
   zhxa 'Z-scores Height-for-Age'
   zwxh 'Z-scores Weight-for-Height'
   under 'Underweight (status)'
   stunt 'Stunted (status)'
   waste 'Wasted (status)' .

VALUE LABELS
 v03
     1 'YES'
     2 'NO' /
 zwxa zhxa zwxh
     0 'SEVERE (Z<-3)'
     1 'MODERATE (Z<-2)'
     2 'MILD (Z<-1)'
     3 'HEALTHY' /
 under
     0 'NOT UNDERWEIGHT'
     1 'UNDERWEIGHT' /
 stunt
     0 'NOT STUNTED'
     1 'STUNTED' /
 waste
     0 'NOT WASTED'
     1 'WASTED' / .


SAVE OUTFILE='.\npsy5.child.anthro.sav'.
